export const launchTrustText = {
  de:{control:'Transparenz & Kontrolle',contract:'Ihr Tarifstatus',contractFree:'Kostenlos · keine Zahlungspflicht · keine automatische Verlängerung',contractPaid:'Kostenpflichtige Nutzung nur für die ausdrücklich gewählte Laufzeit · keine automatische Verlängerung',paymentState:'Zahlungsstatus',paymentOff:'Bezahlfunktion noch deaktiviert',dataTitle:'Ihre Daten',dataNote:'Dokumente und Falldaten bleiben Ihrem Zugang zugeordnet. Vor dem Marktstart werden Datenexport, Löschanfrage und Aufbewahrungsstatus als eigene Kontofunktionen aktiviert.',auditTitle:'Nachvollziehbarkeit',auditNote:'Wichtige Änderungen, Freigaben, Exporte und Versandvorgänge werden mit Status und Zeitpunkt nachvollziehbar geführt. Wo noch kein belastbarer Audit-Eintrag vorliegt, wird kein Erfolg vorgetäuscht.',why:'Warum dieses Ergebnis?',basis:'Berücksichtigte Grundlage',basisDocs:'{n} zugeordnete Dokumente',finding:'Festgestellter Sachstand',missing:'Fehlt noch / kann Bewertung ändern',missingDocs:'Es sind noch keine Dokumente zugeordnet. Eine belastbare Bewertung ist daher nicht möglich.',missingOpen:'Prüfen Sie, ob weitere Unterlagen, Fristen oder Angaben fehlen. Fehlende Informationen müssen vor einer sicheren Bewertung sichtbar bleiben.',assessment:'Bewertung',assessmentNote:'Die Ampel zeigt den derzeit gespeicherten Fallstatus. Sie ist keine versteckte Black-Box-Entscheidung und muss bei neuen Informationen aktualisiert werden.',next:'Nächster Schritt',nextDocs:'Unterlagen ergänzen und Bewertung danach erneut prüfen.',nextReview:'Grundlagen prüfen und bei neuen Informationen die Bewertung aktualisieren.',notFinal:'Nicht sicher bewertbar',notFinalNote:'Wenn die Grundlage nicht ausreicht, darf AS Workspace Gold keine scheinbar sichere Aussage erzeugen.',dataExport:'Meine Daten exportieren',dataExportHelp:'Erstellt sofort eine lokale JSON-Datei mit den aktuell geladenen Kunden-, Fall-, Dokument- und Freigabedaten. Es wird keine Zahlung ausgelöst.',historyTitle:'Aktuelle Gerätehistorie',historyHelp:'Diese Liste zeigt wichtige Aktionen dieses Geräts. Sie ist bewusst als lokale Gerätehistorie gekennzeichnet und ersetzt noch kein serverseitiges Audit-Protokoll.',noHistory:'Auf diesem Gerät sind noch keine Aktionen protokolliert.',passwordReset:'Passwort zurücksetzen',passwordResetHelp:'Wir senden einen sicheren Link an die eingegebene E-Mail-Adresse.',passwordSent:'Wenn die Adresse registriert ist, wurde ein Link zum Zurücksetzen gesendet.'},
  en:{control:'Transparency & control',contract:'Your plan status',contractFree:'Free · no payment obligation · no automatic renewal',contractPaid:'Paid use only for the explicitly selected term · no automatic renewal',paymentState:'Payment status',paymentOff:'Payment still disabled',dataTitle:'Your data',dataNote:'Documents and case data remain assigned to your account. Before launch, data export, deletion requests and retention status will be activated as dedicated account functions.',auditTitle:'Traceability',auditNote:'Important changes, approvals, exports and sending actions are tracked with status and time. Where no reliable audit entry exists, success is not pretended.',why:'Why this result?',basis:'Basis considered',basisDocs:'{n} assigned documents',finding:'Established case status',missing:'Missing / may change assessment',missingDocs:'No documents are assigned yet. A reliable assessment is therefore not possible.',missingOpen:'Check whether further documents, deadlines or information are missing. Missing information must remain visible before a firm assessment.',assessment:'Assessment',assessmentNote:'The traffic light reflects the currently stored case status. It is not a hidden black-box decision and must be updated when new information arrives.',next:'Next step',nextDocs:'Add documents and review the assessment again afterwards.',nextReview:'Review the basis and update the assessment when new information arrives.',notFinal:'Not reliably assessable',notFinalNote:'If the basis is insufficient, AS Workspace Gold must not produce a seemingly certain statement.',dataExport:'Export my data',dataExportHelp:'Immediately creates a local JSON file containing the currently loaded client, case, document and approval data. No payment is triggered.',historyTitle:'Current device history',historyHelp:'This list shows important actions on this device. It is deliberately labelled as local device history and does not yet replace a server-side audit log.',noHistory:'No actions have been logged on this device yet.',passwordReset:'Reset password',passwordResetHelp:'We will send a secure reset link to the email address entered above.',passwordSent:'If the address is registered, a password reset link has been sent.'}
}

export const serverControlText = {
  de:{serverAudit:'Server-Audit',serverAuditHelp:'Diese Einträge werden serverseitig in Ihrem Konto gespeichert und können von normalen Nutzern weder geändert noch gelöscht werden.',noServerAudit:'Noch keine serverseitigen Audit-Einträge vorhanden.',deletion:'Löschanfrage',deletionHelp:'Eine Löschanfrage entfernt Daten nicht sofort. Zuerst werden Abhängigkeiten und mögliche gesetzliche Aufbewahrungspflichten geprüft.',requestDeletion:'Kontolöschung anfragen',cancelDeletion:'Löschanfrage zurücknehmen',deletionPending:'Löschanfrage eingegangen · Prüfung ausstehend',deletionCancelled:'Löschanfrage zurückgenommen',deletionRequested:'Ihre Löschanfrage wurde protokolliert. Bis zur Prüfung wird nichts automatisch gelöscht.',auditFailed:'Die Aktion wurde ausgeführt, aber der serverseitige Audit-Eintrag konnte nicht gespeichert werden.'},
  en:{serverAudit:'Server audit',serverAuditHelp:'These entries are stored server-side in your account and cannot be changed or deleted by normal users.',noServerAudit:'No server-side audit entries yet.',deletion:'Deletion request',deletionHelp:'A deletion request does not remove data immediately. Dependencies and possible legal retention duties are checked first.',requestDeletion:'Request account deletion',cancelDeletion:'Cancel deletion request',deletionPending:'Deletion request received · review pending',deletionCancelled:'Deletion request cancelled',deletionRequested:'Your deletion request has been recorded. Nothing is deleted automatically before review.',auditFailed:'The action succeeded, but the server-side audit entry could not be saved.'},
  tr:{serverAudit:'Sunucu denetim kaydı',serverAuditHelp:'Bu kayıtlar hesabınızda sunucu tarafında saklanır ve normal kullanıcılar tarafından değiştirilemez veya silinemez.',noServerAudit:'Henüz sunucu tarafı denetim kaydı yok.',deletion:'Silme talebi',deletionHelp:'Silme talebi verileri hemen silmez. Önce bağımlılıklar ve olası yasal saklama yükümlülükleri kontrol edilir.',requestDeletion:'Hesap silme talebi oluştur',cancelDeletion:'Silme talebini geri çek',deletionPending:'Silme talebi alındı · inceleme bekliyor',deletionCancelled:'Silme talebi geri çekildi',deletionRequested:'Silme talebiniz kaydedildi. İnceleme öncesinde hiçbir veri otomatik olarak silinmez.',auditFailed:'İşlem tamamlandı ancak sunucu denetim kaydı kaydedilemedi.'},
  pl:{serverAudit:'Audyt serwerowy',serverAuditHelp:'Te wpisy są przechowywane po stronie serwera na Twoim koncie i zwykły użytkownik nie może ich zmieniać ani usuwać.',noServerAudit:'Brak wpisów audytu serwerowego.',deletion:'Wniosek o usunięcie',deletionHelp:'Wniosek nie usuwa danych natychmiast. Najpierw sprawdzane są zależności i możliwe obowiązki przechowywania.',requestDeletion:'Poproś o usunięcie konta',cancelDeletion:'Wycofaj wniosek',deletionPending:'Wniosek o usunięcie przyjęty · oczekuje na weryfikację',deletionCancelled:'Wniosek o usunięcie wycofany',deletionRequested:'Wniosek został zapisany. Do czasu weryfikacji nic nie zostanie automatycznie usunięte.',auditFailed:'Operacja się powiodła, ale wpis audytu serwerowego nie został zapisany.'},
  ru:{serverAudit:'Серверный аудит',serverAuditHelp:'Эти записи хранятся на сервере в вашей учетной записи и не могут быть изменены или удалены обычным пользователем.',noServerAudit:'Серверных записей аудита пока нет.',deletion:'Запрос на удаление',deletionHelp:'Запрос не удаляет данные сразу. Сначала проверяются зависимости и возможные обязанности по хранению.',requestDeletion:'Запросить удаление аккаунта',cancelDeletion:'Отозвать запрос',deletionPending:'Запрос получен · ожидает проверки',deletionCancelled:'Запрос отозван',deletionRequested:'Запрос на удаление сохранен. До проверки ничего автоматически не удаляется.',auditFailed:'Действие выполнено, но серверную запись аудита сохранить не удалось.'},
  ar:{serverAudit:'سجل تدقيق على الخادم',serverAuditHelp:'تُحفظ هذه السجلات على الخادم ضمن حسابك ولا يستطيع المستخدم العادي تعديلها أو حذفها.',noServerAudit:'لا توجد سجلات تدقيق على الخادم حتى الآن.',deletion:'طلب حذف',deletionHelp:'طلب الحذف لا يحذف البيانات فوراً. يتم أولاً فحص الارتباطات وأي التزامات قانونية محتملة للاحتفاظ.',requestDeletion:'طلب حذف الحساب',cancelDeletion:'سحب طلب الحذف',deletionPending:'تم استلام طلب الحذف · قيد المراجعة',deletionCancelled:'تم سحب طلب الحذف',deletionRequested:'تم تسجيل طلب الحذف. لن يُحذف شيء تلقائياً قبل المراجعة.',auditFailed:'تم تنفيذ الإجراء، لكن تعذر حفظ سجل التدقيق على الخادم.'}
}

export const accessPendingMessages = {
  de:'Zugang noch nicht freigegeben.',en:'Access not yet approved.',fr:'Accès pas encore validé.',
  tr:'Erişim henüz onaylanmadı.',pl:'Dostęp nie został jeszcze zatwierdzony.',
  ru:'Доступ ещё не подтверждён.',ar:'لم تتم الموافقة على الوصول بعد.',fa:'دسترسی هنوز تأیید نشده است.'
}
