export const promoTranslations={
  de:{title:'Promo-Code',label:'Promo-Code eingeben',placeholder:'Code',apply:'Anwenden',checking:'Wird geprüft …',clear:'Entfernen',help:'Der Code wird sicher auf dem Server geprüft. Ungültige Codes ändern den Preis nicht.',valid:'Promo-Code angewendet',invalid:'Ungültiger, abgelaufener oder für diese Auswahl nicht gültiger Promo-Code.',validSome:'Der Promo-Code gilt nur für einen Teil der angezeigten Tarife.',discount:'Promo-Rabatt',before:'Vor Promo-Code',saved:'Zusätzlich gespart'},
  en:{title:'Promo code',label:'Enter promo code',placeholder:'Code',apply:'Apply',checking:'Checking …',clear:'Remove',help:'The code is securely checked on the server. Invalid codes do not change the price.',valid:'Promo code applied',invalid:'Invalid, expired or ineligible promo code for this selection.',validSome:'The promo code applies to only some displayed plans.',discount:'Promo discount',before:'Before promo code',saved:'Additional saving'},
  fr:{title:'Code promo',label:'Saisir le code promo',placeholder:'Code',apply:'Appliquer',checking:'Vérification …',clear:'Retirer',help:'Le code est vérifié en sécurité sur le serveur. Un code invalide ne modifie pas le prix.',valid:'Code promo appliqué',invalid:'Code invalide, expiré ou non applicable à cette sélection.',validSome:'Le code ne s’applique qu’à certaines formules affichées.',discount:'Réduction promo',before:'Avant le code promo',saved:'Économie supplémentaire'},
  tr:{title:'Promosyon kodu',label:'Promosyon kodunu girin',placeholder:'Kod',apply:'Uygula',checking:'Kontrol ediliyor …',clear:'Kaldır',help:'Kod sunucuda güvenli biçimde doğrulanır. Geçersiz kod fiyatı değiştirmez.',valid:'Promosyon kodu uygulandı',invalid:'Bu seçim için geçersiz, süresi dolmuş veya uygun olmayan kod.',validSome:'Kod yalnızca gösterilen tarifelerin bir bölümünde geçerlidir.',discount:'Promosyon indirimi',before:'Koddan önce',saved:'Ek tasarruf'},
  pl:{title:'Kod promocyjny',label:'Wpisz kod promocyjny',placeholder:'Kod',apply:'Zastosuj',checking:'Sprawdzanie …',clear:'Usuń',help:'Kod jest bezpiecznie sprawdzany na serwerze. Nieprawidłowy kod nie zmienia ceny.',valid:'Kod promocyjny zastosowany',invalid:'Kod jest nieprawidłowy, wygasł lub nie pasuje do tego wyboru.',validSome:'Kod obowiązuje tylko dla części pokazanych planów.',discount:'Rabat promocyjny',before:'Przed kodem',saved:'Dodatkowa oszczędność'},
  ru:{title:'Промокод',label:'Введите промокод',placeholder:'Код',apply:'Применить',checking:'Проверка …',clear:'Удалить',help:'Код безопасно проверяется на сервере. Неверный код не меняет цену.',valid:'Промокод применён',invalid:'Промокод недействителен, истёк или не подходит для выбранного варианта.',validSome:'Промокод действует только на часть показанных тарифов.',discount:'Скидка по промокоду',before:'До промокода',saved:'Дополнительная экономия'},
  ar:{title:'رمز ترويجي',label:'أدخل الرمز الترويجي',placeholder:'الرمز',apply:'تطبيق',checking:'جارٍ التحقق …',clear:'إزالة',help:'يُتحقق من الرمز بأمان على الخادم. الرمز غير الصالح لا يغيّر السعر.',valid:'تم تطبيق الرمز الترويجي',invalid:'الرمز غير صالح أو منتهي أو لا ينطبق على هذا الاختيار.',validSome:'ينطبق الرمز على بعض الخطط المعروضة فقط.',discount:'خصم ترويجي',before:'قبل الرمز',saved:'توفير إضافي'},
  fa:{title:'کد تخفیف',label:'کد تخفیف را وارد کنید',placeholder:'کد',apply:'اعمال',checking:'در حال بررسی …',clear:'حذف',help:'کد به‌طور امن در سرور بررسی می‌شود. کد نامعتبر قیمت را تغییر نمی‌دهد.',valid:'کد تخفیف اعمال شد',invalid:'کد نامعتبر، منقضی یا برای این انتخاب نامناسب است.',validSome:'کد فقط برای بخشی از طرح‌های نمایش‌داده‌شده معتبر است.',discount:'تخفیف کد',before:'پیش از کد',saved:'صرفه‌جویی افزوده'},
  ro:{title:'Cod promoțional',label:'Introduceți codul promoțional',placeholder:'Cod',apply:'Aplică',checking:'Se verifică …',clear:'Elimină',help:'Codul este verificat în siguranță pe server. Codurile nevalide nu modifică prețul.',valid:'Cod promoțional aplicat',invalid:'Cod nevalid, expirat sau neeligibil pentru această selecție.',validSome:'Codul se aplică doar unor tarife afișate.',discount:'Reducere promoțională',before:'Înainte de cod',saved:'Economie suplimentară'},
  bg:{title:'Промо код',label:'Въведете промо код',placeholder:'Код',apply:'Приложи',checking:'Проверка …',clear:'Премахни',help:'Кодът се проверява сигурно на сървъра. Невалидните кодове не променят цената.',valid:'Промо кодът е приложен',invalid:'Невалиден, изтекъл или неприложим код за този избор.',validSome:'Кодът важи само за част от показаните планове.',discount:'Промо отстъпка',before:'Преди кода',saved:'Допълнително спестяване'},
  vi:{title:'Mã khuyến mãi',label:'Nhập mã khuyến mãi',placeholder:'Mã',apply:'Áp dụng',checking:'Đang kiểm tra …',clear:'Xóa',help:'Mã được kiểm tra an toàn trên máy chủ. Mã không hợp lệ không làm thay đổi giá.',valid:'Đã áp dụng mã khuyến mãi',invalid:'Mã không hợp lệ, đã hết hạn hoặc không áp dụng cho lựa chọn này.',validSome:'Mã chỉ áp dụng cho một số gói được hiển thị.',discount:'Giảm giá khuyến mãi',before:'Giá trước mã',saved:'Tiết kiệm thêm'}
}
