const texts={
  de:['Der fertige KI-Entwurf wird privat zwischengespeichert. Erst nach Ihrer Prüfung und dem bewussten Speichern wird er in die Dokumentangaben übernommen.','KI-Entwurf gesichert · noch nicht übernommen','KI-Entwurf gesichert. Bitte die Angaben prüfen und bewusst speichern.','KI-Entwurf wiederherstellen','KI-Entwurf wird geladen …','Noch kein wiederherstellbarer KI-Entwurf vorhanden. Eine laufende Analyse bitte zunächst abschließen lassen.','Der KI-Entwurf konnte nicht geladen werden. Bitte erneut versuchen.'],
  en:['The completed AI draft is stored privately for recovery. It only becomes document data after you review and deliberately save it.','AI draft secured · not yet accepted','AI draft secured. Please review the details and deliberately save them.','Restore AI draft','Loading AI draft …','No recoverable AI draft is available yet. Please let any running analysis finish first.','The AI draft could not be loaded. Please try again.'],
  pl:['Gotowy szkic AI jest zapisywany prywatnie, aby można go było odzyskać. Staje się danymi dokumentu dopiero po sprawdzeniu i świadomym zapisaniu.','Szkic AI zapisany · jeszcze nieprzyjęty','Szkic AI zapisany. Sprawdź dane i świadomie je zapisz.','Przywróć szkic AI','Ładowanie szkicu AI …','Brak szkicu AI do przywrócenia. Jeśli analiza trwa, poczekaj na jej zakończenie.','Nie udało się wczytać szkicu AI. Spróbuj ponownie.'],
  tr:['Tamamlanan yapay zekâ taslağı, kurtarma için özel olarak saklanır. Ancak inceleyip bilinçli olarak kaydettikten sonra belge bilgilerine aktarılır.','Yapay zekâ taslağı saklandı · henüz kabul edilmedi','Yapay zekâ taslağı saklandı. Bilgileri inceleyip bilinçli olarak kaydedin.','Yapay zekâ taslağını geri yükle','Yapay zekâ taslağı yükleniyor …','Henüz geri yüklenebilecek taslak yok. Devam eden analiz varsa bitmesini bekleyin.','Yapay zekâ taslağı yüklenemedi. Lütfen tekrar deneyin.'],
  ru:['Готовый черновик ИИ сохраняется приватно для восстановления. Он станет данными документа только после вашей проверки и осознанного сохранения.','Черновик ИИ сохранён · ещё не принят','Черновик ИИ сохранён. Проверьте сведения и осознанно сохраните их.','Восстановить черновик ИИ','Загрузка черновика ИИ …','Черновик для восстановления пока отсутствует. Дождитесь завершения запущенного анализа.','Не удалось загрузить черновик ИИ. Попробуйте ещё раз.'],
  ar:['تُحفظ مسودة الذكاء الاصطناعي المكتملة بشكل خاص لاستعادتها. ولا تصبح بيانات للمستند إلا بعد مراجعتك وحفظك الصريح.','حُفظت مسودة الذكاء الاصطناعي · لم تُعتمد بعد','حُفظت المسودة. يرجى مراجعة المعلومات وحفظها صراحةً.','استعادة مسودة الذكاء الاصطناعي','جارٍ تحميل المسودة …','لا توجد مسودة قابلة للاستعادة بعد. يرجى انتظار انتهاء أي تحليل جارٍ.','تعذر تحميل المسودة. يرجى المحاولة مرة أخرى.'],
  fr:['Le brouillon IA terminé est conservé de manière privée pour pouvoir le récupérer. Il ne devient une donnée du document qu’après votre vérification et un enregistrement explicite.','Brouillon IA conservé · pas encore adopté','Brouillon IA conservé. Vérifiez les informations puis enregistrez-les explicitement.','Récupérer le brouillon IA','Chargement du brouillon IA …','Aucun brouillon IA récupérable pour le moment. Laissez toute analyse en cours se terminer.','Impossible de charger le brouillon IA. Veuillez réessayer.'],
  fa:['پیش‌نویس تکمیل‌شدهٔ هوش مصنوعی به‌صورت خصوصی برای بازیابی ذخیره می‌شود. تنها پس از بررسی و ذخیرهٔ آگاهانهٔ شما به اطلاعات سند تبدیل می‌شود.','پیش‌نویس ذخیره شد · هنوز پذیرفته نشده','پیش‌نویس ذخیره شد. اطلاعات را بررسی و آگاهانه ذخیره کنید.','بازیابی پیش‌نویس هوش مصنوعی','در حال بارگیری پیش‌نویس …','هنوز پیش‌نویسی برای بازیابی وجود ندارد. منتظر پایان تحلیل در حال اجرا بمانید.','بارگیری پیش‌نویس ممکن نشد. دوباره تلاش کنید.'],
  ro:['Ciorna AI finalizată este păstrată privat pentru recuperare. Devine parte din datele documentului doar după verificarea și salvarea explicită de către dvs.','Ciornă AI păstrată · încă nepreluată','Ciornă AI păstrată. Verificați informațiile și salvați-le explicit.','Recuperează ciorna AI','Se încarcă ciorna AI …','Nu există încă o ciornă AI recuperabilă. Așteptați finalizarea oricărei analize în curs.','Ciorna AI nu a putut fi încărcată. Încercați din nou.'],
  bg:['Готовата AI чернова се съхранява поверително за възстановяване. Тя става част от данните на документа едва след ваша проверка и изрично запазване.','AI черновата е съхранена · още не е приета','AI черновата е съхранена. Проверете данните и ги запазете изрично.','Възстановяване на AI черновата','AI черновата се зарежда …','Все още няма чернова за възстановяване. Изчакайте приключването на текущия анализ.','AI черновата не можа да се зареди. Опитайте отново.'],
  vi:['Bản nháp AI hoàn tất được lưu riêng tư để có thể khôi phục. Chỉ sau khi bạn kiểm tra và chủ động lưu, nội dung mới được đưa vào dữ liệu tài liệu.','Đã lưu bản nháp AI · chưa tiếp nhận','Đã lưu bản nháp AI. Hãy kiểm tra thông tin và chủ động lưu.','Khôi phục bản nháp AI','Đang tải bản nháp AI …','Chưa có bản nháp AI để khôi phục. Vui lòng đợi quá trình phân tích đang chạy hoàn tất.','Không tải được bản nháp AI. Vui lòng thử lại.']
}
export function documentAnalysisRecoveryCopy(language='de'){
  const [lead,draft,ready,restore,restoring,noDraft,recoveryFailed]=texts[language]||texts.de
  return {lead,draft,ready,restore,restoring,noDraft,recoveryFailed}
}
