export const documentIntakeCopy=Object.freeze({
  de:{file:'Dokument',sourceLanguage:'Dokumentsprache',auto:'Automatisch bei Analyse erkennen',quality:'Vorprüfung',ready:'Datei technisch verwendbar',imageGood:'Bildauflösung ausreichend',imageWeak:'Bildauflösung niedrig – besser neu fotografieren',size:'Dateigröße',type:'Format',voiceTitle:'Problem sprechen',voiceHelp:'Sprechen Sie frei. Der erkannte Text wird zuerst angezeigt und erst nach Ihrer Bestätigung übernommen.',voiceLanguage:'Gesprochene Sprache',voiceStart:'Mikrofon starten',voiceStop:'Aufnahme stoppen',voiceUnsupported:'Spracherkennung wird von diesem Browser nicht unterstützt.',voiceDraft:'Erkannter Text',voiceConfirm:'Text übernehmen',voiceConfirmed:'Gesprochener Kontext übernommen',voiceClear:'Löschen'},
  en:{file:'Document',sourceLanguage:'Document language',auto:'Detect automatically during analysis',quality:'Pre-check',ready:'File technically usable',imageGood:'Image resolution looks sufficient',imageWeak:'Low image resolution – retake the photo if possible',size:'File size',type:'Format',voiceTitle:'Speak about the problem',voiceHelp:'Speak freely. The transcript is shown first and is only accepted after confirmation.',voiceLanguage:'Spoken language',voiceStart:'Start microphone',voiceStop:'Stop recording',voiceUnsupported:'Speech recognition is not supported by this browser.',voiceDraft:'Transcript',voiceConfirm:'Accept text',voiceConfirmed:'Spoken context accepted',voiceClear:'Clear'},
  pl:{file:'Dokument',sourceLanguage:'Język dokumentu',auto:'Wykryj automatycznie podczas analizy',quality:'Kontrola wstępna',ready:'Plik nadaje się technicznie do użycia',imageGood:'Rozdzielczość obrazu jest wystarczająca',imageWeak:'Niska rozdzielczość obrazu – najlepiej zrobić nowe zdjęcie',size:'Rozmiar pliku',type:'Format',voiceTitle:'Opowiedz o problemie',voiceHelp:'Mów swobodnie. Tekst zostanie najpierw wyświetlony i dopiero po potwierdzeniu przyjęty.',voiceLanguage:'Język mówiony',voiceStart:'Uruchom mikrofon',voiceStop:'Zatrzymaj nagrywanie',voiceUnsupported:'Ta przeglądarka nie obsługuje rozpoznawania mowy.',voiceDraft:'Rozpoznany tekst',voiceConfirm:'Zatwierdź tekst',voiceConfirmed:'Kontekst głosowy został przyjęty',voiceClear:'Usuń'},
  tr:{file:'Belge',sourceLanguage:'Belge dili',auto:'Analiz sırasında otomatik algıla',quality:'Ön kontrol',ready:'Dosya teknik olarak kullanılabilir',imageGood:'Görüntü çözünürlüğü yeterli',imageWeak:'Görüntü çözünürlüğü düşük – mümkünse yeniden fotoğraf çekin',size:'Dosya boyutu',type:'Biçim',voiceTitle:'Sorunu anlatın',voiceHelp:'Serbestçe konuşun. Metin önce gösterilir ve yalnızca onayınızdan sonra alınır.',voiceLanguage:'Konuşulan dil',voiceStart:'Mikrofonu başlat',voiceStop:'Kaydı durdur',voiceUnsupported:'Bu tarayıcı konuşma tanımayı desteklemiyor.',voiceDraft:'Algılanan metin',voiceConfirm:'Metni onayla',voiceConfirmed:'Sesli bağlam kaydedildi',voiceClear:'Temizle'},
  ru:{file:'Документ',sourceLanguage:'Язык документа',auto:'Определить автоматически при анализе',quality:'Предварительная проверка',ready:'Файл технически пригоден',imageGood:'Разрешение изображения достаточное',imageWeak:'Низкое разрешение изображения — лучше сделать новое фото',size:'Размер файла',type:'Формат',voiceTitle:'Расскажите о проблеме',voiceHelp:'Говорите свободно. Сначала текст будет показан, и только после подтверждения принят.',voiceLanguage:'Язык речи',voiceStart:'Включить микрофон',voiceStop:'Остановить запись',voiceUnsupported:'Этот браузер не поддерживает распознавание речи.',voiceDraft:'Распознанный текст',voiceConfirm:'Принять текст',voiceConfirmed:'Голосовой контекст принят',voiceClear:'Очистить'},
  ar:{file:'المستند',sourceLanguage:'لغة المستند',auto:'اكتشاف تلقائي أثناء التحليل',quality:'فحص أولي',ready:'الملف صالح تقنياً للاستخدام',imageGood:'دقة الصورة كافية',imageWeak:'دقة الصورة منخفضة — يفضل التقاط صورة جديدة',size:'حجم الملف',type:'التنسيق',voiceTitle:'تحدث عن المشكلة',voiceHelp:'تحدث بحرية. سيظهر النص أولاً ولن يُعتمد إلا بعد تأكيدك.',voiceLanguage:'لغة الكلام',voiceStart:'تشغيل الميكروفون',voiceStop:'إيقاف التسجيل',voiceUnsupported:'هذا المتصفح لا يدعم التعرف على الكلام.',voiceDraft:'النص المتعرف عليه',voiceConfirm:'اعتماد النص',voiceConfirmed:'تم اعتماد السياق الصوتي',voiceClear:'مسح'},
  fr:{file:'Document',sourceLanguage:'Langue du document',auto:'Détecter automatiquement pendant l’analyse',quality:'Pré-contrôle',ready:'Fichier techniquement exploitable',imageGood:'Résolution de l’image suffisante',imageWeak:'Résolution faible — mieux vaut reprendre la photo',size:'Taille du fichier',type:'Format',voiceTitle:'Décrire le problème à l’oral',voiceHelp:'Parlez librement. Le texte est d’abord affiché puis accepté uniquement après votre confirmation.',voiceLanguage:'Langue parlée',voiceStart:'Démarrer le micro',voiceStop:'Arrêter l’enregistrement',voiceUnsupported:'La reconnaissance vocale n’est pas prise en charge par ce navigateur.',voiceDraft:'Texte reconnu',voiceConfirm:'Valider le texte',voiceConfirmed:'Contexte vocal accepté',voiceClear:'Effacer'},
  fa:{file:'سند',sourceLanguage:'زبان سند',auto:'تشخیص خودکار هنگام تحلیل',quality:'بررسی اولیه',ready:'فایل از نظر فنی قابل استفاده است',imageGood:'وضوح تصویر کافی است',imageWeak:'وضوح تصویر پایین است — بهتر است دوباره عکس بگیرید',size:'حجم فایل',type:'فرمت',voiceTitle:'مشکل را توضیح دهید',voiceHelp:'آزادانه صحبت کنید. متن ابتدا نمایش داده می‌شود و فقط پس از تأیید شما ثبت می‌شود.',voiceLanguage:'زبان گفتار',voiceStart:'شروع میکروفون',voiceStop:'توقف ضبط',voiceUnsupported:'این مرورگر از تشخیص گفتار پشتیبانی نمی‌کند.',voiceDraft:'متن تشخیص‌داده‌شده',voiceConfirm:'تأیید متن',voiceConfirmed:'متن گفتاری تأیید شد',voiceClear:'پاک کردن'},
  ro:{file:'Document',sourceLanguage:'Limba documentului',auto:'Detectează automat în timpul analizei',quality:'Verificare preliminară',ready:'Fișierul este utilizabil tehnic',imageGood:'Rezoluția imaginii este suficientă',imageWeak:'Rezoluție scăzută – este mai bine să fotografiați din nou',size:'Dimensiunea fișierului',type:'Format',voiceTitle:'Descrie problema prin voce',voiceHelp:'Vorbiți liber. Textul este afișat mai întâi și este preluat doar după confirmare.',voiceLanguage:'Limba vorbită',voiceStart:'Pornește microfonul',voiceStop:'Oprește înregistrarea',voiceUnsupported:'Acest browser nu acceptă recunoașterea vocală.',voiceDraft:'Text recunoscut',voiceConfirm:'Confirmă textul',voiceConfirmed:'Contextul vocal a fost preluat',voiceClear:'Șterge'},
  bg:{file:'Документ',sourceLanguage:'Език на документа',auto:'Автоматично разпознаване при анализа',quality:'Предварителна проверка',ready:'Файлът е технически годен',imageGood:'Резолюцията на изображението е достатъчна',imageWeak:'Ниска резолюция – по-добре направете нова снимка',size:'Размер на файла',type:'Формат',voiceTitle:'Разкажете за проблема',voiceHelp:'Говорете свободно. Текстът първо се показва и се приема само след потвърждение.',voiceLanguage:'Говорим език',voiceStart:'Стартирай микрофона',voiceStop:'Спри записа',voiceUnsupported:'Този браузър не поддържа разпознаване на реч.',voiceDraft:'Разпознат текст',voiceConfirm:'Потвърди текста',voiceConfirmed:'Гласовият контекст е приет',voiceClear:'Изчисти'},
  vi:{file:'Tài liệu',sourceLanguage:'Ngôn ngữ tài liệu',auto:'Tự động nhận diện khi phân tích',quality:'Kiểm tra ban đầu',ready:'Tệp có thể sử dụng về mặt kỹ thuật',imageGood:'Độ phân giải hình ảnh đủ tốt',imageWeak:'Độ phân giải thấp – nên chụp lại ảnh',size:'Kích thước tệp',type:'Định dạng',voiceTitle:'Nói về vấn đề',voiceHelp:'Hãy nói tự nhiên. Văn bản sẽ được hiển thị trước và chỉ được chấp nhận sau khi bạn xác nhận.',voiceLanguage:'Ngôn ngữ nói',voiceStart:'Bật micro',voiceStop:'Dừng ghi âm',voiceUnsupported:'Trình duyệt này không hỗ trợ nhận dạng giọng nói.',voiceDraft:'Văn bản nhận dạng',voiceConfirm:'Xác nhận văn bản',voiceConfirmed:'Đã lưu ngữ cảnh bằng giọng nói',voiceClear:'Xóa'}
})

export function intakeCopy(language){return documentIntakeCopy[language]||documentIntakeCopy.de}
