const copy={
  de:{warn:'Foto bitte kurz prüfen',help:'Sind Text, Zahlen und alle Seitenränder gut erkennbar? Dann können Sie dieses Foto hochladen. Sonst bitte neu aufnehmen.',low_contrast:'Kaum erkennbare Bilddetails',unreadable:'Das Bild konnte nicht geprüft werden. Bitte als JPG oder PNG erneut auswählen.'},
  en:{warn:'Please check the photo',help:'Are the text, numbers and all page edges visible? If so, you can upload this photo. Otherwise, take it again.',low_contrast:'Very little visible image detail',unreadable:'The image could not be checked. Please select it again as JPG or PNG.'},
  pl:{warn:'Sprawdź zdjęcie',help:'Czy tekst, liczby i wszystkie krawędzie strony są widoczne? Jeśli tak, możesz przesłać zdjęcie. W przeciwnym razie zrób je ponownie.',low_contrast:'Bardzo mało widocznych szczegółów obrazu',unreadable:'Nie można sprawdzić obrazu. Wybierz go ponownie w formacie JPG lub PNG.'},
  tr:{warn:'Lütfen fotoğrafı kontrol edin',help:'Metin, sayılar ve tüm sayfa kenarları görünüyor mu? Öyleyse fotoğrafı yükleyebilirsiniz. Değilse yeniden çekin.',low_contrast:'Görüntüde çok az ayrıntı seçiliyor',unreadable:'Görüntü kontrol edilemedi. Lütfen JPG veya PNG olarak yeniden seçin.'},
  ru:{warn:'Проверьте фотографию',help:'Видны ли текст, числа и все края страницы? Если да, фотографию можно загрузить. Иначе сделайте её заново.',low_contrast:'На изображении почти не видно деталей',unreadable:'Не удалось проверить изображение. Выберите его заново в формате JPG или PNG.'},
  ar:{warn:'يرجى التحقق من الصورة',help:'هل النص والأرقام وجميع حواف الصفحة واضحة؟ إذا كانت كذلك، يمكنك رفع الصورة. وإلا فأعد التقاطها.',low_contrast:'تفاصيل الصورة غير واضحة تقريباً',unreadable:'تعذر فحص الصورة. يرجى اختيارها مجدداً بصيغة JPG أو PNG.'},
  fa:{warn:'لطفاً عکس را بررسی کنید',help:'آیا متن، اعداد و همه لبه‌های صفحه مشخص هستند؟ اگر بله، می‌توانید این عکس را بارگذاری کنید. در غیر این صورت دوباره عکس بگیرید.',low_contrast:'جزئیات تصویر تقریباً مشخص نیست',unreadable:'بررسی تصویر ممکن نشد. لطفاً آن را دوباره با فرمت JPG یا PNG انتخاب کنید.'},
  fr:{warn:'Veuillez vérifier la photo',help:'Le texte, les chiffres et tous les bords de la page sont-ils visibles ? Si oui, vous pouvez envoyer cette photo. Sinon, reprenez-la.',low_contrast:'Très peu de détails visibles dans l’image',unreadable:'L’image n’a pas pu être vérifiée. Sélectionnez-la à nouveau au format JPG ou PNG.'},
  ro:{warn:'Verificați fotografia',help:'Textul, numerele și toate marginile paginii sunt vizibile? Dacă da, puteți încărca fotografia. Altfel, fotografiați din nou.',low_contrast:'Foarte puține detalii vizibile în imagine',unreadable:'Imaginea nu a putut fi verificată. Selectați-o din nou ca JPG sau PNG.'},
  bg:{warn:'Проверете снимката',help:'Виждат ли се текстът, числата и всички краища на страницата? Ако да, можете да качите снимката. Иначе снимайте отново.',low_contrast:'Почти няма видими детайли в изображението',unreadable:'Изображението не можа да бъде проверено. Изберете го отново като JPG или PNG.'},
  vi:{warn:'Vui lòng kiểm tra ảnh',help:'Văn bản, số và tất cả các cạnh trang có rõ không? Nếu có, bạn có thể tải ảnh này lên. Nếu không, hãy chụp lại.',low_contrast:'Hầu như không thấy chi tiết trong ảnh',unreadable:'Không thể kiểm tra ảnh. Vui lòng chọn lại dưới dạng JPG hoặc PNG.'}
}
export function imageQualityGuidance(language='de'){return copy[language]||copy.de}
