const keys=['title','working','cancelled','statusUnavailable']
const rows={
  de:['Ihre Antwort wird vorbereitet','Der Auftrag ist gespeichert und läuft im Hintergrund weiter. Sie können diese Seite schließen. Das Ergebnis finden Sie später in diesem Fall.','Der Auftrag wurde beendet. Ihre Unterlagen bleiben gespeichert.','Der aktuelle Auftragsstatus konnte nicht geladen werden. Ein gespeicherter Auftrag wird dadurch nicht erneut gestartet.'],
  en:['Your answer is being prepared','Your request is saved and continues in the background. You can close this page. Return to this case later for the result.','The request was cancelled. Your documents remain saved.','The current request status could not be loaded. This does not restart a saved request.'],
  fr:['Votre réponse est en préparation','La demande est enregistrée et continue en arrière-plan. Vous pouvez fermer cette page. Retrouvez le résultat plus tard dans ce dossier.','La demande a été annulée. Vos documents restent enregistrés.','Le statut actuel n’a pas pu être chargé. Une demande enregistrée n’est pas relancée pour autant.'],
  tr:['Yanıtınız hazırlanıyor','İsteğiniz kaydedildi ve arka planda devam ediyor. Bu sayfayı kapatabilirsiniz. Sonucu daha sonra bu dosyada bulabilirsiniz.','İstek iptal edildi. Belgeleriniz kayıtlı kalır.','İsteğin güncel durumu yüklenemedi. Kaydedilmiş istek yeniden başlatılmaz.'],
  pl:['Twoja odpowiedź jest przygotowywana','Zlecenie zapisano i jest przetwarzane w tle. Możesz zamknąć stronę. Wynik znajdziesz później w tej sprawie.','Zlecenie anulowano. Dokumenty pozostają zapisane.','Nie udało się wczytać aktualnego statusu. Zapisane zlecenie nie zostanie przez to uruchomione ponownie.'],
  ru:['Ваш ответ готовится','Задание сохранено и выполняется в фоновом режиме. Можно закрыть страницу. Результат появится в этом деле.','Задание отменено. Документы остаются сохранёнными.','Не удалось загрузить текущий статус. Сохранённое задание не запускается повторно.'],
  ar:['يجري إعداد إجابتك','تم حفظ الطلب وتستمر معالجته في الخلفية. يمكنك إغلاق الصفحة. ستجد النتيجة لاحقاً في هذه القضية.','تم إلغاء الطلب. تبقى مستنداتك محفوظة.','تعذّر تحميل الحالة الحالية. لن يؤدي ذلك إلى إعادة تشغيل الطلب المحفوظ.'],
  fa:['پاسخ شما در حال آماده شدن است','درخواست ذخیره شده و در پس‌زمینه ادامه دارد. می‌توانید صفحه را ببندید. نتیجه را بعداً در همین پرونده خواهید یافت.','درخواست لغو شد. اسناد شما ذخیره می‌مانند.','وضعیت فعلی بارگیری نشد. درخواست ذخیره‌شده دوباره شروع نمی‌شود.'],
  ro:['Răspunsul este în pregătire','Cererea este salvată și continuă în fundal. Puteți închide pagina. Rezultatul va fi disponibil mai târziu în acest dosar.','Cererea a fost anulată. Documentele rămân salvate.','Starea actuală nu a putut fi încărcată. Cererea salvată nu este repornită.'],
  bg:['Вашият отговор се подготвя','Заявката е запазена и се обработва във фонов режим. Можете да затворите страницата. Резултатът ще бъде в този случай.','Заявката е отменена. Документите ви остават запазени.','Текущото състояние не може да се зареди. Запазената заявка не се стартира повторно.'],
  vi:['Đang chuẩn bị câu trả lời','Yêu cầu đã được lưu và tiếp tục xử lý ở chế độ nền. Bạn có thể đóng trang này và xem kết quả sau trong hồ sơ này.','Yêu cầu đã bị hủy. Tài liệu của bạn vẫn được lưu.','Không thể tải trạng thái hiện tại. Yêu cầu đã lưu sẽ không bị khởi chạy lại.']
}
export function backgroundCaseCopy(language='de'){return Object.fromEntries(keys.map((key,index)=>[key,(rows[language]||rows.de)[index]]))}
