const copy={
  de:{fallback:'Fallangaben und Unterlagen prüfen.',today:'Jetzt / heute',soon:'Zeitnah',normal:'Als Nächstes',missing:'Zuerst fehlende Unterlagen oder Informationen ergänzen.',deadlineMissing:'Akute Frist sichern: fehlende Unterlagen gezielt ergänzen und die fristwahrende Handlung heute vorbereiten.',deadline:'Die Frist hat Vorrang vor nachgeordneten Arbeitsschritten.',assessment:'Die dokumentierte Bewertung enthält einen konkreten Folgeschritt.',case:'Dieser Schritt ist im Fall als nächste Aktion hinterlegt.',uncertain:'Die Datenlage reicht noch nicht für eine belastbare Handlungsempfehlung.'},
  en:{fallback:'Review the case details and documents.',today:'Now / today',soon:'Soon',normal:'Next',missing:'First add missing documents or information.',deadlineMissing:'Protect the urgent deadline: add the missing information needed and prepare the deadline-preserving action today.',deadline:'The deadline takes priority over lower-priority work.',assessment:'The documented assessment contains a concrete follow-up step.',case:'This step is stored as the next action in the case.',uncertain:'There is not enough reliable information for a firm recommendation yet.'},
  fr:{fallback:'Vérifier les informations du dossier et les documents.',today:'Maintenant / aujourd’hui',soon:'Rapidement',normal:'Ensuite',missing:'Compléter d’abord les documents ou informations manquants.',deadlineMissing:'Sécuriser le délai urgent : compléter les informations nécessaires et préparer aujourd’hui l’action qui préserve le délai.',deadline:'Le délai est prioritaire sur les tâches secondaires.',assessment:'L’évaluation documentée contient une étape suivante concrète.',case:'Cette étape est enregistrée comme prochaine action du dossier.',uncertain:'Les informations ne suffisent pas encore pour une recommandation fiable.'},
  tr:{fallback:'Dosya bilgilerini ve belgeleri kontrol edin.',today:'Şimdi / bugün',soon:'Yakında',normal:'Sıradaki',missing:'Önce eksik belge veya bilgileri tamamlayın.',deadlineMissing:'Acil süreyi koruyun: gerekli eksik bilgileri tamamlayın ve süreyi koruyan işlemi bugün hazırlayın.',deadline:'Süre, ikincil işlerden önce gelir.',assessment:'Belgelenmiş değerlendirmede somut bir sonraki adım var.',case:'Bu adım dosyada sonraki işlem olarak kayıtlıdır.',uncertain:'Güvenilir bir öneri için bilgi henüz yeterli değil.'},
  pl:{fallback:'Sprawdź dane sprawy i dokumenty.',today:'Teraz / dziś',soon:'Wkrótce',normal:'Następnie',missing:'Najpierw uzupełnij brakujące dokumenty lub informacje.',deadlineMissing:'Zabezpiecz pilny termin: uzupełnij potrzebne braki i przygotuj dziś czynność zachowującą termin.',deadline:'Termin ma pierwszeństwo przed mniej pilnymi czynnościami.',assessment:'Udokumentowana ocena zawiera konkretny kolejny krok.',case:'Ten krok jest zapisany w sprawie jako następna czynność.',uncertain:'Brakuje jeszcze wystarczającej podstawy do pewnej rekomendacji.'},
  ru:{fallback:'Проверьте данные дела и документы.',today:'Сейчас / сегодня',soon:'В ближайшее время',normal:'Далее',missing:'Сначала дополните недостающие документы или сведения.',deadlineMissing:'Сохраните срочный срок: дополните необходимые сведения и сегодня подготовьте действие, сохраняющее срок.',deadline:'Срок имеет приоритет над второстепенными действиями.',assessment:'В документированной оценке указан конкретный следующий шаг.',case:'Этот шаг сохранён в деле как следующее действие.',uncertain:'Данных пока недостаточно для надёжной рекомендации.'},
  ar:{fallback:'راجع بيانات الحالة والمستندات.',today:'الآن / اليوم',soon:'قريبًا',normal:'التالي',missing:'أكمل أولًا المستندات أو المعلومات الناقصة.',deadlineMissing:'احمِ المهلة العاجلة: أكمل المعلومات الناقصة اللازمة وجهّز اليوم الإجراء الذي يحافظ على المهلة.',deadline:'الموعد النهائي له الأولوية على الخطوات الأقل إلحاحًا.',assessment:'التقييم الموثق يتضمن خطوة متابعة واضحة.',case:'هذه الخطوة مسجلة في الحالة كالإجراء التالي.',uncertain:'المعلومات الحالية لا تكفي بعد لتوصية موثوقة.'},
  fa:{fallback:'اطلاعات پرونده و مدارک را بررسی کنید.',today:'اکنون / امروز',soon:'به‌زودی',normal:'مرحله بعد',missing:'ابتدا مدارک یا اطلاعات ناقص را تکمیل کنید.',deadlineMissing:'مهلت فوری را حفظ کنید: اطلاعات ضروریِ ناقص را تکمیل و اقدام لازم برای حفظ مهلت را امروز آماده کنید.',deadline:'مهلت بر کارهای کم‌اولویت‌تر مقدم است.',assessment:'ارزیابی ثبت‌شده یک گام بعدی مشخص دارد.',case:'این گام به‌عنوان اقدام بعدی پرونده ثبت شده است.',uncertain:'اطلاعات فعلی هنوز برای توصیه قابل اتکا کافی نیست.'},
  ro:{fallback:'Verificați datele cazului și documentele.',today:'Acum / astăzi',soon:'În curând',normal:'În continuare',missing:'Completați mai întâi documentele sau informațiile lipsă.',deadlineMissing:'Protejați termenul urgent: completați informațiile necesare lipsă și pregătiți astăzi acțiunea care conservă termenul.',deadline:'Termenul are prioritate față de activitățile secundare.',assessment:'Evaluarea documentată conține un pas următor concret.',case:'Acest pas este salvat în caz ca următoarea acțiune.',uncertain:'Informațiile nu sunt încă suficiente pentru o recomandare sigură.'},
  bg:{fallback:'Проверете данните по случая и документите.',today:'Сега / днес',soon:'Скоро',normal:'Следващо',missing:'Първо допълнете липсващите документи или информация.',deadlineMissing:'Запазете спешния срок: допълнете необходимата липсваща информация и подгответе днес действието за запазване на срока.',deadline:'Срокът има предимство пред по-маловажните действия.',assessment:'Документираната оценка съдържа конкретна следваща стъпка.',case:'Тази стъпка е записана в случая като следващо действие.',uncertain:'Информацията все още не е достатъчна за надеждна препоръка.'}
}

export function prioritizeNextStep({language='de',missing=false,deadlineStatus='uncertain',deadlineAction='',assessments=[],caseNext=''}={}){
  const t=copy[language]||copy.de
  if(['immediate','overdue'].includes(deadlineStatus)) return {action:missing?t.deadlineMissing:(deadlineAction||t.fallback),when:t.today,why:t.deadline,kind:'deadline'}
  if(missing) return {action:t.missing,when:t.today,why:t.uncertain,kind:'missing'}
  if(deadlineStatus==='high') return {action:deadlineAction||t.fallback,when:t.soon,why:t.deadline,kind:'deadline'}
  const rank={red:0,yellow:1,green:2}
  const prioritized=[...assessments].filter(a=>a&&a.next).sort((a,b)=>(rank[a.traffic]??3)-(rank[b.traffic]??3))[0]
  if(prioritized) return {action:prioritized.next,when:prioritized.traffic==='red'?t.today:t.soon,why:t.assessment,kind:'assessment'}
  if(caseNext&&caseNext!=='—') return {action:caseNext,when:t.normal,why:t.case,kind:'case'}
  return {action:t.fallback,when:t.normal,why:t.uncertain,kind:'uncertain'}
}

export const supportedRecommendationLanguages=Object.keys(copy)
