// Primary source allowlist. Country scope is not a finding about applicable law.
export const RESEARCH_COUNTRIES={
  DE:{label:'Deutschland / deutsches Recht',domains:['recht.bund.de','verwaltung.bund.de','gesetze-im-internet.de','bundesanzeiger.de','justiz.de','bundesverfassungsgericht.de','bundesgerichtshof.de','bundesarbeitsgericht.de','bsg.bund.de','bverwg.de','bundesfinanzhof.de','bundesjustizamt.de','bfdi.bund.de','bundesfinanzministerium.de','deutsche-rentenversicherung.de','tk.de','bundesgesundheitsministerium.de','finanzamt.hamburg.de'],caveat:'Federal and Länder responsibilities may differ; do not infer a competent authority without the place and subject matter.'},
  PL:{label:'Polen / polnischer Rechtsraum',domains:['sejm.gov.pl','isap.sejm.gov.pl','dziennikustaw.gov.pl','gov.pl','sn.pl','nsa.gov.pl','trybunal.gov.pl','uodo.gov.pl'],caveat:'Use the current Polish text; unofficial translations do not establish the binding wording.'},
  FR:{label:'Frankreich / französischer Rechtsraum',domains:['legifrance.gouv.fr','service-public.fr','service-public.gouv.fr','courdecassation.fr','conseil-etat.fr','conseil-constitutionnel.fr','cnil.fr'],caveat:'Use the current French official text and distinguish legislation, administrative guidance and case law.'},
  TR:{label:'Türkiye / türkischer Rechtsraum',domains:['mevzuat.gov.tr','resmigazete.gov.tr','adalet.gov.tr','anayasa.gov.tr','yargitay.gov.tr','danistay.gov.tr','kvkk.gov.tr','goc.gov.tr','csgb.gov.tr'],caveat:'The binding sources are normally Turkish; translations must be identified as translations and not treated as the controlling text.'},
  GB:{label:'Vereinigtes Königreich',domains:['legislation.gov.uk','gov.uk','judiciary.uk','supremecourt.uk','ico.org.uk'],caveat:'The United Kingdom contains distinct legal systems. England and Wales, Scotland, and Northern Ireland must not be treated as one jurisdiction when the distinction matters.'},
  US:{label:'USA',domains:['uscode.house.gov','congress.gov','govinfo.gov','supremecourt.gov','justice.gov','uscourts.gov','dol.gov','ftc.gov'],caveat:'Federal law and state law are separate. Without a named state, do not claim a complete US rule where state law may control.'},
  RU:{label:'Russland / russischer Rechtsraum',domains:['pravo.gov.ru','publication.pravo.gov.ru','government.ru','vsrf.ru','ksrf.ru'],caveat:'Source accessibility and translations may be limited. Treat any missing current official text as an unresolved source gap.'},
  RO:{label:'Rumänien / rumänischer Rechtsraum',domains:['legislatie.just.ro','just.ro','portal.just.ro','scj.ro','ccr.ro','monitoruloficial.ro','dataprotection.ro'],caveat:'Use the current Romanian official text and distinguish the Official Gazette from consolidated information portals.'},
  BG:{label:'Bulgarien / bulgarischer Rechtsraum',domains:['dv.parliament.bg','parliament.bg','justice.government.bg','vks.bg','sac.government.bg','constcourt.bg','cpdp.bg'],caveat:'Use the current Bulgarian official text; translated summaries alone are not sufficient for a verified claim.'},
  VN:{label:'Vietnam / vietnamesischer Rechtsraum',domains:['phapluat.gov.vn','vietnam.gov.vn','vanban.chinhphu.vn','moj.gov.vn','toaan.gov.vn','quochoi.vn'],caveat:'Use the current Vietnamese official text and show uncertainty when a reliable official translation is unavailable.'},
  SA:{label:'Saudi-Arabien',domains:['boe.gov.sa','laws.boe.gov.sa','moj.gov.sa','laws.moj.gov.sa','hrsd.gov.sa','my.gov.sa'],caveat:'Use current official Saudi sources; distinguish statutes and regulations from general service guidance.'},
  AE:{label:'Vereinigte Arabische Emirate',domains:['uaelegislation.gov.ae','u.ae','moj.gov.ae','dlp.dubai.gov.ae'],caveat:'Federal and Emirate-level rules may differ. Without the relevant Emirate, do not claim a complete rule where local law may control.'},
  IR:{label:'Iran',domains:['dotic.ir','qavanin.ir','rc.majlis.ir','judiciary.ir','divan-edalat.ir'],caveat:'Use the current Persian official text and show a source gap when authoritative current material cannot be accessed.'},
  AF:{label:'Afghanistan',domains:['moj.gov.af','supremecourt.gov.af'],caveat:'The current, applicable legal framework may be difficult to establish. Never bridge missing or conflicting official sources by inference.'}
};
export const SHARED_RESEARCH_DOMAINS=['eur-lex.europa.eu','curia.europa.eu','e-justice.europa.eu','hcch.net','treaties.un.org','coe.int'];

