'use client'

import { useState } from 'react'

const confidenceLabels = (high,medium,low) => ({hoch:high,high,mittel:medium,medium,mid:medium,niedrig:low,low})

const copy = {
  de:{badge:'V26 · kontrollierte Analyse',title:'KI-Vorschlag bewusst starten',lead:'Die Originaldatei ist privat gespeichert. Eine KI-Auswertung startet erst nach Ihrer ausdrücklichen Bestätigung und bleibt bis zum Speichern ein vorläufiger Vorschlag.',privacyTitle:'Keine echten Kundendaten im Testbetrieb',privacyText:'Verwenden Sie ausschließlich interne Testdateien ohne echte Kundendaten. „Analyse starten“ übermittelt die Datei serverseitig an den KI-Dienst.',confirm:'Ich bestätige, dass dies eine interne Testdatei ohne echte Kundendaten ist.',start:'Analyse starten',analyzing:'Dokument wird analysiert …',unsupported:'Automatisches Auslesen ist derzeit nur für PDF, JPG, PNG, WEBP und GIF möglich. Sie können die Felder trotzdem manuell ausfüllen.',limit:'KI-Analyse: maximal 18 MB pro Datei. Die Upload-Testgrenze von 50 MB gilt nicht für die automatische Auswertung.',uploaded:'Analyse noch nicht gestartet',draft:'KI-Vorschlag · vorläufig und nicht gespeichert',saved:'Geprüfte Angaben gespeichert',facts:'Erkannte Zusatzangaben zur Prüfung',sender:'Absender / Verfasser',recipient:'Empfänger',references:'Akten- / Referenznummern',deadlines:'Genannte Fristen',amounts:'Genannte Beträge',confidence:'Erkennungssicherheit',none:'Keine erkannt',manual:'Alle Vorschläge bleiben änderbar. Erst der Speichern-Button übernimmt die geprüften Angaben.',save:'Geprüfte Angaben bewusst speichern',ready:'Analyse abgeschlossen. Bitte alle Angaben prüfen und anschließend bewusst speichern.',failed:'Die Analyse konnte nicht abgeschlossen werden.',savedMessage:'Die geprüften Dokumentangaben wurden gespeichert.',notStarted:'Noch keine Analyse gestartet. Eine belastbare Bewertung ist ohne geprüften Inhalt nicht möglich.',confidenceValues:confidenceLabels('Hoch','Mittel','Niedrig')},
  en:{badge:'V26 · controlled analysis',title:'Deliberately start AI suggestion',lead:'The original file is stored privately. AI analysis starts only after your explicit confirmation and remains provisional until saved.',privacyTitle:'No real customer data during testing',privacyText:'Use internal test files without real customer data only. “Start analysis” sends the file server-side to the AI service.',confirm:'I confirm this is an internal test file without real customer data.',start:'Start analysis',analyzing:'Analysing document …',unsupported:'Automatic reading currently supports PDF, JPG, PNG, WEBP and GIF only. You can still complete the fields manually.',limit:'AI analysis: maximum 18 MB per file. The temporary 50 MB upload limit does not apply to automatic analysis.',uploaded:'Analysis not started',draft:'AI suggestion · provisional and not saved',saved:'Reviewed details saved',facts:'Additional recognised details to review',sender:'Sender / author',recipient:'Recipient',references:'File / reference numbers',deadlines:'Stated deadlines',amounts:'Stated amounts',confidence:'Recognition confidence',none:'None recognised',manual:'Every suggestion remains editable. Only the save button adopts the reviewed details.',save:'Deliberately save reviewed details',ready:'Analysis completed. Review every detail, then deliberately save it.',failed:'The analysis could not be completed.',savedMessage:'The reviewed document details were saved.',notStarted:'Analysis has not started. A reliable assessment is not possible without reviewed content.',confidenceValues:confidenceLabels('High','Medium','Low')},
  tr:{badge:'V26 · kontrollü analiz',title:'Yapay zekâ önerisini bilinçli başlat',lead:'Orijinal dosya özel olarak saklanır. Analiz yalnızca açık onayınızla başlar ve kaydedilene kadar geçici kalır.',privacyTitle:'Test sırasında gerçek müşteri verisi yok',privacyText:'Yalnızca gerçek müşteri verisi içermeyen dahili test dosyaları kullanın. “Analizi başlat” dosyayı sunucu üzerinden yapay zekâ hizmetine gönderir.',confirm:'Bunun gerçek müşteri verisi içermeyen dahili bir test dosyası olduğunu onaylıyorum.',start:'Analizi başlat',analyzing:'Belge analiz ediliyor …',unsupported:'Otomatik okuma yalnızca PDF, JPG, PNG, WEBP ve GIF için mümkündür. Alanları yine de elle doldurabilirsiniz.',limit:'Yapay zekâ analizi: dosya başına en fazla 18 MB. Geçici 50 MB yükleme sınırı otomatik analiz için geçerli değildir.',uploaded:'Analiz başlamadı',draft:'Yapay zekâ önerisi · geçici ve kaydedilmedi',saved:'İncelenen bilgiler kaydedildi',facts:'İncelenecek ek bilgiler',sender:'Gönderen / yazar',recipient:'Alıcı',references:'Dosya / referans numaraları',deadlines:'Belirtilen süreler',amounts:'Belirtilen tutarlar',confidence:'Tanıma güveni',none:'Tanınmadı',manual:'Tüm öneriler değiştirilebilir. İncelenen bilgiler yalnızca kaydet düğmesiyle alınır.',save:'İncelenen bilgileri bilinçli kaydet',ready:'Analiz tamamlandı. Tüm bilgileri kontrol edip bilinçli olarak kaydedin.',failed:'Analiz tamamlanamadı.',savedMessage:'İncelenen belge bilgileri kaydedildi.',notStarted:'Analiz henüz başlamadı. İncelenmiş içerik olmadan güvenilir değerlendirme yapılamaz.',confidenceValues:confidenceLabels('Yüksek','Orta','Düşük')},
  pl:{badge:'V26 · kontrolowana analiza',title:'Świadomie uruchom propozycję AI',lead:'Oryginalny plik jest zapisany prywatnie. Analiza rozpoczyna się dopiero po wyraźnym potwierdzeniu i pozostaje wstępna do chwili zapisania.',privacyTitle:'Bez prawdziwych danych klientów podczas testu',privacyText:'Używaj wyłącznie wewnętrznych plików testowych bez prawdziwych danych klientów. „Rozpocznij analizę” przesyła plik po stronie serwera do usługi AI.',confirm:'Potwierdzam, że jest to wewnętrzny plik testowy bez prawdziwych danych klientów.',start:'Rozpocznij analizę',analyzing:'Analizowanie dokumentu …',unsupported:'Automatyczny odczyt obsługuje tylko PDF, JPG, PNG, WEBP i GIF. Pola można nadal uzupełnić ręcznie.',limit:'Analiza AI: maksymalnie 18 MB na plik. Tymczasowy limit wysyłania 50 MB nie dotyczy analizy automatycznej.',uploaded:'Analiza nierozpoczęta',draft:'Propozycja AI · wstępna i niezapisana',saved:'Sprawdzone dane zapisane',facts:'Dodatkowe rozpoznane dane do sprawdzenia',sender:'Nadawca / autor',recipient:'Odbiorca',references:'Numery akt / referencji',deadlines:'Wskazane terminy',amounts:'Wskazane kwoty',confidence:'Pewność rozpoznania',none:'Nie rozpoznano',manual:'Każdą propozycję można zmienić. Dopiero przycisk zapisu przejmuje sprawdzone dane.',save:'Świadomie zapisz sprawdzone dane',ready:'Analiza zakończona. Sprawdź wszystkie dane, a następnie świadomie je zapisz.',failed:'Nie udało się zakończyć analizy.',savedMessage:'Sprawdzone dane dokumentu zostały zapisane.',notStarted:'Analiza nie została rozpoczęta. Bez sprawdzonej treści nie jest możliwa rzetelna ocena.',confidenceValues:confidenceLabels('Wysoka','Średnia','Niska')},
  uk:{badge:'V26 · контрольований аналіз',title:'Свідомо запустити пропозицію ШІ',lead:'Оригінальний файл зберігається приватно. Аналіз починається лише після явного підтвердження і до збереження залишається попереднім.',privacyTitle:'Без реальних даних клієнтів під час тесту',privacyText:'Використовуйте лише внутрішні тестові файли без реальних даних клієнтів. «Почати аналіз» передає файл сервером до сервісу ШІ.',confirm:'Підтверджую, що це внутрішній тестовий файл без реальних даних клієнтів.',start:'Почати аналіз',analyzing:'Документ аналізується …',unsupported:'Автоматичне зчитування підтримує лише PDF, JPG, PNG, WEBP і GIF. Поля можна заповнити вручну.',limit:'Аналіз ШІ: не більше 18 МБ на файл. Тимчасовий ліміт завантаження 50 МБ не поширюється на автоматичний аналіз.',uploaded:'Аналіз не розпочато',draft:'Пропозиція ШІ · попередня й не збережена',saved:'Перевірені дані збережено',facts:'Додаткові розпізнані дані для перевірки',sender:'Відправник / автор',recipient:'Одержувач',references:'Номери справи / посилання',deadlines:'Зазначені строки',amounts:'Зазначені суми',confidence:'Надійність розпізнавання',none:'Не розпізнано',manual:'Кожну пропозицію можна змінити. Лише кнопка збереження приймає перевірені дані.',save:'Свідомо зберегти перевірені дані',ready:'Аналіз завершено. Перевірте всі дані, а потім свідомо збережіть їх.',failed:'Не вдалося завершити аналіз.',savedMessage:'Перевірені дані документа збережено.',notStarted:'Аналіз ще не розпочато. Без перевіреного вмісту надійна оцінка неможлива.',confidenceValues:confidenceLabels('Висока','Середня','Низька')},
  ru:{badge:'V26 · контролируемый анализ',title:'Осознанно запустить предложение ИИ',lead:'Исходный файл хранится приватно. Анализ начинается только после явного подтверждения и до сохранения остаётся предварительным.',privacyTitle:'Без реальных данных клиентов во время теста',privacyText:'Используйте только внутренние тестовые файлы без реальных данных клиентов. «Начать анализ» передаёт файл на сервере сервису ИИ.',confirm:'Подтверждаю, что это внутренний тестовый файл без реальных данных клиентов.',start:'Начать анализ',analyzing:'Документ анализируется …',unsupported:'Автоматическое чтение поддерживает только PDF, JPG, PNG, WEBP и GIF. Поля можно заполнить вручную.',limit:'Анализ ИИ: не более 18 МБ на файл. Временный лимит загрузки 50 МБ не применяется к автоматическому анализу.',uploaded:'Анализ не начат',draft:'Предложение ИИ · предварительное и не сохранено',saved:'Проверенные данные сохранены',facts:'Дополнительные распознанные данные для проверки',sender:'Отправитель / автор',recipient:'Получатель',references:'Номера дела / ссылки',deadlines:'Указанные сроки',amounts:'Указанные суммы',confidence:'Уверенность распознавания',none:'Не распознано',manual:'Каждое предложение можно изменить. Только кнопка сохранения принимает проверенные данные.',save:'Осознанно сохранить проверенные данные',ready:'Анализ завершён. Проверьте все данные, затем осознанно сохраните их.',failed:'Не удалось завершить анализ.',savedMessage:'Проверенные данные документа сохранены.',notStarted:'Анализ ещё не начат. Без проверенного содержимого надёжная оценка невозможна.',confidenceValues:confidenceLabels('Высокая','Средняя','Низкая')},
  ar:{badge:'V26 · تحليل مضبوط',title:'بدء اقتراح الذكاء الاصطناعي بوعي',lead:'يُحفظ الملف الأصلي بشكل خاص. لا يبدأ التحليل إلا بعد تأكيدك الصريح، ويظل أوليًا حتى الحفظ.',privacyTitle:'لا بيانات عملاء حقيقية أثناء الاختبار',privacyText:'استخدم ملفات اختبار داخلية فقط من دون بيانات عملاء حقيقية. يرسل زر «بدء التحليل» الملف عبر الخادم إلى خدمة الذكاء الاصطناعي.',confirm:'أؤكد أن هذا ملف اختبار داخلي لا يحتوي على بيانات عملاء حقيقية.',start:'بدء التحليل',analyzing:'جارٍ تحليل المستند …',unsupported:'يدعم الاستخراج التلقائي PDF وJPG وPNG وWEBP وGIF فقط. ويمكن تعبئة الحقول يدويًا.',limit:'تحليل الذكاء الاصطناعي: 18 ميغابايت كحد أقصى لكل ملف. حد الرفع المؤقت البالغ 50 ميغابايت لا ينطبق على التحليل التلقائي.',uploaded:'لم يبدأ التحليل',draft:'اقتراح ذكاء اصطناعي · أولي وغير محفوظ',saved:'تم حفظ البيانات المراجعة',facts:'بيانات إضافية مستخرجة للمراجعة',sender:'المرسل / المؤلف',recipient:'المستلم',references:'أرقام الملف / المرجع',deadlines:'المهل المذكورة',amounts:'المبالغ المذكورة',confidence:'درجة ثقة الاستخراج',none:'لم يُتعرف على شيء',manual:'يمكن تعديل كل اقتراح. لا تُعتمد البيانات المراجعة إلا بزر الحفظ.',save:'حفظ البيانات المراجعة عن قصد',ready:'اكتمل التحليل. راجع كل البيانات ثم احفظها عن قصد.',failed:'تعذر إكمال التحليل.',savedMessage:'تم حفظ بيانات المستند المراجعة.',notStarted:'لم يبدأ التحليل بعد. لا يمكن إجراء تقييم موثوق من دون محتوى مُراجع.',confidenceValues:confidenceLabels('مرتفعة','متوسطة','منخفضة')}
}

const analysisFilePattern = /\.(pdf|jpe?g|png|webp|gif)$/i

export function getV26AnalysisCopy(language){ return copy[language] || copy.de }

function factValue(value){
  if(Array.isArray(value)) return value.map(factValue).filter(Boolean).join(', ')
  if(value && typeof value==='object') return Object.values(value).map(factValue).filter(Boolean).join(' · ')
  return value==null?'':String(value)
}

export function ControlledDocumentAnalysis({copy:on,item,draft,onChange,onAnalyze,phase,onPhase}){
  const [confirmed,setConfirmed]=useState(false)
  const [busy,setBusy]=useState(false)
  const [facts,setFacts]=useState(null)
  const analyzable=analysisFilePattern.test(item.title||item.file_path||'')
  const status=phase==='draft'?on.draft:phase==='saved'?on.saved:on.uploaded

  async function analyze(){
    if(!confirmed||!analyzable||busy) return
    setBusy(true)
    try{
      const result=await onAnalyze(item)
      if(result){
        const fields=result.fields||{}
        onChange({
          ...draft,
          extracted_text:fields.extracted_text||draft.extracted_text,
          document_type:fields.document_type||draft.document_type,
          document_date:fields.document_date||draft.document_date,
          case_id:fields.case_id||draft.case_id,
          analysis_summary:fields.analysis_summary||draft.analysis_summary,
          analysis_next_step:fields.analysis_next_step||draft.analysis_next_step,
          analysis_generated:true
        })
        setFacts(result.facts)
        setConfirmed(false)
        onPhase('draft')
      }
    }finally{
      setBusy(false)
    }
  }

  const factRows=facts?[
    [on.sender,factValue(facts.sender_or_author)],[on.recipient,factValue(facts.recipient)],
    [on.references,factValue(facts.reference_numbers)],[on.deadlines,factValue(facts.deadlines)],
    [on.amounts,factValue(facts.monetary_amounts)],[on.confidence,on.confidenceValues[facts.confidence]||factValue(facts.confidence)]
  ]:[]

  return <section className="controlledAnalysis" aria-live="polite">
    <div className="analysisHead"><div><span className="modeBadge">{on.badge}</span><h3>{on.title}</h3><p>{on.lead}</p></div><span className={`analysisStatus analysis-${phase}`}>{status}</span></div>
    <div className="analysisConsent"><div><b>{on.privacyTitle}</b><p>{on.privacyText}</p></div><button type="button" className="primary" disabled={!confirmed||!analyzable||busy} onClick={analyze}>{busy?on.analyzing:on.start}</button><label><input type="checkbox" checked={confirmed} onChange={event=>setConfirmed(event.target.checked)}/><span>{on.confirm}</span></label><small>{on.limit}</small>{!analyzable&&<small className="analysisUnsupported">{on.unsupported}</small>}</div>
    {factRows.length>0&&<div className="analysisFacts"><b>{on.facts}</b><div>{factRows.map(([label,value])=><span key={label}><small>{label}</small><strong>{value||on.none}</strong></span>)}</div></div>}
    <p className="analysisManualNote">{on.manual}</p>
  </section>
}
