'use client'

import { useState } from 'react'
import { componentTranslations } from '../lib/v30ComponentTranslations.mjs'

export const PRIVACY_NOTICE_VERSION='2026-08-30-v1'
export const TERMS_VERSION='2026-08-30-test-v1'

const copy={
  de:{required:'Bitte bestätigen Sie die Rechtstexte und die Testdaten-Regel.',registerLegal:'Ich habe die Datenschutzerklärung und die Nutzungsbedingungen gelesen und akzeptiere die Nutzungsbedingungen für den kostenlosen Test.',registerTest:'Ich verwende ausschließlich synthetische oder wirksam anonymisierte Testdaten – keine echten personenbezogenen Daten Dritter und keine besonders sensiblen Daten.',privacy:'Datenschutzerklärung',terms:'Nutzungsbedingungen',gateBadge:'V28 · notwendige Bestätigung',gateTitle:'Aktuelle Rechtstexte einmal bestätigen',gateLead:'Ihr Konto bleibt unter Ihrer Kontrolle. Vor der weiteren Nutzung dokumentieren wir die aktuelle Datenschutzerklärung und die Bedingungen des kontrollierten Tests.',gateAction:'Bestätigen und fortfahren',classification:'Datenart der Datei',synthetic:'Synthetische Testdaten',anonymized:'Wirksam anonymisierte Testdaten',uploadConfirm:'Ich bestätige: Die Datei enthält keine echten personenbezogenen Daten und keine Daten nach Art. 9 DSGVO. Die Anonymisierung kann nicht mit vertretbarem Aufwand rückgängig gemacht werden.',uploadHelp:'Im kontrollierten Test sind nur synthetische oder wirksam anonymisierte Dateien zulässig. Eine KI-Übermittlung erfolgt erst später pro Dokument nach einer weiteren ausdrücklichen Bestätigung.',uploadRequired:'Bitte wählen Sie eine zulässige Testdatenart und bestätigen Sie die Testdaten-Regel.',saved:'Datenschutz- und Testbedingungen wurden gespeichert.'},
  en:{required:'Please confirm the legal texts and test-data rule.',registerLegal:'I have read the privacy notice and terms of use and accept the terms for the free test.',registerTest:'I will use synthetic or effectively anonymised test data only — no real third-party personal data and no special-category data.',privacy:'Privacy notice',terms:'Terms of use',gateBadge:'V28 · confirmation required',gateTitle:'Confirm the current legal texts once',gateLead:'Your account remains under your control. Before continuing, we record the current privacy notice and controlled-test terms.',gateAction:'Confirm and continue',classification:'File data type',synthetic:'Synthetic test data',anonymized:'Effectively anonymised test data',uploadConfirm:'I confirm that the file contains no real personal data and no special-category data under GDPR Article 9. The anonymisation cannot reasonably be reversed.',uploadHelp:'Only synthetic or effectively anonymised files are allowed during controlled testing. AI transfer starts later only after a separate explicit confirmation for that document.',uploadRequired:'Select an allowed test-data type and confirm the test-data rule.',saved:'Privacy and test terms were recorded.'},
  tr:{required:'Lütfen yasal metinleri ve test verisi kuralını onaylayın.',registerLegal:'Gizlilik bildirimini ve kullanım koşullarını okudum; ücretsiz test koşullarını kabul ediyorum.',registerTest:'Yalnızca sentetik veya etkili biçimde anonimleştirilmiş test verileri kullanacağım; gerçek üçüncü kişi verileri ve özel nitelikli veriler kullanmayacağım.',privacy:'Gizlilik bildirimi',terms:'Kullanım koşulları',gateBadge:'V28 · onay gerekli',gateTitle:'Güncel yasal metinleri bir kez onaylayın',gateLead:'Hesabınız sizin kontrolünüzde kalır. Devam etmeden önce güncel gizlilik bildirimini ve kontrollü test koşullarını kaydederiz.',gateAction:'Onayla ve devam et',classification:'Dosyanın veri türü',synthetic:'Sentetik test verisi',anonymized:'Etkili biçimde anonimleştirilmiş veri',uploadConfirm:'Dosyanın gerçek kişisel veri veya GDPR Madde 9 kapsamındaki özel nitelikli veri içermediğini onaylıyorum. Anonimleştirme makul yollarla geri alınamaz.',uploadHelp:'Kontrollü testte yalnızca sentetik veya etkili biçimde anonimleştirilmiş dosyalara izin verilir. Yapay zekâ aktarımı daha sonra her belge için ayrı açık onayla başlar.',uploadRequired:'İzin verilen test verisi türünü seçin ve kuralı onaylayın.',saved:'Gizlilik ve test koşulları kaydedildi.'},
  pl:{required:'Potwierdź teksty prawne i zasadę danych testowych.',registerLegal:'Przeczytałem(-am) politykę prywatności i warunki korzystania oraz akceptuję warunki bezpłatnego testu.',registerTest:'Będę używać wyłącznie danych syntetycznych lub skutecznie zanonimizowanych — bez prawdziwych danych osób trzecich i danych szczególnych kategorii.',privacy:'Polityka prywatności',terms:'Warunki korzystania',gateBadge:'V28 · wymagane potwierdzenie',gateTitle:'Potwierdź aktualne teksty prawne',gateLead:'Konto pozostaje pod Twoją kontrolą. Przed dalszym użyciem zapisujemy aktualną politykę prywatności i warunki kontrolowanego testu.',gateAction:'Potwierdź i kontynuuj',classification:'Rodzaj danych w pliku',synthetic:'Syntetyczne dane testowe',anonymized:'Skutecznie zanonimizowane dane',uploadConfirm:'Potwierdzam, że plik nie zawiera prawdziwych danych osobowych ani danych szczególnych kategorii z art. 9 RODO. Anonimizacji nie można rozsądnie odwrócić.',uploadHelp:'W kontrolowanym teście dozwolone są tylko pliki syntetyczne lub skutecznie zanonimizowane. Przekazanie do AI następuje później po osobnym wyraźnym potwierdzeniu dla dokumentu.',uploadRequired:'Wybierz dozwolony rodzaj danych testowych i potwierdź zasadę.',saved:'Zapisano warunki prywatności i testu.'},
  ru:{required:'Подтвердите юридические тексты и правило тестовых данных.',registerLegal:'Я прочитал(а) уведомление о конфиденциальности и условия использования и принимаю условия бесплатного теста.',registerTest:'Я буду использовать только синтетические или надёжно анонимизированные тестовые данные — без реальных данных третьих лиц и данных особых категорий.',privacy:'Конфиденциальность',terms:'Условия использования',gateBadge:'V28 · требуется подтверждение',gateTitle:'Подтвердите актуальные юридические тексты',gateLead:'Аккаунт остаётся под вашим контролем. Перед продолжением мы фиксируем актуальное уведомление о конфиденциальности и условия контролируемого теста.',gateAction:'Подтвердить и продолжить',classification:'Тип данных файла',synthetic:'Синтетические тестовые данные',anonymized:'Надёжно анонимизированные данные',uploadConfirm:'Подтверждаю, что файл не содержит реальных персональных данных или данных особых категорий по ст. 9 GDPR. Анонимизацию нельзя обоснованно обратить.',uploadHelp:'В контролируемом тесте разрешены только синтетические или надёжно анонимизированные файлы. Передача ИИ выполняется позже после отдельного явного подтверждения для документа.',uploadRequired:'Выберите допустимый тип тестовых данных и подтвердите правило.',saved:'Условия конфиденциальности и теста сохранены.'},
  ar:{required:'يرجى تأكيد النصوص القانونية وقاعدة بيانات الاختبار.',registerLegal:'قرأت إشعار الخصوصية وشروط الاستخدام وأوافق على شروط الاختبار المجاني.',registerTest:'سأستخدم بيانات اختبار اصطناعية أو مجهولة الهوية بفعالية فقط، من دون بيانات شخصية حقيقية لأطراف أخرى أو بيانات من فئات خاصة.',privacy:'إشعار الخصوصية',terms:'شروط الاستخدام',gateBadge:'V28 · التأكيد مطلوب',gateTitle:'أكد النصوص القانونية الحالية مرة واحدة',gateLead:'يبقى حسابك تحت سيطرتك. قبل المتابعة نسجل إشعار الخصوصية الحالي وشروط الاختبار المضبوط.',gateAction:'تأكيد ومتابعة',classification:'نوع بيانات الملف',synthetic:'بيانات اختبار اصطناعية',anonymized:'بيانات مجهولة الهوية بفعالية',uploadConfirm:'أؤكد أن الملف لا يحتوي على بيانات شخصية حقيقية أو بيانات فئات خاصة وفق المادة 9 من GDPR، وأن إخفاء الهوية لا يمكن عكسه بوسائل معقولة.',uploadHelp:'يُسمح في الاختبار المضبوط بالملفات الاصطناعية أو مجهولة الهوية بفعالية فقط. لا يبدأ النقل إلى الذكاء الاصطناعي إلا لاحقًا بعد تأكيد صريح مستقل لكل مستند.',uploadRequired:'اختر نوع بيانات اختبار مسموحًا وأكد القاعدة.',saved:'تم حفظ شروط الخصوصية والاختبار.'}
}

const aiControlCopy={
  de:{aiControl:'KI-Steuerung',aiEnabled:'KI-Verarbeitung ist auf Kontoebene freigegeben. Jede Übermittlung benötigt zusätzlich eine neue Bestätigung am Dokument.',aiDisabled:'KI-Verarbeitung ist auf Kontoebene ausgeschaltet. Sie wird erst bei einer ausdrücklich bestätigten Dokumentanalyse wieder aktiviert.',disableAi:'KI-Verarbeitung ausschalten',disableAiDone:'KI-Verarbeitung und alle noch offenen Dokumentfreigaben wurden ausgeschaltet.'},
  en:{aiControl:'AI controls',aiEnabled:'AI processing is enabled at account level. Every transfer also requires a new document confirmation.',aiDisabled:'AI processing is disabled at account level. It is re-enabled only by an explicitly confirmed document analysis.',disableAi:'Disable AI processing',disableAiDone:'AI processing and all outstanding document permissions were disabled.'},
  tr:{aiControl:'Yapay zekâ kontrolü',aiEnabled:'Yapay zekâ işleme hesap düzeyinde açık. Her aktarım için ayrıca belgede yeni bir onay gerekir.',aiDisabled:'Yapay zekâ işleme hesap düzeyinde kapalı. Yalnızca açıkça onaylanan belge analiziyle yeniden açılır.',disableAi:'Yapay zekâ işlemeyi kapat',disableAiDone:'Yapay zekâ işleme ve bekleyen tüm belge izinleri kapatıldı.'},
  pl:{aiControl:'Sterowanie AI',aiEnabled:'Przetwarzanie AI jest włączone na poziomie konta. Każde przekazanie wymaga również nowego potwierdzenia przy dokumencie.',aiDisabled:'Przetwarzanie AI jest wyłączone na poziomie konta. Włącza je dopiero wyraźnie potwierdzona analiza dokumentu.',disableAi:'Wyłącz przetwarzanie AI',disableAiDone:'Wyłączono przetwarzanie AI i wszystkie oczekujące zgody dokumentów.'},
  ru:{aiControl:'Управление ИИ',aiEnabled:'Обработка ИИ разрешена на уровне аккаунта. Для каждой передачи также требуется новое подтверждение документа.',aiDisabled:'Обработка ИИ отключена на уровне аккаунта. Она включается только явно подтверждённым анализом документа.',disableAi:'Отключить обработку ИИ',disableAiDone:'Обработка ИИ и все неиспользованные разрешения документов отключены.'},
  ar:{aiControl:'التحكم في الذكاء الاصطناعي',aiEnabled:'المعالجة بالذكاء الاصطناعي مفعلة على مستوى الحساب. وكل نقل يحتاج أيضًا إلى تأكيد جديد للمستند.',aiDisabled:'المعالجة بالذكاء الاصطناعي معطلة على مستوى الحساب، ولا يعاد تفعيلها إلا بتحليل مستند مؤكد صراحةً.',disableAi:'تعطيل المعالجة بالذكاء الاصطناعي',disableAiDone:'تم تعطيل المعالجة بالذكاء الاصطناعي وجميع أذونات المستندات غير المستخدمة.'}
}

Object.assign(copy, componentTranslations.privacyCopy)
Object.assign(aiControlCopy, componentTranslations.aiControlCopy)

export function getV28PrivacyCopy(language){return {...(copy[language]||copy.de),...(aiControlCopy[language]||aiControlCopy.de)}}

export function RegistrationLegalFields({copy:on,accepted,onAccepted,testOnly,onTestOnly}){
  return <div className="legalChecks">
    <label><input type="checkbox" checked={accepted} onChange={event=>onAccepted(event.target.checked)} required/><span>{on.registerLegal} <a href="/datenschutz" target="_blank" rel="noreferrer">{on.privacy}</a> · <a href="/nutzungsbedingungen" target="_blank" rel="noreferrer">{on.terms}</a></span></label>
    <label><input type="checkbox" checked={testOnly} onChange={event=>onTestOnly(event.target.checked)} required/><span>{on.registerTest}</span></label>
  </div>
}

export function LegalAcceptance({copy:on,onAccept,busy=false}){
  const [accepted,setAccepted]=useState(false)
  const [testOnly,setTestOnly]=useState(false)
  return <section className="legalGate">
    <span className="modeBadge">{on.gateBadge}</span><h1>{on.gateTitle}</h1><p>{on.gateLead}</p>
    <RegistrationLegalFields copy={on} accepted={accepted} onAccepted={setAccepted} testOnly={testOnly} onTestOnly={setTestOnly}/>
    <button type="button" className="primary full" disabled={!accepted||!testOnly||busy} onClick={()=>onAccept({accepted,testOnly})}>{on.gateAction}</button>
  </section>
}
