'use client'

import { useEffect } from 'react'
import { supabase } from '../lib/supabaseClient'
import { analyzeCaseConsistency } from '../lib/v41CaseConsistency.mjs'

const labels={
 de:{title:'Fall-Konsistenz & Nachweise',score:'Vollständigkeit',good:'Gut vorbereitet',review:'Prüfung empfohlen',attention:'Lücken schließen',gaps:'Fehlende oder offene Punkte',deviations:'Abweichende Angaben zwischen Dokumenten',deviationNote:'Nicht automatisch als Widerspruch gewertet – prüfen, ob unterschiedliche Zeiträume oder Positionen gemeint sind.',none:'Keine auffälligen Abweichungen erkannt.',goal:'Ziel des Falls fehlt',summary:'Sachstand fehlt',deadline:'Keine Fallfrist hinterlegt',next_action:'Nächster Schritt fehlt',documents:'Noch keine Dokumente',unread_documents:'Dokumente ohne ausgelesenen Inhalt',assessment:'Noch keine dokumentierte Bewertung',red_without_next:'Rote Bewertung ohne nächsten Schritt',amount:'Betrag',date:'Datum'},
 en:{title:'Case consistency & evidence',score:'Completeness',good:'Well prepared',review:'Review recommended',attention:'Close gaps',gaps:'Missing or open items',deviations:'Differing details across documents',deviationNote:'Not automatically treated as a contradiction — verify whether different periods or items are intended.',none:'No notable deviations detected.',goal:'Case goal missing',summary:'Case summary missing',deadline:'No case deadline stored',next_action:'Next action missing',documents:'No documents yet',unread_documents:'Documents without extracted text',assessment:'No documented assessment yet',red_without_next:'Red assessment without next step',amount:'Amount',date:'Date'},
 fr:{title:'Cohérence du dossier et preuves',score:'Complétude',good:'Bien préparé',review:'Vérification recommandée',attention:'Compléter les lacunes',gaps:'Éléments manquants ou ouverts',deviations:'Informations divergentes entre documents',deviationNote:'Pas automatiquement considéré comme une contradiction — vérifier les périodes ou postes différents.',none:'Aucune divergence notable détectée.',goal:'Objectif du dossier manquant',summary:'Résumé manquant',deadline:'Aucun délai de dossier enregistré',next_action:'Étape suivante manquante',documents:'Aucun document',unread_documents:'Documents sans texte extrait',assessment:'Aucune évaluation documentée',red_without_next:'Évaluation rouge sans étape suivante',amount:'Montant',date:'Date'},
 tr:{title:'Dosya tutarlılığı ve kanıtlar',score:'Tamlık',good:'İyi hazırlanmış',review:'Kontrol önerilir',attention:'Eksikleri tamamlayın',gaps:'Eksik veya açık noktalar',deviations:'Belgeler arasındaki farklı bilgiler',deviationNote:'Otomatik olarak çelişki sayılmaz — farklı dönem veya kalem olup olmadığını kontrol edin.',none:'Belirgin bir farklılık bulunmadı.',goal:'Dosya hedefi eksik',summary:'Dosya özeti eksik',deadline:'Dosya süresi kayıtlı değil',next_action:'Sonraki adım eksik',documents:'Henüz belge yok',unread_documents:'Metni çıkarılmamış belgeler',assessment:'Henüz belgelenmiş değerlendirme yok',red_without_next:'Sonraki adımı olmayan kırmızı değerlendirme',amount:'Tutar',date:'Tarih'},
 pl:{title:'Spójność sprawy i dowody',score:'Kompletność',good:'Dobrze przygotowane',review:'Zalecana kontrola',attention:'Uzupełnij braki',gaps:'Brakujące lub otwarte punkty',deviations:'Różne dane w dokumentach',deviationNote:'Nie są automatycznie uznawane za sprzeczność — sprawdź, czy dotyczą różnych okresów lub pozycji.',none:'Nie wykryto istotnych różnic.',goal:'Brak celu sprawy',summary:'Brak opisu stanu sprawy',deadline:'Brak terminu sprawy',next_action:'Brak następnego kroku',documents:'Brak dokumentów',unread_documents:'Dokumenty bez odczytanej treści',assessment:'Brak udokumentowanej oceny',red_without_next:'Czerwona ocena bez następnego kroku',amount:'Kwota',date:'Data'},
 ru:{title:'Согласованность дела и доказательства',score:'Полнота',good:'Хорошо подготовлено',review:'Рекомендуется проверка',attention:'Устранить пробелы',gaps:'Недостающие или открытые пункты',deviations:'Различающиеся данные в документах',deviationNote:'Не считаются автоматически противоречием — проверьте, не относятся ли они к разным периодам или позициям.',none:'Заметных расхождений не выявлено.',goal:'Нет цели дела',summary:'Нет описания дела',deadline:'Срок дела не сохранён',next_action:'Нет следующего шага',documents:'Документов пока нет',unread_documents:'Документы без извлечённого текста',assessment:'Нет документированной оценки',red_without_next:'Красная оценка без следующего шага',amount:'Сумма',date:'Дата'},
 ar:{title:'اتساق الحالة والأدلة',score:'الاكتمال',good:'معد جيدًا',review:'يوصى بالمراجعة',attention:'أكمل النواقص',gaps:'نقاط ناقصة أو مفتوحة',deviations:'بيانات مختلفة بين المستندات',deviationNote:'لا تُعد تلقائيًا تناقضًا — تحقق مما إذا كانت تخص فترات أو بنودًا مختلفة.',none:'لم يتم اكتشاف اختلافات ملحوظة.',goal:'هدف الحالة مفقود',summary:'ملخص الحالة مفقود',deadline:'لا توجد مهلة مسجلة',next_action:'الخطوة التالية مفقودة',documents:'لا توجد مستندات بعد',unread_documents:'مستندات بلا نص مستخرج',assessment:'لا يوجد تقييم موثق',red_without_next:'تقييم أحمر بلا خطوة تالية',amount:'مبلغ',date:'تاريخ'},
 fa:{title:'سازگاری پرونده و مدارک',score:'کامل بودن',good:'خوب آماده شده',review:'بررسی توصیه می‌شود',attention:'نواقص را تکمیل کنید',gaps:'موارد ناقص یا باز',deviations:'اطلاعات متفاوت میان اسناد',deviationNote:'به‌طور خودکار تناقض محسوب نمی‌شود — بررسی کنید آیا مربوط به دوره‌ها یا اقلام متفاوت است.',none:'اختلاف قابل توجهی شناسایی نشد.',goal:'هدف پرونده وارد نشده',summary:'شرح وضعیت پرونده وارد نشده',deadline:'مهلت پرونده ثبت نشده',next_action:'گام بعدی مشخص نشده',documents:'هنوز سندی وجود ندارد',unread_documents:'اسناد بدون متن استخراج‌شده',assessment:'هنوز ارزیابی مستندی وجود ندارد',red_without_next:'ارزیابی قرمز بدون گام بعدی',amount:'مبلغ',date:'تاریخ'},
 ro:{title:'Coerența cazului și dovezi',score:'Completitudine',good:'Bine pregătit',review:'Verificare recomandată',attention:'Completați lipsurile',gaps:'Puncte lipsă sau deschise',deviations:'Date diferite între documente',deviationNote:'Nu sunt tratate automat ca contradicție — verificați dacă privesc perioade sau poziții diferite.',none:'Nu au fost detectate diferențe notabile.',goal:'Lipsește obiectivul cazului',summary:'Lipsește situația cazului',deadline:'Nu este salvat un termen',next_action:'Lipsește pasul următor',documents:'Nu există documente',unread_documents:'Documente fără text extras',assessment:'Nu există evaluare documentată',red_without_next:'Evaluare roșie fără pas următor',amount:'Sumă',date:'Dată'},
 bg:{title:'Съгласуваност на случая и доказателства',score:'Пълнота',good:'Добре подготвено',review:'Препоръчва се проверка',attention:'Попълнете липсите',gaps:'Липсващи или отворени точки',deviations:'Различни данни между документите',deviationNote:'Не се приемат автоматично за противоречие — проверете дали се отнасят за различни периоди или позиции.',none:'Не са открити съществени разлики.',goal:'Липсва цел на случая',summary:'Липсва описание на случая',deadline:'Няма записан срок',next_action:'Липсва следваща стъпка',documents:'Все още няма документи',unread_documents:'Документи без извлечен текст',assessment:'Няма документирана оценка',red_without_next:'Червена оценка без следваща стъпка',amount:'Сума',date:'Дата'}
}

function lang(){const v=(document.documentElement.lang||'de').toLowerCase().slice(0,2);return labels[v]?v:'de'}
function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function referenceFromDom(){const p=document.querySelector('.caseTitleRow p')?.textContent||'';return p.includes(' · ')?p.split(' · ').pop().trim():''}

export function V41CaseConsistency(){
 useEffect(()=>{
   let last='';let cancelled=false
   async function render(){
     const row=document.querySelector('.caseTitleRow');if(!row){document.querySelector('[data-v41-consistency]')?.remove();last='';return}
     const title=row.querySelector('h2')?.textContent?.trim()||'';const ref=referenceFromDom();const domSig=`${title}|${ref}|${document.querySelectorAll('.sourceList button').length}|${document.querySelectorAll('.assessmentList .assessment').length}`
     if(!title||domSig===last)return;last=domSig
     let query=supabase.from('cases').select('id,title,reference_no,goal,summary,deadline_at,next_action').eq('title',title).limit(5)
     const {data:cases,error}=await query;if(error||cancelled||!cases?.length)return
     const caseItem=(ref?cases.find(c=>c.reference_no===ref):null)||cases[0]
     const [{data:documents},{data:assessments}]=await Promise.all([
       supabase.from('documents').select('id,title,document_date,extracted_text').eq('case_id',caseItem.id),
       supabase.from('assessments').select('id,title,traffic_light,reasoning,next_step').eq('case_id',caseItem.id)
     ])
     if(cancelled)return
     const result=analyzeCaseConsistency({caseItem,documents:documents||[],assessments:assessments||[]});const t=labels[lang()]
     let section=document.querySelector('[data-v41-consistency]');if(!section){section=document.createElement('section');section.dataset.v41Consistency='true';section.className='detailCard v41CaseConsistency';const anchor=document.querySelector('[data-v40-handoff]')||document.querySelector('[data-v39-timeline]')||document.querySelector('.caseCoreGrid');anchor?.insertAdjacentElement('afterend',section)}
     if(!section)return
     const state=t[result.status];const icon=result.status==='good'?'🟢':result.status==='review'?'🟡':'🔴'
     const gapHtml=result.gaps.length?`<ul>${result.gaps.map(g=>`<li>${esc(t[g]||g)}${g==='unread_documents'?` (${result.unreadCount})`:''}</li>`).join('')}</ul>`:`<p>✓ ${esc(t.good)}</p>`
     const devHtml=result.deviations.length?`<ul>${result.deviations.map(d=>`<li><b>${esc(t[d.type]||d.type)} · ${esc(d.concept)}</b>: ${d.values.map(v=>esc(v.value)).join(' ↔ ')}</li>`).join('')}</ul><small>${esc(t.deviationNote)}</small>`:`<p>${esc(t.none)}</p>`
     section.innerHTML=`<div class="detailCardHead"><div><span class="modeBadge">V41</span><h3>${esc(t.title)}</h3></div><strong>${icon} ${result.score}% · ${esc(state)}</strong></div><h4>${esc(t.gaps)}</h4>${gapHtml}<h4>${esc(t.deviations)}</h4>${devHtml}`
   }
   render();const timer=setInterval(render,1800);return()=>{cancelled=true;clearInterval(timer);document.querySelector('[data-v41-consistency]')?.remove()}
 },[])
 return null
}
