// Entirely fictional, reusable regression case. No information from client chats.
export const roadmapTestCase={id:'11111111-1111-4111-8111-111111111111',owner_id:'22222222-2222-4222-8222-222222222222',title:'Synthetischer Fall: Auszahlung und Beitragsklärung',goal:'Die Auszahlung verstehen, offene Berechnungsgrundlagen beschaffen und zwei Anfragen vorbereiten.',summary:'Zwei erfundene Stellen haben Schreiben zur selben Auszahlung geschickt. Die Berechnungsgrundlagen sind noch offen.',home_country:'DE',target_country:'DE',reference_no:'SYN-V136',next_action:'Fehlende Berechnungen anfordern.'}
export const roadmapTestDocuments=[
  {id:'33333333-3333-4333-8333-333333333333',owner_id:roadmapTestCase.owner_id,case_id:roadmapTestCase.id,title:'Muster-Versorgung – Kapitalzahlung',document_date:'2026-09-18',updated_at:'2026-09-18T12:00:00Z',data_classification:'synthetic',extracted_text:'SYNTHETISCHER TESTFALL. Keine echten Personen oder Unternehmen.\nMuster-Versorgung an Testkundin Nora Muster. Dokumentdatum: 18.09.2026. Referenz SYN-V136-A.\nDie einmalige Kapitalzahlung beträgt 18.000 EUR brutto und 17.000 EUR netto.\nDie Berechnungsanlage fehlt. Ob weitere Zahlungen folgen, ist noch nicht bestätigt.\nBitte reichen Sie die fehlende Empfangsbestätigung bis 30.09.2026 ein.'},
  {id:'44444444-4444-4444-8444-444444444444',owner_id:roadmapTestCase.owner_id,case_id:roadmapTestCase.id,title:'Muster-Kasse – Rückfrage zur Auszahlung',document_date:'2026-09-18',updated_at:'2026-09-18T12:01:00Z',data_classification:'synthetic',extracted_text:'SYNTHETISCHER TESTFALL. Keine echten Personen oder Unternehmen.\nMuster-Kasse an Testkundin Nora Muster. Dokumentdatum: 18.09.2026. Referenz SYN-V136-B.\nDie Meldung über die Kapitalzahlung von 18.000 EUR liegt vor.\nFür die Beitragsprüfung fehlen der Zahlungsnachweis und die vollständige Berechnungsanlage der Muster-Versorgung.\nEs ist noch kein Beitrag festgesetzt. Eine monatliche Zahlung darf nicht als bestätigt angenommen werden.'}
]
const a=roadmapTestDocuments[0].id,b=roadmapTestDocuments[1].id
export const roadmapTestResult={
  title:'Dein Fahrplan zur Auszahlung',opening:'Die Auszahlung ist beschrieben; die Berechnungsgrundlagen und die Beitragsfrage sind noch offen. Du kannst jetzt die fehlenden Unterlagen beschaffen und beide Stellen gezielt anschreiben.',key_points:['Empfangsbestätigung rechtzeitig einreichen.','Die beiden Stellen getrennt um die fehlenden Angaben bitten.','Eine Beitragshöhe ist noch nicht bestätigt.'],meaning:'Die Schreiben gehören zusammen. Aus der Kapitalzahlung allein lässt sich noch kein monatlicher Beitrag ableiten.',next:'Prüfe zuerst die Empfangsbestätigung und die ausdrücklich genannte Frist.',customer_action:'Stelle den Zahlungsnachweis zusammen und prüfe die beiden vorbereiteten Anfragen.',
  facts:[{text:'Die Muster-Versorgung nennt 18.000 EUR brutto und 17.000 EUR netto.',evidence:[{document_id:a,quote:'Die einmalige Kapitalzahlung beträgt 18.000 EUR brutto und 17.000 EUR netto.'}]},{text:'Die Muster-Kasse kennt die Kapitalzahlung, hat aber noch keinen Beitrag festgesetzt.',evidence:[{document_id:b,quote:'Es ist noch kein Beitrag festgesetzt.'}]}],
  open_questions:[{question:'Wie wurde die Nettozahlung berechnet und folgen weitere Zahlungen?',who:'Muster-Versorgung',why:'Die Berechnungsanlage und die Abschlussbestätigung fehlen.'},{question:'Welche Unterlagen fehlen für die Beitragsprüfung?',who:'Muster-Kasse',why:'Eine gesicherte Beitragshöhe lässt sich bislang nicht nennen.'}],
  steps:[
    {id:'frist',title:'Empfangsbestätigung prüfen und einreichen',phase:'now',light:'red',reason:'Im Schreiben steht eine ausdrückliche Frist.',owner:'Du',action:'Prüfe die verlangte Empfangsbestätigung. Reiche sie mit zutreffenden Angaben rechtzeitig ein.',waiting_for:'',after_response:'Bewahre die Eingangsbestätigung auf.',done_when:'Die Empfangsbestätigung ist eingereicht und der Zugang belegt.',follow_up:'Bei fehlender Eingangsbestätigung rechtzeitig nachfragen.',depends_on:[],deadline:{date:'2026-09-30',document_id:a,quote:'Bitte reichen Sie die fehlende Empfangsbestätigung bis 30.09.2026 ein.'},evidence:[{document_id:a,quote:'Bitte reichen Sie die fehlende Empfangsbestätigung bis 30.09.2026 ein.'}]},
    {id:'anfragen',title:'Beide Auskunftsanfragen vorbereiten',phase:'parallel',light:'yellow',reason:'Beide Schreiben nennen noch fehlende Grundlagen.',owner:'Du',action:'Ergänze die zwei getrennten Entwürfe. Prüfe sie vor dem Versand und lege den vorhandenen Zahlungsnachweis bei.',waiting_for:'Antworten von Muster-Versorgung und Muster-Kasse.',after_response:'Ordne die Antworten den jeweiligen Fragen zu.',done_when:'Beide Anfragen sind geprüft und versandt; die Versandnachweise sind abgelegt.',follow_up:'Vorschlag zur Wiedervorlage: nach 14 Tagen nachfragen. Dies ist keine gesetzliche Antwortfrist.',depends_on:[],deadline:null,evidence:[{document_id:a,quote:'Die Berechnungsanlage fehlt.'},{document_id:b,quote:'Für die Beitragsprüfung fehlen der Zahlungsnachweis und die vollständige Berechnungsanlage der Muster-Versorgung.'}]},
    {id:'antworten',title:'Antworten auf Vollständigkeit prüfen',phase:'waiting',light:'yellow',reason:'Eine Anfrage allein beantwortet die offenen Fragen noch nicht.',owner:'Du mit Unterstützung bei Rückfragen',action:'Vergleiche die eingegangenen Antworten mit den offenen Fragen.',waiting_for:'Berechnungsanlage, Abschlussbestätigung und Auskunft zur Beitragsprüfung.',after_response:'Fehlende Punkte gezielt nachfordern; vollständig geklärte Ergebnisse dokumentieren.',done_when:'Die Antworten liegen vollständig vor und die Berechnungsgrundlagen sind nachvollziehbar.',follow_up:'Unbeantwortete Fragen gesondert nachfordern.',depends_on:['anfragen'],deadline:null,evidence:[{document_id:a,quote:'Ob weitere Zahlungen folgen, ist noch nicht bestätigt.'},{document_id:b,quote:'Es ist noch kein Beitrag festgesetzt.'}]},
    {id:'abschluss',title:'Ergebnis abgleichen und weiter beobachten',phase:'afterwards',light:'yellow',reason:'Erst die Antworten ermöglichen den nächsten belastbaren Stand.',owner:'Du',action:'Gleiche neue Unterlagen mit der Auszahlung ab. Notiere neue Pflichten nur anhand der tatsächlich eingegangenen Mitteilung.',waiting_for:'',after_response:'Bei weiteren Schreiben den Fall ergänzen und den Fahrplan erneuern.',done_when:'Alle Antworten sind geprüft, offene Punkte erledigt und die Ergebnisse abgelegt.',follow_up:'Neue Mitteilungen prüfen; die bestehenden Unterlagen aufbewahren.',depends_on:['frist','antworten'],deadline:null,evidence:[]}
  ],
  letters:[
    {id:'versorgung',recipient:'Muster-Versorgung',subject:'Bitte um Berechnungsanlage und Abschlussbestätigung – SYN-V136-A',body:'Sehr geehrte Damen und Herren,\n\nbitte übersenden Sie die vollständige Berechnungsanlage zur Kapitalzahlung und erläutern Sie die Differenz zwischen Brutto- und Nettobetrag. Bitte bestätigen Sie außerdem, ob noch weitere Zahlungen folgen.\n\nVielen Dank.\nMit freundlichen Grüßen\nNora Muster',customer_translation:'',document_ids:[a]},
    {id:'kasse',recipient:'Muster-Kasse',subject:'Unterlagen zur Beitragsprüfung – SYN-V136-B',body:'Sehr geehrte Damen und Herren,\n\nbitte teilen Sie mir mit, welche Unterlagen Sie neben dem Zahlungsnachweis und der Berechnungsanlage für Ihre Prüfung benötigen. Die Berechnungsanlage habe ich angefordert. Bitte erläutern Sie nach deren Eingang die Grundlage und das Ergebnis Ihrer Prüfung.\n\nVielen Dank.\nMit freundlichen Grüßen\nNora Muster',customer_translation:'',document_ids:[a,b]}
  ],closing:'Ich hoffe, dass dir dieser Fahrplan weiterhilft. Bei Rückfragen helfe ich dir gern weiter.'
}
export function roadmapTestRecord(){return {id:'55555555-5555-4555-8555-555555555555',case_id:roadmapTestCase.id,style:{customer_name:'Nora Muster',salutation:'Hallo Nora,',tone:'personal',sender_name:'Musterberatung',letterhead:'Musterberatung\nSynthetische Funktionsvorschau',closing:''},output_language:'de',reference_language:'de',result:structuredClone(roadmapTestResult),source_documents:roadmapTestDocuments.map(({id,title,updated_at})=>({id,title,updated_at})),progress:{},events:[],created_at:'2026-09-18T12:10:00Z',updated_at:'2026-09-18T12:10:00Z'}}
