// Conversation-derived requirements, entirely fictional test inputs.
// No original chats, client names, identifiers, addresses or customer amounts.
// Source labels describe coverage; these are NOT generated or validated AI answers.
// The prior register's generic catch-all row 14 cannot be reconstructed as a case.
export const historyCoverageLimits = {
  completeChatExport: false,
  rawChatImport: false,
  unresolvedRegisterRows: [14],
  modelRun: 'pending',
  liveRun: 'pending'
}
export const historyTestToday = new Date('2030-04-10T12:00:00Z')

// id, theme, source basis, register rows, original A, original B, review criteria.
const definitions = [
  ['C01','Leitungsschaden und Verantwortlichkeit','register+context+retrieval',[1],
    'Die Leitungslage ist unklar. Eine kurze Planeinsicht ist bestätigt, eine Übergabe des Plans jedoch nicht.',
    'Die Untersuchung läuft. Eine Haftungsentscheidung und die tatsächliche Verlegetiefe fehlen.',
    'Planlage, Tiefe und Auftraggeberanweisung getrennt prüfen.|Die gewünschte Person als Absender verwenden; keine Vertretung erfinden.|Keine Haftungsanerkennung aus der laufenden Prüfung ableiten.'],
  ['C02','Versicherungsschaden und Betriebsunterbrechung','register+context+retrieval',[2],
    'Abrechnung: 8.460 EUR, davon 240 EUR verrechnet und 8.220 EUR überwiesen. Die zusätzliche Forderung von 27.640 EUR ist nicht anerkannt.',
    'Umsätze stammen laut Betreiber aus einem Ersatzverkauf. Wiedereröffnung und vollständiges Gutachten sind nicht bestätigt.',
    'Forderung, Anerkenntnis, Verrechnung und Zahlung getrennt ausweisen.|Keine Doppelzählung von Gesamtsumme und Teilbeträgen.|Ersatzverkauf nicht als Wiedereröffnung auslegen.|Reparaturansprüche als eigenen Vorgang führen.'],
  ['C03','Personen- und Unternehmenszuordnung','register',[3],
    'Zwei Firmen tragen ähnliche Namen. Eine Identität der Gesellschaften ist nicht bestätigt.',
    'Ein älterer Registerauszug nennt eine Geschäftsführung. Der aktuelle Registerstand fehlt.',
    'Ähnliche Namen nicht zusammenführen.|Zeitpunkt und Quelle jeder Organstellung nennen.|Aktuelle Primärquelle beschaffen, bevor Gegenwartsbehauptungen entstehen.'],
  ['C04','Reiserücktritt und getrennte Empfänger','register+context',[4],
    'Ein versichertes Ereignis wurde gemeldet. Die Erstattung ist angeblich genehmigt.',
    'Reisevertrag, Vollmacht und benötigte Nachweise sind unvollständig. Die Versicherungsentscheidung liegt nicht vor.',
    'Versicherung, Veranstalter und Nachweiserbringer getrennt anschreiben.|Erstattung ohne Entscheidung nicht zusagen.|Persönlichen Anlass respektvoll behandeln.'],
  ['C05','Fahrerlaubnis und Wiedererteilung','register',[5],
    'Der Antrag soll bewilligt werden. Die Entscheidung ist nicht vorgelegt.',
    'Zuständige Stelle, bisheriger Bescheid und verlangte Nachweise sind unklar.',
    'Zuständigkeit und Originalentscheidung zuerst beschaffen.|Keine Fahrerlaubnis oder neue Frist erfinden.'],
  ['C06','Versicherungsvertrag, Rechnung und Inkasso','register+context',[6],
    'Ein Folgevertrag besteht. Rechnung und Vertragszeitraum passen nicht zusammen; Inkasso fordert Zahlung.',
    'Der korrigierte Betrag ist noch nicht bestätigt. Die Zahlung wird später bestätigt.',
    'Folgevertrag und Abrechnungszeitraum abgleichen.|Korrekturbetrag von ursprünglicher Forderung trennen.|Versicherer und Inkasso getrennt informieren.'],
  ['C07','Ratenzahlungsanfrage','register',[7],
    'Eine Ratenzahlung wurde beantragt. Nur der Eingang wurde bestätigt.',
    'Ratenhöhe, erster Termin und Zustimmung der Stelle sind unklar.',
    'Anfrage nicht als Vereinbarung behandeln.|Keine Raten oder Fälligkeiten ohne Grundlage ergänzen.'],
  ['C08','Wiederherstellung, Nachfassen und Eskalation','register+context+retrieval',[8],
    'Ein Leistungsverzeichnis bestätigt den Reparaturumfang. Anschlussarbeiten sind nicht enthalten.',
    'Angebot, Beauftragung, Fertigstellung und Übergabe sind verschiedene Schritte. Eine Abnahme fehlt.',
    'Ausgeschlossene Arbeiten und Zuständigkeit offen nennen.|Reparaturangebot nicht mit Fertigstellung gleichsetzen.|Menschlich nachfassen; nächste Eskalation an konkrete ausbleibende Reaktion knüpfen.'],
  ['C09','Fahrzeugversicherung und Empfängerzuordnung','register',[9],
    'Eine Versicherungsbestätigung ist angefragt. Die Zuordnung zum Fahrzeug ist nicht bestätigt.',
    'Zwei mögliche Empfänger stehen im Vorgang. Die richtige Zuordnung ist unklar.',
    'Fahrzeug, Versicherungskennung und Empfänger eindeutig abgleichen.|Keine Kennung oder Empfängeradresse erraten.'],
  ['C10','Gastronomiekonzept und Wirtschaftlichkeit','register',[10],
    'Die Umsatzplanung beträgt fiktiv 36.700 EUR pro Monat. Mietangebot und Personalkosten sind vorläufig.',
    'Eine Rentabilität wäre bestätigt, wenn alle Annahmen eintreten. Istumsätze fehlen.',
    'Annahmen, Umsatz, Kosten, Investition und Ergebnis trennen.|Prognose nicht als erzielten Gewinn ausgeben.|Szenarien und Rechenweg nachvollziehbar zeigen.'],
  ['C11','Dienstleistungsbetrieb und Geschäftskonzept','register',[11],
    'Geplant ist ein kleiner Dienstleistungsbetrieb mit Zusatzverkauf. Auslastung und Investitionsangebot fehlen.',
    'Die Finanzierung sei bewilligt, behauptet ein Beteiligter. Ein Finanzierungsbescheid liegt nicht vor.',
    'Zwei Geschäftsteile und ihre Kosten unterscheiden.|Break-even nur aus belegten oder ausdrücklich gesetzten Annahmen berechnen.|Eine Finanzierungszusage nachweisen.'],
  ['C12','Wohnungssuche und Objektvergleich','register',[12],
    'Drei Angebote wurden gefunden. Aktuelle Verfügbarkeit, Nebenkosten und Grundrisse sind unvollständig.',
    'Eine Besichtigung ist bestätigt, eine Mietzusage jedoch nicht.',
    'Preis, Fläche, Zustand und Verfügbarkeit vergleichbar darstellen.|Aktuelle Angebote und Links prüfen.|Besichtigung nicht als Vertrag behandeln.'],
  ['C13','Internationaler Systemvergleich','register',[13],
    'Mehrere Verkehrssysteme sollen verglichen werden. Vergleichsjahre und Kostengrenzen sind unklar.',
    'Ein Sicherheitsvorteil wird behauptet. Eine vergleichbare Primärquelle fehlt.',
    'Länder, Bezugsjahr und Systemgrenzen sichtbar halten.|Kosten und Sicherheit nicht aus ungleichen Bezugsgrößen vergleichen.|Quellenstand und Unsicherheit nennen.'],
  ['C14','Pacht, Räumung und Schäden','register+context+retrieval',[15],
    'Kündigung und Zahlungsaufforderung liegen vor. Die Rückgabe ist nicht bestätigt.',
    'Frostschäden und Reinigungskosten werden gefordert. Ursache und vollständige Belege fehlen.',
    'Pacht, Nutzungsentschädigung und einzelne Schäden getrennt führen.|Kausalität und Forderung nicht als bewiesen darstellen.|Gegenpartei und andere Unternehmensfälle getrennt halten.'],
  ['C15','Forderungsaufstellung und Teilzahlungen','register+context',[16],
    'Die Übersicht enthält 6.430 EUR Hauptforderung und 1.120 EUR Teilzahlung. Zeitraum und Zinsgrundlage sind unklar.',
    'Die Teilzahlung wurde bestätigt. Eine vollständige Zahlung ist nicht belegt.',
    'Teilzahlungen nur einmal zuordnen.|Zeitraum, Hauptforderung, Nebenforderung und Zinsen getrennt berechnen.|Zinsbeginn nicht ohne belegten Auslöser bestimmen.'],
  ['C16','Chronologie und Beweismatrix','register+context',[17],
    'Ein alter Brief wurde erneut hochgeladen. Das Originaldatum ist unklar.',
    'Eine Anlage fehlt. Die Zeugenangabe ist bislang nicht durch ein Original belegt.',
    'Original-, Ereignis-, Zugangs- und Uploaddatum trennen.|Widersprüche und fehlende Anlagen sichtbar halten.|Behauptung, Quelle und Prüfstatus getrennt dokumentieren.'],
  ['C17','Übergabeakte und Anlagenverzeichnis','register+context',[18],
    'Die Akte enthält einen Auszug mit den Seiten 4 bis 6. Vollständigkeit ist nicht bestätigt.',
    'Ein Archiv ist vorhanden, sein Inhalt wurde noch nicht ausgewertet.',
    'Gefundene und tatsächlich ausgewertete Unterlagen unterscheiden.|Anlagen nachvollziehbar verlinken.|Keine Gesamtprüfung eines ungeöffneten Archivs behaupten.'],
  ['C18','Beschäftigungsvorwürfe und Vollstreckung','register+context+retrieval',[19],
    'Eine Zeugin behauptet, die Beschäftigung sei bestätigt. Eine Person bestreitet jede Beschäftigung; eine weitere war nur zur Probe anwesend.',
    'Eine dritte Person ist nachweislich angemeldet. Vollstreckung und Zahlungsaufforderung laufen; Aussetzung ist nicht bestätigt.',
    'Jede Person und jede Kasse gesondert zuordnen.|Anwesenheit nicht als Beschäftigungsbeweis behandeln.|Belegte Anmeldung und bestrittene Beschäftigung nicht vermischen.|Aussetzungsantrag stoppt Vollstreckung nicht automatisch.'],
  ['C19','Reinigung und Entsorgungskalkulation','register',[20],
    'Ein Reinigungsangebot nennt 31 Kubikmeter. Dichte, Entsorgungspreis und Gerätezeiten sind vorläufig.',
    'Die Durchführung ist nicht bestätigt. Eine Rechnung liegt noch nicht vor.',
    'Mengen, Einheiten, Leistung und Preis offenlegen.|Angebot von Rechnung und ausgeführter Leistung trennen.|Kosten nicht doppelt als pauschalen und einzelnen Schaden ansetzen.'],
  ['C20','Maschinenkauf, Miete und Finanzierung','register',[21],
    'Kauf, Miete und Finanzierung einer Maschine werden verglichen. Nutzungsstunden und Wartungskosten fehlen.',
    'Eine Abschreibung ist keine Auszahlung. Vermietungserlöse sind nur geplant und nicht bestätigt.',
    'Liquidität, Aufwand und Abschreibung unterscheiden.|Kauf und Miete über denselben Zeitraum vergleichen.|Unbestätigte Erlöse als Annahme zeigen.'],
  ['C21','Unterkünfte für ein Team','register',[22],
    'Für ein Team wurden Unterkünfte gefunden. Verfügbarkeit für den gewünschten Zeitraum ist unklar.',
    'Ein Gastgeber könnte die Zimmer bestätigen. Eine Buchung liegt nicht vor.',
    'Personenzahl, Zeitraum, Umkreis und Gesamtkosten prüfen.|Anfrage und bestätigte Buchung trennen.|Keine verbindliche Reservierung ohne Freigabe.'],
  ['C22','Nutzungsänderung von Hallen','register',[23],
    'Geplant ist eine Lager- und Unterstellnutzung. Eine Genehmigung ist nicht bestätigt.',
    'Bestandsnutzung, Flächen und Behördenauskunft sind unvollständig.',
    'Vorhandene Nutzung und geplante Nutzung getrennt darstellen.|Benötigte Grundlagen und Zuständigkeit klären.|Ein Konzept nicht als genehmigte Nutzung ausgeben.'],
  ['C23','Lohnabrechnung und Entgeltersatz','register',[24],
    'Die Monatsabrechnung enthält variable Zuschläge. Ihre Berücksichtigung beim Entgeltersatz ist unklar.',
    'Arbeitgeber und Kasse haben noch nicht vollständig geantwortet.',
    'Abrechnungsmonat und Berechnungszeitraum abgleichen.|Zuschläge nicht ohne Grundlage gleich behandeln.|Zwei Auskunftsanfragen mit getrennten Fragen vorbereiten.'],
  ['C24','Bauvoranfrage und Netzanschluss','register+context',[25],
    'Ein Mehrfamilienhaus mit Tiefgarage ist geplant. Eine Bauvoranfrage ist noch nicht entschieden.',
    'Ein Netzanschluss wurde angefragt. Leistung und Anschlussbedingungen sind nicht bestätigt.',
    'Entwurf, Voranfrage und Genehmigung unterscheiden.|Grundstück, Zugang, Nachbarbelange und Netzbedarf als getrennte Grundlagen prüfen.|Planwerte nicht als gesicherte Anschlusszusage behandeln.'],
  ['C25','Immobilienexposé und Projektunterlagen','register',[26],
    'Das Exposé enthält eine Visualisierung. Ein genehmigter Plan fehlt.',
    'Flächenangaben und Wirtschaftlichkeit sind vorläufig.',
    'Rendering als Visualisierung kennzeichnen.|Bestand, Plan und Genehmigung trennen.|Keine ungesicherten Kennzahlen als zugesicherte Eigenschaften darstellen.'],
  ['C26','Grundsteuer und Behördenauskunft','register+context',[27],
    'Mehrere Grundstücke und Schreiben sind vorhanden. Jahr, Bescheid und Zahlung sind noch nicht vollständig zugeordnet.',
    'Eine Erstattung sei genehmigt. Die schriftliche Entscheidung fehlt.',
    'Grundstück, Veranlagungsjahr, Bescheid und Zahlung getrennt halten.|Mögliche Erstattung nicht zusagen.|Absendekonto, Anfrage und Behördenantwort nachvollziehbar zuordnen.'],
  ['C27','Mietobjekt, Einbruchsversuch und Türschaden','register+context+retrieval',[28],
    'Eine Eingangstür ist beschädigt. Eine Zwischenabsicherung ist nicht bestätigt.',
    'Ein späterer Reparaturtermin ist angekündigt. Versicherungspflicht und Elektroarbeiten bleiben unklar.',
    'Sofortsicherung und spätere Instandsetzung trennen.|Vertragsgrundlage prüfen.|Unabhängigen Gastronomie-Versicherungsfall ausschließen.'],
  ['C28','Fahrzeugdiagnose','register',[29],
    'Ein Fehlercode wurde ausgelesen. Das defekte Bauteil ist damit noch nicht bestätigt.',
    'Messwerte, Umgebungsbedingungen und genaue Motorvariante fehlen.',
    'Fehlercode nicht als abschließende Diagnose darstellen.|Prüfreihenfolge und fehlende Messungen nennen.|Teilekompatibilität nachweisen.'],
  ['C29','Ziehungsvergleich und Rücktest','register',[30],
    'Ein Rücktest zeigt einzelne Treffer. Ein künftiger Gewinn ist nicht bestätigt.',
    'Ziehungsdaten, Einsatz und vollständige Verlustserie fehlen.',
    'Historische Treffer, Einsatz und Nettoergebnis trennen.|Keine Vorhersagefähigkeit aus Zufallstreffern ableiten.|Quellen und vollständigen Testzeitraum offenlegen.'],
  ['C30','Arbeitsstandard und Kundenkommunikation','register+context+retrieval',[31],
    'Eine Kundenfassung ist vorbereitet. Die Vorschau ist noch nicht geprüft.',
    'Eine Freigabe eines alten Entwurfs ist bestätigt. Die geänderte Fassung ist nicht freigegeben.',
    'Kurzergebnis, Ampel, höchstens drei Kernpunkte, Bedeutung und nächste Handlung zeigen.|Runde farbige Punkte in der Kundenübersicht; formale Empfängerschreiben getrennt halten.|Aktuelle Vorschau vor externer Wirkung prüfen.|Keine automatische Umstellung historischer Akten behaupten.'],
  ['C31','Produktisierung, Markt und Geschäftsmodell','register+context',[32],
    'Ein Produkt wird mit Alternativen verglichen. Marktpreise und Nutzungsannahmen sind vorläufig.',
    'Einzelne Funktionen sind geplant. Ihre produktive Verfügbarkeit ist nicht bestätigt.',
    'Istfunktion, Vorschau und Planung unterscheiden.|Preis, Herstellkosten, Deckungsbeitrag und Ergebnis getrennt rechnen.|Vorteile gegenüber bloßer KI-Nutzung konkret nachweisen.'],
  ['C32','Positionierung und Leistungsbeschreibung','register',[33],
    'Eine Beratungsmarke wird positioniert. Zielgruppe und Leistungsumfang sind noch nicht bestätigt.',
    'Ein Nutzenversprechen wird behauptet. Fallbeispiele und Wirksamkeitsnachweise fehlen.',
    'Zielgruppe, Leistung und nachgewiesenes Ergebnis verständlich darstellen.|Keine unbewiesenen Erfolgsgarantien in Werbetexte übernehmen.'],
  ['C33','Hinterbliebenenzahlungen und zwei Kinder','context+retrieval',[],
    'Für zwei Kinder liegen unterschiedliche Zahlungen vor. Weitere Einkünfte wurden verneint. Die Berechnungsanlagen fehlen.',
    'Eine steuerliche Erstattung wäre möglich. Beitragspflicht, Zahlungsart und Auskunft der auszahlenden Stelle sind unklar.',
    'Für jedes Kind eigenes Geld, Bescheid und Zeitraum führen.|Kapitalzahlung und laufende Zahlung unterscheiden.|Steuerfrage, Krankenkasse und auszahlende Stelle getrennt behandeln.|Kundenbrief in Du-Form; getrennte formale Auskunftsschreiben.|Keine bestimmte Erstattung ohne Berechnungsgrundlage versprechen.'],
  ['C34','Lohnsteuerprüfung und Belegsammlung','context',[],
    'Lohnunterlagen mehrerer Unternehmen wurden gesammelt. Die Arbeitgeberzuordnung ist nicht vollständig.',
    'Ein Schreiben mit dem Prüfungszeitraum liegt als Foto vor. Lesbarkeit und zuständige Stelle sind unklar.',
    'Nur den ausgewählten Arbeitgeber berücksichtigen.|Ausgeschlossenen Gastronomiebetrieb vollständig herauslassen.|Prüfungszeitraum, Mitarbeitende und Monate auf Lücken prüfen.|PDF und ZIP erst nach tatsächlichem Öffnen als vollständig ausweisen.'],
  ['C35','Sozialleistungen und zweisprachige Unterstützung','context',[],
    'Ein Antrag auf Leistungen wurde begonnen. Die Auszahlung ist nicht bestätigt.',
    'Ein rückwirkender Anspruch wird vermutet. Unterlagen und bisherige Bescheide fehlen.',
    'Akuten Bedarf, Antrag, Entscheidung und Auszahlung unterscheiden.|Rückwirkung nicht zusagen.|Deutsches Anschreiben und gewünschte Übersetzung vollständig bereitstellen.'],
  ['C36','Wohnung nach Todesfall','context',[],
    'Eine Person ist Miterbe und hat regelmäßig in der Wohnung übernachtet. Ein Eintritt in den Mietvertrag ist nicht bestätigt.',
    'Der Mietvertrag und die Auskunft zum gemeinsamen Haushalt fehlen.',
    'Erbenstellung, Haushaltszugehörigkeit und Mietvertragsnachfolge nicht gleichsetzen.|Keine Partnerschaft erfinden.|Fehlende Tatsachen gezielt abfragen.'],
  ['C37','Immobilienverkauf im Bestand','context',[],
    'Das Objekt soll im unrenovierten Zustand verkauft werden. Eine daneben diskutierte Neubauplanung ist nicht Gegenstand des Inserats.',
    'Ein früherer Angebotspreis fand keine Nachfrage. Ein aktueller Verkaufspreis ist nicht bestätigt.',
    'Neubauprojekt aus dem Bestandsinserat heraushalten.|Alten Angebotspreis nicht als erzielbaren Marktwert ausgeben.|Aktuelle Vergleichsangebote und Zustand berücksichtigen.'],
  ['C38','Klappbarer Transportwagen und Prototyp','context',[],
    'Geplant ist ein leichter Wagen mit gleich hohen klappbaren Wänden, inneren Zubehörschienen und äußeren Stützen. Die Traglast ist nicht bestätigt.',
    'Antrieb, Sandbetrieb und Treppenfunktion sollen erprobt werden. Ein Sicherheitstest für Kindertransport fehlt.',
    'Klappbar und faltbar unterscheiden.|Überlappung der Wände und Innen-/Außenzubehör berücksichtigen.|Konzept, Prototypkosten und getestete Belastbarkeit getrennt darstellen.|Keine Freigabe für Kindertransport aus einer Visualisierung ableiten.'],
  ['C39','Fahrzeug- und Personenzuordnung im Formular','context',[],
    'Ein Fuhrparkformular enthält Fahrzeuge und Personen. Zwei Fahrzeuge sollen entfernt werden.',
    'Die korrigierte Zuordnung ist noch nicht veröffentlicht. Ein Alias ist nicht eindeutig.',
    'Neueste ausdrücklich bestätigte Zuordnung übernehmen.|Entfernte Fahrzeuge nicht wieder einfügen.|Formularvorschau und tatsächlichen Versand getrennt prüfen.'],
  ['C40','Reisekette, Flüge und Buchungsstatus','context+retrieval',[],
    'Eine Reisekette mit Anschluss am Folgetag ist geplant. Flugpreis und Gepäck sind nicht bestätigt.',
    'Die Buchung könnte bestätigt werden. Gewünscht ist vorerst ein klickbarer Link zur eigenen Eingabe.',
    'Reiserichtung, Datum, Anschluss, Gepäck und Personenzahl abgleichen.|Livepreis und Suchstand nennen.|Linkbereitstellung nicht als Buchung ausgeben.|Gewünschten Buchungsanbieter beachten.'],
  ['C41','Produktvergleich und Budget','context',[],
    'Zwei Geräte tragen ähnliche Modellnummern. Die Ausstattung ist nicht vollständig bestätigt.',
    'Ein Budget ist vorgegeben. Verfügbarkeit und aktueller Preis fehlen.',
    'Genaue Modellnummern und Varianten abgleichen.|Budget berücksichtigen.|Aktuelle Herstellerdaten und tatsächlich verfügbaren Preis prüfen.'],
  ['C42','Gebrauchtgerät und Wertschätzung','context',[],
    'Ein gebrauchtes Gerät funktioniert laut Eigentümer. Baujahr und Marktpreis sind unklar.',
    'Eine technische Prüfung ist nicht bestätigt. Vergleichbare abgeschlossene Verkäufe fehlen.',
    'Eigentümeraussage und eigener Prüfnachweis trennen.|Angebotspreis nicht als Verkaufserlös ausgeben.|Spanne mit Zustands- und Quellenbezug nennen.'],
  ['C43','Bauteilkompatibilität und Fotomaße','context',[],
    'Ein Verbinder und ein Sitz sollen zu einer Maschine passen. Anschlussmaße sind nicht bekannt.',
    'Die Sitzbreite wurde aus einem Foto geschätzt. Passgenauigkeit ist nicht bestätigt.',
    'Fotoschätzung von Messwert unterscheiden.|Anschlussmaße und Fahrzeugmodell zuerst klären.|Kauflink auf tatsächlich passendes Teil prüfen.'],
  ['C44','Werbung als A4-Dokument','context+retrieval',[],
    'Ein Werbeblatt mit Bildern ist vorbereitet. Das gewünschte A4-Format ist noch nicht geprüft.',
    'Preis, Kontaktdaten und Bildquelle sind unvollständig.',
    'Spätere Formatkorrektur auf A4 übernehmen.|Druckansicht und Lesbarkeit prüfen.|Keine Preise oder Kontaktdaten erfinden.'],
  ['C45','Sprachen, Rechtstexte und Rechtsraum','context+retrieval',[],
    'Die Oberfläche wurde übersetzt. Vollständige Rechtstexte sind noch nicht in allen Sprachen geprüft.',
    'Ausgabesprache und Rechtsraum werden getrennt gewählt. Eine Rechtsraumprüfung ist nicht durch eine Übersetzung bestätigt.',
    'Vollständige Inhalte statt nur Überschriften übersetzen.|Spätere Korrektur zugunsten übersetzter Rechtstexte beachten.|Zwei frei wählbare Ausgabesprachen, RTL und Zahlenrichtung prüfen.|Sprache nicht mit geltendem Recht verwechseln.'],
  ['C46','Rollen, interne Änderungen und Veröffentlichung','context',[],
    'Eine Person bezeichnet sich als Eigentümer. Die technische Berechtigung ist nicht bestätigt.',
    'Eine Änderung ist intern vorbereitet. Die Freigabe zur Veröffentlichung fehlt.',
    'Eigentümerbehauptung nicht als technisch verifizierte Rolle ausgeben.|Interne Bearbeitung und Produktionsfreigabe getrennt prüfen.|Rollen, zweite Freigabe und Rücksetzung anhand echter Berechtigungen testen.'],
  ['C47','Handy, Installation, Anmeldung und Dokumentaufnahme','context',[],
    'Installation, Zurück-Navigation und Mikrofon sind vorgesehen. Ein Gerätetest ist nicht bestätigt.',
    'Ein Foto wurde synchronisiert. Lesbarkeit, Fallzuordnung und erfolgreicher Upload sind unklar.',
    'Installationszustand und doppelten Button prüfen.|Zurück-Navigation auf jeder Ebene testen.|Login, Passwortzurücksetzung, Scan und Mikrofon bis zur Speicherung prüfen.|Synchronisierung nicht mit erfolgreicher Auswertung gleichsetzen.'],
  ['C48','Marke und mehrsprachige Erklärvideos','context+retrieval',[],
    'Ein Markenname wurde geändert. Das Frontlogo ist noch nicht geprüft.',
    'Ein Video lädt. Die Aussprache und Erklärung aktueller Funktionen sind nicht bestätigt.',
    'Logo, alte Assets und aktuelle Produktfunktionen abgleichen.|Deutschen Markennamen als einzelne Buchstaben sprechen.|Ladender Player beweist keine korrekte Tonspur.|Alle angebotenen Sprachfassungen und Sprecher prüfen.'],
  ['C49','Mehrere E-Mail-Konten und Antwortzuordnung','context',[],
    'Zwei Konten zeigen ähnliche Nachrichten. Das verwendete Absendekonto ist unklar.',
    'Eine Antwort ist eingegangen. Die richtige Fallzuordnung und eine Versandfreigabe sind nicht bestätigt.',
    'Konto, Absender, Empfänger, Thread und Fall getrennt zuordnen.|Neue Antwort löst erneute Prüfung aus.|Empfänger nur aus zugelassenem Fall-/Chatkontext ermitteln.|Unklare Zuordnung vor Versand auflösen.'],
  ['C50','Privates Marketing und Reaktionsauswertung','context',[],
    'Zielgruppen, Kampagnen und Entwürfe sind angelegt. Eine Versandfreigabe liegt nicht vor.',
    'Ein Testklick ist erfasst. Echte Empfängerreaktionen und eine Veröffentlichung sind nicht bestätigt.',
    'Privaten Prototyp und öffentliches Angebot getrennt halten.|Entwurf, Versand, Klick und Antwort nicht verwechseln.|Echte Statistik und synthetische Testwerte kennzeichnen.|Keine Nachrichten ohne konkrete Vorschau und Freigabe.'],
  ['C51','Nächste Schritte, Produktstufen und Testzugang','context',[],
    'Nach einem Ergebnis sollen nächste Schritte angeboten werden. Ein kostenpflichtiger Auftrag ist nicht bestätigt.',
    'Ein Testcode ist vorgesehen. Eine erfolgreiche Einlösung und ein zahlungsfreier Test sind unklar.',
    'Erklären, was weitere Bearbeitung oder eine höhere Stufe konkret bewirkt.|Aktive Auswahl verlangen; kein automatischer Kauf.|Kein ungewünschtes Abonnement.|Testcode, Zugang und Zahlungssperre tatsächlich prüfen.'],
  ['C52','Theoretischer Aufwand und tatsächlich berechnete Leistung','register+context+retrieval',[],
    'Die Arbeit wird theoretisch mit 124 Stunden angesetzt. Es wurde bislang nichts berechnet.',
    'Ein möglicher Leistungswert ist eine Schätzung. Umsatz und Zahlung sind nicht bestätigt.',
    'Eigene Zeit und theoretischen Fremdaufwand getrennt ausweisen.|Geschätzten Leistungswert nicht als Rechnung oder Umsatz behandeln.|Teilprojekte und Überschneidungen nicht doppelt zählen.']
]

export const historyCaseCorpus = definitions.map(([id,topic,basis,registerRows,first,second,criteria]) => {
  const item={id:`history-${id}`,owner_id:'synthetic-history-owner',title:`TEST ${id} · ${topic}`,goal:'Belege prüfen und den nächsten gesicherten Schritt bestimmen.',summary:first,next_action:'Offene Fragen anhand der Originale klären.',home_country:'DE',target_country:'DE'}
  const documents=[first,second].map((extracted_text,index)=>({
    id:`history-${id}-doc-${index+1}`,case_id:item.id,owner_id:item.owner_id,
    title:`TEST ${id} · ${index?'Ergänzung':'Ausgangsunterlage'}`,extracted_text,
    data_classification:'synthetic',document_date:index?null:'2030-04-02',
    created_at:'2030-04-09T10:00:00Z',updated_at:'2030-04-09T10:00:00Z'
  }))
  return {id,topic,basis,registerRows,item,documents,reviewCriteria:criteria.split('|'),modelStatus:'pending',liveStatus:'pending'}
})
