export const TEAM_LOGIN_SCREEN='team-login'
export const TEAM_LOGIN_PATH='/?start=team-login'

export function isTeamLoginScreen(screen){
  return screen===TEAM_LOGIN_SCREEN
}

export const teamAccountCopy={
  de:{badge:'PASSWORT 1 · GEMEINSAMES TEAMKONTO',title:'Interner Teamzugang',lead:'Passwort 1 öffnet den gesamten internen Bereich. Alle autorisierten Personen sehen denselben Arbeitsstand und dürfen in sämtlichen internen Bereichen arbeiten.',rights:'Vollzugriff: Fälle, Kunden, Dokumente, Auswertungen, Schreiben, Freigaben, Einstellungen, Löschungen und Programmierungsanträge.',login:'Gesamten internen Bereich öffnen',back:'Zur internen Übersicht',settingsTitle:'Gemeinsames Teamkonto',settingsLead:'Alle angemeldeten Teammitglieder dürfen auch die Kontoeinstellungen ändern.',settingsAction:'Gemeinsames Passwort ändern'},
  en:{badge:'SHARED TEAM ACCOUNT',title:'Internal team access',lead:'Everyone uses the same credentials, sees the same workspace and may make changes in every area.',rights:'Full access: cases, clients, documents, analyses, letters, approvals, settings and deletions.',login:'Open shared account',back:'Back to internal overview',settingsTitle:'Shared team account',settingsLead:'Every signed-in team member may also change the account settings.',settingsAction:'Change shared password'},
  fr:{badge:'COMPTE D’ÉQUIPE PARTAGÉ',title:'Accès interne de l’équipe',lead:'Toutes les personnes utilisent les mêmes identifiants, voient le même espace et peuvent tout modifier.',rights:'Accès complet : dossiers, clients, documents, analyses, courriers, validations, paramètres et suppressions.',login:'Ouvrir le compte commun',back:'Retour à l’aperçu interne',settingsTitle:'Compte d’équipe partagé',settingsLead:'Chaque membre connecté peut également modifier les paramètres du compte.',settingsAction:'Modifier le mot de passe commun'},
  tr:{badge:'ORTAK EKİP HESABI',title:'Dahili ekip erişimi',lead:'Herkes aynı giriş bilgilerini kullanır, aynı çalışma alanını görür ve her bölümde değişiklik yapabilir.',rights:'Tam erişim: vakalar, müşteriler, belgeler, analizler, yazılar, onaylar, ayarlar ve silme işlemleri.',login:'Ortak hesabı aç',back:'Dahili genel bakışa dön',settingsTitle:'Ortak ekip hesabı',settingsLead:'Oturum açan her ekip üyesi hesap ayarlarını da değiştirebilir.',settingsAction:'Ortak parolayı değiştir'},
  pl:{badge:'WSPÓLNE KONTO ZESPOŁU',title:'Wewnętrzny dostęp zespołu',lead:'Wszyscy używają tych samych danych logowania, widzą ten sam obszar i mogą zmieniać wszystko.',rights:'Pełny dostęp: sprawy, klienci, dokumenty, analizy, pisma, zatwierdzenia, ustawienia i usuwanie.',login:'Otwórz wspólne konto',back:'Wróć do widoku wewnętrznego',settingsTitle:'Wspólne konto zespołu',settingsLead:'Każdy zalogowany członek zespołu może również zmieniać ustawienia konta.',settingsAction:'Zmień wspólne hasło'},
  ru:{badge:'ОБЩАЯ УЧЁТНАЯ ЗАПИСЬ',title:'Внутренний доступ команды',lead:'Все используют общие данные входа, видят единое рабочее пространство и могут изменять всё.',rights:'Полный доступ: дела, клиенты, документы, анализы, письма, согласования, настройки и удаление.',login:'Открыть общий аккаунт',back:'Назад к внутреннему обзору',settingsTitle:'Общая учётная запись',settingsLead:'Каждый вошедший участник команды может также менять настройки аккаунта.',settingsAction:'Изменить общий пароль'},
  ar:{badge:'حساب فريق مشترك',title:'دخول الفريق الداخلي',lead:'يستخدم الجميع بيانات الدخول نفسها ويرون مساحة العمل نفسها ويمكنهم تعديل جميع الأقسام.',rights:'وصول كامل: القضايا والعملاء والمستندات والتحليلات والخطابات والموافقات والإعدادات والحذف.',login:'فتح الحساب المشترك',back:'العودة إلى النظرة الداخلية',settingsTitle:'حساب الفريق المشترك',settingsLead:'يمكن لكل عضو مسجّل الدخول تعديل إعدادات الحساب أيضاً.',settingsAction:'تغيير كلمة المرور المشتركة'},
  fa:{badge:'حساب مشترک تیم',title:'دسترسی داخلی تیم',lead:'همه از اطلاعات ورود یکسان استفاده می‌کنند، فضای کاری یکسان را می‌بینند و می‌توانند همه بخش‌ها را تغییر دهند.',rights:'دسترسی کامل: پرونده‌ها، مشتریان، اسناد، تحلیل‌ها، نامه‌ها، تأییدها، تنظیمات و حذف.',login:'باز کردن حساب مشترک',back:'بازگشت به نمای داخلی',settingsTitle:'حساب مشترک تیم',settingsLead:'هر عضو واردشده می‌تواند تنظیمات حساب را نیز تغییر دهد.',settingsAction:'تغییر گذرواژه مشترک'},
  ro:{badge:'CONT COMUN DE ECHIPĂ',title:'Acces intern al echipei',lead:'Toți folosesc aceleași date de conectare, văd același spațiu și pot modifica toate zonele.',rights:'Acces complet: cazuri, clienți, documente, analize, scrisori, aprobări, setări și ștergeri.',login:'Deschide contul comun',back:'Înapoi la prezentarea internă',settingsTitle:'Cont comun de echipă',settingsLead:'Fiecare membru conectat poate modifica și setările contului.',settingsAction:'Schimbă parola comună'},
  bg:{badge:'ОБЩ ЕКИПЕН АКАУНТ',title:'Вътрешен екипен достъп',lead:'Всички използват едни и същи данни за вход, виждат общото работно пространство и могат да променят всичко.',rights:'Пълен достъп: случаи, клиенти, документи, анализи, писма, одобрения, настройки и изтриване.',login:'Отвори общия акаунт',back:'Назад към вътрешния преглед',settingsTitle:'Общ екипен акаунт',settingsLead:'Всеки влязъл член на екипа може да променя и настройките на акаунта.',settingsAction:'Промени общата парола'},
  vi:{badge:'TÀI KHOẢN NHÓM DÙNG CHUNG',title:'Truy cập nội bộ của nhóm',lead:'Mọi người dùng chung thông tin đăng nhập, thấy cùng một không gian làm việc và có thể thay đổi mọi phần.',rights:'Toàn quyền: vụ việc, khách hàng, tài liệu, phân tích, thư, phê duyệt, cài đặt và xóa.',login:'Mở tài khoản dùng chung',back:'Quay lại tổng quan nội bộ',settingsTitle:'Tài khoản nhóm dùng chung',settingsLead:'Mọi thành viên đã đăng nhập đều có thể thay đổi cả cài đặt tài khoản.',settingsAction:'Đổi mật khẩu dùng chung'}
}

const teamGovernanceCopy={
  de:{approvalRule:'Passwort 2 bleibt bei Sebastian. Es gibt einen vollständig vorbereiteten Entwurf als neue Live-Version frei.',sharedPasswordLabel:'Passwort 1 · gemeinsames Zugangspasswort',settingsLead:'Mit Passwort 1 darf auf alles zugegriffen und jede Änderung an AS Workspace vorbereitet werden. Passwort 2 gibt die neue Live-Version frei.',settingsAction:'Änderung an AS Workspace vorbereiten'},
  en:{approvalRule:'Password 2 remains with Sebastian. It releases one fully prepared draft as the new live version.',sharedPasswordLabel:'Password 1 · shared access password',settingsLead:'Password 1 grants access to everything and allows any AS Workspace change to be prepared. Password 2 releases the new live version.',settingsAction:'Prepare an AS Workspace change'}
}

export function getTeamAccountCopy(language){
  return {...(teamAccountCopy[language]||teamAccountCopy.de),...(teamGovernanceCopy[language]||teamGovernanceCopy.de)}
}
