import { LegalDocument, LegalNotice, LegalSection } from '../components/LegalDocument'

export const metadata={title:'Nutzungsbedingungen | AS Workspace Gold',description:'Nutzungsbedingungen für den kontrollierten Testbetrieb von AS Workspace Gold.'}

export default function Terms(){
  return <LegalDocument pageId="nutzungsbedingungen" title="Nutzungsbedingungen" intro="Bedingungen für den aktuellen kostenlosen und kontrollierten Testbetrieb von AS Workspace Gold." updated="30. August 2026 · Version 2026-08-30-test-v1">
    <LegalNotice tone="warning"><b>Keine Zahlung, kein Abo</b><p>Die Bezahlfunktion ist deaktiviert. Registrierung und Testzugang lösen keine Zahlung, kein kostenpflichtiges Abonnement und keine automatische Verlängerung aus.</p></LegalNotice>
    <LegalSection title="1. Anbieter und Geltungsbereich"><p>Anbieter ist Sebastian Auls – Unternehmens- und Konzeptberatung, Chrysanderstraße 75, 21029 Hamburg. Diese Bedingungen gelten für die Registrierung und Nutzung von AS Workspace Gold im kontrollierten Test. Abweichende Bedingungen gelten nur, wenn sie ausdrücklich vereinbart wurden.</p></LegalSection>
    <LegalSection title="2. Testzugang"><p>Der Zugang dient der Erprobung von Fallstruktur, Dokumentablage, manueller Prüfung, Freigaben, Exporten und optionaler KI-Analyse. Verfügbarkeit, Funktionen und Testumfang können sachlich begründet angepasst oder beendet werden. Vor einer wesentlichen nachteiligen Änderung werden registrierte Nutzer angemessen informiert, soweit dies möglich und zumutbar ist.</p></LegalSection>
    <LegalSection title="3. Registrierung und Kontosicherheit"><p>Registrierende Personen müssen geschäftsfähig oder wirksam vertreten sein, richtige Angaben machen, ein sicheres Passwort wählen und Zugangsdaten geheim halten. Konten dürfen nicht ohne Zustimmung an Dritte weitergegeben werden. Verdächtige Zugriffe sind unverzüglich zu melden.</p></LegalSection>
    <LegalSection title="4. Strikte Testdaten-Regel"><p>Zulässig sind ausschließlich selbst erzeugte synthetische Daten oder Daten, die so anonymisiert wurden, dass eine Person mit vertretbaren Mitteln nicht mehr identifiziert werden kann. Unzulässig sind insbesondere echte Kundendaten, Kontaktdaten Dritter, Personalakten, Gesundheitsdaten, biometrische oder genetische Daten, Zugangsdaten, amtliche Geheimnisse und sonstige besondere Kategorien personenbezogener Daten. Nutzer tragen die Verantwortung, vor dem Upload sicherzustellen, dass sie zur Nutzung der Inhalte berechtigt sind.</p></LegalSection>
    <LegalSection title="5. KI-Analyse"><p>Eine KI-Analyse startet nur nach einer separaten Bestätigung im einzelnen Dokument. Dabei wird die freigegebene Testdatei an die OpenAI API übermittelt. Ergebnisse sind vorläufig, können falsch oder unvollständig sein und müssen fachlich geprüft werden. Details stehen unter <a href="/ki-transparenz">KI-Transparenz</a>.</p></LegalSection>
    <LegalSection title="6. Keine Beratung und keine automatische Außenwirkung"><p>AS Workspace Gold unterstützt beim Ordnen und Prüfen von Informationen. Das Produkt ersetzt keine Rechts-, Steuer-, Finanz- oder sonstige Fachberatung. Fristen, Risiken, Beträge und Handlungsvorschläge müssen eigenverantwortlich geprüft werden. AS Workspace Gold versendet derzeit keine Nachrichten automatisch und führt keine Zahlung oder Vertragsverlängerung aus.</p></LegalSection>
    <LegalSection title="7. Nutzungsrechte und zulässige Verwendung"><p>Für die Dauer des Testzugangs erhält der Nutzer ein einfaches, nicht übertragbares Recht, AS Workspace Gold für eigene zulässige Testzwecke zu verwenden. Untersagt sind missbräuchliche Zugriffe, Sicherheitsumgehung, Schadcode, automatisierte Überlastung, Rechteverletzungen und die Nutzung für rechtswidrige Zwecke.</p></LegalSection>
    <LegalSection title="8. Preise als Produktvorschau"><p>Die dargestellten Tarife und Laufzeiten beschreiben die geplante Produktstaffel. Solange die Bezahlfunktion als deaktiviert gekennzeichnet ist, stellen sie kein zahlungspflichtiges Bestellangebot dar. Vor einer späteren Aktivierung werden Gesamtpreis, Leistungsumfang, Laufzeit, Zahlungsbedingungen, Widerruf und der eindeutig beschriftete zahlungspflichtige Bestellschritt gesondert angezeigt. Geplant ist keine automatische Verlängerung; eine neue Laufzeit soll nur durch eine neue ausdrückliche Auswahl entstehen.</p></LegalSection>
    <LegalSection title="9. Laufzeit, Beendigung und Daten"><p>Der kostenlose Test läuft bis zur Beendigung durch den Nutzer oder Anbieter. Der Nutzer kann den Zugang über die <a href="/widerruf">Widerrufsfunktion</a>, per E-Mail oder über den Löschantrag im Konto beenden. Ein Löschantrag wird vor Ausführung auf Identität, Abhängigkeiten und gesetzliche Aufbewahrungspflichten geprüft. Bei pausiertem Zugang werden Arbeitsdaten grundsätzlich höchstens drei Monate zur Reaktivierung vorgehalten, sofern keine frühere Löschung verlangt wird oder gesetzliche Gründe entgegenstehen.</p></LegalSection>
    <LegalSection title="10. Gewährleistung und Haftung"><p>Es gelten die gesetzlichen Mängel- und Haftungsregeln. Die Kennzeichnung als Test, der Hinweis auf notwendige fachliche Prüfung und die fehlende Garantie für KI-Ergebnisse schränken zwingende Verbraucherrechte oder die Haftung für Vorsatz, grobe Fahrlässigkeit, Verletzung von Leben, Körper oder Gesundheit sowie nach zwingendem Produkthaftungsrecht nicht ein.</p></LegalSection>
    <LegalSection title="11. Datenschutz"><p>Die Verarbeitung personenbezogener Daten ist in der <a href="/datenschutz">Datenschutzerklärung</a> beschrieben. Datenschutzbestätigung und Vertragsannahme werden getrennt verständlich angezeigt; die Datenschutzerklärung selbst ist keine pauschale Einwilligung.</p></LegalSection>
    <LegalSection title="12. Anwendbares Recht und Streitbeilegung"><p>Es gilt deutsches Recht unter Wahrung zwingender Verbraucherschutzvorschriften des Staates, in dem ein Verbraucher seinen gewöhnlichen Aufenthalt hat. Der Anbieter ist weder verpflichtet noch bereit, an einem Streitbeilegungsverfahren vor einer Verbraucherschlichtungsstelle teilzunehmen.</p></LegalSection>
  </LegalDocument>
}
