export const extraPageTranslations={
  dashboardGuide:{
    ro:{
      free:{title:'Bun venit – începeți simplu',lead:'Nu trebuie să pregătiți nimic. Încărcați mai întâi un document; AS Gold vă arată clar ce poate identifica.',steps:['1. Încărcați un document','2. Verificați rezultatul','3. Decideți dacă aveți nevoie de mai multă profunzime'],next:'Încărcați primul document',nextSection:'documents',mode:'Start ghidat'},
      start:{title:'Organizați mai întâi cazul',lead:'Creați clientul sau cazul, apoi asociați documentele disponibile.',steps:['1. Adăugați client','2. Creați caz','3. Asociați documente'],next:'Adăugați client',nextSection:'clients',mode:'Start structurat'},
      klar:{title:'Faceți vizibile lipsurile și prioritățile',lead:'Lucrați caz cu caz. Verificați documentele, punctele deschise și starea curentă.',steps:['1. Deschideți cazul','2. Verificați documentele','3. Prioritizați punctele deschise'],next:'Verificați cazurile',nextSection:'cases',mode:'Mod claritate'},
      analyse:{title:'Evaluați situația, riscurile și pașii următori',lead:'Folosiți prezentarea cazului ca centru de lucru. Riscurile și opțiunile sunt prioritare.',steps:['1. Selectați cazul','2. Verificați riscurile','3. Stabiliți pașii următori'],next:'Deschideți analiza',nextSection:'cases',mode:'Mod analiză'},
      komplett:{title:'Procesați cazul ca flux complet',lead:'Clienții, cazurile, documentele, rezultatele și aprobările sunt gestionate într-un singur proces.',steps:['1. Verificați starea','2. Pregătiți rezultate și scrisori','3. Controlați aprobările'],next:'Deschideți cazurile de lucru',nextSection:'cases',mode:'Mod procesare'},
      business:{title:'Centrul dvs. Business',lead:'Gestionați mai mulți clienți și cazuri în paralel. Folosiți stările, documentele și aprobările ca vedere operațională.',steps:['Gestionați portofoliul de clienți și cazuri','Monitorizați aprobările în așteptare','Controlați starea documentelor și proceselor'],next:'Gestionați cazurile Business',nextSection:'cases',mode:'Control Business'}
    },
    bg:{
      free:{title:'Добре дошли – започнете лесно',lead:'Не е нужно да подготвяте нищо. Първо качете документ; AS Gold ясно ще покаже какво може да извлече.',steps:['1. Качете документ','2. Прегледайте резултата','3. Решете дали ви трябва повече дълбочина'],next:'Качете първия документ',nextSection:'documents',mode:'Воден старт'},
      start:{title:'Първо организирайте случая',lead:'Създайте клиент или случай, след което свържете наличните документи.',steps:['1. Добавете клиент','2. Създайте случай','3. Свържете документите'],next:'Добавете клиент',nextSection:'clients',mode:'Структуриран старт'},
      klar:{title:'Направете липсите и приоритетите видими',lead:'Работете по случаи. Проверете документите, откритите точки и текущия статус.',steps:['1. Отворете случая','2. Проверете документите','3. Подредете откритите точки'],next:'Проверете случаите',nextSection:'cases',mode:'Режим яснота'},
      analyse:{title:'Оценете ситуацията, рисковете и следващите стъпки',lead:'Използвайте прегледа на случая като работен център. Рисковете и опциите са с приоритет.',steps:['1. Изберете случай','2. Проверете рисковете','3. Определете следващите стъпки'],next:'Отворете анализа',nextSection:'cases',mode:'Режим анализ'},
      komplett:{title:'Обработете случая като цялостен процес',lead:'Клиенти, случаи, документи, резултати и одобрения се управляват в един процес.',steps:['1. Проверете състоянието','2. Подгответе резултати и писма','3. Контролирайте одобренията'],next:'Отворете работните случаи',nextSection:'cases',mode:'Режим обработка'},
      business:{title:'Вашият Business контролен център',lead:'Управлявайте няколко клиента и случая паралелно. Използвайте статусите, документите и одобренията като оперативен преглед.',steps:['Управлявайте портфейла от клиенти и случаи','Следете чакащите одобрения','Контролирайте статуса на документите и процесите'],next:'Управлявайте Business случаите',nextSection:'cases',mode:'Business управление'}
    }
  },
  caseDiscoveryText:{
    ro:{nav:'Tipuri de cazuri',chooseCase:'Alegeți tipul potrivit de caz',freeHint:'Începeți gratuit: până la 3 documente · fără plată · fără reînnoire automată',eyebrow:'Pentru cine și pentru ce situații',title:'Pentru ce aveți nevoie de claritate acum?',lead:'Alegeți tipul de caz. Vedeți imediat exemple, cum ajută AS Gold și ce rezultat primiți.',typical:'Cazuri tipice',support:'Cum vă ajută AS Gold',result:'Primiți',results:['o imagine de ansamblu structurată','lipsuri, contradicții și termene vizibile','o evaluare trasabilă tip semafor','pași următori concreți și proiecte potrivite'],start:'Începeți gratuit acest caz',stepsTitle:'Trei pași către un caz clar',steps:[['01','Alegeți tipul cazului','Selectați domeniul care se potrivește cel mai bine situației.'],['02','Adăugați documente','Scrisori, contracte, e-mailuri, facturi sau fotografii sunt asociate cazului.'],['03','Verificați rezultatul','Vedeți starea, dovezile lipsă, semaforul și pasul logic următor.']],transparencyDetails:'Afișați toate regulile de transparență',cases:[
      {key:'insurance',title:'Asigurare și daună',short:'Acoperire, daună, dovezi',examples:'Daune materiale, auto, de călătorie, sănătate sau profesionale și prestații refuzate ori reduse.',help:'Ordonează documentele și răspunsurile asigurătorului, identifică dovezile lipsă și pregătește pasul următor.'},
      {key:'property',title:'Chirie, leasing și imobiliare',short:'Restanțe, daune, predare',examples:'Restanțe de chirie, reziliere, daune, predare, costuri auxiliare și obligații de reparație.',help:'Leagă contractele, plățile, starea, responsabilitățile, termenele și dovezile într-un dosar trasabil.'},
      {key:'contract',title:'Contract și creanță',short:'Factură, prestație, reziliere',examples:'Facturi greșite, creanțe deschise, prestații neexecutate, modificări contractuale și rezilieri.',help:'Compară contractul cu desfășurarea reală, evidențiază abaterile și pregătește un răspuns motivat.'},
      {key:'authority',title:'Autorități și asigurări sociale',short:'Decizie, termen, dovadă',examples:'Cazuri cu asigurarea de sănătate, pensii, vamă, administrație sau autorități de autorizare.',help:'Rezuma clar corespondența oficială, protejează termenele și indică informațiile ori dovezile lipsă.'},
      {key:'work',title:'Muncă și salarizare',short:'Salariu, boală, angajare',examples:'Fluturași de salariu, indemnizație de boală, timp de lucru, sporuri și comunicarea cu angajatorul.',help:'Compară calculele, perioadele și declarațiile, evidențiază neconcordanțele și pregătește o scrisoare factuală.'},
      {key:'business',title:'Companie și clienți',short:'Caz client, proiect, aprobare',examples:'Cazuri de clienți, reclamații, proiecte, furnizori, sarcini recurente și aprobări interne.',help:'Reunește persoane, documente, sarcini și decizii într-un flux controlat.'},
      {key:'dispute',title:'Litigiu și dovezi',short:'Cronologie, pretenție, dovadă',examples:'Litigii de durată cu declarații contradictorii, pretenții și corespondență extinsă.',help:'Pregătește cronologia, situația dovezilor și punctele deschise pentru negociere, consiliere sau instanță.'},
      {key:'private',title:'Situație personală complexă',short:'Călătorie, vehicul, contract',examples:'Probleme de călătorie, vehicule, contracte private sau alte situații cu multe documente.',help:'Transformă informațiile dispersate într-o imagine clară a ceea ce este dovedit, ce lipsește și ce urmează.'}
    ]},
    bg:{nav:'Видове случаи',chooseCase:'Изберете подходящ вид случай',freeHint:'Започнете безплатно: до 3 документа · без плащане · без автоматично подновяване',eyebrow:'За кого и за какви ситуации',title:'За какво ви трябва яснота сега?',lead:'Изберете вид случай. Веднага ще видите примери, как AS Gold помага и какъв резултат получавате.',typical:'Типични случаи',support:'Как AS Gold помага',result:'Получавате',results:['структуриран преглед на случая','видими липси, противоречия и срокове','проследима светофарна оценка','конкретни следващи стъпки и подходящи проекти'],start:'Започнете този случай безплатно',stepsTitle:'Три стъпки към ясен случай',steps:[['01','Изберете вид случай','Изберете областта, която най-добре съответства на ситуацията ви.'],['02','Добавете документи','Писма, договори, имейли, фактури или снимки се свързват със случая.'],['03','Проверете резултата','Вижте състоянието, липсващите доказателства, светофара и логичната следваща стъпка.']],transparencyDetails:'Покажи всички правила за прозрачност',cases:[
      {key:'insurance',title:'Застраховка и щета',short:'Покритие, щета, доказателства',examples:'Имуществени, автомобилни, туристически, здравни или бизнес щети и отказани или намалени обезщетения.',help:'Подрежда документите и отговорите на застрахователя, открива липсващи доказателства и подготвя следващата стъпка.'},
      {key:'property',title:'Наем, аренда и имоти',short:'Задължения, щети, предаване',examples:'Просрочен наем, прекратяване, щети, предаване, допълнителни разходи и задължения за ремонт.',help:'Свързва договори, плащания, състояние, отговорности, срокове и доказателства в проследим случай.'},
      {key:'contract',title:'Договор и вземане',short:'Фактура, услуга, прекратяване',examples:'Грешни фактури, неплатени вземания, неизпълнени услуги, договорни промени и прекратявания.',help:'Сравнява договора с реалното развитие, показва отклоненията и подготвя мотивиран отговор.'},
      {key:'authority',title:'Администрация и социално осигуряване',short:'Решение, срок, доказателство',examples:'Случаи със здравно осигуряване, пенсии, митници, администрация или разрешителни органи.',help:'Обобщава официалните писма, следи сроковете и посочва липсващата информация или доказателства.'},
      {key:'work',title:'Работа и заплащане',short:'Заплата, болест, заетост',examples:'Фишове за заплати, обезщетения по болест, работно време, добавки и комуникация с работодателя.',help:'Сравнява изчисления, периоди и декларации, показва несъответствия и подготвя фактическо писмо.'},
      {key:'business',title:'Бизнес и клиенти',short:'Клиентски случай, проект, одобрение',examples:'Клиентски случаи, рекламации, проекти, доставчици, повтарящи се задачи и вътрешни одобрения.',help:'Събира хора, документи, задачи и решения в контролиран работен поток.'},
      {key:'dispute',title:'Спор и доказателства',short:'Хронология, претенция, доказателство',examples:'Продължителни спорове с противоречиви твърдения, претенции и обширна кореспонденция.',help:'Подготвя хронология, преглед на доказателствата и откритите точки за преговори, консултация или съд.'},
      {key:'private',title:'Сложна лична ситуация',short:'Пътуване, автомобил, договор',examples:'Проблеми с пътуване, автомобил, частни договори или други ситуации с много документи.',help:'Превръща разпръснатата информация в ясен преглед на доказаното, липсващото и следващата стъпка.'}
    ]}
  }
}
