const workspaceCopy={
  quickTitle:'Bắt đầu nhanh',quickLead:'Tạo hồ sơ hoặc thêm tài liệu thử nghiệm.',newCase:'Hồ sơ mới',scanDocument:'Quét tài liệu',uploadFile:'Tải tệp lên',clients:'Khách hàng',deadlines:'Thời hạn',approvals:'Phê duyệt',dueSoon:'Sắp đến hạn',noDeadline:'Không có thời hạn',caseSetup:'Thiết lập hồ sơ',caseSetupHelp:'Ghi lại mục tiêu, tình trạng và hành động tiếp theo.',title:'Tiêu đề',documentTitle:'Tiêu đề tài liệu',client:'Khách hàng',noClient:'Không có khách hàng',reference:'Mã tham chiếu',goal:'Mục tiêu',summary:'Tình trạng',deadline:'Thời hạn',nextAction:'Hành động tiếp theo',createCase:'Tạo hồ sơ',saveChanges:'Lưu thay đổi',cancel:'Hủy',editCase:'Chỉnh sửa hồ sơ',sourceBasis:'Cơ sở nguồn',assessmentState:'Trạng thái đánh giá',notAssessable:'Chưa thể đánh giá',reviewRequired:'Cần kiểm tra',reviewed:'Đã kiểm tra',noDocuments:'Chưa có tài liệu',currentAssessments:'Đánh giá hiện tại',noAssessment:'Chưa có đánh giá',addAssessment:'Thêm đánh giá',assessmentTitle:'Tiêu đề đánh giá',trafficLight:'Đèn trạng thái',reasoning:'Lý do',assessmentNext:'Bước tiếp theo',saveAssessment:'Lưu đánh giá',green:'Xanh',yellow:'Vàng',red:'Đỏ',documentUpload:'Tải tài liệu lên',uploadMode:'Tải tệp',scanMode:'Quét bằng camera',scanHelp:'Chụp tài liệu rõ nét và kiểm tra ảnh trước khi lưu.',uploadHelp:'Chọn tệp thử nghiệm được phép.',file:'Tệp',documentType:'Loại tài liệu',documentDate:'Ngày tài liệu',withoutCase:'Không gắn với hồ sơ',upload:'Tải lên',uploading:'Đang tải lên …',documentReview:'Kiểm tra tài liệu',documentReviewHelp:'Kiểm tra bản gốc và tất cả thông tin được nhận diện.',originalFile:'Tệp gốc',extractedText:'Văn bản trích xuất',noExtraction:'Chưa có văn bản trích xuất',textAvailable:'Đã có văn bản',analysisSummary:'Tóm tắt phân tích',analysisNext:'Bước tiếp theo từ phân tích',saveDocument:'Lưu tài liệu',back:'Quay lại',created:'Đã tạo',clientUnknown:'Khách hàng chưa xác định',documents:'Tài liệu',caseRecord:'Hồ sơ',selectCase:'Chọn hồ sơ'
}

const approvalCopy={
  title:'Phê duyệt',lead:'Kiểm tra nội dung trước khi xuất hoặc gửi.',newApproval:'Phê duyệt mới',cancel:'Hủy',case:'Hồ sơ',chooseCase:'Chọn hồ sơ',document:'Tài liệu',noDocument:'Không có tài liệu',type:'Loại phê duyệt',types:{send:'Gửi',binding_use:'Sử dụng có tính ràng buộc',export_delivery:'Xuất / bàn giao'},recipient:'Người nhận',subject:'Chủ đề',body:'Nội dung',create:'Tạo phê duyệt',none:'Chưa có phê duyệt',pending:'Đang chờ',approved:'Đã phê duyệt',rejected:'Bị từ chối',revision:'Bản sửa đổi',back:'Quay lại',preview:'Xem trước',previewHelp:'Kiểm tra người nhận, nội dung và tệp đính kèm.',attachments:'Tệp đính kèm',noAttachments:'Không có tệp đính kèm',edit:'Chỉnh sửa',save:'Lưu',confirm:'Xác nhận kiểm tra',approve:'Phê duyệt',reject:'Từ chối',approvedAt:'Phê duyệt lúc',approvedRevision:'Bản đã phê duyệt',invalidated:'Phê duyệt không còn hiệu lực sau khi nội dung thay đổi.',stale:'Nội dung đã thay đổi sau lần phê duyệt cuối.',saved:'Đã lưu thay đổi.',created:'Đã tạo yêu cầu phê duyệt.',approvedMessage:'Nội dung đã được phê duyệt.',rejectedMessage:'Nội dung đã bị từ chối.',prepareFromDocument:'Chuẩn bị từ tài liệu',caseRequired:'Vui lòng chọn hồ sơ.',contentRequired:'Vui lòng nhập chủ đề hoặc nội dung.',documentMismatch:'Tài liệu không thuộc hồ sơ đã chọn.',recipientRequired:'Vui lòng nhập người nhận trước khi phê duyệt việc gửi.'
}

const analysisCopy={
  badge:'Phân tích AI tự nguyện',title:'Phân tích tài liệu',lead:'AS Gold tạo đề xuất có thể chỉnh sửa để bạn kiểm tra.',privacyTitle:'Chỉ bắt đầu sau khi xác nhận',privacyText:'Tệp thử nghiệm được phép sẽ được gửi đến OpenAI API để phân tích. Kết quả là tạm thời và không thay thế việc kiểm tra chuyên môn.',details:'Nội dung nào được truyền?',confirm:'Tôi chủ động yêu cầu phân tích tài liệu này và sẽ kiểm tra kết quả.',start:'Bắt đầu phân tích AI',analyzing:'Đang phân tích …',unsupported:'Hiện AI chỉ đọc PDF, JPG, PNG, WEBP và GIF. Bạn vẫn có thể nhập các trường thủ công.',limit:'Phân tích AI: tối đa 18 MB mỗi tệp. Giới hạn tải lên tạm thời 50 MB không áp dụng cho phân tích tự động.',uploaded:'Chưa bắt đầu phân tích',draft:'Đề xuất AI · tạm thời và chưa lưu',saved:'Đã lưu dữ liệu được kiểm tra',facts:'Thông tin nhận diện thêm để kiểm tra',sender:'Người gửi / tác giả',recipient:'Người nhận',references:'Số hồ sơ / tham chiếu',deadlines:'Thời hạn được nêu',amounts:'Khoản tiền được nêu',confidence:'Độ tin cậy nhận diện',none:'Không nhận diện được mục nào',manual:'Mọi đề xuất đều có thể chỉnh sửa. Chỉ nút lưu mới tiếp nhận dữ liệu đã kiểm tra.',save:'Lưu dữ liệu đã tự nguyện kiểm tra',ready:'Phân tích hoàn tất. Hãy kiểm tra từng thông tin trước khi lưu.',failed:'Không thể hoàn tất phân tích.',savedMessage:'Dữ liệu tài liệu đã kiểm tra được lưu.',notStarted:'Chưa bắt đầu phân tích. Không thể đánh giá đáng tin cậy nếu chưa có nội dung được kiểm tra.',confidenceValues:{hoch:'Cao',high:'Cao',mittel:'Trung bình',medium:'Trung bình',mid:'Trung bình',niedrig:'Thấp',low:'Thấp'}
}

const privacyCopy={
  required:'Vui lòng xác nhận văn bản pháp lý và quy tắc dữ liệu thử nghiệm.',registerLegal:'Tôi đã đọc thông tin quyền riêng tư và điều khoản sử dụng, đồng thời chấp nhận điều kiện của thử nghiệm miễn phí.',registerTest:'Tôi chỉ sử dụng dữ liệu thử nghiệm tổng hợp hoặc đã ẩn danh hiệu quả — không dùng dữ liệu cá nhân thật của bên thứ ba hoặc dữ liệu nhạy cảm.',privacy:'Thông tin quyền riêng tư',terms:'Điều khoản sử dụng',gateBadge:'V28 · cần xác nhận',gateTitle:'Xác nhận một lần các văn bản pháp lý hiện hành',gateLead:'Tài khoản vẫn do bạn kiểm soát. Trước khi tiếp tục, chúng tôi ghi nhận việc bạn xác nhận các văn bản pháp lý Đức hiện hành và điều kiện thử nghiệm có kiểm soát.',gateAction:'Xác nhận và tiếp tục',classification:'Loại dữ liệu trong tệp',synthetic:'Dữ liệu thử nghiệm tổng hợp',anonymized:'Dữ liệu thử nghiệm đã ẩn danh hiệu quả',uploadConfirm:'Tôi xác nhận tệp không chứa dữ liệu cá nhân thật hoặc dữ liệu nhạy cảm và việc ẩn danh không thể bị đảo ngược một cách hợp lý.',uploadHelp:'Trong thử nghiệm có kiểm soát chỉ cho phép tệp tổng hợp hoặc đã ẩn danh hiệu quả. Việc truyền cho AI chỉ bắt đầu sau một xác nhận riêng cho từng tài liệu.',uploadRequired:'Chọn loại dữ liệu thử nghiệm được phép và xác nhận quy tắc.',saved:'Đã ghi nhận điều kiện quyền riêng tư và thử nghiệm.'
}

const aiControlCopy={aiControl:'Kiểm soát AI',aiEnabled:'Xử lý AI được phép ở cấp tài khoản. Mỗi lần truyền vẫn cần xác nhận mới cho tài liệu.',aiDisabled:'Xử lý AI đã bị tắt ở cấp tài khoản và chỉ bật lại khi bạn chủ động xác nhận phân tích một tài liệu.',disableAi:'Tắt xử lý AI',disableAiDone:'Đã tắt xử lý AI và mọi phê duyệt tài liệu đang mở.'}
const passwordCopy={title:'Mật khẩu thử nghiệm an toàn',intro:'Dùng ít nhất 12 ký tự và chỉ sử dụng mật khẩu này cho AS Gold.',length:'Ít nhất 12 ký tự',letter:'Ít nhất một chữ cái',number:'Ít nhất một chữ số',symbol:'Ít nhất một ký tự đặc biệt',variety:'Ít nhất 8 ký tự khác nhau',personal:'Không chứa tên, phần email hoặc mật khẩu phổ biến',match:'Hai lần nhập khớp nhau',invalid:'Mật khẩu chưa đáp ứng yêu cầu bảo mật.'}

export const vietnameseComponentTranslations={workspaceCopy,approvalCopy,analysisCopy,privacyCopy,aiControlCopy,passwordCopy}
