const de={
  eyebrow:'Quellengebundene Fallprüfung',title:'Rechtsraumvergleich',intro:'Vergleicht die konkrete Rechtsfrage dieses Falls zwischen Heimatland und Zielland und erklärt die praktische Bedeutung.',baseline:'Heimatland und Zielland bestimmen nicht automatisch, welches Recht gilt. Dafür werden Vertrag, Ort, Parteien und Zuständigkeit gesondert geprüft.',legend:'Bedeutung der Vergleichsampel',greenLabel:'Belegt vergleichbar',greenMeaning:'Beide Seiten sind amtlich belegt; kein wesentlicher Unterschied erkannt.',yellowLabel:'Unterschied oder offen',yellowMeaning:'Abweichung, offene Zuständigkeit oder weitere Prüfung nötig.',redLabel:'Belegtes Risiko',redMeaning:'Eine amtlich belegte Abweichung kann akuten Handlungsbedarf auslösen.',whiteLabel:'Nicht belegbar',whiteMeaning:'Mindestens eine Seite hat noch keine belastbare amtliche Quelle.',topic:'Gewünschtes Rechtsgebiet',question:'Konkrete Frage des Kunden',requestedQuestion:'Kundenfrage',questionHelp:'Je genauer die Frage, desto verständlicher und belastbarer wird die Übersicht.',classification:'Datenart dieses Falls',synthetic:'Synthetische Testdaten',anonymized:'Wirksam anonymisierte Daten',consent:'Ich bestätige, dass die Fallangaben und einbezogenen Dokumentzusammenfassungen der gewählten Datenart entsprechen, und erlaube die einmalige KI-Recherche in aktuellen amtlichen Quellen.',create:'Vergleich mit Primärquellen erstellen',creating:'Amtliche Quellen werden recherchiert und verglichen …',loadFailed:'Frühere Vergleiche konnten nicht geladen werden.',createFailed:'Der Rechtsraumvergleich konnte nicht erstellt werden.',noResults:'Noch kein Rechtsraumvergleich für diesen Fall.',history:'Vergleichsstand',sameCountry:'Heimatland und Zielland sind identisch. Für einen Ländervergleich bitte den Fall bearbeiten.',result:'Erklärender Vergleich',applicableLaw:'Welches Recht ist wahrscheinlich anwendbar?',missingFactors:'Noch benötigte Angaben',comparisonPoints:'Vergleich nach Einzelpunkten',practicalMeaning:'Bedeutung für den Kunden',confidence:'Quellensicherheit',sources:'Amtliche Quellen',sourceType_legislation:'Gesetz / Verordnung',sourceType_court:'Gericht',sourceType_authority:'Behörde / amtliche Hinweise',sourceType_treaty:'Staatsvertrag / internationales Recht',sourceType_other:'Sonstige amtliche Quelle',noSources:'Keine belastbare Primärquelle gefunden.',openQuestions:'Offene Fragen',nextSteps:'Nächste Schritte',customerExplanation:'Einfache Erklärung für den Kunden',reviewRequired:'Rechercheentwurf: Vor einer rechtlich verbindlichen Verwendung ist eine fachliche Prüfung erforderlich.',sourceChecked:'Quellenstand',newComparison:'Neue Frage vergleichen',known:'belegt',likely:'wahrscheinlich',unclear:'ungeklärt',high:'hoch',medium:'mittel',low:'niedrig',same:'vergleichbar',different:'Unterschied',risk:'akutes Risiko',privacyRequired:'Bitte bestätigen Sie die Datenart.',questionRequired:'Bitte formulieren Sie eine konkrete Frage mit mindestens 12 Zeichen.'
}

const en={
  eyebrow:'Source-bound case review',title:'Jurisdiction comparison',intro:'Compares this case question between the home and target countries and explains the practical effect.',baseline:'Home and target country do not automatically determine the applicable law. Contract, place, parties and jurisdiction are checked separately.',legend:'Meaning of the comparison lights',greenLabel:'Supported and comparable',greenMeaning:'Both sides have official support; no material difference was identified.',yellowLabel:'Difference or open point',yellowMeaning:'A difference, open jurisdiction issue or further review remains.',redLabel:'Supported risk',redMeaning:'An officially supported difference may require urgent action.',whiteLabel:'Not supported',whiteMeaning:'At least one side still lacks a reliable official source.',topic:'Requested legal area',question:'Customer’s specific question',requestedQuestion:'Customer question',questionHelp:'A precise question produces a clearer and more reliable overview.',classification:'Data type for this case',synthetic:'Synthetic test data',anonymized:'Effectively anonymised data',consent:'I confirm that the case details and included document summaries match the selected data type and allow a one-time AI search of current official sources.',create:'Create comparison from primary sources',creating:'Searching and comparing official sources …',loadFailed:'Previous comparisons could not be loaded.',createFailed:'The jurisdiction comparison could not be created.',noResults:'No jurisdiction comparison for this case yet.',history:'Comparison version',sameCountry:'Home and target country are identical. Edit the case to compare countries.',result:'Explanatory comparison',applicableLaw:'Which law is likely to apply?',missingFactors:'Information still required',comparisonPoints:'Comparison by issue',practicalMeaning:'Practical meaning for the customer',confidence:'Source confidence',sources:'Official sources',sourceType_legislation:'Legislation / regulation',sourceType_court:'Court',sourceType_authority:'Authority / official guidance',sourceType_treaty:'Treaty / international law',sourceType_other:'Other official source',noSources:'No reliable primary source found.',openQuestions:'Open questions',nextSteps:'Next steps',customerExplanation:'Plain-language customer explanation',reviewRequired:'Research draft: professional review is required before legally binding use.',sourceChecked:'Sources checked',newComparison:'Compare another question',known:'supported',likely:'likely',unclear:'unclear',high:'high',medium:'medium',low:'low',same:'comparable',different:'difference',risk:'urgent risk',privacyRequired:'Please confirm the data type.',questionRequired:'Please enter a specific question of at least 12 characters.'
}

const tr={
  eyebrow:'Kaynağa bağlı dosya incelemesi',title:'Hukuk alanı karşılaştırması',intro:'Bu dosyadaki somut soruyu ana ülke ile hedef ülke arasında karşılaştırır ve pratik sonucu açıklar.',baseline:'Ana ülke ve hedef ülke uygulanacak hukuku otomatik olarak belirlemez. Sözleşme, yer, taraflar ve yetki ayrıca incelenir.',topic:'İstenen hukuk alanı',question:'Müşterinin somut sorusu',questionHelp:'Soru ne kadar netse özet o kadar anlaşılır ve güvenilir olur.',classification:'Bu dosyanın veri türü',synthetic:'Sentetik test verileri',anonymized:'Etkin biçimde anonimleştirilmiş veriler',consent:'Veri türünü onaylıyor ve güncel resmî kaynaklarda tek seferlik yapay zekâ araştırmasına izin veriyorum.',create:'Birincil kaynaklarla karşılaştırma oluştur',creating:'Resmî kaynaklar araştırılıyor ve karşılaştırılıyor …',loadFailed:'Önceki karşılaştırmalar yüklenemedi.',createFailed:'Hukuk alanı karşılaştırması oluşturulamadı.',noResults:'Bu dosya için henüz karşılaştırma yok.',history:'Karşılaştırma sürümü',sameCountry:'Ana ülke ile hedef ülke aynı. Ülkeleri karşılaştırmak için dosyayı düzenleyin.',result:'Açıklamalı karşılaştırma',applicableLaw:'Hangi hukukun uygulanması muhtemel?',missingFactors:'Gerekli ek bilgiler',comparisonPoints:'Konu bazında karşılaştırma',practicalMeaning:'Müşteri için anlamı',confidence:'Kaynak güveni',sources:'Resmî kaynaklar',noSources:'Güvenilir birincil kaynak bulunamadı.',openQuestions:'Açık sorular',nextSteps:'Sonraki adımlar',customerExplanation:'Müşteri için sade açıklama',reviewRequired:'Araştırma taslağıdır; hukuken bağlayıcı kullanımdan önce uzman incelemesi gerekir.',sourceChecked:'Kaynak tarihi',newComparison:'Yeni soru karşılaştır',known:'belgeli',likely:'muhtemel',unclear:'belirsiz',high:'yüksek',medium:'orta',low:'düşük',same:'benzer',different:'fark',risk:'acil risk',privacyRequired:'Lütfen veri türünü onaylayın.',questionRequired:'Lütfen en az 12 karakterlik somut bir soru yazın.'
}

const pl={
  eyebrow:'Analiza sprawy oparta na źródłach',title:'Porównanie porządków prawnych',intro:'Porównuje konkretne pytanie w kraju pochodzenia i kraju docelowym oraz wyjaśnia praktyczne skutki.',baseline:'Kraj pochodzenia i kraj docelowy nie przesądzają automatycznie o prawie właściwym. Osobno sprawdzane są umowa, miejsce, strony i jurysdykcja.',topic:'Wybrana dziedzina prawa',question:'Konkretne pytanie klienta',questionHelp:'Im dokładniejsze pytanie, tym jaśniejsze i bardziej wiarygodne zestawienie.',classification:'Rodzaj danych w sprawie',synthetic:'Syntetyczne dane testowe',anonymized:'Skutecznie zanonimizowane dane',consent:'Potwierdzam rodzaj danych i zezwalam na jednorazowe wyszukanie aktualnych źródeł urzędowych przez AI.',create:'Utwórz porównanie ze źródeł pierwotnych',creating:'Wyszukiwanie i porównywanie źródeł urzędowych …',loadFailed:'Nie udało się wczytać wcześniejszych porównań.',createFailed:'Nie udało się utworzyć porównania.',noResults:'Brak porównania dla tej sprawy.',history:'Wersja porównania',sameCountry:'Kraj pochodzenia i docelowy są takie same. Edytuj sprawę, aby porównać kraje.',result:'Porównanie z objaśnieniami',applicableLaw:'Które prawo prawdopodobnie ma zastosowanie?',missingFactors:'Brakujące informacje',comparisonPoints:'Porównanie punkt po punkcie',practicalMeaning:'Znaczenie dla klienta',confidence:'Pewność źródeł',sources:'Źródła urzędowe',noSources:'Nie znaleziono wiarygodnego źródła pierwotnego.',openQuestions:'Otwarte pytania',nextSteps:'Następne kroki',customerExplanation:'Proste wyjaśnienie dla klienta',reviewRequired:'Projekt badawczy: przed wiążącym użyciem prawnym wymagana jest kontrola specjalisty.',sourceChecked:'Stan źródeł',newComparison:'Porównaj nowe pytanie',known:'potwierdzone',likely:'prawdopodobne',unclear:'niejasne',high:'wysoka',medium:'średnia',low:'niska',same:'porównywalne',different:'różnica',risk:'pilne ryzyko',privacyRequired:'Potwierdź rodzaj danych.',questionRequired:'Wpisz konkretne pytanie o długości co najmniej 12 znaków.'
}

const fr={
  eyebrow:'Examen du dossier fondé sur les sources',title:'Comparaison des espaces juridiques',intro:'Compare la question précise du dossier entre le pays d’origine et le pays cible et explique les effets pratiques.',baseline:'Les pays d’origine et cible ne déterminent pas automatiquement la loi applicable. Le contrat, le lieu, les parties et la compétence sont vérifiés séparément.',topic:'Domaine juridique souhaité',question:'Question précise du client',questionHelp:'Plus la question est précise, plus la synthèse est claire et fiable.',classification:'Type de données du dossier',synthetic:'Données de test synthétiques',anonymized:'Données effectivement anonymisées',consent:'Je confirme le type de données et autorise une recherche IA unique dans les sources officielles actuelles.',create:'Créer la comparaison avec des sources primaires',creating:'Recherche et comparaison des sources officielles …',loadFailed:'Les comparaisons précédentes n’ont pas pu être chargées.',createFailed:'La comparaison juridique n’a pas pu être créée.',noResults:'Aucune comparaison pour ce dossier.',history:'Version de la comparaison',sameCountry:'Le pays d’origine et le pays cible sont identiques. Modifiez le dossier pour comparer des pays.',result:'Comparaison expliquée',applicableLaw:'Quelle loi est probablement applicable ?',missingFactors:'Informations encore nécessaires',comparisonPoints:'Comparaison point par point',practicalMeaning:'Conséquence pour le client',confidence:'Fiabilité des sources',sources:'Sources officielles',noSources:'Aucune source primaire fiable trouvée.',openQuestions:'Questions ouvertes',nextSteps:'Prochaines étapes',customerExplanation:'Explication simple pour le client',reviewRequired:'Projet de recherche : une vérification professionnelle est nécessaire avant tout usage juridiquement contraignant.',sourceChecked:'État des sources',newComparison:'Comparer une nouvelle question',known:'établi',likely:'probable',unclear:'incertain',high:'élevée',medium:'moyenne',low:'faible',same:'comparable',different:'différence',risk:'risque urgent',privacyRequired:'Veuillez confirmer le type de données.',questionRequired:'Veuillez saisir une question précise d’au moins 12 caractères.'
}

const compact={
  ru:{title:'Сравнение правовых систем',intro:'Сравнивает конкретный вопрос дела в стране происхождения и целевой стране и объясняет практическое значение.',topic:'Область права',question:'Конкретный вопрос клиента',create:'Создать сравнение по первичным источникам',creating:'Поиск и сравнение официальных источников …',sameCountry:'Страны совпадают. Измените дело для сравнения.',result:'Сравнение с пояснениями',applicableLaw:'Какое право, вероятно, применяется?',comparisonPoints:'Сравнение по пунктам',practicalMeaning:'Значение для клиента',sources:'Официальные источники',openQuestions:'Открытые вопросы',nextSteps:'Следующие шаги',customerExplanation:'Простое объяснение для клиента',reviewRequired:'Исследовательский проект требует профессиональной проверки до юридически значимого использования.',newComparison:'Сравнить новый вопрос'},
  ar:{title:'مقارنة الأنظمة القانونية',intro:'تقارن السؤال المحدد في القضية بين بلد الأصل والبلد المستهدف وتشرح الأثر العملي.',topic:'المجال القانوني',question:'سؤال العميل المحدد',create:'إنشاء مقارنة من المصادر الأولية',creating:'جارٍ البحث في المصادر الرسمية ومقارنتها …',sameCountry:'بلد الأصل والبلد المستهدف متطابقان. عدّل القضية للمقارنة.',result:'مقارنة تفسيرية',applicableLaw:'ما القانون المرجح تطبيقه؟',comparisonPoints:'المقارنة حسب النقاط',practicalMeaning:'المعنى العملي للعميل',sources:'المصادر الرسمية',openQuestions:'أسئلة مفتوحة',nextSteps:'الخطوات التالية',customerExplanation:'شرح مبسط للعميل',reviewRequired:'مسودة بحث تتطلب مراجعة مهنية قبل أي استخدام ملزم قانوناً.',newComparison:'مقارنة سؤال جديد'},
  fa:{title:'مقایسه حوزه‌های حقوقی',intro:'پرسش مشخص پرونده را میان کشور مبدأ و کشور مقصد مقایسه و اثر عملی را توضیح می‌دهد.',topic:'حوزه حقوقی',question:'پرسش مشخص مشتری',create:'ایجاد مقایسه با منابع اولیه',creating:'در حال جست‌وجو و مقایسه منابع رسمی …',sameCountry:'کشور مبدأ و مقصد یکسان است. برای مقایسه پرونده را ویرایش کنید.',result:'مقایسه توضیحی',applicableLaw:'احتمالاً کدام قانون اعمال می‌شود؟',comparisonPoints:'مقایسه موردی',practicalMeaning:'معنای عملی برای مشتری',sources:'منابع رسمی',openQuestions:'پرسش‌های باز',nextSteps:'گام‌های بعدی',customerExplanation:'توضیح ساده برای مشتری',reviewRequired:'این پیش‌نویس پژوهشی پیش از استفاده الزام‌آور حقوقی به بررسی حرفه‌ای نیاز دارد.',newComparison:'مقایسه پرسش جدید'},
  ro:{title:'Comparație între jurisdicții',intro:'Compară întrebarea concretă a cazului între țara de origine și țara țintă și explică efectul practic.',topic:'Domeniul juridic',question:'Întrebarea concretă a clientului',create:'Creează comparația din surse primare',creating:'Se caută și se compară surse oficiale …',sameCountry:'Țara de origine și țara țintă sunt identice. Editați cazul pentru comparație.',result:'Comparație explicată',applicableLaw:'Ce lege este probabil aplicabilă?',comparisonPoints:'Comparație pe puncte',practicalMeaning:'Semnificația pentru client',sources:'Surse oficiale',openQuestions:'Întrebări deschise',nextSteps:'Pașii următori',customerExplanation:'Explicație simplă pentru client',reviewRequired:'Proiect de cercetare: este necesară verificarea profesională înainte de utilizarea juridică obligatorie.',newComparison:'Compară o întrebare nouă'},
  bg:{title:'Сравнение на правни системи',intro:'Сравнява конкретния въпрос по случая между държавата по произход и целевата държава и обяснява практическото значение.',topic:'Правна област',question:'Конкретен въпрос на клиента',create:'Създай сравнение от първични източници',creating:'Търсене и сравняване на официални източници …',sameCountry:'Държавите съвпадат. Редактирайте случая за сравнение.',result:'Обяснително сравнение',applicableLaw:'Кое право вероятно се прилага?',comparisonPoints:'Сравнение по точки',practicalMeaning:'Значение за клиента',sources:'Официални източници',openQuestions:'Отворени въпроси',nextSteps:'Следващи стъпки',customerExplanation:'Разбираемо обяснение за клиента',reviewRequired:'Изследователски проект: необходима е професионална проверка преди правно обвързваща употреба.',newComparison:'Сравни нов въпрос'},
  vi:{title:'So sánh hệ thống pháp luật',intro:'So sánh câu hỏi cụ thể của vụ việc giữa quốc gia gốc và quốc gia đích, đồng thời giải thích ý nghĩa thực tế.',topic:'Lĩnh vực pháp lý',question:'Câu hỏi cụ thể của khách hàng',create:'Tạo so sánh từ nguồn sơ cấp',creating:'Đang tìm và so sánh nguồn chính thức …',sameCountry:'Quốc gia gốc và đích giống nhau. Hãy sửa vụ việc để so sánh.',result:'So sánh có giải thích',applicableLaw:'Pháp luật nào có khả năng áp dụng?',comparisonPoints:'So sánh theo từng điểm',practicalMeaning:'Ý nghĩa đối với khách hàng',sources:'Nguồn chính thức',openQuestions:'Câu hỏi còn mở',nextSteps:'Bước tiếp theo',customerExplanation:'Giải thích dễ hiểu cho khách hàng',reviewRequired:'Bản dự thảo nghiên cứu cần được chuyên gia kiểm tra trước khi sử dụng có tính ràng buộc pháp lý.',newComparison:'So sánh câu hỏi mới'}
}

const baseByLanguage={de,en,tr,pl,fr,ru:{...en,...compact.ru},ar:{...en,...compact.ar},fa:{...en,...compact.fa},ro:{...en,...compact.ro},bg:{...en,...compact.bg},vi:{...en,...compact.vi}}

const topicLabels={
  de:{applicable_law_jurisdiction:'Anwendbares Recht und Zuständigkeit',contract_consumer:'Vertrag und Verbraucher',employment:'Arbeit',rent_property:'Miete und Immobilie',claims_payments:'Forderung und Zahlung',insurance:'Versicherung',administrative_social:'Behörde und Sozialleistung',travel_residence:'Reise, Einreise und Aufenthalt',data_protection:'Datenschutz',other:'Andere Rechtsfrage'},
  en:{applicable_law_jurisdiction:'Applicable law and jurisdiction',contract_consumer:'Contract and consumer',employment:'Employment',rent_property:'Rent and property',claims_payments:'Claims and payments',insurance:'Insurance',administrative_social:'Authorities and social benefits',travel_residence:'Travel, entry and residence',data_protection:'Data protection',other:'Other legal question'},
  tr:{applicable_law_jurisdiction:'Uygulanacak hukuk ve yetki',contract_consumer:'Sözleşme ve tüketici',employment:'İş hukuku',rent_property:'Kira ve taşınmaz',claims_payments:'Alacak ve ödeme',insurance:'Sigorta',administrative_social:'İdare ve sosyal yardım',travel_residence:'Seyahat, giriş ve ikamet',data_protection:'Veri koruma',other:'Diğer hukuk sorusu'},
  pl:{applicable_law_jurisdiction:'Prawo właściwe i jurysdykcja',contract_consumer:'Umowy i konsumenci',employment:'Prawo pracy',rent_property:'Najem i nieruchomości',claims_payments:'Roszczenia i płatności',insurance:'Ubezpieczenia',administrative_social:'Urzędy i świadczenia społeczne',travel_residence:'Podróż, wjazd i pobyt',data_protection:'Ochrona danych',other:'Inna kwestia prawna'},
  fr:{applicable_law_jurisdiction:'Loi applicable et compétence',contract_consumer:'Contrat et consommation',employment:'Travail',rent_property:'Location et immobilier',claims_payments:'Créances et paiements',insurance:'Assurance',administrative_social:'Administration et prestations sociales',travel_residence:'Voyage, entrée et séjour',data_protection:'Protection des données',other:'Autre question juridique'}
}

export function legalComparisonUi(language='de'){
  return {...en,...(baseByLanguage[language]||de)}
}

export function legalComparisonTopicLabels(language='de'){
  return topicLabels[language]||topicLabels.en
}
