// Customer-facing labels shared by the public explanation and real results.
const copy={
  de:{title:'Länder vergleichen. Unterschiede verstehen.',intro:'Ihre Frage, zwei Länder, Ihre Sprache. ASH vergleicht belegbare rechtliche Regeln für Privatpersonen und Firmen.',here:'Hier gilt …',there:'Dort gilt …',meaning:'Das bedeutet für Sie …',rule:'Die Regel zur konkreten Frage, mit amtlicher Quelle.',difference:'Was gleich ist, was abweicht und welche Angaben noch fehlen.',resultLanguage:'Ergebnis in',unsupported:'Für diese Länderauswahl ist noch kein Quellenmodul eingerichtet. Bitte wählen Sie im Fall ein verfügbares Land.',benefit:'Rechtslagen zwischen Ländern vergleichen'},
  en:{title:'Compare countries. Understand the differences.',intro:'Your question, two countries, your language. ASH compares source-supported legal rules for individuals and businesses.',here:'The rule here …',there:'The rule there …',meaning:'What this means for you …',rule:'The rule for your specific question, with an official source.',difference:'What is similar, what differs and which facts are still missing.',resultLanguage:'Result in',unsupported:'A source module is not yet configured for these countries. Please choose an available country in the case.',benefit:'Compare legal rules between countries'},
  fr:{title:'Comparer les pays. Comprendre les différences.',intro:'Votre question, deux pays, votre langue. ASH compare des règles juridiques étayées par des sources pour les particuliers et les entreprises.',here:'Ici, la règle est …',there:'Là-bas, la règle est …',meaning:'Ce que cela signifie pour vous …',rule:'La règle pour votre question précise, avec une source officielle.',difference:'Les similitudes, les différences et les faits encore manquants.',resultLanguage:'Résultat en',unsupported:'Aucun module de sources n’est encore configuré pour ces pays. Choisissez un pays disponible dans le dossier.',benefit:'Comparer les règles juridiques entre pays'},
  tr:{title:'Ülkeleri karşılaştırın. Farkları anlayın.',intro:'Sorunuz, iki ülke, sizin diliniz. ASH bireyler ve şirketler için kaynaklarla desteklenen hukuk kurallarını karşılaştırır.',here:'Burada geçerli olan …',there:'Orada geçerli olan …',meaning:'Sizin için anlamı …',rule:'Somut sorunuza ilişkin kural ve resmî kaynak.',difference:'Benzerlikler, farklılıklar ve hâlâ eksik olan bilgiler.',resultLanguage:'Sonuç dili',unsupported:'Bu ülkeler için henüz bir kaynak modülü yapılandırılmadı. Vakada mevcut bir ülke seçin.',benefit:'Ülkeler arasındaki hukuk kurallarını karşılaştırın'},
  pl:{title:'Porównaj kraje. Zrozum różnice.',intro:'Twoje pytanie, dwa kraje, Twój język. ASH porównuje zasady prawne poparte źródłami dla osób prywatnych i firm.',here:'Tutaj obowiązuje …',there:'Tam obowiązuje …',meaning:'Co to oznacza dla Ciebie …',rule:'Zasada dotycząca konkretnego pytania, z urzędowym źródłem.',difference:'Podobieństwa, różnice i informacje, których nadal brakuje.',resultLanguage:'Wynik w języku',unsupported:'Dla tych krajów nie skonfigurowano jeszcze modułu źródeł. Wybierz w sprawie dostępny kraj.',benefit:'Porównaj zasady prawne między krajami'},
  ru:{title:'Сравните страны. Поймите различия.',intro:'Ваш вопрос, две страны, ваш язык. ASH сравнивает правовые нормы, подтверждённые источниками, для частных лиц и компаний.',here:'Здесь действует …',there:'Там действует …',meaning:'Что это значит для вас …',rule:'Норма по конкретному вопросу с официальным источником.',difference:'Сходства, различия и недостающие сведения.',resultLanguage:'Язык результата',unsupported:'Для этих стран модуль источников ещё не настроен. Выберите доступную страну в деле.',benefit:'Сравните правовые нормы разных стран'},
  ar:{title:'قارن البلدان وافهم الاختلافات.',intro:'سؤالك وبلدان ولغتك. يقارن ASH القواعد القانونية المدعومة بمصادر للأفراد والشركات.',here:'القاعدة هنا …',there:'القاعدة هناك …',meaning:'ماذا يعني ذلك لك …',rule:'القاعدة المتعلقة بسؤالك المحدد مع مصدر رسمي.',difference:'أوجه التشابه والاختلاف والمعلومات التي لا تزال ناقصة.',resultLanguage:'لغة النتيجة',unsupported:'لم تُعدّ وحدة مصادر لهذه البلدان بعد. يرجى اختيار بلد متاح في القضية.',benefit:'قارن القواعد القانونية بين البلدان'},
  fa:{title:'کشورها را مقایسه کنید. تفاوت‌ها را بفهمید.',intro:'پرسش شما، دو کشور و زبان شما. ASH قواعد حقوقی مستند به منابع را برای اشخاص و شرکت‌ها مقایسه می‌کند.',here:'قاعده در اینجا …',there:'قاعده در آنجا …',meaning:'معنای آن برای شما …',rule:'قاعده مربوط به پرسش مشخص شما، همراه با منبع رسمی.',difference:'شباهت‌ها، تفاوت‌ها و اطلاعاتی که هنوز کم است.',resultLanguage:'زبان نتیجه',unsupported:'برای این کشورها هنوز ماژول منابع تنظیم نشده است. لطفاً در پرونده کشوری از گزینه‌های موجود انتخاب کنید.',benefit:'قواعد حقوقی کشورها را مقایسه کنید'},
  ro:{title:'Comparați țările. Înțelegeți diferențele.',intro:'Întrebarea dumneavoastră, două țări, limba aleasă. ASH compară reguli juridice susținute de surse pentru persoane și firme.',here:'Aici se aplică …',there:'Acolo se aplică …',meaning:'Ce înseamnă pentru dumneavoastră …',rule:'Regula pentru întrebarea concretă, cu o sursă oficială.',difference:'Asemănările, diferențele și informațiile care încă lipsesc.',resultLanguage:'Limba rezultatului',unsupported:'Nu există încă un modul de surse configurat pentru aceste țări. Alegeți în dosar o țară disponibilă.',benefit:'Comparați regulile juridice între țări'},
  bg:{title:'Сравнете държавите. Разберете разликите.',intro:'Вашият въпрос, две държави, Вашият език. ASH сравнява правни правила, подкрепени с източници, за хора и фирми.',here:'Тук важи …',there:'Там важи …',meaning:'Какво означава това за Вас …',rule:'Правилото по конкретния въпрос с официален източник.',difference:'Приликите, разликите и все още липсващите данни.',resultLanguage:'Език на резултата',unsupported:'За тези държави все още няма настроен модул с източници. Изберете налична държава в случая.',benefit:'Сравнете правните правила между държави'},
  vi:{title:'So sánh các quốc gia. Hiểu sự khác biệt.',intro:'Câu hỏi của bạn, hai quốc gia, ngôn ngữ của bạn. ASH so sánh quy định pháp luật có nguồn chứng minh cho cá nhân và doanh nghiệp.',here:'Quy định ở đây …',there:'Quy định ở đó …',meaning:'Điều này có ý nghĩa gì với bạn …',rule:'Quy định cho câu hỏi cụ thể của bạn, kèm nguồn chính thức.',difference:'Điểm giống, điểm khác và dữ kiện còn thiếu.',resultLanguage:'Ngôn ngữ kết quả',unsupported:'Chưa thiết lập mô-đun nguồn cho các quốc gia này. Vui lòng chọn quốc gia hiện có trong hồ sơ.',benefit:'So sánh quy định pháp luật giữa các quốc gia'}
}

export function legalComparisonPresentation(language='de'){return copy[language]||copy.de}
