const AUTH_MESSAGES=Object.freeze({
  de:{invalidCredentials:'E-Mail-Adresse oder Passwort ist nicht korrekt. Falls das Konto bereits besteht, nutzen Sie bitte „Passwort zurücksetzen“.',emailNotConfirmed:'Ihre E-Mail-Adresse wurde noch nicht bestätigt. Bitte öffnen Sie zuerst den Bestätigungslink in Ihrer E-Mail.',tooManyRequests:"Der Anmeldedienst begrenzt vorübergehend weitere Anfragen. Eine genaue Wartezeit wurde nicht übermittelt. Bitte versuchen Sie es später erneut.",emailRateLimited:"E-Mail-Versandlimit erreicht. Der Anmeldedienst versendet derzeit keine weitere Nachricht. Die genaue Freigabezeit wurde nicht übermittelt. Prüfen Sie die zuletzt erhaltene Rücksetz-E-Mail oder versuchen Sie es später einmal erneut.",resetDeliveryFailed:'Die Rücksetz-E-Mail konnte nicht versendet werden. Bitte laden Sie die App neu und versuchen Sie es noch einmal.',generic:'Die Anmeldung konnte nicht abgeschlossen werden. Bitte versuchen Sie es erneut oder setzen Sie Ihr Passwort zurück.'},
  en:{invalidCredentials:'The email address or password is incorrect. If the account already exists, please use “Reset password”.',emailNotConfirmed:'Your email address has not been confirmed yet. Please open the confirmation link in your email first.',tooManyRequests:"The sign-in service is temporarily limiting further requests. It has not provided an exact waiting time. Please try again later.",emailRateLimited:"Email sending limit reached. The sign-in service cannot send another message right now. It has not provided an exact reset time. Check your latest password-reset email or try again later.",resetDeliveryFailed:'The reset email could not be sent. Please reload the app and try again.',generic:'Authentication could not be completed. Please try again or reset your password.'},
  fr:{invalidCredentials:'L’adresse e-mail ou le mot de passe est incorrect. Si le compte existe déjà, utilisez « Réinitialiser le mot de passe ».',emailNotConfirmed:'Votre adresse e-mail n’a pas encore été confirmée. Ouvrez d’abord le lien de confirmation reçu par e-mail.',tooManyRequests:"Le service de connexion limite temporairement les nouvelles demandes. Aucun délai précis n’a été fourni. Réessayez plus tard.",emailRateLimited:"La limite d’envoi d’e-mails est atteinte. Le service de connexion ne peut pas envoyer de nouveau message pour le moment. Aucune heure précise de reprise n’a été fournie. Consultez le dernier e-mail de réinitialisation reçu ou réessayez plus tard.",resetDeliveryFailed:'L’e-mail de réinitialisation n’a pas pu être envoyé. Rechargez l’application et réessayez.',generic:'L’authentification n’a pas pu être terminée. Réessayez ou réinitialisez votre mot de passe.'},
  tr:{invalidCredentials:'E-posta adresi veya parola yanlış. Hesap zaten varsa lütfen “Parolayı sıfırla” seçeneğini kullanın.',emailNotConfirmed:'E-posta adresiniz henüz doğrulanmadı. Önce e-postanızdaki doğrulama bağlantısını açın.',tooManyRequests:"Giriş hizmeti yeni istekleri geçici olarak sınırlıyor. Kesin bir bekleme süresi bildirilmedi. Lütfen daha sonra tekrar deneyin.",emailRateLimited:"E-posta gönderme sınırına ulaşıldı. Giriş hizmeti şu anda başka bir ileti gönderemiyor. Yeniden gönderimin açılacağı kesin zaman bildirilmedi. Son parola sıfırlama e-postanızı kontrol edin veya daha sonra tekrar deneyin.",resetDeliveryFailed:'Sıfırlama e-postası gönderilemedi. Lütfen uygulamayı yeniden yükleyip tekrar deneyin.',generic:'Kimlik doğrulama tamamlanamadı. Lütfen tekrar deneyin veya parolanızı sıfırlayın.'},
  pl:{invalidCredentials:'Adres e-mail lub hasło są nieprawidłowe. Jeśli konto już istnieje, użyj opcji „Zresetuj hasło”.',emailNotConfirmed:'Adres e-mail nie został jeszcze potwierdzony. Najpierw otwórz link potwierdzający w wiadomości e-mail.',tooManyRequests:"Usługa logowania tymczasowo ogranicza kolejne żądania. Nie podano dokładnego czasu oczekiwania. Spróbuj ponownie później.",emailRateLimited:"Osiągnięto limit wysyłania e-maili. Usługa logowania nie może teraz wysłać kolejnej wiadomości. Nie podano dokładnego czasu odblokowania. Sprawdź ostatni e-mail do resetowania hasła lub spróbuj ponownie później.",resetDeliveryFailed:'Nie udało się wysłać wiadomości do resetowania hasła. Odśwież aplikację i spróbuj ponownie.',generic:'Nie udało się zakończyć uwierzytelniania. Spróbuj ponownie lub zresetuj hasło.'},
  ru:{invalidCredentials:'Адрес электронной почты или пароль неверны. Если учётная запись уже существует, воспользуйтесь функцией «Сбросить пароль».',emailNotConfirmed:'Адрес электронной почты ещё не подтверждён. Сначала откройте ссылку подтверждения в письме.',tooManyRequests:"Сервис входа временно ограничивает новые запросы. Точное время ожидания не сообщено. Повторите попытку позже.",emailRateLimited:"Достигнут лимит отправки писем. Сервис входа пока не может отправить новое письмо. Точное время снятия ограничения не сообщено. Проверьте последнее письмо для сброса пароля или повторите попытку позже.",resetDeliveryFailed:'Не удалось отправить письмо для сброса пароля. Перезагрузите приложение и повторите попытку.',generic:'Не удалось завершить вход. Повторите попытку или сбросьте пароль.'},
  ar:{invalidCredentials:'عنوان البريد الإلكتروني أو كلمة المرور غير صحيحة. إذا كان الحساب موجودًا بالفعل، فاستخدم «إعادة تعيين كلمة المرور».',emailNotConfirmed:'لم يتم تأكيد عنوان بريدك الإلكتروني بعد. افتح رابط التأكيد في بريدك أولًا.',tooManyRequests:"تحدّ خدمة تسجيل الدخول مؤقتًا من الطلبات الإضافية. لم يُحدَّد وقت انتظار دقيق. يرجى المحاولة لاحقًا.",emailRateLimited:"تم بلوغ حد إرسال رسائل البريد الإلكتروني. لا يمكن لخدمة تسجيل الدخول إرسال رسالة أخرى حاليًا. لم يُحدَّد وقت دقيق لاستئناف الإرسال. راجع أحدث رسالة لإعادة تعيين كلمة المرور أو حاول لاحقًا.",resetDeliveryFailed:'تعذر إرسال رسالة إعادة تعيين كلمة المرور. أعد تحميل التطبيق وحاول مرة أخرى.',generic:'تعذر إكمال المصادقة. حاول مرة أخرى أو أعد تعيين كلمة المرور.'},
  fa:{invalidCredentials:'نشانی ایمیل یا گذرواژه نادرست است. اگر حساب از قبل وجود دارد، از «بازنشانی گذرواژه» استفاده کنید.',emailNotConfirmed:'نشانی ایمیل شما هنوز تأیید نشده است. ابتدا پیوند تأیید موجود در ایمیل را باز کنید.',tooManyRequests:"سرویس ورود موقتاً درخواست‌های بیشتر را محدود کرده است. زمان انتظار دقیق اعلام نشده است. لطفاً بعداً دوباره تلاش کنید.",emailRateLimited:"محدودیت ارسال ایمیل پر شده است. سرویس ورود اکنون نمی‌تواند پیام دیگری بفرستد. زمان دقیق رفع محدودیت اعلام نشده است. آخرین ایمیل بازنشانی گذرواژه را بررسی کنید یا بعداً دوباره تلاش کنید.",resetDeliveryFailed:'ایمیل بازنشانی گذرواژه ارسال نشد. برنامه را دوباره بارگذاری کنید و مجدداً تلاش کنید.',generic:'احراز هویت کامل نشد. دوباره تلاش کنید یا گذرواژه خود را بازنشانی کنید.'},
  ro:{invalidCredentials:'Adresa de e-mail sau parola este incorectă. Dacă există deja contul, folosiți „Resetare parolă”.',emailNotConfirmed:'Adresa de e-mail nu a fost încă confirmată. Deschideți mai întâi linkul de confirmare din e-mail.',tooManyRequests:"Serviciul de autentificare limitează temporar cererile noi. Nu a fost comunicat un timp exact de așteptare. Încercați din nou mai târziu.",emailRateLimited:"S-a atins limita de trimitere a e-mailurilor. Serviciul de autentificare nu poate trimite acum un alt mesaj. Nu a fost comunicată ora exactă a deblocării. Verificați ultimul e-mail de resetare a parolei sau încercați din nou mai târziu.",resetDeliveryFailed:'E-mailul de resetare nu a putut fi trimis. Reîncărcați aplicația și încercați din nou.',generic:'Autentificarea nu a putut fi finalizată. Încercați din nou sau resetați parola.'},
  bg:{invalidCredentials:'Имейл адресът или паролата са неправилни. Ако акаунтът вече съществува, използвайте „Нулиране на паролата“.',emailNotConfirmed:'Имейл адресът ви още не е потвърден. Първо отворете връзката за потвърждение в имейла.',tooManyRequests:"Услугата за вход временно ограничава новите заявки. Не е посочено точно време за изчакване. Опитайте отново по-късно.",emailRateLimited:"Достигнат е лимитът за изпращане на имейли. Услугата за вход не може да изпрати ново съобщение в момента. Не е посочено точно време за възобновяване. Проверете последния имейл за нулиране на паролата или опитайте отново по-късно.",resetDeliveryFailed:'Имейлът за нулиране не можа да бъде изпратен. Презаредете приложението и опитайте отново.',generic:'Удостоверяването не можа да завърши. Опитайте отново или нулирайте паролата.'},
  vi:{invalidCredentials:'Địa chỉ email hoặc mật khẩu không đúng. Nếu tài khoản đã tồn tại, hãy dùng “Đặt lại mật khẩu”.',emailNotConfirmed:'Địa chỉ email của bạn chưa được xác nhận. Trước tiên, hãy mở liên kết xác nhận trong email.',tooManyRequests:"Dịch vụ đăng nhập đang tạm thời giới hạn các yêu cầu mới. Chưa có thời gian chờ chính xác. Vui lòng thử lại sau.",emailRateLimited:"Đã đạt giới hạn gửi email. Dịch vụ đăng nhập hiện chưa thể gửi thêm thư. Chưa có thời điểm chính xác để gửi lại. Hãy kiểm tra email đặt lại mật khẩu mới nhất hoặc thử lại sau.",resetDeliveryFailed:'Không thể gửi email đặt lại mật khẩu. Vui lòng tải lại ứng dụng và thử lại.',generic:'Không thể hoàn tất xác thực. Vui lòng thử lại hoặc đặt lại mật khẩu.'}
})

export function getAuthErrorMessage(error,language='de'){
  const messages=AUTH_MESSAGES[language]||AUTH_MESSAGES.de
  if(error?.code==='invalid_credentials')return messages.invalidCredentials
  if(error?.code==='email_not_confirmed')return messages.emailNotConfirmed
  if(error?.code==='over_email_send_rate_limit')return messages.emailRateLimited
  if(['over_request_rate_limit','too_many_requests'].includes(error?.code))return messages.tooManyRequests
  if(error?.code==='reset_delivery_failed')return messages.resetDeliveryFailed
  return messages.generic
}
