const AUTH_MESSAGES=Object.freeze({
  de:{invalidCredentials:'E-Mail-Adresse oder Passwort ist nicht korrekt. Falls das Konto bereits besteht, nutzen Sie bitte „Passwort zurücksetzen“.',emailNotConfirmed:'Ihre E-Mail-Adresse wurde noch nicht bestätigt. Bitte öffnen Sie zuerst den Bestätigungslink in Ihrer E-Mail.',tooManyRequests:'Zu viele Versuche in kurzer Zeit. Bitte warten Sie einen Moment und versuchen Sie es erneut.',resetDeliveryFailed:'Die Rücksetz-E-Mail konnte nicht versendet werden. Bitte laden Sie die App neu und versuchen Sie es noch einmal.',generic:'Die Anmeldung konnte nicht abgeschlossen werden. Bitte versuchen Sie es erneut oder setzen Sie Ihr Passwort zurück.'},
  en:{invalidCredentials:'The email address or password is incorrect. If the account already exists, please use “Reset password”.',emailNotConfirmed:'Your email address has not been confirmed yet. Please open the confirmation link in your email first.',tooManyRequests:'Too many attempts in a short time. Please wait a moment and try again.',resetDeliveryFailed:'The reset email could not be sent. Please reload the app and try again.',generic:'Authentication could not be completed. Please try again or reset your password.'},
  fr:{invalidCredentials:'L’adresse e-mail ou le mot de passe est incorrect. Si le compte existe déjà, utilisez « Réinitialiser le mot de passe ».',emailNotConfirmed:'Votre adresse e-mail n’a pas encore été confirmée. Ouvrez d’abord le lien de confirmation reçu par e-mail.',tooManyRequests:'Trop de tentatives en peu de temps. Attendez un instant puis réessayez.',resetDeliveryFailed:'L’e-mail de réinitialisation n’a pas pu être envoyé. Rechargez l’application et réessayez.',generic:'L’authentification n’a pas pu être terminée. Réessayez ou réinitialisez votre mot de passe.'},
  tr:{invalidCredentials:'E-posta adresi veya parola yanlış. Hesap zaten varsa lütfen “Parolayı sıfırla” seçeneğini kullanın.',emailNotConfirmed:'E-posta adresiniz henüz doğrulanmadı. Önce e-postanızdaki doğrulama bağlantısını açın.',tooManyRequests:'Kısa sürede çok fazla deneme yapıldı. Lütfen biraz bekleyip tekrar deneyin.',resetDeliveryFailed:'Sıfırlama e-postası gönderilemedi. Lütfen uygulamayı yeniden yükleyip tekrar deneyin.',generic:'Kimlik doğrulama tamamlanamadı. Lütfen tekrar deneyin veya parolanızı sıfırlayın.'},
  pl:{invalidCredentials:'Adres e-mail lub hasło są nieprawidłowe. Jeśli konto już istnieje, użyj opcji „Zresetuj hasło”.',emailNotConfirmed:'Adres e-mail nie został jeszcze potwierdzony. Najpierw otwórz link potwierdzający w wiadomości e-mail.',tooManyRequests:'Zbyt wiele prób w krótkim czasie. Odczekaj chwilę i spróbuj ponownie.',resetDeliveryFailed:'Nie udało się wysłać wiadomości do resetowania hasła. Odśwież aplikację i spróbuj ponownie.',generic:'Nie udało się zakończyć uwierzytelniania. Spróbuj ponownie lub zresetuj hasło.'},
  ru:{invalidCredentials:'Адрес электронной почты или пароль неверны. Если учётная запись уже существует, воспользуйтесь функцией «Сбросить пароль».',emailNotConfirmed:'Адрес электронной почты ещё не подтверждён. Сначала откройте ссылку подтверждения в письме.',tooManyRequests:'Слишком много попыток за короткое время. Подождите немного и повторите попытку.',resetDeliveryFailed:'Не удалось отправить письмо для сброса пароля. Перезагрузите приложение и повторите попытку.',generic:'Не удалось завершить вход. Повторите попытку или сбросьте пароль.'},
  ar:{invalidCredentials:'عنوان البريد الإلكتروني أو كلمة المرور غير صحيحة. إذا كان الحساب موجودًا بالفعل، فاستخدم «إعادة تعيين كلمة المرور».',emailNotConfirmed:'لم يتم تأكيد عنوان بريدك الإلكتروني بعد. افتح رابط التأكيد في بريدك أولًا.',tooManyRequests:'عدد كبير جدًا من المحاولات خلال وقت قصير. انتظر قليلًا ثم حاول مرة أخرى.',resetDeliveryFailed:'تعذر إرسال رسالة إعادة تعيين كلمة المرور. أعد تحميل التطبيق وحاول مرة أخرى.',generic:'تعذر إكمال المصادقة. حاول مرة أخرى أو أعد تعيين كلمة المرور.'},
  fa:{invalidCredentials:'نشانی ایمیل یا گذرواژه نادرست است. اگر حساب از قبل وجود دارد، از «بازنشانی گذرواژه» استفاده کنید.',emailNotConfirmed:'نشانی ایمیل شما هنوز تأیید نشده است. ابتدا پیوند تأیید موجود در ایمیل را باز کنید.',tooManyRequests:'در مدت کوتاهی تلاش‌های زیادی انجام شده است. کمی صبر کنید و دوباره امتحان کنید.',resetDeliveryFailed:'ایمیل بازنشانی گذرواژه ارسال نشد. برنامه را دوباره بارگذاری کنید و مجدداً تلاش کنید.',generic:'احراز هویت کامل نشد. دوباره تلاش کنید یا گذرواژه خود را بازنشانی کنید.'},
  ro:{invalidCredentials:'Adresa de e-mail sau parola este incorectă. Dacă există deja contul, folosiți „Resetare parolă”.',emailNotConfirmed:'Adresa de e-mail nu a fost încă confirmată. Deschideți mai întâi linkul de confirmare din e-mail.',tooManyRequests:'Prea multe încercări într-un timp scurt. Așteptați puțin și încercați din nou.',resetDeliveryFailed:'E-mailul de resetare nu a putut fi trimis. Reîncărcați aplicația și încercați din nou.',generic:'Autentificarea nu a putut fi finalizată. Încercați din nou sau resetați parola.'},
  bg:{invalidCredentials:'Имейл адресът или паролата са неправилни. Ако акаунтът вече съществува, използвайте „Нулиране на паролата“.',emailNotConfirmed:'Имейл адресът ви още не е потвърден. Първо отворете връзката за потвърждение в имейла.',tooManyRequests:'Твърде много опити за кратко време. Изчакайте малко и опитайте отново.',resetDeliveryFailed:'Имейлът за нулиране не можа да бъде изпратен. Презаредете приложението и опитайте отново.',generic:'Удостоверяването не можа да завърши. Опитайте отново или нулирайте паролата.'},
  vi:{invalidCredentials:'Địa chỉ email hoặc mật khẩu không đúng. Nếu tài khoản đã tồn tại, hãy dùng “Đặt lại mật khẩu”.',emailNotConfirmed:'Địa chỉ email của bạn chưa được xác nhận. Trước tiên, hãy mở liên kết xác nhận trong email.',tooManyRequests:'Có quá nhiều lần thử trong thời gian ngắn. Vui lòng chờ một lát rồi thử lại.',resetDeliveryFailed:'Không thể gửi email đặt lại mật khẩu. Vui lòng tải lại ứng dụng và thử lại.',generic:'Không thể hoàn tất xác thực. Vui lòng thử lại hoặc đặt lại mật khẩu.'}
})

export function getAuthErrorMessage(error,language='de'){
  const messages=AUTH_MESSAGES[language]||AUTH_MESSAGES.de
  if(error?.code==='invalid_credentials')return messages.invalidCredentials
  if(error?.code==='email_not_confirmed')return messages.emailNotConfirmed
  if(['over_request_rate_limit','over_email_send_rate_limit','too_many_requests'].includes(error?.code))return messages.tooManyRequests
  if(error?.code==='reset_delivery_failed')return messages.resetDeliveryFailed
  return messages.generic
}
