import { ProductBrand } from '../brand/ProductBrand'
import { LanguageSwitcher } from '../language/LanguageSwitcher'
import { LegalFooter } from '../compliance/LegalFooter'
import { RegistrationLegalFields } from '../compliance/PrivacyControls'
import { PasswordPolicyChecklist } from './PasswordPolicy'
import { PasswordField } from './PasswordField'

export function AuthSurface({screen,t,a,language,setLanguage,tt,displayName,setDisplayName,email,setEmail,password,setPassword,password2,setPassword2,showPassword,setShowPassword,showPassword2,setShowPassword2,pui,recoveryCopy,v28,acceptedLegal,setAcceptedLegal,confirmedTestData,setConfirmedTestData,registerReady,recoveryReady,register,signIn,resetPassword,completePasswordRecovery,message,lt,setScreen}){
  const resetSensitiveFields=()=>{setShowPassword(false);setShowPassword2(false);setPassword('');setPassword2('');setAcceptedLegal(false);setConfirmedTestData(false)}
  const authForm=screen==='register'?<form onSubmit={register}><label>{a.name}<input value={displayName} onChange={e=>setDisplayName(e.target.value)} autoComplete="name" required/></label><label>{a.email}<input type="email" value={email} onChange={e=>setEmail(e.target.value)} autoComplete="email" required/></label><PasswordField id="register-password" label={a.password} value={password} onChange={e=>setPassword(e.target.value)} visible={showPassword} onToggle={()=>setShowPassword(v=>!v)} labels={pui} autoComplete="new-password" describedBy="v29-password-policy"/><PasswordField id="register-password-repeat" label={a.passwordAgain} value={password2} onChange={e=>setPassword2(e.target.value)} visible={showPassword2} onToggle={()=>setShowPassword2(v=>!v)} labels={pui} autoComplete="new-password" describedBy="v29-password-policy"/><PasswordPolicyChecklist language={language} password={password} passwordRepeat={password2} email={email} displayName={displayName}/><RegistrationLegalFields copy={v28} accepted={acceptedLegal} onAccepted={setAcceptedLegal} testOnly={confirmedTestData} onTestOnly={setConfirmedTestData}/><button className="primary full" disabled={!registerReady}>{a.registerFree}</button></form>:screen==='recovery'?<form onSubmit={completePasswordRecovery}><p className="muted">{recoveryCopy.lead}</p><PasswordField id="recovery-password" label={a.password} value={password} onChange={e=>setPassword(e.target.value)} visible={showPassword} onToggle={()=>setShowPassword(v=>!v)} labels={pui} autoComplete="new-password" describedBy="v29-password-policy"/><PasswordField id="recovery-password-repeat" label={a.passwordAgain} value={password2} onChange={e=>setPassword2(e.target.value)} visible={showPassword2} onToggle={()=>setShowPassword2(v=>!v)} labels={pui} autoComplete="new-password" describedBy="v29-password-policy"/><PasswordPolicyChecklist language={language} password={password} passwordRepeat={password2} email={email} displayName={displayName}/><button className="primary full" disabled={!recoveryReady}>{recoveryCopy.submit}</button></form>:<form onSubmit={signIn}><label>{a.email}<input type="email" value={email} onChange={e=>setEmail(e.target.value)} autoComplete="username" required/></label><PasswordField id="login-password" label={a.password} value={password} onChange={e=>setPassword(e.target.value)} visible={showPassword} onToggle={()=>setShowPassword(v=>!v)} labels={pui} autoComplete="current-password"/><button className="primary full">{t.login}</button><button type="button" className="linkBtn full" onClick={resetPassword}>{lt.passwordReset}</button><small className="authHelp">{lt.passwordResetHelp}</small></form>
  return <><main className="center"><section className="card authCard"><ProductBrand showDescriptor language={language}/><div className="languageSwitch"><span>{t.language}</span><LanguageSwitcher value={language} onChange={setLanguage} label={t.language}/></div><p className="muted">{screen==='register'?a.registerTitle:screen==='recovery'?recoveryCopy.title:a.protected}</p>{screen==='register'&&<div className="registerTransparency"><b>{tt.registerTitle}</b><p>{tt.registerNote}</p><span>✓ {a.noSubscription}</span></div>}{authForm}{message&&<div className="note" role="status">{message}</div>}<button className="linkBtn full" onClick={()=>{resetSensitiveFields();setScreen(screen==='recovery'?'login':screen==='register'?'login':'register')}}>{screen==='recovery'?recoveryCopy.back:screen==='register'?a.already:a.newHere}</button><button className="backBtn full authBackBtn" onClick={()=>{resetSensitiveFields();setScreen('public')}}>{a.backExplanation}</button></section></main><LegalFooter language={language}/></>
}
