const copy={
  de:{title:'Arbeitsbereich laden',connecting:'Ihr Arbeitsbereich wird geladen. Bitte einen Moment warten.',unavailable:'Der Arbeitsbereich konnte nicht geladen werden. Bitte versuchen Sie es erneut. Ein neues Konto ist dafür nicht erforderlich.',retry:'Erneut verbinden',deniedTitle:'Arbeitsbereich nicht freigegeben',denied:'Sie sind angemeldet. Für dieses Konto ist der Arbeitsbereich derzeit nicht freigegeben. Sie können die Freigabe erneut prüfen oder sich abmelden.',deniedRetry:'Freigabe erneut prüfen',signOut:'Abmelden'},
  en:{title:'Load workspace',connecting:'Your workspace is loading. Please wait a moment.',unavailable:'The workspace could not be loaded. Please try again. You do not need to create a new account.',retry:'Reconnect',deniedTitle:'Workspace access unavailable',denied:'You are signed in. This account currently has no approved workspace access. You can check access again or sign out.',deniedRetry:'Check access again',signOut:'Sign out'},
  fr:{title:'Charger l’espace de travail',connecting:'Votre espace de travail se charge. Veuillez patienter.',unavailable:'L’espace de travail n’a pas pu être chargé. Veuillez réessayer. Il n’est pas nécessaire de créer un nouveau compte.',retry:'Reconnecter',deniedTitle:'Accès à l’espace non autorisé',denied:'Vous êtes connecté. Ce compte n’a actuellement pas accès à l’espace de travail. Vous pouvez vérifier l’accès ou vous déconnecter.',deniedRetry:'Vérifier l’accès',signOut:'Se déconnecter'},
  tr:{title:'Çalışma alanını yükle',connecting:'Çalışma alanınız yükleniyor. Lütfen biraz bekleyin.',unavailable:'Çalışma alanı yüklenemedi. Lütfen tekrar deneyin. Yeni bir hesap oluşturmanız gerekmez.',retry:'Yeniden bağlan',deniedTitle:'Çalışma alanı erişimi onaylanmadı',denied:'Oturumunuz açık. Bu hesabın çalışma alanı erişimi şu anda onaylı değil. Erişimi yeniden kontrol edebilir veya çıkış yapabilirsiniz.',deniedRetry:'Erişimi yeniden kontrol et',signOut:'Çıkış yap'},
  pl:{title:'Wczytywanie obszaru roboczego',connecting:'Obszar roboczy się ładuje. Proszę chwilę poczekać.',unavailable:'Nie udało się wczytać obszaru roboczego. Spróbuj ponownie. Nie musisz tworzyć nowego konta.',retry:'Połącz ponownie',deniedTitle:'Brak zatwierdzonego dostępu',denied:'Jesteś zalogowany. To konto nie ma obecnie zatwierdzonego dostępu do obszaru roboczego. Możesz sprawdzić dostęp ponownie lub się wylogować.',deniedRetry:'Sprawdź dostęp ponownie',signOut:'Wyloguj się'},
  ru:{title:'Загрузка рабочей области',connecting:'Рабочая область загружается. Пожалуйста, подождите.',unavailable:'Не удалось загрузить рабочую область. Попробуйте ещё раз. Создавать новую учётную запись не нужно.',retry:'Подключиться снова',deniedTitle:'Доступ к рабочей области не разрешён',denied:'Вы вошли в систему. Для этой учётной записи доступ к рабочей области сейчас не разрешён. Можно проверить доступ снова или выйти.',deniedRetry:'Проверить доступ снова',signOut:'Выйти'},
  ar:{title:'تحميل مساحة العمل',connecting:'جارٍ تحميل مساحة العمل. يرجى الانتظار قليلاً.',unavailable:'تعذّر تحميل مساحة العمل. يرجى المحاولة مجدداً. لا تحتاج إلى إنشاء حساب جديد.',retry:'إعادة الاتصال',deniedTitle:'الوصول إلى مساحة العمل غير معتمد',denied:'أنت مسجّل الدخول. الوصول إلى مساحة العمل غير معتمد حالياً لهذا الحساب. يمكنك التحقق من الوصول مجدداً أو تسجيل الخروج.',deniedRetry:'التحقق من الوصول مجدداً',signOut:'تسجيل الخروج'},
  fa:{title:'بارگذاری فضای کار',connecting:'فضای کار در حال بارگذاری است. لطفاً کمی صبر کنید.',unavailable:'فضای کار بارگذاری نشد. لطفاً دوباره تلاش کنید. نیازی به ساخت حساب جدید نیست.',retry:'اتصال دوباره',deniedTitle:'دسترسی به فضای کار تأیید نشده است',denied:'شما وارد شده‌اید. دسترسی این حساب به فضای کار اکنون تأیید نشده است. می‌توانید دسترسی را دوباره بررسی کنید یا خارج شوید.',deniedRetry:'بررسی دوباره دسترسی',signOut:'خروج'},
  ro:{title:'Încarcă spațiul de lucru',connecting:'Spațiul de lucru se încarcă. Vă rugăm să așteptați.',unavailable:'Spațiul de lucru nu a putut fi încărcat. Încercați din nou. Nu este necesar un cont nou.',retry:'Reconectare',deniedTitle:'Accesul la spațiul de lucru nu este aprobat',denied:'Sunteți autentificat. Acest cont nu are momentan acces aprobat la spațiul de lucru. Puteți verifica din nou accesul sau vă puteți deconecta.',deniedRetry:'Verifică din nou accesul',signOut:'Deconectare'},
  bg:{title:'Зареждане на работното пространство',connecting:'Работното пространство се зарежда. Моля, изчакайте.',unavailable:'Работното пространство не можа да бъде заредено. Опитайте отново. Не е необходим нов профил.',retry:'Свържи отново',deniedTitle:'Достъпът до работното пространство не е одобрен',denied:'Влезли сте в профила си. Този профил в момента няма одобрен достъп до работното пространство. Можете да проверите достъпа отново или да излезете.',deniedRetry:'Провери достъпа отново',signOut:'Изход'},
  vi:{title:'Tải không gian làm việc',connecting:'Không gian làm việc đang tải. Vui lòng chờ một lát.',unavailable:'Không thể tải không gian làm việc. Vui lòng thử lại. Bạn không cần tạo tài khoản mới.',retry:'Kết nối lại',deniedTitle:'Quyền truy cập chưa được phê duyệt',denied:'Bạn đã đăng nhập. Tài khoản này hiện chưa được phép truy cập không gian làm việc. Bạn có thể kiểm tra lại quyền truy cập hoặc đăng xuất.',deniedRetry:'Kiểm tra lại quyền truy cập',signOut:'Đăng xuất'}
}

export function getWorkspaceConnectionCopy(language='de'){
  return copy[language]||copy.de
}
