const copy={
  de:{title:'Arbeitsbereich verbinden',connecting:'Ihre Anmeldung wurde angenommen. Der Arbeitsbereich wird geladen. Bei einer vorübergehenden Störung versuchen wir es automatisch erneut.',unavailable:'Ihre Anmeldung wurde angenommen, aber der Arbeitsbereich ist momentan nicht erreichbar. Ihre Sitzung bleibt erhalten. Laden Sie den Arbeitsbereich erneut; ein Zurücksetzen des Passworts behebt diesen Verbindungsfehler nicht.',retry:'Arbeitsbereich erneut laden',signOut:'Abmelden'},
  en:{title:'Connect to your workspace',connecting:'Your sign-in was accepted. Your workspace is loading. We will retry automatically if the service is temporarily unavailable.',unavailable:'Your sign-in was accepted, but your workspace is currently unavailable. Your session is retained. Try loading the workspace again; resetting your password does not resolve this connection error.',retry:'Load workspace again',signOut:'Sign out'},
  fr:{title:'Connexion à votre espace de travail',connecting:'Votre connexion a été acceptée. Votre espace se charge. Nous réessayons automatiquement en cas de panne temporaire.',unavailable:'Votre connexion a été acceptée, mais votre espace est indisponible. Votre session est conservée. Réessayez de charger l’espace ; réinitialiser le mot de passe ne résout pas cette erreur de connexion.',retry:'Recharger l’espace de travail',signOut:'Se déconnecter'},
  tr:{title:'Çalışma alanına bağlan',connecting:'Girişiniz kabul edildi. Çalışma alanı yükleniyor. Geçici bir kesinti olursa otomatik olarak yeniden deneyeceğiz.',unavailable:'Girişiniz kabul edildi ancak çalışma alanına şu anda ulaşılamıyor. Oturumunuz korunuyor. Çalışma alanını yeniden yükleyin; parolayı sıfırlamak bu bağlantı hatasını çözmez.',retry:'Çalışma alanını yeniden yükle',signOut:'Çıkış yap'},
  pl:{title:'Łączenie z obszarem roboczym',connecting:'Logowanie zostało przyjęte. Obszar roboczy się ładuje. W razie przejściowej awarii spróbujemy ponownie automatycznie.',unavailable:'Logowanie zostało przyjęte, ale obszar roboczy jest chwilowo niedostępny. Sesja zostaje zachowana. Załaduj obszar ponownie; resetowanie hasła nie rozwiązuje tego błędu połączenia.',retry:'Załaduj obszar ponownie',signOut:'Wyloguj się'},
  ru:{title:'Подключение к рабочей области',connecting:'Вход принят. Рабочая область загружается. При временном сбое мы автоматически повторим попытку.',unavailable:'Вход принят, но рабочая область сейчас недоступна. Сеанс сохранён. Попробуйте загрузить рабочую область снова; сброс пароля не устраняет эту ошибку соединения.',retry:'Загрузить рабочую область снова',signOut:'Выйти'},
  ar:{title:'الاتصال بمساحة العمل',connecting:'تم قبول تسجيل الدخول. جارٍ تحميل مساحة العمل. سنعيد المحاولة تلقائياً عند حدوث عطل مؤقت.',unavailable:'تم قبول تسجيل الدخول، لكن مساحة العمل غير متاحة حالياً. تم الاحتفاظ بجلستك. حاول تحميل مساحة العمل مجدداً؛ إعادة تعيين كلمة المرور لا تحل خطأ الاتصال هذا.',retry:'تحميل مساحة العمل مجدداً',signOut:'تسجيل الخروج'},
  fa:{title:'اتصال به فضای کار',connecting:'ورود شما پذیرفته شد. فضای کار در حال بارگذاری است. در صورت اختلال موقت، خودکار دوباره تلاش می‌کنیم.',unavailable:'ورود شما پذیرفته شد، اما فضای کار اکنون در دسترس نیست. نشست شما حفظ می‌شود. فضای کار را دوباره بارگذاری کنید؛ بازنشانی گذرواژه این خطای اتصال را برطرف نمی‌کند.',retry:'بارگذاری دوباره فضای کار',signOut:'خروج'},
  ro:{title:'Conectare la spațiul de lucru',connecting:'Autentificarea a fost acceptată. Spațiul de lucru se încarcă. Vom reîncerca automat în cazul unei întreruperi temporare.',unavailable:'Autentificarea a fost acceptată, dar spațiul de lucru este momentan indisponibil. Sesiunea este păstrată. Încercați să încărcați din nou spațiul; resetarea parolei nu rezolvă această eroare de conexiune.',retry:'Reîncarcă spațiul de lucru',signOut:'Deconectare'},
  bg:{title:'Свързване с работното пространство',connecting:'Входът е приет. Работното пространство се зарежда. При временно прекъсване ще опитаме отново автоматично.',unavailable:'Входът е приет, но работното пространство в момента е недостъпно. Сесията се запазва. Заредете пространството отново; нулирането на паролата не решава тази грешка във връзката.',retry:'Зареди работното пространство отново',signOut:'Изход'},
  vi:{title:'Kết nối không gian làm việc',connecting:'Đăng nhập đã được chấp nhận. Không gian làm việc đang tải. Chúng tôi sẽ tự động thử lại nếu dịch vụ tạm thời bị gián đoạn.',unavailable:'Đăng nhập đã được chấp nhận nhưng không gian làm việc hiện chưa khả dụng. Phiên của bạn được giữ lại. Hãy tải lại không gian làm việc; đặt lại mật khẩu không khắc phục lỗi kết nối này.',retry:'Tải lại không gian làm việc',signOut:'Đăng xuất'}
}

export function getWorkspaceConnectionCopy(language='de'){
  return copy[language]||copy.de
}
