import { LegalDocument, LegalNotice, LegalSection } from '../components/LegalDocument'

export const metadata={title:'Datenschutzerklärung | AS Gold',description:'Datenschutzerklärung für AS Gold.'}

export default function Privacy(){
  return <LegalDocument title="Datenschutzerklärung" intro="Diese Erklärung beschreibt den tatsächlichen Datenfluss des kontrollierten AS-Gold-Tests." updated="30. August 2026 · Version 2026-08-30-v1">
    <LegalNotice tone="warning"><b>Testbetrieb ohne echte Kundendaten</b><p>AS Gold darf derzeit nur mit synthetischen oder wirksam anonymisierten Daten verwendet werden. Echte personenbezogene Daten Dritter und besondere Kategorien nach Art. 9 DSGVO sind nicht freigegeben.</p></LegalNotice>
    <LegalSection title="1. Verantwortlicher"><address><b>Sebastian Auls – Unternehmens- und Konzeptberatung</b><br/>Chrysanderstraße 75<br/>21029 Hamburg<br/>Deutschland<br/>E-Mail: <a href="mailto:sebastian.auls@gmail.com">sebastian.auls@gmail.com</a></address></LegalSection>
    <LegalSection title="2. Welche Daten verarbeitet werden"><ul><li><b>Webaufruf:</b> IP-Adresse, Zeitpunkt, angeforderte URL, Browser-/Geräteinformationen sowie Sicherheits- und Fehlerdaten.</li><li><b>Konto:</b> Name, E-Mail-Adresse, verschlüsselter Passwortnachweis beim Auth-Anbieter, Sitzungsdaten, Rollen- und Zugangsstatus.</li><li><b>Arbeitsbereich:</b> selbst eingetragene Fälle, Testkunden, Dokumentmetadaten, Dateien, Bewertungen, Freigaben, Exporte und Auditereignisse.</li><li><b>Datenschutzsteuerung:</b> Version und Zeitpunkt der bestätigten Hinweise, Datenklassifizierung und dokumentbezogene KI-Freigaben.</li><li><b>Widerruf:</b> Name, Vertrags-/Kontoreferenz, Erklärung, Eingangszeitpunkt, Bestätigungskanal und ein kurzzeitig pseudonymisierter Missbrauchsschutz.</li><li><b>Lokaler Browser:</b> Sprache, Ausgabesprache, notwendige Sitzungstoken und eine lokale Gerätehistorie.</li></ul></LegalSection>
    <LegalSection title="3. Zwecke und Rechtsgrundlagen">
      <div className="legalTableWrap"><table><thead><tr><th>Zweck</th><th>Rechtsgrundlage</th></tr></thead><tbody>
        <tr><td>Öffentliche Seite sicher ausliefern, Angriffe und Fehler erkennen</td><td>Art. 6 Abs. 1 lit. f DSGVO (sicherer, stabiler Betrieb)</td></tr>
        <tr><td>Konto, kostenloser Test und gewünschte Funktionen bereitstellen</td><td>Art. 6 Abs. 1 lit. b DSGVO; bei vorvertraglichen Anfragen ebenfalls lit. b</td></tr>
        <tr><td>Nachweis von Vertrags-, Datenschutz-, Freigabe- und Widerrufsvorgängen</td><td>Art. 6 Abs. 1 lit. c und f DSGVO</td></tr>
        <tr><td>Freiwillig gestartete KI-Analyse eines freigegebenen Testdokuments</td><td>Art. 6 Abs. 1 lit. b DSGVO; soweit eine Einwilligung im Einzelfall maßgeblich ist, Art. 6 Abs. 1 lit. a</td></tr>
        <tr><td>Rechtsansprüche, Missbrauchsschutz und IT-Sicherheit</td><td>Art. 6 Abs. 1 lit. f DSGVO</td></tr>
      </tbody></table></div>
      <p>Eine Einwilligung kann jederzeit mit Wirkung für die Zukunft widerrufen werden. Die Rechtmäßigkeit der vorherigen Verarbeitung bleibt unberührt.</p>
    </LegalSection>
    <LegalSection title="4. Hosting und Empfänger"><h3>Vercel</h3><p>Die Webanwendung wird über Vercel Inc., USA, ausgeliefert. Dabei fallen insbesondere technische Zugriffs-, Sicherheits- und Fehlerdaten an. Vercel kann Daten über ein globales Netz verarbeiten. Geeignete Garantien für Drittlandtransfers sind vertraglich und anhand der jeweils aktuellen Unterauftragsverarbeiter zu prüfen.</p><h3>Supabase</h3><p>Supabase Inc. stellt Authentifizierung, Postgres-Datenbank, privaten Dateispeicher und Edge Functions bereit. Das Primärprojekt liegt technisch in <b>eu-west-2 (London, Vereinigtes Königreich)</b>; das Vereinigte Königreich ist kein EU-Mitgliedstaat. Backups, Protokolle, Edge-Ausführung und Unterauftragsverarbeiter können die Datenorte beeinflussen.</p><h3>OpenAI</h3><p>Nur nach ausdrücklichem Start einer Dokumentanalyse erhält die OpenAI API die freigegebene Testdatei und die zur strukturierten Auswertung notwendigen Anweisungen. Die Anfrage setzt <code>store: false</code>. API-Geschäftsdaten werden standardmäßig nicht zum Training verwendet; Sicherheitsprotokolle können grundsätzlich bis zu 30 Tage vorgehalten werden, sofern keine Zero-Data-Retention-Freigabe besteht.</p><p>Weitere Empfänger kommen nur hinzu, wenn dies für Betrieb, Rechtsverteidigung oder gesetzliche Pflichten erforderlich ist. Daten werden nicht zu Werbezwecken verkauft.</p></LegalSection>
    <LegalSection title="5. Internationale Übermittlungen"><p>Bei Dienstleistern oder Unterauftragsverarbeitern außerhalb EU/EWR werden – je nach Anbieter und Datenfluss – Angemessenheitsbeschlüsse, das EU-US Data Privacy Framework, Standardvertragsklauseln und ergänzende Maßnahmen herangezogen. Die konkreten Auftragsverarbeitungsverträge und Transferbewertungen müssen vor einer Freigabe echter personenbezogener Daten abgeschlossen und dokumentiert sein. Bis dahin bleibt deren Verarbeitung gesperrt.</p></LegalSection>
    <LegalSection title="6. Dokumente und KI-Schutzschalter"><p>Jede Datei wird privat unter einer nutzerbezogenen Speicheradresse abgelegt. Zeilenbasierte Datenbankregeln und signierte, kurzlebige Download-Links begrenzen den Zugriff. Vor KI-Verarbeitung prüft der Server: gültige Anmeldung, Eigentum, aktuelle Hinweisversion, zulässige Datenklasse, Konto-Freigabe, Dokument-Freigabe, Dateityp und Größenlimit. Für echte oder besonders sensible Daten existieren zusätzliche serverseitige Sperrschalter, die im Test nicht freigegeben sind.</p></LegalSection>
    <LegalSection title="7. Speicherdauer"><ul><li><b>Konto- und Arbeitsdaten:</b> während des aktiven Tests; nach einer Pause grundsätzlich bis zu drei Monate zur Reaktivierung, soweit keine frühere Löschung verlangt wird oder Aufbewahrungspflichten entgegenstehen.</li><li><b>Dateien:</b> grundsätzlich zusammen mit dem zugehörigen Dokument-/Kontodatensatz.</li><li><b>Audit- und Vertragsnachweise:</b> solange sie für Sicherheit, Rechenschaft und mögliche Rechtsansprüche erforderlich sind.</li><li><b>Widerrufsnachweise:</b> bis zum Ende der regelmäßigen zivilrechtlichen Nachweis- und Verjährungsfristen, anschließend Löschung oder Anonymisierung.</li><li><b>OpenAI API:</b> nach Anbieterangaben grundsätzlich bis zu 30 Tage für Sicherheitszwecke, soweit keine Ausnahme oder längere gesetzliche Pflicht gilt.</li><li><b>Technische Logs:</b> nach den erforderlichen Sicherheits- und Fehlerbehebungsfristen der jeweiligen Infrastruktur-Anbieter.</li></ul><p>Ein Löschantrag kann im Konto oder per E-Mail gestellt werden. Er wird vor Ausführung auf Identität, technische Abhängigkeiten und gesetzliche Aufbewahrungspflichten geprüft.</p></LegalSection>
    <LegalSection title="8. Browser-Speicher"><p>AS Gold verwendet notwendigen lokalen Speicher für die Sitzung, Sprachwahl und lokale Gerätehistorie. Aktuell sind keine eigenen Werbe- oder Reichweitenmessungs-Tracker eingebunden. Einzelheiten stehen unter <a href="/cookies">Cookies & Browser-Speicher</a>.</p></LegalSection>
    <LegalSection title="9. Betroffenenrechte"><p>Betroffene Personen haben nach Maßgabe der DSGVO insbesondere Rechte auf Auskunft, Berichtigung, Löschung, Einschränkung, Datenübertragbarkeit und Widerspruch sowie das Recht, eine Einwilligung für die Zukunft zu widerrufen. Anfragen können an <a href="mailto:sebastian.auls@gmail.com">sebastian.auls@gmail.com</a> gerichtet werden. Zur Vermeidung unbefugter Auskünfte kann eine angemessene Identitätsprüfung erforderlich sein.</p></LegalSection>
    <LegalSection title="10. Beschwerderecht"><p>Eine Beschwerde kann bei einer Datenschutzaufsichtsbehörde eingereicht werden, insbesondere bei:</p><address>Der Hamburgische Beauftragte für Datenschutz und Informationsfreiheit<br/>Ludwig-Erhard-Straße 22<br/>20459 Hamburg<br/><a href="https://datenschutz-hamburg.de/service-information/beschwerde-oder-hinweis-einreichen">Beschwerde oder Hinweis einreichen</a></address></LegalSection>
    <LegalSection title="11. Automatisierte Entscheidungen"><p>AS Gold trifft keine ausschließlich automatisierten Entscheidungen, die rechtliche Wirkung entfalten oder Personen in ähnlicher Weise erheblich beeinträchtigen. KI-Ergebnisse sind sichtbar als vorläufig gekennzeichnet, änderbar und werden erst nach menschlicher Prüfung bewusst gespeichert.</p></LegalSection>
    <LegalSection title="12. Pflicht zur Bereitstellung"><p>Für Registrierung und geschützten Zugang sind Name, E-Mail-Adresse, Passwort und die Bestätigung der Testbedingungen erforderlich. Ohne diese Angaben kann kein Konto bereitgestellt werden. Weitere Inhalte werden freiwillig für die jeweils gewählte Funktion eingegeben; der Test kann auch ohne KI-Analyse genutzt werden.</p></LegalSection>
    <LegalSection title="13. Änderungen"><p>Bei wesentlichen Änderungen wird die Versionsnummer angepasst und eine erneute Bestätigung im Konto verlangt. Frühere Verarbeitungen bleiben nach den damals geltenden Grundlagen zu beurteilen.</p></LegalSection>
  </LegalDocument>
}
