import assert from 'node:assert/strict'
import fs from 'node:fs'

const read=path=>fs.readFileSync(path,'utf8')
const exists=path=>assert.ok(fs.existsSync(path),`missing workflow module: ${path}`)
const paths={controller:'app/modules/workspace/WorkspaceController.js',cases:'app/modules/cases/caseWorkflow.js',approvals:'app/modules/cases/approvalWorkflow.js',documents:'app/modules/documents/documentWorkflow.js',exports:'app/modules/documents/exportWorkflow.js',auth:'app/modules/auth/workspaceAuthWorkflow.js',pricing:'app/modules/pricing/pricingWorkflow.js',account:'app/modules/compliance/accountWorkflow.js'}
for(const path of Object.values(paths)) exists(path)
const page=read('app/page.js')
const current=read('app/modules/workspace/WorkspaceAppCurrent.js')
const legacy=read('app/modules/workspace/WorkspaceAppV2.js')
const controller=read(paths.controller)
const workflows=Object.fromEntries(Object.entries(paths).filter(([key])=>key!=='controller').map(([key,path])=>[key,read(path)]))
assert.match(page,/modules\/workspace\/WorkspaceAppCurrent/,'root page must use the single current workspace entry')
assert.match(current,/WorkspaceController/,'current entry must delegate directly to the active version-neutral controller')
assert.match(legacy,/WorkspaceController/,'legacy V2 path must be compatibility-only')
assert.equal(fs.existsSync('app/modules/workspace/WorkspaceApp.js'),false,'obsolete WorkspaceApp.js must stay removed')
for(const expected of ["from '../cases/caseWorkflow'","from '../cases/approvalWorkflow'","from '../documents/documentWorkflow'","from '../documents/exportWorkflow'","from '../auth/workspaceAuthWorkflow'","from '../pricing/pricingWorkflow'","from '../compliance/accountWorkflow'"]) assert.match(controller,new RegExp(expected.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')),`controller must import ${expected}`)
for(const forbidden of ['createClientRecord','createCaseRecord','updateCaseRecord','createAssessmentRecord','createApprovalRecord','updateApprovalRecord','approveApprovalRecord','rejectApprovalRecord','authorizeDocumentAnalysis','uploadWorkspaceDocument','updateDocumentRecord','createWorkspaceDocumentSignedUrl','invokeDocumentAnalysis','createWorkspaceExportArtifact','createAccountDataArtifact','recordExportEntry','getWorkspaceAccess','loadWorkspaceBundle','ensureRegistrationPrivacy','registerTestAccount','sendPasswordReset','signInSession','getUpgradeQuotes','requestUpgradeRecord','acknowledgeLegalSettings','requestDeletionRecord','cancelDeletionRecord','listDeletionRequests']) assert.doesNotMatch(controller,new RegExp(`\\b${forbidden}\\b`),`controller must not own ${forbidden}`)
for(const token of ['createClientRecord','createCaseRecord','updateCaseRecord','createAssessmentRecord']) assert.match(workflows.cases,new RegExp(token))
for(const token of ['createApprovalRecord','approveApprovalRecord']) assert.match(workflows.approvals,new RegExp(token))
for(const token of ['authorizeDocumentAnalysis','invokeDocumentAnalysis','uploadWorkspaceDocument']) assert.match(workflows.documents,new RegExp(token))
for(const token of ['createWorkspaceExportArtifact','createAccountDataArtifact','recordExportEntry']) assert.match(workflows.exports,new RegExp(token))
for(const token of ['getWorkspaceAccess','loadWorkspaceBundle','ensureRegistrationPrivacy','registerTestAccount','sendPasswordReset','signInSession']) assert.match(workflows.auth,new RegExp(token))
for(const token of ['getUpgradeQuotes','startCheckoutRecord','awaitCheckoutApplied']) assert.match(workflows.pricing,new RegExp(token))
for(const token of ['acknowledgeLegalSettings','requestDeletionRecord','cancelDeletionRecord','listDeletionRequests']) assert.match(workflows.account,new RegExp(token))
for(const source of [controller,...Object.values(workflows)]) assert.doesNotMatch(source,/MutationObserver|setInterval\(|history\.(back|pushState|replaceState)|window\.fetch\s*=/,'workflow/controller must not reintroduce post-render or global interception hacks')
for(const route of ['app/testen/page.js','app/tester-freischalten/page.js','app/tester-verwaltung/page.js','app/einladungen/page.js']){
  const source=read(route)
  assert.match(source,/redirect\('\/'\)/,`${route} must retire legacy tester/invitation UI and return to the app`)
  assert.doesNotMatch(source,/PromoTesterGate|PersonalTesterRedeem|TesterAdminPanel|InvitationWorkflowPanel|PersonalInvitationStudio|TesterGuide|TesterPaused/)
}
const pricing=read('app/modules/pricing/UpgradePanel.js')
const promo=read('app/modules/pricing/promoTranslations.mjs')
assert.match(pricing,/PromoCodeControl/)
assert.doesNotMatch(pricing,/tester-freischalten/,'pricing must not link back to the retired tester redemption route')
assert.doesNotMatch(promo,/Tester-Vollzugang|tester access|testeur complet|test erişim|testowy dostęp|тестов.*доступ|مختبر|آزمایشی|testeri|тестер|thử nghiệm/i)
console.log('V131 controller workflow guard passed: WorkspaceController stays modular and legacy tester UI is retired in favor of promo-code-only access.')
