import assert from 'node:assert/strict'
import fs from 'node:fs'

const read=path=>fs.readFileSync(path,'utf8')
const exists=path=>assert.ok(fs.existsSync(path),`missing module file: ${path}`)
const required=['app/page.js','app/modules/workspace/WorkspaceAppCurrent.js','app/modules/workspace/WorkspaceController.js','app/modules/workspace/WorkspaceAppV2.js','app/modules/language/languageRegistry.mjs','app/modules/language/v36Languages.mjs','app/modules/language/useLanguagePreferences.js','app/modules/language/LanguageSwitcher.js','app/modules/documents/DocumentsSurface.js','app/modules/documents/documentWorkflow.js','app/modules/documents/exportWorkflow.js','app/modules/services/documentAnalysis.js','app/modules/cases/caseWorkflow.js','app/modules/cases/approvalWorkflow.js','app/modules/auth/workspaceAuthWorkflow.js','app/modules/pricing/pricingWorkflow.js','app/modules/compliance/accountWorkflow.js','app/modules/public/PublicLanding.js','app/modules/workspace/ProtectedWorkspaceShell.js','supabase/functions/gold-document-analysis/index.ts']
for(const path of required) exists(path)
assert.equal(fs.existsSync('app/modules/workspace/WorkspaceApp.js'),false,'obsolete workspace facade must stay removed')
const page=read('app/page.js');const current=read('app/modules/workspace/WorkspaceAppCurrent.js');const active=read('app/modules/workspace/WorkspaceController.js');const legacy=read('app/modules/workspace/WorkspaceAppV2.js');const registry=read('app/modules/language/languageRegistry.mjs');const languageFacade=read('app/modules/language/v36Languages.mjs');const languagePreferences=read('app/modules/language/useLanguagePreferences.js');const documentWorkflow=read('app/modules/documents/documentWorkflow.js');const documentService=read('app/modules/services/documentAnalysis.js');const exportWorkflow=read('app/modules/documents/exportWorkflow.js');const edge=read('supabase/functions/gold-document-analysis/index.ts')
assert.match(page,/WorkspaceAppCurrent/,'root page must use the single current workspace entry');assert.ok(page.length<500,'root page must remain a thin entry point');assert.match(current,/WorkspaceController/,'current controller entry must delegate directly to WorkspaceController');assert.match(legacy,/WorkspaceController/,'legacy V2 controller path must be compatibility-only')
for(const workflow of ['createWorkspaceAuthActions','createPricingWorkflowActions','createAccountWorkflowActions','createCaseWorkflowActions','createApprovalWorkflowActions','createDocumentWorkflowActions','createExportWorkflowActions']) assert.match(active,new RegExp(workflow),`active controller must compose ${workflow}`)
assert.match(active,/useLanguagePreferences/);assert.match(active,/DocumentsSurface/);assert.match(active,/PublicLanding/);assert.doesNotMatch(active,/from '@supabase\/supabase-js'/);assert.doesNotMatch(active,/const supabase\s*=\s*createClient/)
assert.match(registry,/LANGUAGE_CATALOG/,'central language registry must own the catalog');assert.match(registry,/supportedLanguages/);assert.match(registry,/localeForLanguage/);assert.match(registry,/pageTranslations/);assert.match(registry,/basePageTranslations/);assert.match(languageFacade,/languageRegistry\.mjs/,'legacy language facade must delegate to registry');assert.doesNotMatch(languageFacade,/export const LANGUAGE_CATALOG|LANGUAGE_CATALOG\s*=\s*Object\.freeze/,'legacy language facade must not define a second catalog');assert.match(languagePreferences,/asgold-language/);assert.match(languagePreferences,/asgold-output-language/);assert.match(languagePreferences,/rtlLanguages/)
assert.match(documentWorkflow,/invokeDocumentAnalysis/);assert.match(documentWorkflow,/dataClassification=form\.elements\.data_classification\?\.value\|\|'personal'/);assert.doesNotMatch(documentWorkflow,/\['synthetic','anonymized'\]\.includes/);assert.match(documentService,/gold-document-analysis/);assert.doesNotMatch(documentService,/gold-ocr-v28/);assert.match(edge,/OUTPUT_LANGUAGES/);assert.match(exportWorkflow,/createWorkspaceExportArtifact/);assert.match(exportWorkflow,/canExport/)
const layout=read('app/layout.js');assert.doesNotMatch(layout,/MutationObserver|OutputLanguageBridge|V44LanguageOrder/,'global layout must not patch product behavior');assert.match(layout,/AccessibilityHardening/);assert.match(layout,/MobileResilience/)
console.log('V80 modular-boundaries guard passed: WorkspaceController is the single active implementation, with one language registry, isolated workflows and current document service.')
