import assert from 'node:assert/strict'
import fs from 'node:fs'
const entry=fs.readFileSync('scripts/v46_finalize_release_candidate.mjs','utf8')
const finalizer=fs.readFileSync('scripts/v46_finalize_release_candidate_v72.mjs','utf8')
assert.match(entry,/v46_finalize_release_candidate_v72\.mjs/)
assert.match(finalizer,/V72/)
assert.match(finalizer,/allen 11 App-Sprachen einschließlich Vietnamesisch/)
assert.ok(finalizer.includes('.length,11'),'tester translation count must be eleven')
assert.match(finalizer,/WorkspaceAppV2\.js/)
assert.match(finalizer,/useWorkspaceAudit\.js/)
assert.match(finalizer,/useWorkspaceSession\.js/)
assert.match(finalizer,/active workspace controller must delegate audit and auth session lifecycle/)
assert.match(finalizer,/test:v46-session-audit/)
assert.match(finalizer,/test_v72_vietnamese_modular_coverage\.mjs/)
console.log('V46 V72 canonical finalizer parity guard passed')
