import assert from 'node:assert/strict'
import fs from 'node:fs'
const component=fs.readFileSync(new URL('../app/components/V42ActionableGaps.js',import.meta.url),'utf8')
const layout=fs.readFileSync(new URL('../app/layout.js',import.meta.url),'utf8')
for(const language of ['de','en','fr','tr','pl','ru','ar','fa','ro','bg']) assert.match(component,new RegExp(`\\b${language}:\\{`))
assert.match(component,/Jetzt erledigen/)
assert.match(component,/data-v42-task/)
assert.match(component,/V42ActionableGaps/)
assert.match(component,/Fall bearbeiten/)
assert.match(component,/Dokument hinzufügen/)
assert.match(component,/Dokument prüfen/)
assert.match(component,/Bewertung ergänzen/)
assert.match(component,/Abweichung prüfen/)
assert.match(layout,/V42ActionableGaps/)
console.log('V42 actionable gaps guard passed: detected gaps become concrete navigation tasks in all 10 languages.')
