import assert from 'node:assert/strict'
import fs from 'node:fs'
const read=p=>fs.readFileSync(new URL('../'+p,import.meta.url),'utf8')
const workspace=read('app/modules/workspace/WorkspaceAppV2.js')
const current=read('app/modules/workspace/WorkspaceAppCurrent.js')
const landing=read('app/modules/public/PublicLanding.js')
const caseDiscovery=read('app/modules/public/PublicCaseDiscoverySection.js')
const languages=read('app/modules/public/PublicLanguageModules.js')
const action=read('app/modules/public/V37FirstAction.js')
const problem=read('app/modules/public/ProblemNavigator.js')
const intro=read('app/modules/public/ProductIntroCompact.js')
const hero=read('app/modules/public/HeroTitleStabilizer.js')
const copy=read('app/modules/public/asGoldIntroCopy.mjs')
const registry=read('app/modules/language/languageRegistry.mjs')
const css=read('app/globals.css')

assert.match(current,/WorkspaceAppV2/)
assert.match(workspace,/const publicLanguage=language/)
assert.match(workspace,/t=\{publicT\}/)
assert.match(workspace,/cd=\{publicCd\}/)
assert.match(registry,/LANGUAGE_CATALOG/)
assert.match(landing,/heroTitleCopy\[language\]/)
assert.match(landing,/<LegalFooter language=\{language\}/)
assert.match(landing,/language==='de'\?'\/testen':`\/testen\?lang=\$\{language\}`/)
assert.match(landing,/PublicCaseDiscoverySection/)
assert.doesNotMatch(languages,/asgold-customer-module-slot/)
assert.match(languages,/function returnToGerman\(\)/)
assert.match(languages,/onLanguageChange\('de'\)/)
assert.match(languages,/onOutputLanguageChange\('de'\)/)
assert.match(languages,/Back to German \/ Zurück zu Deutsch/)
assert.match(languages,/className="publicWelcome"/)
const productIndex=landing.indexOf('<ProductIntroCompact')
const problemIndex=landing.indexOf('<ProblemNavigator')
assert.ok(productIndex>=0&&problemIndex>productIndex,'direct public flow must be explanation -> single problem input')
assert.doesNotMatch(landing,/V37FirstAction/)
assert.match(problem,/<V37FirstAction language=\{interfaceLanguage\}/)
assert.doesNotMatch(action,/data-first-action-voice|const startTitles=|onFocusProblem|onSpeakProblem|\{c\.problem\}|\{c\.voice\}/)
for(const label of ['Dokument hochladen','Upload document','Ajouter un document','Belge yükle','Prześlij dokument','Загрузить документ','حمّل مستنداً','بارگذاری سند','Încărcați un document','Качете документ']) assert.ok(action.includes(label),label)
assert.match(problem,/const concernTitles=/)
assert.match(problem,/forwardRef/)
assert.match(problem,/useImperativeHandle/)
assert.doesNotMatch(landing,/problemNavigatorRef/)
assert.match(problem,/data-problem-voice onClick=\{voice\}/)
assert.doesNotMatch(landing,/setProblemFocusSignal|setProblemVoiceSignal/)
assert.match(problem,/aria-label=\{concernTitle\}/)
assert.match(intro,/howAsGoldWorksCopy/)
assert.match(intro,/\{index\+1\}/)
assert.match(hero,/whatIsAsGoldCopy/)
for(const term of ['digitaler Fallassistent','Sie beschreiben Ihr Anliegen oder laden Unterlagen hoch','Fristen, offene Punkte und Risiken','Sie prüfen und entscheiden selbst','So arbeitet AS Workspace Gold mit Ihnen']) assert.match(copy,new RegExp(term))
assert.equal((caseDiscovery.match(/\{audience\.title\}/g)||[]).length,1)
assert.match(caseDiscovery,/id="asgold-user-audience"/)
assert.match(caseDiscovery,/jumpToPublicCaseResult\(\)/)
assert.match(css,/\.publicWelcome\{grid-column:1\/-1;[^\n]*font-size:1\.08rem/)
assert.match(css,/\.publicWelcome span\{font-size:1\.35rem/)
assert.match(css,/\.publicBackButton\{grid-column:1\/-1;justify-self:end/)
assert.match(css,/@media\(max-width:760px\)\{\.publicBackButton\{width:100%;max-width:none;justify-self:stretch\}\}/)
console.log('V80 public-parity guard passed against the active workspace, central language registry and direct modular public React flow.')
