import assert from 'node:assert/strict'
import fs from 'node:fs'
import {buildProfessionalHandoff,handoffPriority} from '../app/modules/lib/v40ProfessionalHandoff.mjs'

const full=buildProfessionalHandoff({title:'Testfall',goal:'Zahlung',summary:'Sachstand',deadline:'03.09.2026',nextAction:'Antworten',documents:[{title:'Schreiben',date:'2026-09-01'}],assessments:[{trafficLight:'red',title:'Frist',reasoning:'kurz',nextStep:'prüfen'}],timeline:[{date:'2026-09-03',title:'Frist'},{date:'2026-09-01',title:'Schreiben'}]})
assert.equal(full.ready,true)
assert.equal(full.timeline[0].date,'2026-09-01')
assert.equal(handoffPriority(full.assessments),'red')
const incomplete=buildProfessionalHandoff({summary:'Nur Sachstand'})
assert.equal(incomplete.ready,false)
assert.ok(incomplete.missing.includes('documents'))
assert.ok(incomplete.missing.includes('assessments'))

const component=fs.readFileSync(new URL('../app/modules/cases/CaseCompletionPanels.js',import.meta.url),'utf8')
const adapter=fs.readFileSync(new URL('../app/modules/cases/V40ProfessionalHandoff.js',import.meta.url),'utf8')
const compatibility=fs.readFileSync(new URL('../app/components/V40ProfessionalHandoff.js',import.meta.url),'utf8')
const layout=fs.readFileSync(new URL('../app/layout.js',import.meta.url),'utf8')
const caseUi=fs.readFileSync(new URL('../app/modules/cases/V24Workspace.js',import.meta.url),'utf8')
for(const language of ['de','en','fr','tr','pl','ru','ar','fa','ro','bg']) assert.match(component,new RegExp('\\b'+language+':\\{'))
assert.match(component,/Professionelle Übergabe/)
assert.match(component,/data-v40-handoff=\"direct\"/)
assert.match(component,/jspdf/)
assert.match(component,/docx/)
assert.match(component,/Keine zusätzliche Datenübermittlung/)
assert.doesNotMatch(component,/MutationObserver|querySelector/)
assert.match(adapter,/CaseCompletionPanels/)
assert.match(compatibility,/modules\/cases\/V40ProfessionalHandoff/)
assert.doesNotMatch(layout,/V40ProfessionalHandoff/)
assert.match(caseUi,/CaseCompletionPanels/)
console.log('V40 professional handoff guard passed: direct React handoff, local PDF/DOCX export and 10-language UI verified without a global DOM enhancer.')
