import assert from 'node:assert/strict'
import fs from 'node:fs'

const read=path=>fs.readFileSync(new URL(`../${path}`,import.meta.url),'utf8')
const exists=path=>fs.existsSync(new URL(`../${path}`,import.meta.url))

const page=read('app/modules/workspace/WorkspaceController.js')
const authRepository=read('app/modules/services/authRepository.js')
const passwordResetRoute=read('app/api/auth/password-reset/route.js')
const pageEntry=read('app/page.js')
const documentsSurface=read('app/modules/documents/DocumentsSurface.js')
const caseSurfaces=read('app/modules/cases/WorkspaceCaseSurfaces.js')
const privacyControls=read('app/modules/compliance/PrivacyControls.js')
const legalFooter=read('app/modules/compliance/LegalFooter.js')
const nextConfig=read('next.config.mjs')
const packageJson=JSON.parse(read('package.json'))
const terms=read('app/nutzungsbedingungen/page.js')
const privacy=read('app/datenschutz/page.js')
const imprint=read('app/impressum/page.js')
const aiTransparency=read('app/ki-transparenz/page.js')
const cookies=read('app/cookies/page.js')
const testing=read('app/testen/page.js')+'\n'+read('app/modules/tester/TesterPaused.js')
const legalHub=read('app/rechtliches/page.js')
const integrationTokens=read('app/modules/integrations/tokens.js')
const uploadConfig=read('app/modules/documents/uploadConfig.js')
const workspaceText=read('app/modules/workspace/workspaceText.js')
const publicUi=read('app/modules/public/publicUi.js')
const workspaceCopy=page+'\n'+workspaceText+'\n'+publicUi
const googleStart=read('app/api/integrations/google/start/route.js')
const googleCallback=read('app/api/integrations/google/callback/route.js')
const microsoftStart=read('app/api/integrations/microsoft/start/route.js')
const microsoftCallback=read('app/api/integrations/microsoft/callback/route.js')
const integrationStatus=read('app/api/integrations/status/route.js')

assert.match(pageEntry,/modules\/workspace\/WorkspaceAppCurrent/)
assert.match(authRepository,/signInWithPassword/)
assert.match(authRepository+passwordResetRoute,/resetPasswordForEmail/)
assert.match(authRepository,/auth\.signUp/)
assert.match(page,/acceptedLegal/)
assert.match(page,/confirmedTestData/)
assert.match(authRepository,/test_data_only:true/)
assert.match(privacyControls,/PRIVACY_NOTICE_VERSION/)
assert.match(privacyControls,/TERMS_VERSION/)
assert.match(privacyControls,/Art\. 9 DSGVO/)
assert.match(workspaceCopy,/Bezahlfunktion ist vorübergehend deaktiviert/)
assert.match(workspaceCopy,/keine Zahlung ausgelöst/)
assert.match(workspaceCopy,/Keine automatische Verlängerung/)
assert.match(terms,/Keine Zahlung, kein Abo/)
assert.match(terms,/Bezahlfunktion ist deaktiviert/)
assert.equal(typeof packageJson.dependencies?.stripe,'string','Stripe SDK muss für den serverseitigen Testcheckout fest versioniert sein')
const paymentConfig=read('app/modules/payments/paymentConfig.mjs')
const paymentWebhook=read('app/api/payments/webhook/route.js')
assert.match(paymentConfig,/isStripeTestKey/)
assert.match(paymentConfig,/liveLocked/)
assert.match(paymentWebhook,/webhooks\.constructEvent/)
assert.match(paymentWebhook,/live_event_rejected/)
assert.match(paymentWebhook,/payment_status!=='paid'/)
for(const path of ['app/impressum/page.js','app/datenschutz/page.js','app/datenschutzsteuerung/page.js','app/nutzungsbedingungen/page.js','app/widerruf/page.js','app/cookies/page.js','app/ki-transparenz/page.js','app/rechtliches/page.js','app/kontakt/page.js','app/testen/page.js']) assert.ok(exists(path),`Pflicht-/Transparenzseite fehlt: ${path}`)
assert.match(legalFooter,/Verbindlich sind die deutschen Rechtstexte/)
assert.match(imprint,/§ 5 Digitale-Dienste-Gesetz \(DDG\)/)
assert.match(privacy,/Art\. 6 Abs\. 1/)
assert.match(privacy,/Betroffenenrechte/)
assert.match(terms,/keine automatische Außenwirkung/i)
assert.match(aiTransparency,/keine automatische Entscheidung und keine Rechtsberatung/i)
assert.match(aiTransparency,/store: false/)
assert.match(cookies,/Kein Marketing-Tracking/)
const testerPaused=/Testerzugang vorübergehend geschlossen/.test(testing)
if(testerPaused){assert.match(testing,/Aktuell keine Testerfreigabe/);assert.match(testing,/Bitte noch keinen Test starten und keine Testdaten hochladen/);assert.doesNotMatch(testing,/\?start=register/,'paused tester page must not expose the public registration start CTA')}else{assert.match(testing,/Bezahlfunktion bleibt deaktiviert/)}
assert.match(legalHub,/Vor einem späteren Bezahlbetrieb/)
assert.match(uploadConfig,/maxUploadBytes = 50 \* 1024 \* 1024/)
assert.match(uploadConfig,/allowedUploadExtensions/)
assert.match(uploadConfig,/tooLarge/)
assert.match(uploadConfig,/unsupported/)
assert.match(documentsSurface,/disabled=\{uploading\}/)
assert.match(caseSurfaces,/emptyState/)
for(const exportType of ['pdf','docx','xlsx','pptx','csv','txt']) assert.match(page,new RegExp(`value=\\"${exportType}\\"`,'i'),`Export ${exportType} fehlt`)
assert.match(page,/exportMyData/)
assert.match(page,/requestAccountDeletion/)
assert.match(page,/serverAudit/)
for(const token of ['Content-Security-Policy','Referrer-Policy','X-Content-Type-Options','X-Frame-Options','Cross-Origin-Opener-Policy','Permissions-Policy','Strict-Transport-Security']) assert.match(nextConfig,new RegExp(token))
assert.match(nextConfig,/frame-ancestors 'none'/)
assert.match(nextConfig,/object-src 'none'/)
assert.match(nextConfig,/payment=\(\)/)
assert.match(integrationStatus,/GOOGLE_CLIENT_ID/)
assert.match(integrationStatus,/MICROSOFT_CLIENT_ID/)
assert.match(integrationStatus,/INTEGRATION_TOKEN_KEY/)
assert.match(googleStart,/randomUUID/)
assert.match(googleStart,/httpOnly:true,secure:true,sameSite:'lax'/)
assert.match(googleCallback,/expected!==stateValue/)
assert.match(googleCallback,/sealIntegrationToken/)
assert.match(microsoftStart,/randomUUID/)
assert.match(microsoftStart,/httpOnly:true,secure:true,sameSite:'lax'/)
assert.match(microsoftCallback,/state!==expected/)
assert.match(microsoftCallback,/sealIntegrationToken/)
assert.match(integrationTokens,/aes-256-gcm/)
assert.match(integrationTokens,/createHash\('sha256'\)/)
for(const guard of ['test:v37-readiness','test:v38-deadlines','test:v38-assessments','test:v38-next-step','test:v38-simulation','test:v38-mobile','test:v38-accessibility']) assert.match(packageJson.scripts.prebuild,new RegExp(guard.replace(':','\\:')))
console.log('V80 pre-launch guard passed against WorkspaceController, current document surface, security controls and integration boundaries.')
