import assert from 'node:assert/strict'
import fs from 'node:fs'

const read=path=>fs.readFileSync(new URL(`../${path}`,import.meta.url),'utf8')
const install=read('app/modules/public/InstallAppButton.js')
const installShare=read('app/modules/public/InstallShareButton.js')
const languages=read('app/modules/public/PublicLanguageModules.js')
const header=read('app/modules/public/PublicHeader.js')
const auth=read('app/modules/auth/AuthSurface.js')
const installPage=read('app/installieren/page.js')
const insiderPage=read('app/insider/page.js')
const insiderLanding=read('app/modules/insider/InsiderLanding.js')
const insiderAccess=read('app/modules/insider/InsiderAccessController.js')
const teamEntry=read('app/modules/team-account/TeamAccountEntry.js')
const session=read('app/modules/workspace/useWorkspaceSession.js')
const dashboard=read('app/modules/workspace/DashboardSurface.js')
const account=read('app/modules/compliance/AccountControlPanel.js')
const legalFooter=read('app/modules/compliance/LegalFooter.js')
const teamConfig=read('app/modules/team-account/teamAccountConfig.mjs')
const teamLoginRoute=read('app/api/team-account/login/route.js')
const decisionRoute=read('app/api/internal-change-control/decision/route.js')
const changeSurface=read('app/modules/team-account/InternalChangeControlSurface.js')
const changeCopy=read('app/modules/team-account/internalChangeCopy.mjs')
const changeMigration=read('supabase/migrations/20260910120000_v132_internal_change_control.sql')
const envExample=read('.env.example')
const css=read('app/globals.css')
const insiderCss=read('app/insider/insider.css')

assert.match(languages,/<InstallAppButton language=\{language\} surface="public"\/>/,'install entry must sit directly in the public welcome area')
assert.doesNotMatch(header,/<InstallAppButton/,'install entry must not be hidden among small navigation actions')
assert.match(auth,/screen==='login'\|\|screen==='register'/,'login and registration must expose installation')
assert.match(install,/beforeinstallprompt/,'native Chromium installation prompt must remain supported')
assert.match(install,/iPad\|iPhone\|iPod/,'iOS instructions must be device-aware')
assert.match(install,/ChatGPT\|FBAN\|FBAV\|Instagram\|WhatsApp/,'in-app browsers must receive an external-browser instruction')
assert.match(install,/detectedEnvironment!=='inApp'/,'embedded Android browsers must never be mistaken for an installed app')
assert.match(install,/installAppInstalledPanel/,'genuinely installed devices must receive a visible installed status instead of an unexplained gap')
assert.match(install,/installIntroBackdrop/,'first-time visitors must receive an unmistakable installation dialog')
assert.match(install,/asworkspace-install-intro-seen/,'dismissed installation dialog must not reopen repeatedly in the same session')
assert.match(install,/Ohne Installation weiter/,'installation dialog must offer a clear non-install continuation')
assert.match(install,/forceIntro\|\|sessionStorage/,'direct installation links must reopen the installation decision reliably')
assert.match(install,/<InstallShareButton\/>/,'direct installation flow must expose its forwarding action before and after installation')
assert.match(install,/showShareAction=surface==='install'\|\|surface==='public'/,'the forwarding action must also remain visible on the normal public start page')
assert.match(installShare,/AS Workspace weiterleiten/,'forwarding action must be named clearly')
assert.match(installShare,/navigator\.share/,'mobile forwarding must open the native sharing menu')
assert.match(installShare,/navigator\.clipboard\.writeText/,'forwarding must copy the installation link when native sharing is unavailable')
assert.match(installShare,/\/installieren\?neu=1/,'forwarding must always use the dedicated public installation link')
assert.match(installPage,/<InstallAppButton language="de" surface="install" forceIntro\/>/,'shareable installation page must open the installation decision directly')
assert.match(installPage,/AS Workspace installieren/,'shareable installation page must name its single primary task clearly')
assert.doesNotMatch(installPage,/Insider|Chef/,'public installation page must never expose the insider area')
assert.match(insiderPage,/robots:\{index:false,follow:false\}/,'insider landing must stay out of public search indexes')
assert.match(insiderPage,/<InsiderAccessController\/>/,'the insider landing must stay behind its dedicated access controller')
assert.match(insiderAccess,/signInTeamAccount/,'the full insider surface must require the shared access password when no authorised session exists')
assert.match(insiderAccess,/stage==='allowed'.*<InsiderLanding\/>/s,'insider content must not render until server-backed access has been verified')
assert.match(insiderLanding,/Gemeinsamer interner Arbeitsbereich/,'the shared internal account must have a dedicated landing surface')
assert.match(insiderLanding,/Passwort 1 gibt.*Vollzugriff auf das gesamte AS Workspace/,'the internal landing must describe Password 1 full access to everything')
assert.match(insiderLanding,/Passwort 2 bleibt ausschließlich/,'the internal landing must keep publication release separate from team access')
assert.match(insiderLanding,/Zugangsbutton neben dem Impressum/,'the internal landing must explain the public footer entry without exposing protected content')
assert.match(insiderLanding,/Nutzerlink kopieren/,'owner surface must provide the public installation link directly')
assert.match(insiderLanding,/<InstallAppButton language="de" surface="preview" previewOnly\/>/,'owner surface must show the user installation view even on an installed device')
assert.match(teamEntry,/TEAM_LOGIN_PATH/,'internal surface must lead directly to the shared team-account sign-in')
assert.match(session,/start==='team-login'/,'dedicated team link must open the team-account login surface')
assert.match(auth,/isTeamLoginScreen\(screen\)/,'authentication must provide a visibly distinct shared team-account mode')
assert.match(auth,/TeamAccountLoginNotice language=\{language\}/,'team login must explain the shared full-access consequence before sign-in')
assert.match(auth,/team-access-password/,'shared team sign-in must ask for its dedicated access password')
assert.doesNotMatch(auth,/isTeamLogin\)\{[\s\S]{0,500}<input type="email"/,'the dedicated team form must not expose the server-held team email')
assert.match(teamConfig,/Passwort 1 · gemeinsames Zugangspasswort/,'team copy must name Password 1 as shared access password')
assert.match(teamConfig,/Passwort 2 bleibt bei Sebastian/,'team copy must name Sebastian’s separate publication secret')
assert.match(teamLoginRoute,/readTeamSecurity\(admin\)/,'team identity must stay in the server-only setup record')
assert.match(teamLoginRoute,/auth\.admin\.getUserById\(teamUserId\)/,'team sign-in must resolve the configured account only on the server')
assert.doesNotMatch(teamLoginRoute,/TEAM_ACCOUNT_EMAIL|TEAM_ACCOUNT_USER_ID/,'team identity must not depend on exposed or manually copied account data')
assert.match(teamLoginRoute,/signInWithPassword/,'team access password must authenticate through Supabase Auth')
assert.match(account,/onOpenChangeControl/,'account changes must lead into the controlled request module')
assert.doesNotMatch(account,/href="\/passwort-aendern"/,'shared account settings must not let every teammate replace the access password directly')
assert.match(changeCopy,/Gesamtes AS Workspace · alle Bereiche/,'the separate module must accept changes affecting every part of the product')
assert.match(changeCopy,/Passwort 1 · Vollzugriff auf alles/,'Password 1 must grant access to all of AS Workspace')
assert.match(changeCopy,/Passwort 2 · Freigabe der Live-Version/,'Password 2 must be explicitly limited to live-version publication')
assert.match(changeSurface,/confirmCheck/,'the single publication-release step must require explicit owner confirmation')
assert.match(changeSurface,/masterPassword/,'publication release must require the separate master password')
assert.doesNotMatch(changeSurface,/prepareHandoff|navigator\.clipboard/,'the obsolete manual handoff step must not remain')
assert.match(decisionRoute,/verifyMasterPassword/,'master approval must be verified only in the server route')
assert.match(decisionRoute,/VALID_ACTIONS=new Set\(\['release','reject'\]\)/,'only explicit release or rejection actions may reach the server transition')
assert.match(decisionRoute,/internal_master_auth_state/,'master-password attempts must be rate limited')
assert.match(changeMigration,/status text not null default 'requested'.*'released'.*'published'/s,'database workflow must preserve requested, released and published states')
assert.match(changeMigration,/revoke all on table public\.internal_change_requests from public, anon, authenticated/,'browser roles must not gain direct update or delete privileges')
assert.match(changeMigration,/grant select, insert on table public\.internal_change_requests to authenticated/,'team browser sessions may only read and submit requests')
assert.match(changeMigration,/p_action='release' and v_row\.status='requested'/,'Password 2 must release exactly one requested change')
assert.match(changeMigration,/v_row\.status<>'released'/,'the trusted publication record must require prior Password-2 release')
assert.doesNotMatch(envExample,/TEAM_MASTER_PASSWORD_HASH/,'the private setup must keep master-password material out of environment configuration')
assert.match(install,/previewOnly/,'owner-only user preview must bypass installed-device presentation without changing the public flow')
assert.match(dashboard,/access\?\.app_role==='owner'\|\|access\?\.permissions\?\.shared_team_access===true/,'internal entry must only appear for an owner or an explicitly shared team account')
assert.doesNotMatch(dashboard,/hasInsiderAccess=access\?\.app_role==='owner'\|\|access\?\.permissions\?\.test_access/,'ordinary promo testers must not be shown the internal team entry')
assert.match(dashboard,/href="\/insider"/,'authorized insiders must be able to find their separate landing surface')
assert.match(dashboard,/setSection\('change-control'\)/,'authorized team accounts must receive the dedicated change-control module')
assert.match(legalFooter,/href=\{href\('\/impressum',language\)\}[^\n]*className="internalAccessAction" href="\/insider"/,'the protected internal entry button must sit directly beside the imprint link')
assert.match(legalFooter,/de:'Interner Bereich'/,'the footer button must have a clear German label')
assert.match(css,/\.installAppFloatingButton\{display:none\}/,'floating installation control must be scoped to compact viewports')
assert.match(css,/@media\(max-width:760px\)[\s\S]*\.installAppFloatingButton\{position:fixed/,'installation action must stay reachable while mobile users scroll')
assert.match(css,/\.installIntroBackdrop,.installGuideBackdrop\{position:fixed/,'installation decision must be centered above the page')
assert.match(css,/\.installIntroPrimary\{[^}]*background:#ffd765/,'primary installation action must have high visual contrast')
assert.match(css,/\.installShareButton\{[^}]*min-height:58px/,'forwarding action must remain large enough for touch use')
assert.match(css,/body:has\(\.installAppFloatingButton\) \[data-persistent-back\]/,'installation and return controls must not overlap')
assert.match(insiderCss,/\.insiderLanding\{min-height:100svh/,'insider landing must be a visibly separate full-height surface')
assert.match(insiderCss,/\.insiderGate\{min-height:100svh/,'the internal surface must present a full-height access gate before its content')

console.log('V131 installation/team guard passed: the public site stays separate, Password 1 grants full AS Workspace access, and Password 2 releases the new live version.')
