import fs from 'node:fs'
import path from 'node:path'

const root=process.cwd()
const read=p=>fs.readFileSync(path.join(root,p),'utf8')
const fail=message=>{throw new Error('V34: '+message)}
const expect=(condition,message)=>{if(!condition) fail(message)}

const layout=read('app/layout.js')
const publicLanding=read('app/modules/public/PublicLanding.js')
const caseDiscovery=read('app/modules/public/PublicCaseDiscoverySection.js')
const languageModules=read('app/modules/public/PublicLanguageModules.js')
const navigator=read('app/modules/public/ProblemNavigator.js')
const navigatorCompatibility=read('app/components/ProblemNavigator.js')
const intro=read('app/modules/public/ProductIntroCompact.js')
const introCopy=read('app/modules/public/asGoldIntroCopy.mjs')
const introCompatibility=read('app/components/ProductIntroCompact.js')
const jump=read('app/modules/public/caseNavigation.js')
const jumpCompatibility=read('app/components/CaseChoiceJumpEnhancer.js')
const title=read('app/modules/public/HeroTitleStabilizer.js')
const titleCompatibility=read('app/components/HeroTitleStabilizer.js')
const languages=read('app/modules/public/problemNavigatorLanguagesV36.mjs')
const languagesCompatibility=read('app/lib/problemNavigatorLanguagesV36.mjs')

expect((publicLanding.match(/<ProblemNavigator[^>]*outputLanguage=\{outputLanguage\}/g)||[]).length===1,'ProblemNavigator must be rendered exactly once by PublicLanding with the customer/output language')
expect(!publicLanding.includes('customerModule={customerModule}'),'customer navigator must not be tunneled through the language module')
expect(!languageModules.includes('asgold-customer-module-slot')&&!languageModules.includes('{customerModule}'),'language/output module must not own the problem navigator')
expect(!languageModules.includes('createPortal')&&!languageModules.includes('MutationObserver'),'customer-language shell must not use DOM mounting enhancers')
expect(!layout.includes('FreeEntryAfterRecommendation'),'legacy free-entry helper must not be mounted')
expect(!layout.includes('HeroProblemOrder'),'legacy DOM-reorder helper must not be mounted')

const introPos=publicLanding.indexOf('<ProductIntroCompact language={outputLanguage}/>')
const problemPos=publicLanding.indexOf('<ProblemNavigator outputLanguage={outputLanguage}')
const videoPos=publicLanding.indexOf('<ExplainerVideo key=')
expect(introPos>=0&&problemPos>introPos&&videoPos>problemPos,'hero order must remain explanation -> single problem input -> optional video')
expect(!publicLanding.includes('V37FirstAction'),'PublicLanding must not render a second entry card before the problem input')
expect(!layout.includes('V37FirstAction')&&!layout.includes('ProblemNavigator')&&!layout.includes('ExplainerVideo')&&!layout.includes('ProductIntroCompact'),'public hero modules must not be mounted globally')
expect(!layout.includes('<CaseChoiceJumpEnhancer/>'),'case-choice navigation must no longer be a global enhancer')
expect(!layout.includes('<HeroCopyEnhancer/>')&&!layout.includes('<HeroTitleStabilizer/>'),'hero copy must be rendered directly by PublicLanding')
expect(publicLanding.includes("./ProblemNavigator"),'problem navigator must be owned by PublicLanding')
expect(publicLanding.includes("./ProductIntroCompact"),'product intro must be owned by PublicLanding')
expect(publicLanding.includes("./PublicCaseDiscoverySection"),'case discovery must be owned by the public landing composition')
expect(caseDiscovery.includes("./caseNavigation"),'case-choice behavior must be owned by the case discovery module')
expect(publicLanding.includes("./HeroTitleStabilizer"),'hero title copy must be consumed directly by public landing')
expect(navigatorCompatibility.includes("../modules/public/ProblemNavigator"),'legacy problem navigator import must remain a compatibility re-export')
expect(introCompatibility.includes("../modules/public/ProductIntroCompact"),'legacy product intro import must remain a compatibility re-export')
expect(jumpCompatibility.includes("../modules/public/CaseChoiceJumpEnhancer"),'legacy case-choice import must remain a compatibility re-export')
expect(titleCompatibility.includes("../modules/public/HeroTitleStabilizer"),'legacy hero-title import must remain a compatibility re-export')
expect(languagesCompatibility.includes("../modules/public/problemNavigatorLanguagesV36.mjs"),'legacy problem-language path must remain a compatibility re-export')

expect(navigator.includes('<textarea ref={textRef} value={value} onChange='),'problem input must remain a controlled textarea')
expect(navigator.includes('onInput={event=>updateValue(event.currentTarget.value)}'),'mobile input events must update the controlled problem value immediately')
expect(navigator.includes('So funktioniert die Eingabe:'),'German input explanation is missing')
expect(navigator.includes('inputHelp'),'multilingual input help is missing')
expect((navigator.match(/id="asgold-problem-navigator-react"/g)||[]).length===1,'problem navigator section must exist exactly once in component')
expect(navigator.includes('data-customer-language={customerLanguage}'),'problem navigator must expose the selected customer language')
expect(navigator.includes('getSpeechLocale(customerLanguage)'),'speech recognition must follow the customer language')
expect(navigator.includes('3 Dokumente kostenlos kennenlernen'),'free 3-document entry is missing from recommendation flow')
expect(navigator.includes("<V37FirstAction language={customerLanguage} onRegister={onRegister}/>") ,'upload and example actions must stay inside the single problem card')
expect(navigator.includes('data-problem-voice onClick={voice}'),'the single problem card must activate speech directly')
expect(navigator.includes('text.length>1800'),'complete-plan recommendation must be reserved for genuinely extensive narratives')
expect(navigator.includes('text.length>360'),'medium narratives must enter analysis before the complete-plan threshold')

const supported=['de','en','fr','tr','pl','ru','ar','fa','ro','bg']
for(const code of supported){
  expect(introCopy.includes(code+':{title:'),'public product explanation missing language '+code)
  if(code==='ro'||code==='bg') expect(languages.includes(code+':{locale:'),'problem language profile missing '+code)
}
expect(languages.includes("import {problemLanguageProfiles as baseProfiles"),'V36 profile layer must include the base eight languages')
expect(languages.includes('problemLanguageProfiles={...baseProfiles,...extraProfiles}'),'V36 profile layer must merge base and extra languages')
expect(intro.includes('howAsGoldWorksCopy'),'product-intro component must consume the canonical direct module copy')
expect(intro.includes('{index+1}'),'product flow must render four numbered steps')
expect(title.includes('whatIsAsGoldCopy'),'hero title must consume the canonical AS Gold explanation directly')
expect(publicLanding.includes('{hero.title}')&&publicLanding.includes('{hero.lead}'),'hero copy must be rendered directly by PublicLanding')
expect(caseDiscovery.includes('id="asgold-user-audience"'),'audience content must be rendered directly by the case discovery module')
expect((caseDiscovery.match(/\{audience\.title\}/g)||[]).length===1,'audience heading must be rendered once')
expect(caseDiscovery.includes('jumpToPublicCaseResult()'),'case choice must invoke direct navigation from its React click handler')
expect(jump.includes("getElementById('asgold-public-case-result')"),'case navigation must target the selected result card')
expect(jump.includes("behavior:'auto'"),'case choice navigation must use a direct jump instead of slow scrolling')
expect(jump.includes('publicTop'),'case jump must account for the mobile header')
expect(!jump.includes('addEventListener'),'case navigation must not install a global click listener')
expect(!title.includes('MutationObserver')&&!title.includes('querySelector'),'hero title module must not patch the rendered DOM')

console.log('V34 customer-path regression checks passed for direct modular public-language flow and synchronous microphone ref')
