import fs from 'node:fs'

// Final production verification follows the single active workspace implementation.
const page=fs.readFileSync('app/modules/workspace/WorkspaceAppV2.js','utf8')
const pageEntry=fs.readFileSync('app/page.js','utf8')
const layout=fs.readFileSync('app/layout.js','utf8')
const firstAction=fs.readFileSync('app/modules/public/V37FirstAction.js','utf8')
const firstActionCompatibility=fs.readFileSync('app/components/V37FirstAction.js','utf8')
const problem=fs.readFileSync('app/modules/public/ProblemNavigator.js','utf8')
const problemCompatibility=fs.readFileSync('app/components/ProblemNavigator.js','utf8')
const analysisService=fs.readFileSync('app/modules/services/documentAnalysis.js','utf8')
const workspaceRepository=fs.readFileSync('app/modules/services/workspaceRepository.js','utf8')
const exportService=fs.readFileSync('app/modules/services/exportService.js','utf8')
const authRepository=fs.readFileSync('app/modules/services/authRepository.js','utf8')
const uploadConfig=fs.readFileSync('app/modules/documents/uploadConfig.js','utf8')
const authSurface=fs.readFileSync('app/modules/auth/AuthSurface.js','utf8')
const publicLanding=fs.readFileSync('app/modules/public/PublicLanding.js','utf8')
const publicHeader=fs.readFileSync('app/modules/public/PublicHeader.js','utf8')
const documentsSurface=fs.readFileSync('app/modules/documents/DocumentsSurface.js','utf8')
const approvalsSurface=fs.readFileSync('app/modules/cases/ApprovalsSurface.js','utf8')
const caseSurfaces=fs.readFileSync('app/modules/cases/WorkspaceCaseSurfaces.js','utf8')
const dashboardSurface=fs.readFileSync('app/modules/workspace/DashboardSurface.js','utf8')
const caseWorkspace=fs.readFileSync('app/modules/cases/V24Workspace.js','utf8')

const mustContain=(source,needle,label)=>{
  if(!source.includes(needle)) throw new Error(`E2E guard: missing ${label}: ${needle}`)
}

mustContain(pageEntry,"./modules/workspace/WorkspaceAppCurrent",'single workspace entrypoint')
if(publicLanding.includes('V37FirstAction')) throw new Error('E2E guard: duplicate first-action card must not be mounted by PublicLanding')
mustContain(publicLanding,'ProblemNavigator','problem navigator direct public mount')
mustContain(publicLanding,"./ProblemNavigator",'problem navigator public ownership')
mustContain(publicLanding,"./PublicHeader",'public header module boundary')
if(layout.includes('V37FirstAction')||layout.includes('ProblemNavigator')) throw new Error('E2E guard: public interaction modules must not be global layout mounts')
mustContain(firstActionCompatibility,"../modules/public/V37FirstAction",'first-action compatibility re-export')
mustContain(problemCompatibility,"../modules/public/ProblemNavigator",'problem navigator compatibility re-export')
mustContain(firstAction,'Dokument hochladen','upload CTA')
mustContain(firstAction,'Beispiel ansehen','sample CTA')
mustContain(problem,'<V37FirstAction language={interfaceLanguage}','supplemental upload/example actions inside the single problem card')
if(firstAction.includes('{c.problem}')||firstAction.includes('{c.voice}')) throw new Error('E2E guard: duplicate describe/speak controls returned')
mustContain(problem,'analyse()','problem analysis trigger')
mustContain(problem,'recommendation','first recommendation result')

mustContain(publicLanding,"setScreen('register')",'registration route in public content')
mustContain(publicHeader,"onScreenChange('register')",'registration route in public header')
mustContain(publicHeader,"onScreenChange('login')",'login route in public header')
mustContain(authRepository,'signInWithPassword','password login service')
mustContain(authRepository,'auth.signUp','registration service action')

for(const ext of ['pdf','jpg','png','docx','xlsx','pptx','eml','msg']) mustContain(uploadConfig,`'${ext}'`,`upload extension ${ext}`)
mustContain(page,"action==='scan'||action==='upload'",'quick upload route')
mustContain(documentsSurface,'name="file"','current document upload form')
mustContain(documentsSurface,'APP_VERSION','current release badge in document workspace')
mustContain(page,'DocumentsSurface','document workspace composition')

mustContain(page,'createDocumentWorkflowActions','document workflow boundary')
mustContain(analysisService,"supabase.functions.invoke('gold-document-analysis'",'current document analysis backend')
mustContain(page,'analysisUi','analysis UI wiring')
mustContain(page,'createCaseWorkflowActions','case workflow boundary')
mustContain(workspaceRepository,"traffic_light:'yellow'",'default case traffic light')
mustContain(workspaceRepository,"traffic_light:draft.traffic_light",'assessment traffic light')
mustContain(workspaceRepository,"from('cases')",'case repository persistence')
mustContain(workspaceRepository,"from('clients')",'client repository persistence')

mustContain(page,'createApprovalWorkflowActions','approval workflow boundary')
mustContain(approvalsSurface,'ApprovalSection','approval workspace module')
mustContain(page,'ApprovalDetail','approval detail')
mustContain(page,'prepareDocumentApproval','prepare approval from document')

mustContain(page,'createExportWorkflowActions','export workflow boundary')
mustContain(exportService,'function downloadExportArtifact','download delivery service')

mustContain(caseSurfaces,'backOverview','cases/clients overview navigation')
mustContain(page,'<CaseDetail','case detail active route')
mustContain(page,'onBack={()=>setSelectedCase(null)}','case-detail back navigation')
mustContain(caseWorkspace,'export function CaseDetail','case detail module')
mustContain(caseSurfaces,'backClients','client-detail navigation')
mustContain(dashboardSurface,'setSection','dashboard navigation ownership')
mustContain(authSurface,'backExplanation','navigation backExplanation in auth module')

console.log('Current code-path end-to-end regression checks passed against the live WorkspaceAppV2 implementation and current service boundaries')
