import assert from 'node:assert/strict'
import fs from 'node:fs'

const read=path=>fs.readFileSync(new URL(`../${path}`,import.meta.url),'utf8')
const install=read('app/modules/public/InstallAppButton.js')
const languages=read('app/modules/public/PublicLanguageModules.js')
const header=read('app/modules/public/PublicHeader.js')
const auth=read('app/modules/auth/AuthSurface.js')
const installPage=read('app/installieren/page.js')
const css=read('app/globals.css')

assert.match(languages,/<InstallAppButton language=\{language\} surface="public"\/>/,'install entry must sit directly in the public welcome area')
assert.doesNotMatch(header,/<InstallAppButton/,'install entry must not be hidden among small navigation actions')
assert.match(auth,/screen==='login'\|\|screen==='register'/,'login and registration must expose installation')
assert.match(install,/beforeinstallprompt/,'native Chromium installation prompt must remain supported')
assert.match(install,/iPad\|iPhone\|iPod/,'iOS instructions must be device-aware')
assert.match(install,/ChatGPT\|FBAN\|FBAV\|Instagram\|WhatsApp/,'in-app browsers must receive an external-browser instruction')
assert.match(install,/detectedEnvironment!=='inApp'/,'embedded Android browsers must never be mistaken for an installed app')
assert.match(install,/installAppInstalledPanel/,'genuinely installed devices must receive a visible installed status instead of an unexplained gap')
assert.match(install,/installIntroBackdrop/,'first-time visitors must receive an unmistakable installation dialog')
assert.match(install,/asworkspace-install-intro-seen/,'dismissed installation dialog must not reopen repeatedly in the same session')
assert.match(install,/Ohne Installation weiter/,'installation dialog must offer a clear non-install continuation')
assert.match(install,/forceIntro\|\|sessionStorage/,'direct installation links must reopen the installation decision reliably')
assert.match(installPage,/<InstallAppButton language="de" surface="install" forceIntro\/>/,'shareable installation page must open the installation decision directly')
assert.match(installPage,/AS Workspace installieren/,'shareable installation page must name its single primary task clearly')
assert.match(css,/\.installAppFloatingButton\{display:none\}/,'floating installation control must be scoped to compact viewports')
assert.match(css,/@media\(max-width:760px\)[\s\S]*\.installAppFloatingButton\{position:fixed/,'installation action must stay reachable while mobile users scroll')
assert.match(css,/\.installIntroBackdrop,.installGuideBackdrop\{position:fixed/,'installation decision must be centered above the page')
assert.match(css,/\.installIntroPrimary\{[^}]*background:#ffd765/,'primary installation action must have high visual contrast')
assert.match(css,/body:has\(\.installAppFloatingButton\) \[data-persistent-back\]/,'installation and return controls must not overlap')

console.log('V131 installation-entry guard passed: first-visit dialog, high-contrast welcome action, mobile floating control, platform guidance and auth visibility are active.')
