import fs from 'node:fs'
import assert from 'node:assert/strict'

const module=fs.readFileSync('app/modules/language/outputLanguage.js','utf8')
const registry=fs.readFileSync('app/modules/language/languageRegistry.mjs','utf8')
const service=fs.readFileSync('app/modules/services/documentAnalysis.js','utf8')
const workspace=fs.readFileSync('app/modules/workspace/WorkspaceController.js','utf8')
const fn=fs.readFileSync('supabase/functions/gold-document-analysis/index.ts','utf8')
const layout=fs.readFileSync('app/layout.js','utf8')
assert.match(module,/OUTPUT_LANGUAGE_STORAGE_KEY='asgold-output-language'/)
assert.match(module,/normalizeOutputLanguage/)
assert.match(service,/gold-document-analysis/)
assert.match(service,/output_language:outputLanguage/)
assert.match(workspace,/createDocumentWorkflowActions/)
assert.match(workspace,/outputLanguage/)
assert.match(workspace,/languageRegistry\.mjs/)
assert.match(registry,/LANGUAGE_CATALOG/)
assert.equal(fs.existsSync('app/modules/language/v36Languages.mjs'),false)
assert.doesNotMatch(layout,/OutputLanguageBridge/)
assert.match(fn,/OUTPUT_LANGUAGES/)
assert.match(fn,/summary und next_step vollständig auf/)
assert.match(fn,/output_language:requestedOutputLanguage/)
assert.doesNotMatch(fn,/gold-ocr-v28/)
console.log('V80 output-language guard passed directly against WorkspaceController, languageRegistry and the current document-analysis service.')
