import assert from 'node:assert/strict'
import fs from 'node:fs'
const read=p=>fs.readFileSync(new URL('../'+p,import.meta.url),'utf8')
const workspace=read('app/modules/workspace/WorkspaceApp.js')
const landing=read('app/modules/public/PublicLanding.js')
const caseDiscovery=read('app/modules/public/PublicCaseDiscoverySection.js')
const languages=read('app/modules/public/PublicLanguageModules.js')
const action=read('app/modules/public/V37FirstAction.js')
const problem=read('app/modules/public/ProblemNavigator.js')
const intro=read('app/modules/public/ProductIntroCompact.js')
const hero=read('app/modules/public/HeroTitleStabilizer.js')
const copy=read('app/modules/public/asGoldIntroCopy.mjs')
const css=read('app/globals.css')
assert.match(workspace,/const publicLanguage = outputLanguage/)
assert.match(workspace,/t=\{publicT\}/)
assert.match(workspace,/cd=\{publicCd\}/)
assert.match(landing,/heroTitleCopy\[outputLanguage\]/)
assert.match(landing,/<LegalFooter language=\{outputLanguage\}/)
assert.match(landing,/PublicCaseDiscoverySection/)
assert.doesNotMatch(languages,/asgold-customer-module-slot/)
assert.match(languages,/function returnToGerman\(\)/)
assert.match(languages,/onLanguageChange\('de'\)/)
assert.match(languages,/onOutputLanguageChange\('de'\)/)
assert.match(languages,/Back to German \/ Zurück zu Deutsch/)
assert.match(languages,/className="publicWelcome"/)
const productIndex=landing.indexOf('<ProductIntroCompact')
const actionIndex=landing.indexOf('<V37FirstAction')
const problemIndex=landing.indexOf('<ProblemNavigator')
assert.ok(productIndex>=0&&actionIndex>productIndex&&problemIndex>actionIndex,'direct public flow must be explanation -> action -> problem input')
for(const label of ['Problem einsprechen','Speak problem','Dicter le problème','Sorunu sesli anlat','Powiedz problem','Продиктовать проблему','قل المشكلة','بیان صوتی مشکل','Spuneți problema','Кажете проблема']) assert.ok(action.includes(label),label)
assert.match(action,/data-first-action-voice/)
assert.match(action,/const startTitles=/)
assert.match(action,/onFocusProblem/)
assert.match(action,/onSpeakProblem/)
assert.match(problem,/const concernTitles=/)
assert.match(problem,/forwardRef/)
assert.match(problem,/useImperativeHandle/)
assert.match(landing,/const problemNavigatorRef=useRef\(null\)/)
assert.match(landing,/onFocusProblem=\{\(\)=>problemNavigatorRef\.current\?\.focus\(\)\}/)
assert.match(landing,/onSpeakProblem=\{\(\)=>problemNavigatorRef\.current\?\.speak\(\)\}/)
assert.doesNotMatch(landing,/setProblemFocusSignal|setProblemVoiceSignal/)
assert.match(problem,/aria-label=\{concernTitle\}/)
assert.match(intro,/howAsGoldWorksCopy/)
assert.match(intro,/\{index\+1\}/)
assert.match(hero,/whatIsAsGoldCopy/)
for(const term of ['digitaler Fallassistent','Sie beschreiben Ihr Anliegen oder laden Unterlagen hoch','Fristen, offene Punkte und Risiken','Sie prüfen und entscheiden selbst','So arbeitet AS Gold mit Ihnen']) assert.match(copy,new RegExp(term))
assert.equal((caseDiscovery.match(/\{audience\.title\}/g)||[]).length,1)
assert.match(caseDiscovery,/id="asgold-user-audience"/)
assert.match(caseDiscovery,/jumpToPublicCaseResult\(\)/)
assert.match(css,/\.publicWelcome\{grid-column:1\/-1;[^\n]*font-size:1\.08rem/)
assert.match(css,/\.publicWelcome span\{font-size:1\.35rem/)
assert.match(css,/\.publicBackButton\{grid-column:1\/-1;justify-self:end/)
assert.match(css,/@media\(max-width:760px\)\{\.publicBackButton\{width:100%;max-width:none;justify-self:stretch\}\}/)
console.log('V69 modular public parity guard passed: current public-language, direct microphone-ref, intro, case discovery and navigation behavior is direct React without DOM enhancers.')
