import assert from 'node:assert/strict'
import fs from 'node:fs'
const component=fs.readFileSync(new URL('../app/modules/cases/CaseCompletionPanels.js',import.meta.url),'utf8')
const adapter=fs.readFileSync(new URL('../app/modules/cases/V42ActionableGaps.js',import.meta.url),'utf8')
const layout=fs.readFileSync(new URL('../app/layout.js',import.meta.url),'utf8')
const caseUi=fs.readFileSync(new URL('../app/modules/cases/V24Workspace.js',import.meta.url),'utf8')
for(const language of ['de','en','fr','tr','pl','ru','ar','fa','ro','bg']) assert.match(component,new RegExp('\\b'+language+':\\{'))
assert.match(component,/Jetzt erledigen/)
assert.match(component,/data-v42-task/)
assert.match(component,/Fall bearbeiten/)
assert.match(component,/Dokument hinzufügen/)
assert.match(component,/Dokument prüfen/)
assert.match(component,/Bewertung ergänzen/)
assert.match(component,/Abweichung prüfen/)
assert.doesNotMatch(component,/MutationObserver|querySelectorAll|addEventListener\('click'/)
assert.match(adapter,/CaseCompletionPanels/)
assert.doesNotMatch(layout,/V42ActionableGaps/)
assert.match(caseUi,/onEdit=\{\(\)=>setEditing\(true\)\}/)
assert.match(caseUi,/onAddDocument=\{\(\)=>onAddDocument\(item.id\)\}/)
console.log('V42 actionable gaps guard passed: detected gaps render as direct React actions with explicit callbacks and no global DOM click routing.')
