import assert from 'node:assert/strict'
import { scryptSync } from 'node:crypto'
import fs from 'node:fs'

import { createMasterPasswordHash, parseMasterPasswordHash, verifyMasterPassword } from '../app/modules/team-account/serverSecurity.js'

const read=path=>fs.readFileSync(new URL(`../${path}`,import.meta.url),'utf8')
const salt=Buffer.from('00112233445566778899aabbccddeeff','hex')
const password='Only-Sebastian-Can-Approve-132!'
const encoded=`scrypt:${salt.toString('hex')}:${scryptSync(password,salt,64).toString('hex')}`

assert.ok(parseMasterPasswordHash(encoded),'valid scrypt master hashes must parse')
assert.equal(verifyMasterPassword(password,encoded),true,'the correct master password must verify')
assert.equal(verifyMasterPassword(`${password}x`,encoded),false,'an incorrect master password must fail')
assert.equal(verifyMasterPassword('too-short',encoded),false,'short master passwords must be rejected')
assert.equal(parseMasterPasswordHash('plain-text-password'),null,'plain-text master secrets must never be accepted as configuration')
const generated=createMasterPasswordHash(password)
assert.ok(parseMasterPasswordHash(generated),'the private setup must generate a valid salted scrypt hash')
assert.equal(verifyMasterPassword(password,generated),true,'the generated master hash must verify')
assert.notEqual(generated,createMasterPasswordHash(password),'each setup hash must use a fresh random salt')

const authSurface=read('app/modules/auth/AuthSurface.js')
const publicLanding=read('app/modules/public/PublicLanding.js')
const installPage=read('app/installieren/page.js')
const decisionRoute=read('app/api/internal-change-control/decision/route.js')
const loginRoute=read('app/api/team-account/login/route.js')
const setupRoute=read('app/api/team-account/setup/route.js')
const setupSurface=read('app/modules/team-account/TeamPasswordSetup.js')
const changeSurface=read('app/modules/team-account/InternalChangeControlSurface.js')
const changeCopy=read('app/modules/team-account/internalChangeCopy.mjs')
const migration=read('supabase/migrations/20260910120000_v132_internal_change_control.sql')
const envExample=read('.env.example')

assert.match(authSurface,/id="team-access-password"/,'the shared access password needs a dedicated input')
assert.match(authSurface,/Passwort 2 wird hier niemals eingegeben/,'the access form must keep Password 2 separate')
assert.doesNotMatch(publicLanding,/team-account|change-control|Masterpasswort/,'public landing must not expose internal access or approval controls')
assert.doesNotMatch(installPage,/team-account|change-control|Masterpasswort/,'public installation must not expose internal controls')
assert.match(loginRoute,/readTeamSecurity\(admin\)/,'team login must load its account identity from server-only setup state')
assert.doesNotMatch(loginRoute,/TEAM_ACCOUNT_EMAIL|TEAM_ACCOUNT_USER_ID/,'team identity must not require manually copied environment values')
assert.match(decisionRoute,/userData\.user\.id!==teamUserId/,'master decisions must be pinned to the configured shared account')
assert.match(decisionRoute,/masterPasswordConfigured\(security\.master_password_hash\)/,'master decisions must fail closed without the server-only database hash')
assert.match(decisionRoute,/master_locked/,'master verification must enforce a lockout')
assert.doesNotMatch(decisionRoute,/console\.|TEAM_MASTER_PASSWORD(?!_HASH)/,'the decision route must neither log nor accept a plain-text configured master password')
assert.match(setupRoute,/access\?\.app_role!=='owner'/,'only the currently authenticated owner may perform first setup')
assert.match(setupRoute,/auth\.admin\.updateUserById\(user\.id,\{password:accessPassword\}\)/,'the shared access password must be handed directly to Supabase Auth')
assert.match(setupRoute,/createMasterPasswordHash\(masterPassword\)/,'the master password must be irreversibly hashed before persistence')
assert.doesNotMatch(setupRoute,/console\.|masterPassword[^\n]*return|accessPassword[^\n]*return/,'setup must never log or return either password')
assert.match(setupSurface,/Passwort 1 · Vollzugriff auf alles/,'Password 1 must clearly open all of AS Workspace')
assert.match(setupSurface,/Passwort 2 · Freigabe der Live-Version/,'Password 2 must be limited to publication release')
assert.match(setupSurface,/accessPasswordRepeat/,'the access password must be entered twice')
assert.match(setupSurface,/masterPasswordRepeat/,'the master password must be entered twice')
assert.match(changeCopy,/Passwort 1 · Vollzugriff auf alles/,'the change centre must explain Password 1 full access to all of AS Workspace')
assert.match(changeCopy,/Passwort 2 · Freigabe der Live-Version/,'the change centre must explain the single Password 2 live-version release')
assert.match(changeCopy,/Gesamtes AS Workspace · alle Bereiche/,'the change centre must cover the complete product without an area restriction')
assert.match(changeSurface,/decide\(item\.id,'release'\)/,'Password 2 must have one explicit publication-release action')
assert.match(changeSurface,/data-publication-button/,'the Password-2 release needs one large button at the bottom of the decision area')
assert.match(changeCopy,/Änderung zur Veröffentlichung freigeben/,'the bottom action must state its exact publication-release purpose')
assert.doesNotMatch(changeSurface,/decide\(item\.id,'(?:approve|confirm)'\)|navigator\.clipboard/,'the obsolete double approval and manual clipboard handoff must be removed')
assert.match(migration,/for select[\s\S]*for insert/,'team sessions may select and insert requests')
assert.doesNotMatch(migration,/create policy internal_change_requests_update/,'no browser update policy may bypass master approval')
assert.match(migration,/status in \('requested','released','rejected','published'\)/,'the database must model request, Password-2 release, rejection and actual publication')
assert.match(migration,/p_action='release' and v_row\.status='requested'/,'Password 2 must release a requested change in one transition')
assert.doesNotMatch(migration,/p_action='approve'|p_action='confirm'|status='approved'|status='confirmed'/,'the obsolete two-stage master flow must not remain')
assert.match(migration,/grant execute on function public\.apply_internal_change_decision\(uuid,uuid,text,text\) to service_role/,'only the service role may execute decision transitions')
assert.match(migration,/grant execute on function public\.record_internal_change_publication\(uuid,uuid,text\) to service_role/,'only the trusted server process may record a successful publication')
assert.match(migration,/v_row\.status<>'released'/,'publication recording must fail unless Password 2 released the exact request')
assert.doesNotMatch(migration,/security definer/i,'privileged change-control functions must not bypass RLS through SECURITY DEFINER')
assert.match(migration,/create table if not exists public\.team_account_security/,'setup state must have a dedicated server-only table')
assert.match(migration,/alter table public\.team_account_security enable row level security/,'the setup table must enforce RLS')
assert.doesNotMatch(migration,/create policy[^;]*team_account_security/,'the setup table must have no browser policy')
assert.doesNotMatch(envExample,/^TEAM_(?:ACCOUNT_EMAIL|ACCOUNT_USER_ID|MASTER_PASSWORD(?:_HASH)?)=/m,'no team or master password material may be configured in the environment')

console.log('Team change-control security guard passed: Password 1 grants full access to all of AS Workspace and one Password 2 release gates the new live version.')
