import fs from 'node:fs'
import assert from 'node:assert/strict'

const bridge=fs.readFileSync('app/components/V45OutputLanguageBridge.js','utf8')
const fn=fs.readFileSync('supabase/functions/gold-ocr-v28/index.ts','utf8')
const layout=fs.readFileSync('app/layout.js','utf8')
const page=fs.readFileSync('app/page.js','utf8')
const problem=fs.readFileSync('app/components/ProblemNavigator.js','utf8')

assert.match(bridge,/asgold-output-language/)
assert.match(bridge,/gold-ocr-v28/)
assert.match(bridge,/output_language/)
assert.match(fn,/OUTPUT_LANGUAGES/)
assert.match(fn,/summary und next_step vollständig auf/)
assert.match(fn,/output_language:requestedOutputLanguage/)
assert.match(layout,/V45OutputLanguageBridge/)
assert.match(page,/document\.dispatchEvent\(new CustomEvent\('asgold:output-language'/)
assert.match(problem,/addEventListener\('asgold:output-language'/)
assert.match(problem,/recommend\(result\.value,outputProfile\)/)
assert.match(problem,/outputProfile\.cases\[recommendation\.caseKey\]/)
assert.match(problem,/const c=outputProfile\.ui/)
assert.match(problem,/getSpeechLocale\(outputLanguage\)/)
assert.match(problem,/data-customer-language=\{outputLanguage\}/)
assert.match(page,/getV24Copy\(outputLanguage\)/)
assert.match(page,/getV25ApprovalCopy\(outputLanguage\)/)
assert.match(problem,/data-problem-voice/)
assert.match(page,/className="secondary heroVoiceShortcut"/)
assert.match(page,/setTimeout\(\(\)=>microphone\.click\(\),350\)/)
const modules=fs.readFileSync('app/components/PublicLanguageModules.js','utf8')
const flow=fs.readFileSync('app/components/HomepageFlowAnchors.js','utf8')
assert.doesNotMatch(modules,/id="asgold-customer-module-slot"/)
assert.match(problem,/getElementById\('asgold-customer-module-slot'\)/)
assert.match(flow,/asgold-problem-slot/)
assert.doesNotMatch(modules,/querySelector\('textarea'\)\?\.focus/)
console.log('V55 output-language guard passed: the selected customer language controls the full problem input, microphone, recommendation, AI analysis and exports.')
