import assert from 'node:assert/strict'
import fs from 'node:fs'
const read=p=>fs.readFileSync(new URL('../'+p,import.meta.url),'utf8')
const workspace=read('app/modules/workspace/WorkspaceController.js')
const current=read('app/modules/workspace/WorkspaceAppCurrent.js')
const legacy=read('app/modules/workspace/WorkspaceAppV2.js')
const landing=read('app/modules/public/PublicLanding.js')
const testingPage=read('app/testen/page.js')
const footer=read('app/modules/compliance/LegalFooter.js')
const notFound=read('app/not-found.js')
const caseDiscovery=read('app/modules/public/PublicCaseDiscoverySection.js')
const languages=read('app/modules/public/PublicLanguageModules.js')
const action=read('app/modules/public/FirstAction.js')
const actionLegacy=read('app/modules/public/V37FirstAction.js')
const problem=read('app/modules/public/ProblemNavigator.js')
const intro=read('app/modules/public/ProductIntroCompact.js')
const hero=read('app/modules/public/HeroTitleStabilizer.js')
const copy=read('app/modules/public/asGoldIntroCopy.mjs')
const registry=read('app/modules/language/languageRegistry.mjs')
const css=read('app/globals.css')
assert.match(current,/WorkspaceController/);assert.match(legacy,/WorkspaceController/);assert.match(actionLegacy,/FirstAction/)
assert.match(workspace,/const publicLanguage=language/);assert.match(workspace,/t=\{publicT\}/);assert.match(workspace,/cd=\{publicCd\}/);assert.match(registry,/LANGUAGE_CATALOG/);assert.match(landing,/heroTitleCopy\[language\]/);assert.match(landing,/<LegalFooter language=\{language\}/);assert.doesNotMatch(landing,/href=\{language==='de'\?'\/testen'/,'normal product homepage must not expose legacy tester surface');assert.doesNotMatch(footer,/\/testen|Sicher testen|Safe testing|Test sécurisé|Güvenli test|Bezpieczny test|Безопасный тест|اختبار آمن|آزمایش امن|Testare sigură|Безопасен test|Thử nghiệm an toàn/,'global footer must not promote legacy tester surface');assert.doesNotMatch(notFound,/Testzugang|\/testen/,'404 surface must not promote legacy tester surface');assert.match(testingPage,/redirect\('\/'\)/);assert.match(testingPage,/robots:\{index:false,follow:false\}/);assert.doesNotMatch(testingPage,/PromoTesterGate|TesterPaused|TesterGuide|GuestTestStartButton|TesterShareButton/);assert.match(landing,/PublicCaseDiscoverySection/);assert.doesNotMatch(languages,/asgold-customer-module-slot/);assert.match(languages,/function returnToGerman\(\)/);assert.match(languages,/onLanguageChange\('de'\)/);assert.match(languages,/onOutputLanguageChange\('de'\)/);assert.match(languages,/Back to German \/ Zurück zu Deutsch/);assert.match(languages,/className="publicWelcome"/)
for(const lang of ['de','en','fr','tr','pl','ru','ar','fa','ro','bg','vi']) assert.match(landing,new RegExp(`\\b${lang}:\\{`),`homepage capability copy missing ${lang}`)
for(const term of ['Dokumente & Fotos','Spracheingabe','Ampelanalyse','Nachweise & Lücken','Fristen & Verlauf','Rechtsraumvergleich','11 Sprachen','Zweisprachige Schreiben','Vorschau & Freigabe','PDF & Word','Übergabeakte','Kontrolle & Nachvollziehbarkeit']) assert.ok(landing.includes(term),`homepage capability missing: ${term}`)
const productIndex=landing.indexOf('<ProductIntroCompact');const problemIndex=landing.indexOf('<ProblemNavigator');assert.ok(productIndex>=0&&problemIndex>productIndex,'direct public flow must be explanation -> single problem input');assert.doesNotMatch(landing,/V37FirstAction/);assert.match(problem,/<V37FirstAction language=\{interfaceLanguage\}/);assert.doesNotMatch(action,/data-first-action-voice|const startTitles=|onFocusProblem|onSpeakProblem|\{c\.problem\}|\{c\.voice\}/)
for(const label of ['Dokument hochladen','Upload document','Ajouter un document','Belge yükle','Prześlij dokument','Загрузить документ','حمّل مستنداً','بارگذاری سند','Încărcați un document','Качете документ']) assert.ok(action.includes(label),label)
assert.match(problem,/const concernTitles=/);assert.match(problem,/forwardRef/);assert.match(problem,/useImperativeHandle/);assert.doesNotMatch(landing,/problemNavigatorRef/);assert.match(problem,/data-problem-voice onClick=\{voice\}/);assert.doesNotMatch(landing,/setProblemFocusSignal|setProblemVoiceSignal/);assert.match(problem,/aria-label=\{concernTitle\}/);assert.match(intro,/howAsGoldWorksCopy/);assert.match(intro,/\{index\+1\}/);assert.match(hero,/whatIsAsGoldCopy/)
for(const term of ['digitaler Fallassistent','Sie beschreiben Ihr Anliegen oder laden Unterlagen hoch','Fristen, offene Punkte und Risiken','Sie prüfen und entscheiden selbst','So arbeitet AS Workspace Gold mit Ihnen']) assert.match(copy,new RegExp(term))
assert.equal((caseDiscovery.match(/\{audience\.title\}/g)||[]).length,1);assert.match(caseDiscovery,/id="asgold-user-audience"/);assert.match(caseDiscovery,/jumpToPublicCaseResult\(\)/);assert.match(css,/\.publicWelcome\{grid-column:1\/-1;[^\n]*font-size:1\.08rem/);assert.match(css,/\.publicWelcome span\{font-size:1\.35rem/);assert.match(css,/\.publicBackButton\{grid-column:1\/-1;justify-self:end/);assert.match(css,/@media\(max-width:760px\)\{\.publicBackButton\{width:100%;max-width:none;justify-self:stretch\}\}/)
console.log('V131 public-parity guard passed: capability-first homepage, 11-language copy and promo-only public flow stay aligned.')
