import assert from 'node:assert/strict'
import fs from 'node:fs'
import { analyzeCaseConsistency } from '../app/modules/lib/caseConsistency.mjs'

const result=analyzeCaseConsistency({caseItem:{title:'Test',goal:'Zahlung prüfen',summary:'Zwei Schreiben liegen vor',deadline_at:'2026-09-10',next_action:'Antwort vorbereiten'},documents:[{title:'Schreiben A',extracted_text:'Die Forderung beträgt 1.000,00 EUR. Zahlung bis 10.09.2026.'},{title:'Schreiben B',extracted_text:'Die Forderung beträgt 1.250,00 EUR. Zahlung bis 12.09.2026.'}],assessments:[{traffic_light:'yellow',next_step:'Beträge prüfen'}]})
assert.equal(result.gaps.length,0)
assert.ok(result.deviations.some(x=>x.concept==='forderung'&&x.type==='amount'))
assert.ok(result.deviations.some(x=>x.concept==='zahlung'&&x.type==='date'))
assert.ok(result.score<100)
const gaps=analyzeCaseConsistency({caseItem:{},documents:[{title:'X',extracted_text:''}],assessments:[{traffic_light:'red',next_step:''}]})
for(const key of ['goal','summary','deadline','next_action','unread_documents','red_without_next']) assert.ok(gaps.gaps.includes(key))

const completeCase={title:'Test',goal:'Ziel',summary:'Sachstand',deadline_at:'2026-09-10',next_action:'Prüfen'}
const ideal=analyzeCaseConsistency({caseItem:completeCase,documents:[{title:'D1',extracted_text:'Vollständiger Inhalt'}],assessments:[{title:'Grundlage',traffic_light:'green',next_step:'Abschließen'}]})
assert.equal(ideal.score,100)
assert.equal(ideal.readableCount,1)

const mediumDocuments=Array.from({length:12},(_,index)=>({title:`D${index+1}`,extracted_text:index===11?'':`Dokument ${index+1}`}))
const medium=analyzeCaseConsistency({caseItem:{},documents:mediumDocuments,assessments:[{id:'r1',title:'Forderung',traffic_light:'red',next_step:''}]})
const largeDocuments=Array.from({length:30},(_,index)=>({title:`D${index+1}`,extracted_text:index>=26?'':`Dokument ${index+1}`}))
const largeAssessments=Array.from({length:30},(_,index)=>({id:`a${index+1}`,title:index<10?'Forderung':index<20?'Fristen':'Verantwortlichkeit',traffic_light:index<19?'red':index<25?'yellow':'green',next_step:index<19?'':'Prüfen'}))
const large=analyzeCaseConsistency({caseItem:{},documents:largeDocuments,assessments:largeAssessments})
assert.ok(large.score<medium.score,`large score ${large.score} must be lower than medium score ${medium.score}`)
assert.equal(large.unreadCount,4)
assert.equal(large.redCount,19)
assert.equal(large.redWithoutNextCount,19)
assert.equal(large.assessmentComplexes.length,3)
assert.deepEqual(large.assessmentComplexes.map(item=>item.title),['Forderung','Fristen','Verantwortlichkeit'])
assert.ok(large.penalties.unread>medium.penalties.unread)
assert.ok(large.penalties.unresolvedRed>medium.penalties.unresolvedRed)

const component=fs.readFileSync(new URL('../app/modules/cases/CaseCompletionPanels.js',import.meta.url),'utf8')
const adapter=fs.readFileSync(new URL('../app/modules/cases/V41CaseConsistency.js',import.meta.url),'utf8')
const layout=fs.readFileSync(new URL('../app/layout.js',import.meta.url),'utf8')
for(const language of ['de','en','fr','tr','pl','ru','ar','fa','ro','bg']) assert.match(component,new RegExp('\\b'+language+':\\{'))
assert.match(component,/Nicht automatisch als Widerspruch gewertet/)
assert.match(component,/data-v41-consistency=\"direct\"/)
assert.match(component,/analyzeCaseConsistency/)
assert.match(component,/\{result\.readableCount\}\/\{result\.documentCount\}/)
assert.match(component,/result\.redWithoutNextCount/)
assert.match(component,/result\.assessmentComplexes/)
assert.doesNotMatch(component,/createClient|from\('documents'\)|from\('assessments'\)|MutationObserver|querySelector/)
assert.match(adapter,/CaseCompletionPanels/)
assert.doesNotMatch(layout,/V41CaseConsistency/)
console.log('V80 case consistency guard passed against canonical engine and direct React panels.')
