import assert from 'node:assert/strict'
import fs from 'node:fs'
const component=fs.readFileSync(new URL('../app/modules/cases/CaseCompletionPanels.js',import.meta.url),'utf8')
const caseDetail=fs.readFileSync(new URL('../app/modules/cases/V24Workspace.js',import.meta.url),'utf8')
for(const language of ['de','en','fr','tr','pl','ru','ar','fa','ro','bg']) assert.match(component,new RegExp(`\\b${language}:\\{`))
assert.match(component,/Jetzt erledigen/)
assert.match(component,/data-v42-task/)
assert.match(component,/ActionableGapsPanel/)
assert.match(component,/Fall bearbeiten/)
assert.match(component,/Dokument hinzufügen/)
assert.match(component,/Dokument prüfen/)
assert.match(component,/Bewertung ergänzen/)
assert.match(component,/Abweichung prüfen/)
assert.match(caseDetail,/CaseCompletionPanels/)
console.log('V42 actionable gaps guard passed: the active modular case detail turns detected gaps into concrete navigation tasks in all 10 languages.')
