import fs from 'node:fs'

const workspacePath='app/modules/workspace/WorkspaceApp.js'
let source=fs.readFileSync(workspacePath,'utf8')

function ensureImport(anchor,line){
  if(source.includes(line)) return
  if(!source.includes(anchor)) throw new Error(`import anchor missing: ${anchor}`)
  source=source.replace(anchor,`${anchor}\n${line}`)
}

function replaceExact(oldText,newText,label){
  if(source.includes(newText)) return
  if(!source.includes(oldText)) throw new Error(`replacement anchor missing: ${label}`)
  source=source.replace(oldText,newText)
}

function replaceFunction(startName,nextName,replacement){
  const start=`  async function ${startName}`
  const startIndex=source.indexOf(start)
  const nextCandidates=[
    source.indexOf(`\n  async function ${nextName}`,startIndex),
    source.indexOf(`\n  function ${nextName}`,startIndex)
  ].filter(index=>index>=0)
  const nextIndex=nextCandidates.length?Math.min(...nextCandidates):-1
  if(startIndex<0||nextIndex<0) throw new Error(`Could not isolate ${startName}`)
  source=source.slice(0,startIndex)+replacement+source.slice(nextIndex)
}

fs.writeFileSync('app/modules/services/pricingRepository.js',`export async function getUpgradeQuotes(supabase,{upgrades,termMonths,promoCode=''}){\n  const pairs=await Promise.all(upgrades.map(async upgrade=>{\n    const args={p_to_plan:upgrade.plan_key,p_term_months:termMonths}\n    if(promoCode)args.p_promo_code=promoCode\n    const {data,error}=await supabase.rpc('gold_upgrade_quote',args)\n    return [upgrade.plan_key,error?null:data]\n  }))\n  return Object.fromEntries(pairs)\n}\n\nexport function requestUpgradeRecord(supabase,{planKey,termMonths,promoCode=''}){\n  const args={p_to_plan:planKey,p_term_months:termMonths}\n  if(promoCode)args.p_promo_code=promoCode\n  return supabase.rpc('gold_request_upgrade',args)\n}\n`)

fs.writeFileSync('app/modules/services/complianceRepository.js',`export function acknowledgeLegalSettings(supabase,{ownerId,privacyNoticeVersion,termsVersion}){\n  const now=new Date().toISOString()\n  const payload={owner_id:ownerId,privacy_notice_version:privacyNoticeVersion,privacy_notice_acknowledged_at:now,terms_version:termsVersion,terms_acknowledged_at:now,real_data_authorized:false,ai_processing_enabled:false,special_categories_authorized:false,retention_days:90}\n  return supabase.from('account_privacy_settings').upsert(payload,{onConflict:'owner_id'}).select().single()\n}\n\nexport async function authorizeDocumentAnalysis(supabase,{ownerId,documentId,privacyNoticeVersion,termsVersion}){\n  const enabled=await supabase.from('account_privacy_settings').update({ai_processing_enabled:true,updated_at:new Date().toISOString()}).eq('owner_id',ownerId).eq('privacy_notice_version',privacyNoticeVersion).eq('terms_version',termsVersion).select().single()\n  if(enabled.error)return {privacy:null,document:null,error:enabled.error}\n  const allowed=await supabase.from('documents').update({ai_processing_allowed:true,privacy_notice_version:privacyNoticeVersion,ai_notice_version:privacyNoticeVersion,updated_at:new Date().toISOString()}).eq('id',documentId).eq('owner_id',ownerId).in('data_classification',['synthetic','anonymized']).select().single()\n  if(allowed.error)return {privacy:enabled.data,document:null,error:allowed.error}\n  return {privacy:enabled.data,document:allowed.data,error:null}\n}\n`)

fs.writeFileSync('app/modules/services/documentRepository.js',`export function updateDocumentRecord(supabase,{ownerId,documentId,draft}){\n  const payload={title:String(draft.title||'').trim(),case_id:draft.case_id||null,document_type:String(draft.document_type||'').trim()||null,document_date:draft.document_date||null,extracted_text:String(draft.extracted_text||'').trim()||null,analysis_summary:String(draft.analysis_summary||'').trim()||null,analysis_next_step:String(draft.analysis_next_step||'').trim()||null,updated_at:new Date().toISOString()}\n  return supabase.from('documents').update(payload).eq('id',documentId).eq('owner_id',ownerId).select().single()\n}\n\nexport async function uploadWorkspaceDocument(supabase,{ownerId,file,caseId,dataClassification,privacyNoticeVersion,documentType,documentDate,source}){\n  const extension=file.name.includes('.')?file.name.split('.').pop().toLowerCase():''\n  const path=\`${'${ownerId}'}/\${Date.now()}-\${file.name.replace(/[^a-zA-Z0-9._-]/g,'_')}\`\n  const upload=await supabase.storage.from('goldstandard-private').upload(path,file,{upsert:false})\n  if(upload.error)return {data:null,error:upload.error}\n  let extractedText=null\n  if(['txt','csv'].includes(extension)&&file.size<=2*1024*1024){\n    try{extractedText=(await file.text()).trim()||null}catch{extractedText=null}\n  }\n  const insert=await supabase.from('documents').insert({owner_id:ownerId,title:file.name,file_path:path,case_id:caseId,document_type:documentType||extension.toUpperCase(),document_date:documentDate||null,source:source||'upload',extracted_text:extractedText,data_classification:dataClassification,privacy_notice_version:privacyNoticeVersion,ai_processing_allowed:false}).select().single()\n  if(insert.error){await supabase.storage.from('goldstandard-private').remove([path]);return {data:null,error:insert.error}}\n  return {data:insert.data,error:null}\n}\n\nexport function createWorkspaceDocumentSignedUrl(supabase,filePath,expiresIn=300){\n  return supabase.storage.from('goldstandard-private').createSignedUrl(filePath,expiresIn)\n}\n\nexport function recordExportEntry(supabase,{ref,type}){\n  return supabase.from('exports').insert({case_id:ref.kind==='case'?ref.item.id:ref.item.case_id||null,document_id:ref.kind==='document'?ref.item.id:null,export_type:type,title:\`${'${ref.item.title||\'AS Workspace Gold Export\'}'} (\${type.toUpperCase()})\`,status:'ready'})\n}\n`)

fs.writeFileSync('app/modules/services/approvalRepository.js',`export function createApprovalRecord(supabase,{ownerId,draft,linkedDocument}){\n  const payload={owner_id:ownerId,case_id:draft.case_id,document_id:draft.document_id||null,approval_type:draft.approval_type,status:'pending',recipient:draft.recipient.trim()||null,subject:draft.subject.trim(),body:draft.body.trim(),attachment_names:linkedDocument?[linkedDocument.title]:[],preview_required:true}\n  return supabase.from('approvals').insert(payload).select().single()\n}\n\nexport async function updateApprovalRecord(supabase,{ownerId,approvalId,current,draft}){\n  const next={recipient:draft.recipient.trim()||null,subject:draft.subject.trim(),body:draft.body.trim()}\n  const contentChanged=(current.recipient||null)!==next.recipient||(current.subject||'')!==next.subject||(current.body||'')!==next.body\n  const payload={...next}\n  if(contentChanged&&current.status==='rejected')Object.assign(payload,{status:'pending',approved_at:null,approved_revision:null})\n  const result=await supabase.from('approvals').update(payload).eq('id',approvalId).eq('owner_id',ownerId).eq('preview_revision',current.preview_revision).select().maybeSingle()\n  const invalidated=!!result.data&&current.status==='approved'&&result.data.status==='pending'\n  return {data:result.data||null,error:result.error||null,invalidated}\n}\n\nexport function approveApprovalRecord(supabase,{ownerId,item}){\n  return supabase.from('approvals').update({status:'approved',approved_at:new Date().toISOString(),approved_revision:item.preview_revision,invalidated_at:null}).eq('id',item.id).eq('owner_id',ownerId).eq('status','pending').eq('preview_revision',item.preview_revision).select().maybeSingle()\n}\n\nexport function rejectApprovalRecord(supabase,{ownerId,item}){\n  return supabase.from('approvals').update({status:'rejected',approved_at:null,approved_revision:null}).eq('id',item.id).eq('owner_id',ownerId).eq('status','pending').eq('preview_revision',item.preview_revision).select().maybeSingle()\n}\n`)

const repoImport="import { cancelDeletionRecord, createAssessmentRecord, createCaseRecord, createClientRecord, ensureRegistrationPrivacy, getWorkspaceAccess, listDeletionRequests, loadWorkspaceBundle, recordAuditEvent, requestDeletionRecord, updateCaseRecord } from '../services/workspaceRepository'"
ensureImport(repoImport,"import { getUpgradeQuotes, requestUpgradeRecord } from '../services/pricingRepository'")
ensureImport("import { getUpgradeQuotes, requestUpgradeRecord } from '../services/pricingRepository'","import { acknowledgeLegalSettings, authorizeDocumentAnalysis } from '../services/complianceRepository'")
ensureImport("import { acknowledgeLegalSettings, authorizeDocumentAnalysis } from '../services/complianceRepository'","import { createWorkspaceDocumentSignedUrl, recordExportEntry, updateDocumentRecord, uploadWorkspaceDocument } from '../services/documentRepository'")
ensureImport("import { createWorkspaceDocumentSignedUrl, recordExportEntry, updateDocumentRecord, uploadWorkspaceDocument } from '../services/documentRepository'","import { approveApprovalRecord, createApprovalRecord, rejectApprovalRecord, updateApprovalRecord } from '../services/approvalRepository'")

replaceExact(`  useEffect(()=>{\n    if(screen!=='app' || !upgrades.length) return\n    let cancelled=false\n    ;(async()=>{\n      setQuoteLoading(true)\n      const pairs = await Promise.all(upgrades.map(async u=>{\n        const args={p_to_plan:u.plan_key,p_term_months:termMonths}\n        if(appliedPromoCode) args.p_promo_code=appliedPromoCode\n        const {data,error}=await supabase.rpc('gold_upgrade_quote',args)\n        return [u.plan_key,error?null:data]\n      }))\n      if(!cancelled){ setQuotes(Object.fromEntries(pairs)); setQuoteLoading(false) }\n    })()\n    return ()=>{cancelled=true}\n  },[screen,termMonths,upgrades.length,appliedPromoCode,promoRevision])`,`  useEffect(()=>{\n    if(screen!=='app' || !upgrades.length) return\n    let cancelled=false\n    ;(async()=>{\n      setQuoteLoading(true)\n      const nextQuotes=await getUpgradeQuotes(supabase,{upgrades,termMonths,promoCode:appliedPromoCode})\n      if(!cancelled){ setQuotes(nextQuotes); setQuoteLoading(false) }\n    })()\n    return ()=>{cancelled=true}\n  },[screen,termMonths,upgrades.length,appliedPromoCode,promoRevision])`,'upgrade quote effect')

replaceFunction('acknowledgeCurrentLegal','signIn',`  async function acknowledgeCurrentLegal(){\n    if(!user?.id||privacyBusy) return false\n    setPrivacyBusy(true);setMessage('')\n    const {data:stored,error}=await acknowledgeLegalSettings(supabase,{ownerId:user.id,privacyNoticeVersion:PRIVACY_NOTICE_VERSION,termsVersion:TERMS_VERSION})\n    if(error){setPrivacyBusy(false);setMessage(error.message);return false}\n    setPrivacySettings(stored)\n    await recordServerAudit('legal_notices_acknowledged',{},'account',null)\n    setPrivacyBusy(false);setMessage(v28.saved)\n    return true\n  }\n`)

replaceFunction('requestUpgrade','createClient',`  async function requestUpgrade(plan){\n    setMessage('')\n    const selectedQuote=quotes[plan.plan_key]\n    if(appliedPromoCode&&selectedQuote?.promo_code_state!=='valid') return setMessage(promo.invalid)\n    const {data,error}=await requestUpgradeRecord(supabase,{planKey:plan.plan_key,termMonths,promoCode:appliedPromoCode})\n    if(error) return setMessage(appliedPromoCode?promo.invalid:error.message)\n    await recordServerAudit('upgrade_requested',{plan_key:plan.plan_key,term_months:Number(termMonths),promo_applied:data?.promo_code_state==='valid'},'account',null)\n    setMessage(\`${'${n.upgradeReserved} ${n.selected}: ${data?.to_plan_name || plan.plan_name}, ${termMonths} ${termMonths===1?n.monthOne:n.monthMany}.'}\`)\n  }\n`)

replaceExact(`    const enabled=await supabase.from('account_privacy_settings').update({ai_processing_enabled:true,updated_at:new Date().toISOString()}).eq('owner_id',user.id).eq('privacy_notice_version',PRIVACY_NOTICE_VERSION).eq('terms_version',TERMS_VERSION).select().single()\n    if(enabled.error){setMessage(enabled.error.message);return false}\n    const allowed=await supabase.from('documents').update({ai_processing_allowed:true,privacy_notice_version:PRIVACY_NOTICE_VERSION,ai_notice_version:PRIVACY_NOTICE_VERSION,updated_at:new Date().toISOString()}).eq('id',document.id).eq('owner_id',user.id).in('data_classification',['synthetic','anonymized']).select().single()\n    if(allowed.error){setMessage(allowed.error.message);return false}\n    setPrivacySettings(enabled.data)`,`    const authorization=await authorizeDocumentAnalysis(supabase,{ownerId:user.id,documentId:document.id,privacyNoticeVersion:PRIVACY_NOTICE_VERSION,termsVersion:TERMS_VERSION})\n    if(authorization.error){setMessage(authorization.error.message);return false}\n    setPrivacySettings(authorization.privacy)`,'document AI authorization')

replaceFunction('updateDocument','createApproval',`  async function updateDocument(documentId,draft){\n    setMessage('')\n    const {data:updated,error}=await updateDocumentRecord(supabase,{ownerId:user.id,documentId,draft})\n    if(error){setMessage(error.message);return false}\n    const eventType=draft.analysis_generated?'document_analysis_saved':'document_reviewed'\n    recordLocalAction(eventType)\n    const auditSaved=await recordServerAudit(eventType,{status:'saved'},'document',updated.id)\n    setData(previous=>({...previous,documents:previous.documents.map(item=>item.id===updated.id?updated:item)})); setSelectedDocument(updated)\n    setMessage(auditSaved?(draft.analysis_generated?analysisUi.savedMessage:\`${'${core.documentReview} ✓'}\`):sct.auditFailed)\n    return true\n  }\n`)

replaceFunction('createApproval','updateApproval',`  async function createApproval(draft){\n    setMessage('')\n    if(!draft.case_id){setMessage(approvalUi.caseRequired);return false}\n    if(!draft.subject.trim()||!draft.body.trim()){setMessage(approvalUi.contentRequired);return false}\n    if(draft.approval_type==='send'&&!draft.recipient.trim()){setMessage(approvalUi.recipientRequired);return false}\n    const linkedDocument=draft.document_id?data.documents.find(item=>item.id===draft.document_id):null\n    if(linkedDocument?.case_id!==draft.case_id&&draft.document_id){setMessage(approvalUi.documentMismatch);return false}\n    const {data:created,error}=await createApprovalRecord(supabase,{ownerId:user.id,draft,linkedDocument})\n    if(error){setMessage(error.message);return false}\n    recordLocalAction('approval_created')\n    await recordServerAudit('approval_created',{revision:Number(created.preview_revision)},'approval',created.id)\n    setData(previous=>({...previous,approvals:[created,...previous.approvals]}))\n    setApprovalDefaults({caseId:'',documentId:''})\n    setSelectedApproval(created)\n    setMessage(approvalUi.created)\n    return created\n  }\n`)

replaceFunction('updateApproval','approveApproval',`  async function updateApproval(approvalId,draft){\n    setMessage('')\n    const current=data.approvals.find(item=>item.id===approvalId)\n    if(!current) return false\n    if(!draft.subject.trim()||!draft.body.trim()){setMessage(approvalUi.contentRequired);return false}\n    if(current.approval_type==='send'&&!draft.recipient.trim()){setMessage(approvalUi.recipientRequired);return false}\n    const {data:updated,error,invalidated}=await updateApprovalRecord(supabase,{ownerId:user.id,approvalId,current,draft})\n    if(error){setMessage(error.message);return false}\n    if(!updated){setMessage(approvalUi.stale);return false}\n    recordLocalAction(invalidated?'approval_invalidated':'approval_updated')\n    await recordServerAudit(invalidated?'approval_invalidated':'approval_updated',{revision:Number(updated.preview_revision)},'approval',updated.id)\n    setData(previous=>({...previous,approvals:previous.approvals.map(item=>item.id===updated.id?updated:item)}))\n    setSelectedApproval(updated)\n    setMessage(approvalUi.saved)\n    return updated\n  }\n`)

replaceFunction('approveApproval','rejectApproval',`  async function approveApproval(item){\n    setMessage('')\n    const {data:updated,error}=await approveApprovalRecord(supabase,{ownerId:user.id,item})\n    if(error){setMessage(error.message);return false}\n    if(!updated){setMessage(approvalUi.stale);return false}\n    recordLocalAction('approval_approved')\n    await recordServerAudit('approval_approved',{revision:Number(updated.approved_revision)},'approval',updated.id)\n    setData(previous=>({...previous,approvals:previous.approvals.map(entry=>entry.id===updated.id?updated:entry)}))\n    setSelectedApproval(updated)\n    setMessage(approvalUi.approvedMessage)\n    return updated\n  }\n`)

replaceFunction('rejectApproval','uploadDocument',`  async function rejectApproval(item){\n    setMessage('')\n    const {data:updated,error}=await rejectApprovalRecord(supabase,{ownerId:user.id,item})\n    if(error){setMessage(error.message);return false}\n    if(!updated){setMessage(approvalUi.stale);return false}\n    recordLocalAction('approval_rejected')\n    await recordServerAudit('approval_rejected',{revision:Number(updated.preview_revision)},'approval',updated.id)\n    setData(previous=>({...previous,approvals:previous.approvals.map(entry=>entry.id===updated.id?updated:entry)}))\n    setSelectedApproval(updated)\n    setMessage(approvalUi.rejectedMessage)\n    return updated\n  }\n  function prepareDocumentApproval(document){\n    setSelectedDocument(null);setSelectedCase(null);setSelectedApproval(null)\n    setApprovalDefaults({caseId:document.case_id||'',documentId:document.id})\n    setSection('approvals')\n  }\n`)

replaceFunction('uploadDocument','openDocument',`  async function uploadDocument(e){\n    e.preventDefault(); setMessage('')\n    const form=e.currentTarget\n    const file=form.elements.file.files[0], caseId=form.elements.case_id.value||null\n    if(!file) return setMessage(n.chooseFile)\n    const dataClassification=form.elements.data_classification?.value\n    const testDataConfirmed=!!form.elements.test_data_confirmed?.checked\n    if(!['synthetic','anonymized'].includes(dataClassification)||!testDataConfirmed) return setMessage(v28.uploadRequired)\n    if(!privacyCurrent) return setMessage(v28.required)\n    const extension=file.name.includes('.')?file.name.split('.').pop().toLowerCase():''\n    if(!allowedUploadExtensions.has(extension)) return setMessage(uui.unsupported)\n    if(file.size>maxUploadBytes) return setMessage(uui.tooLarge)\n    const limit=Number(access?.permissions?.document_limit||0)\n    if(access?.app_role!=='owner' && limit>0 && data.documents.length>=limit) return setMessage(n.docLimit.replace('{limit}',limit))\n    setUploading(true)\n    const {data:created,error}=await uploadWorkspaceDocument(supabase,{ownerId:user.id,file,caseId,dataClassification,privacyNoticeVersion:PRIVACY_NOTICE_VERSION,documentType:form.elements.document_type?.value.trim()||extension.toUpperCase(),documentDate:form.elements.document_date?.value||null,source:form.elements.source?.value||'upload'})\n    if(error){setUploading(false);return setMessage(error.message)}\n    recordLocalAction('document_uploaded'); await recordServerAudit('document_uploaded',{classification:dataClassification},'document',created.id); setData(previous=>({...previous,documents:[created,...previous.documents]})); setUploading(false); form.reset(); setSection('documents'); setSelectedDocument(created)\n  }\n`)

replaceFunction('openDocument','canExport',`  async function openDocument(doc){\n    if(!doc.file_path) return\n    const {data:signed,error}=await createWorkspaceDocumentSignedUrl(supabase,doc.file_path,300)\n    if(error) return setMessage(error.message)\n    recordLocalAction('document_opened'); await recordServerAudit('document_opened',{},'document',doc.id); window.open(signed.signedUrl,'_blank','noopener')\n  }\n`)

replaceExact(`      const {error:exportLogError}=await supabase.from('exports').insert({case_id:ref.kind==='case'?ref.item.id:ref.item.case_id||null,document_id:ref.kind==='document'?ref.item.id:null,export_type:type,title:\`${'${ref.item.title||\'AS Workspace Gold Export\'}'} (\${type.toUpperCase()})\`,status:'ready'})`,`      const {error:exportLogError}=await recordExportEntry(supabase,{ref,type})`,'export log')

fs.writeFileSync(workspacePath,source)

const guardPath='scripts/test_v46_modular_boundaries.mjs'
let guard=fs.readFileSync(guardPath,'utf8')
const marker="console.log('V46 transactional service boundaries verified.')"
if(!guard.includes(marker)){
  guard += `\nfor(const path of ['app/modules/services/pricingRepository.js','app/modules/services/complianceRepository.js','app/modules/services/documentRepository.js','app/modules/services/approvalRepository.js']) exists(path)\nassert.match(workspace,/pricingRepository/)\nassert.match(workspace,/complianceRepository/)\nassert.match(workspace,/documentRepository/)\nassert.match(workspace,/approvalRepository/)\nfor(const legacyCall of [\"supabase.rpc('gold_upgrade_quote'\",\"supabase.rpc('gold_request_upgrade'\",\"supabase.from('approvals')\",\"supabase.from('documents').update\",\"supabase.from('account_privacy_settings').upsert\",\"supabase.storage.from('goldstandard-private').upload\",\"supabase.from('exports').insert\"]) assert.ok(!workspace.includes(legacyCall),\`workspace controller must not own low-level transaction: \${legacyCall}\`)\nconsole.log('V46 transactional service boundaries verified.')\n`
  fs.writeFileSync(guardPath,guard)
}

const readmePath='app/modules/README.md'
let readme=fs.readFileSync(readmePath,'utf8')
const note='- `services/`: transactional pricing, compliance, approval and document storage/database operations are now isolated behind repository/service boundaries; WorkspaceApp retains workflow state and user-facing validation only.'
if(!readme.includes(note)){
  readme += `\n${note}\n`
  fs.writeFileSync(readmePath,readme)
}

console.log('V46 transactional service extraction applied')
