import fs from 'node:fs'

const layoutPath='app/layout.js'
const casePath='app/modules/cases/V24Workspace.js'
const completionPath='app/modules/cases/CaseCompletionPanels.js'
const guardPath='scripts/test_v46_modular_boundaries.mjs'
const docsPath='docs/APP_GOLD_MODULARISIERUNG_V46.md'

let layout=fs.readFileSync(layoutPath,'utf8')
for(const line of [
  "import { V40ProfessionalHandoff } from './modules/cases/V40ProfessionalHandoff'\n",
  "import { V41CaseConsistency } from './modules/cases/V41CaseConsistency'\n",
  "import { V42ActionableGaps } from './modules/cases/V42ActionableGaps'\n"
]) layout=layout.replace(line,'')
layout=layout.replace('<AccessibilityHardening/><MobileResilience/><V40ProfessionalHandoff/><V41CaseConsistency/><V42ActionableGaps/>{children}','<AccessibilityHardening/><MobileResilience/>{children}')
fs.writeFileSync(layoutPath,layout)

let cases=fs.readFileSync(casePath,'utf8')
const importAnchor="import { CaseTimeline, DocumentAutoAssessment } from './V39CaseTimelineAutoAssessment'"
if(!cases.includes("import { CaseCompletionPanels } from './CaseCompletionPanels'")){
  if(!cases.includes(importAnchor)) throw new Error('V46 direct case completion: V39 import anchor missing')
  cases=cases.replace(importAnchor,`${importAnchor}\nimport { CaseCompletionPanels } from './CaseCompletionPanels'`)
}
const timeline="    <CaseTimeline language={language} caseDeadline={item.deadline_at||''} documents={documents}/>"
if(!cases.includes('<CaseCompletionPanels ')){
  if(!cases.includes(timeline)) throw new Error('V46 direct case completion: CaseTimeline anchor missing')
  cases=cases.replace(timeline,`${timeline}\n    <CaseCompletionPanels language={language} item={item} documents={documents} assessments={assessments} onEdit={()=>setEditing(true)} onAddDocument={()=>onAddDocument(item.id)} onOpenDocument={onOpenDocument} onAssess={()=>setAssessment(current=>({...current,title:current.title||on.addAssessment}))}/>`)
}
fs.writeFileSync(casePath,cases)

fs.writeFileSync('app/modules/cases/V40ProfessionalHandoff.js',"export { ProfessionalHandoffPanel, V40ProfessionalHandoff } from './CaseCompletionPanels'\n")
fs.writeFileSync('app/modules/cases/V41CaseConsistency.js',"export { CaseConsistencyPanel, V41CaseConsistency } from './CaseCompletionPanels'\n")
fs.writeFileSync('app/modules/cases/V42ActionableGaps.js',"export { ActionableGapsPanel, V42ActionableGaps } from './CaseCompletionPanels'\n")

fs.writeFileSync('scripts/test_v40_professional_handoff.mjs',`import assert from 'node:assert/strict'\nimport fs from 'node:fs'\nimport {buildProfessionalHandoff,handoffPriority} from '../app/modules/lib/v40ProfessionalHandoff.mjs'\n\nconst full=buildProfessionalHandoff({title:'Testfall',goal:'Zahlung',summary:'Sachstand',deadline:'03.09.2026',nextAction:'Antworten',documents:[{title:'Schreiben',date:'2026-09-01'}],assessments:[{trafficLight:'red',title:'Frist',reasoning:'kurz',nextStep:'prüfen'}],timeline:[{date:'2026-09-03',title:'Frist'},{date:'2026-09-01',title:'Schreiben'}]})\nassert.equal(full.ready,true)\nassert.equal(full.timeline[0].date,'2026-09-01')\nassert.equal(handoffPriority(full.assessments),'red')\nconst incomplete=buildProfessionalHandoff({summary:'Nur Sachstand'})\nassert.equal(incomplete.ready,false)\nassert.ok(incomplete.missing.includes('documents'))\nassert.ok(incomplete.missing.includes('assessments'))\n\nconst component=fs.readFileSync(new URL('../app/modules/cases/CaseCompletionPanels.js',import.meta.url),'utf8')\nconst adapter=fs.readFileSync(new URL('../app/modules/cases/V40ProfessionalHandoff.js',import.meta.url),'utf8')\nconst compatibility=fs.readFileSync(new URL('../app/components/V40ProfessionalHandoff.js',import.meta.url),'utf8')\nconst layout=fs.readFileSync(new URL('../app/layout.js',import.meta.url),'utf8')\nconst caseUi=fs.readFileSync(new URL('../app/modules/cases/V24Workspace.js',import.meta.url),'utf8')\nfor(const language of ['de','en','fr','tr','pl','ru','ar','fa','ro','bg']) assert.match(component,new RegExp('\\\\b'+language+':\\\\{'))\nassert.match(component,/Professionelle Übergabe/)\nassert.match(component,/data-v40-handoff=\\"direct\\"/)\nassert.match(component,/jspdf/)\nassert.match(component,/docx/)\nassert.match(component,/Keine zusätzliche Datenübermittlung/)\nassert.doesNotMatch(component,/MutationObserver|querySelector/)\nassert.match(adapter,/CaseCompletionPanels/)\nassert.match(compatibility,/modules\\/cases\\/V40ProfessionalHandoff/)\nassert.doesNotMatch(layout,/V40ProfessionalHandoff/)\nassert.match(caseUi,/CaseCompletionPanels/)\nconsole.log('V40 professional handoff guard passed: direct React handoff, local PDF/DOCX export and 10-language UI verified without a global DOM enhancer.')\n`)

fs.writeFileSync('scripts/test_v41_case_consistency.mjs',`import assert from 'node:assert/strict'\nimport fs from 'node:fs'\nimport { analyzeCaseConsistency } from '../app/modules/lib/v41CaseConsistency.mjs'\n\nconst result=analyzeCaseConsistency({caseItem:{title:'Test',goal:'Zahlung prüfen',summary:'Zwei Schreiben liegen vor',deadline_at:'2026-09-10',next_action:'Antwort vorbereiten'},documents:[{title:'Schreiben A',extracted_text:'Die Forderung beträgt 1.000,00 EUR. Zahlung bis 10.09.2026.'},{title:'Schreiben B',extracted_text:'Die Forderung beträgt 1.250,00 EUR. Zahlung bis 12.09.2026.'}],assessments:[{traffic_light:'yellow',next_step:'Beträge prüfen'}]})\nassert.equal(result.gaps.length,0)\nassert.ok(result.deviations.some(x=>x.concept==='forderung'&&x.type==='amount'))\nassert.ok(result.deviations.some(x=>x.concept==='zahlung'&&x.type==='date'))\nassert.ok(result.score<100)\nconst gaps=analyzeCaseConsistency({caseItem:{},documents:[{title:'X',extracted_text:''}],assessments:[{traffic_light:'red',next_step:''}]})\nfor(const key of ['goal','summary','deadline','next_action','unread_documents','red_without_next']) assert.ok(gaps.gaps.includes(key))\n\nconst component=fs.readFileSync(new URL('../app/modules/cases/CaseCompletionPanels.js',import.meta.url),'utf8')\nconst adapter=fs.readFileSync(new URL('../app/modules/cases/V41CaseConsistency.js',import.meta.url),'utf8')\nconst layout=fs.readFileSync(new URL('../app/layout.js',import.meta.url),'utf8')\nfor(const language of ['de','en','fr','tr','pl','ru','ar','fa','ro','bg']) assert.match(component,new RegExp('\\\\b'+language+':\\\\{'))\nassert.match(component,/Nicht automatisch als Widerspruch gewertet/)\nassert.match(component,/data-v41-consistency=\\"direct\\"/)\nassert.match(component,/analyzeCaseConsistency/)\nassert.doesNotMatch(component,/createClient|from\\('documents'\\)|from\\('assessments'\\)|MutationObserver|querySelector/)\nassert.match(adapter,/CaseCompletionPanels/)\nassert.doesNotMatch(layout,/V41CaseConsistency/)\nconsole.log('V41 case consistency guard passed: direct React evidence gaps and cautious deviations use existing case data without duplicate Supabase queries or DOM polling.')\n`)

fs.writeFileSync('scripts/test_v42_actionable_gaps.mjs',`import assert from 'node:assert/strict'\nimport fs from 'node:fs'\nconst component=fs.readFileSync(new URL('../app/modules/cases/CaseCompletionPanels.js',import.meta.url),'utf8')\nconst adapter=fs.readFileSync(new URL('../app/modules/cases/V42ActionableGaps.js',import.meta.url),'utf8')\nconst layout=fs.readFileSync(new URL('../app/layout.js',import.meta.url),'utf8')\nconst caseUi=fs.readFileSync(new URL('../app/modules/cases/V24Workspace.js',import.meta.url),'utf8')\nfor(const language of ['de','en','fr','tr','pl','ru','ar','fa','ro','bg']) assert.match(component,new RegExp('\\\\b'+language+':\\\\{'))\nassert.match(component,/Jetzt erledigen/)\nassert.match(component,/data-v42-task/)\nassert.match(component,/Fall bearbeiten/)\nassert.match(component,/Dokument hinzufügen/)\nassert.match(component,/Dokument prüfen/)\nassert.match(component,/Bewertung ergänzen/)\nassert.match(component,/Abweichung prüfen/)\nassert.doesNotMatch(component,/MutationObserver|querySelectorAll|addEventListener\\('click'/)\nassert.match(adapter,/CaseCompletionPanels/)\nassert.doesNotMatch(layout,/V42ActionableGaps/)\nassert.match(caseUi,/onEdit=\\{\\(\\)=>setEditing\\(true\\)\\}/)\nassert.match(caseUi,/onAddDocument=\\{\\(\\)=>onAddDocument\\(item.id\\)\\}/)\nconsole.log('V42 actionable gaps guard passed: detected gaps render as direct React actions with explicit callbacks and no global DOM click routing.')\n`)

let guard=fs.readFileSync(guardPath,'utf8')
const block=`\nconst caseCompletionPanels=read('app/modules/cases/CaseCompletionPanels.js')\nassert.match(read('app/modules/cases/V24Workspace.js'),/CaseCompletionPanels/)\nassert.doesNotMatch(read('app/layout.js'),/V40ProfessionalHandoff|V41CaseConsistency|V42ActionableGaps/,'V40-V42 must not be mounted globally')\nassert.doesNotMatch(caseCompletionPanels,/MutationObserver|querySelector/,'direct V40-V42 panels must not patch rendered DOM')\nassert.doesNotMatch(caseCompletionPanels,/createClient|from\\('documents'\\)|from\\('assessments'\\)/,'case consistency must consume existing case data')\nassert.match(caseCompletionPanels,/data-v40-handoff="direct"/)\nassert.match(caseCompletionPanels,/data-v41-consistency="direct"/)\nassert.match(caseCompletionPanels,/data-v42-actions="direct"/)\nconsole.log('V46 direct V40-V42 case-completion boundary verified.')\n`
if(!guard.includes('V46 direct V40-V42 case-completion boundary verified.')) guard += block
fs.writeFileSync(guardPath,guard)

let docs=fs.readFileSync(docsPath,'utf8')
const note=`\n\n### V46 Direkte Fall-Abschlussmodule V40–V42\n\n- Professionelle Übergabe, Fall-Konsistenz/Nachweise und konkrete Lücken-Aufgaben werden direkt in CaseDetail gerendert.\n- Die drei globalen Komponenten V40ProfessionalHandoff, V41CaseConsistency und V42ActionableGaps sind aus app/layout.js entfernt.\n- V41 verwendet die bereits geladenen Fall-, Dokument- und Bewertungsdaten und erzeugt keine zweite Supabase-Abfrage mehr.\n- V42 erhält explizite React-Callbacks für Fallbearbeitung, Dokumentupload, Dokumentprüfung und Bewertung statt querySelector-/Click-Weiterleitung.\n- V40 behält lokale PDF-/DOCX-Exporte, ohne MutationObserver oder nachträgliche UI-Montage.\n- Die alten Modulpfade bleiben nur als dünne Kompatibilitäts-Re-Exports erhalten.\n`
if(!docs.includes('### V46 Direkte Fall-Abschlussmodule V40–V42')) docs += note
fs.writeFileSync(docsPath,docs)

console.log('V46 direct case-completion migration prepared: V40-V42 are direct React panels with explicit data and callbacks.')
