'use client'

import { useMemo, useState } from 'react'
import { buildProfessionalHandoff, handoffPriority } from '../lib/v40ProfessionalHandoff.mjs'
import { analyzeCaseConsistency } from '../lib/v41CaseConsistency.mjs'

const labels={
  de:{handoffTitle:'Professionelle Übergabe',handoffLead:'Bereitet den aktuellen Fall strukturiert für Anwalt, Versicherung oder Berater auf. Die Datei wird lokal im Browser erstellt.',ready:'Übergabeakte vollständig vorbereitet',check:'Vor Weitergabe noch prüfen',missing:'Noch offen',pdf:'Übergabeakte PDF',docx:'Übergabeakte DOCX',privacy:'Keine zusätzliche Datenübermittlung durch den Export. Vor Weitergabe Originale, Fristen und Ampeln selbst prüfen.',goal:'Ziel',summary:'Sachstand',deadline:'Nächste Frist',next:'Nächster Schritt',documents:'Dokumente',assessments:'Bewertungen',timeline:'Timeline',generated:'Erstellt mit AS Workspace Gold · strukturierte Arbeitsunterlage, keine anwaltliche Prüfung',consistencyTitle:'Fall-Konsistenz & Nachweise',score:'Vollständigkeit',good:'Gut vorbereitet',review:'Prüfung empfohlen',attention:'Lücken schließen',gaps:'Fehlende oder offene Punkte',deviations:'Abweichende Angaben zwischen Dokumenten',deviationNote:'Nicht automatisch als Widerspruch gewertet – prüfen, ob unterschiedliche Zeiträume oder Positionen gemeint sind.',none:'Keine auffälligen Abweichungen erkannt.',gapLabels:{goal:'Ziel des Falls fehlt',summary:'Sachstand fehlt',deadline:'Keine Fallfrist hinterlegt',next_action:'Nächster Schritt fehlt',documents:'Noch keine Dokumente',unread_documents:'Dokumente ohne ausgelesenen Inhalt',assessment:'Noch keine dokumentierte Bewertung',red_without_next:'Rote Bewertung ohne nächsten Schritt'},amount:'Betrag',date:'Datum',actionsTitle:'Jetzt erledigen',actionsLead:'AS Workspace Gold macht aus offenen Punkten konkrete Aufgaben.',edit:'Fall bearbeiten',upload:'Dokument hinzufügen',reviewDoc:'Dokument prüfen',assess:'Bewertung ergänzen',followup:'Folgeaktion festlegen',deviation:'Abweichung prüfen',done:'Kein unmittelbarer Handlungsbedarf aus den erkannten Lücken.'},
  en:{handoffTitle:'Professional handoff',handoffLead:'Prepares the current case for a lawyer, insurer or adviser. The file is generated locally in your browser.',ready:'Handoff file ready',check:'Review before sharing',missing:'Still missing',pdf:'Handoff PDF',docx:'Handoff DOCX',privacy:'The export sends no additional data. Verify originals, deadlines and traffic lights before sharing.',goal:'Goal',summary:'Summary',deadline:'Next deadline',next:'Next step',documents:'Documents',assessments:'Assessments',timeline:'Timeline',generated:'Created with AS Workspace Gold · structured working file, not a lawyer review',consistencyTitle:'Case consistency & evidence',score:'Completeness',good:'Well prepared',review:'Review recommended',attention:'Close gaps',gaps:'Missing or open items',deviations:'Differing details across documents',deviationNote:'Not automatically treated as a contradiction — verify whether different periods or items are intended.',none:'No notable deviations detected.',gapLabels:{goal:'Case goal missing',summary:'Case summary missing',deadline:'No case deadline stored',next_action:'Next action missing',documents:'No documents yet',unread_documents:'Documents without extracted text',assessment:'No documented assessment yet',red_without_next:'Red assessment without next step'},amount:'Amount',date:'Date',actionsTitle:'Do next',actionsLead:'AS Workspace Gold turns open items into concrete tasks.',edit:'Edit case',upload:'Add document',reviewDoc:'Review document',assess:'Add assessment',followup:'Set follow-up action',deviation:'Review deviation',done:'No immediate action is required from the detected gaps.'},
  fr:{handoffTitle:'Transmission professionnelle',handoffLead:'Prépare le dossier pour un avocat, assureur ou conseiller. Le fichier est créé localement dans le navigateur.',ready:'Dossier de transmission prêt',check:'À vérifier avant transmission',missing:'Encore manquant',pdf:'Dossier PDF',docx:'Dossier DOCX',privacy:'Aucune transmission supplémentaire de données lors de l’export. Vérifiez les originaux, délais et feux avant partage.',goal:'Objectif',summary:'État du dossier',deadline:'Prochain délai',next:'Étape suivante',documents:'Documents',assessments:'Évaluations',timeline:'Chronologie',generated:'Créé avec AS Workspace Gold · dossier de travail structuré, sans contrôle avocat',consistencyTitle:'Cohérence du dossier et preuves',score:'Complétude',good:'Bien préparé',review:'Vérification recommandée',attention:'Compléter les lacunes',gaps:'Éléments manquants ou ouverts',deviations:'Informations divergentes entre documents',deviationNote:'Pas automatiquement considéré comme une contradiction — vérifier les périodes ou postes différents.',none:'Aucune divergence notable détectée.',gapLabels:{goal:'Objectif du dossier manquant',summary:'Résumé manquant',deadline:'Aucun délai de dossier enregistré',next_action:'Étape suivante manquante',documents:'Aucun document',unread_documents:'Documents sans texte extrait',assessment:'Aucune évaluation documentée',red_without_next:'Évaluation rouge sans étape suivante'},amount:'Montant',date:'Date',actionsTitle:'À faire maintenant',actionsLead:'AS Workspace Gold transforme les points ouverts en tâches concrètes.',edit:'Modifier le dossier',upload:'Ajouter un document',reviewDoc:'Vérifier le document',assess:'Ajouter une évaluation',followup:'Définir l’action suivante',deviation:'Vérifier l’écart',done:'Aucune action immédiate issue des lacunes détectées.'},
  tr:{handoffTitle:'Profesyonel devir',handoffLead:'Mevcut dosyayı avukat, sigorta veya danışman için yapılandırır. Dosya tarayıcıda yerel olarak oluşturulur.',ready:'Devir dosyası hazır',check:'Paylaşmadan önce kontrol edin',missing:'Eksik',pdf:'Devir PDF',docx:'Devir DOCX',privacy:'Dışa aktarma ek veri aktarmaz. Paylaşmadan önce asılları, süreleri ve değerlendirmeleri kontrol edin.',goal:'Hedef',summary:'Dosya durumu',deadline:'Sonraki süre',next:'Sonraki adım',documents:'Belgeler',assessments:'Değerlendirmeler',timeline:'Zaman çizelgesi',generated:'AS Workspace Gold ile oluşturuldu · yapılandırılmış çalışma dosyası, avukat incelemesi değildir',consistencyTitle:'Dosya tutarlılığı ve kanıtlar',score:'Tamlık',good:'İyi hazırlanmış',review:'Kontrol önerilir',attention:'Eksikleri tamamlayın',gaps:'Eksik veya açık noktalar',deviations:'Belgeler arasındaki farklı bilgiler',deviationNote:'Otomatik olarak çelişki sayılmaz — farklı dönem veya kalem olup olmadığını kontrol edin.',none:'Belirgin bir farklılık bulunmadı.',gapLabels:{goal:'Dosya hedefi eksik',summary:'Dosya özeti eksik',deadline:'Dosya süresi kayıtlı değil',next_action:'Sonraki adım eksik',documents:'Henüz belge yok',unread_documents:'Metni çıkarılmamış belgeler',assessment:'Henüz belgelenmiş değerlendirme yok',red_without_next:'Sonraki adımı olmayan kırmızı değerlendirme'},amount:'Tutar',date:'Tarih',actionsTitle:'Şimdi yapılacak',actionsLead:'AS Workspace Gold açık noktaları somut görevlere dönüştürür.',edit:'Dosyayı düzenle',upload:'Belge ekle',reviewDoc:'Belgeyi kontrol et',assess:'Değerlendirme ekle',followup:'Sonraki işlemi belirle',deviation:'Farkı kontrol et',done:'Algılanan eksiklerden kaynaklanan acil bir işlem yok.'},
  pl:{handoffTitle:'Profesjonalne przekazanie',handoffLead:'Przygotowuje sprawę dla prawnika, ubezpieczyciela lub doradcy. Plik powstaje lokalnie w przeglądarce.',ready:'Pakiet przekazania gotowy',check:'Sprawdź przed przekazaniem',missing:'Brakuje',pdf:'Pakiet PDF',docx:'Pakiet DOCX',privacy:'Eksport nie powoduje dodatkowego przesyłania danych. Sprawdź oryginały, terminy i oceny przed udostępnieniem.',goal:'Cel',summary:'Stan sprawy',deadline:'Najbliższy termin',next:'Następny krok',documents:'Dokumenty',assessments:'Oceny',timeline:'Oś czasu',generated:'Utworzono w AS Workspace Gold · uporządkowany materiał roboczy, bez weryfikacji prawnika',consistencyTitle:'Spójność sprawy i dowody',score:'Kompletność',good:'Dobrze przygotowane',review:'Zalecana kontrola',attention:'Uzupełnij braki',gaps:'Brakujące lub otwarte punkty',deviations:'Różne dane w dokumentach',deviationNote:'Nie są automatycznie uznawane za sprzeczność — sprawdź, czy dotyczą różnych okresów lub pozycji.',none:'Nie wykryto istotnych różnic.',gapLabels:{goal:'Brak celu sprawy',summary:'Brak opisu stanu sprawy',deadline:'Brak terminu sprawy',next_action:'Brak następnego kroku',documents:'Brak dokumentów',unread_documents:'Dokumenty bez odczytanej treści',assessment:'Brak udokumentowanej oceny',red_without_next:'Czerwona ocena bez następnego kroku'},amount:'Kwota',date:'Data',actionsTitle:'Co zrobić teraz',actionsLead:'AS Workspace Gold zamienia otwarte punkty w konkretne zadania.',edit:'Edytuj sprawę',upload:'Dodaj dokument',reviewDoc:'Sprawdź dokument',assess:'Dodaj ocenę',followup:'Ustal następne działanie',deviation:'Sprawdź różnicę',done:'Brak pilnych działań wynikających z wykrytych braków.'},
  ru:{handoffTitle:'Профессиональная передача',handoffLead:'Готовит дело для юриста, страховщика или консультанта. Файл создаётся локально в браузере.',ready:'Пакет готов',check:'Проверьте перед передачей',missing:'Не хватает',pdf:'Пакет PDF',docx:'Пакет DOCX',privacy:'Экспорт не передаёт дополнительные данные. Перед отправкой проверьте оригиналы, сроки и оценки.',goal:'Цель',summary:'Состояние дела',deadline:'Ближайший срок',next:'Следующий шаг',documents:'Документы',assessments:'Оценки',timeline:'Хронология',generated:'Создано с AS Workspace Gold · структурированный рабочий материал, не юридическая проверка',consistencyTitle:'Согласованность дела и доказательства',score:'Полнота',good:'Хорошо подготовлено',review:'Рекомендуется проверка',attention:'Устранить пробелы',gaps:'Недостающие или открытые пункты',deviations:'Различающиеся данные в документах',deviationNote:'Не считаются автоматически противоречием — проверьте, не относятся ли они к разным периодам или позициям.',none:'Заметных расхождений не выявлено.',gapLabels:{goal:'Нет цели дела',summary:'Нет описания дела',deadline:'Срок дела не сохранён',next_action:'Нет следующего шага',documents:'Документов пока нет',unread_documents:'Документы без извлечённого текста',assessment:'Нет документированной оценки',red_without_next:'Красная оценка без следующего шага'},amount:'Сумма',date:'Дата',actionsTitle:'Что сделать сейчас',actionsLead:'AS Workspace Gold превращает открытые пункты в конкретные задачи.',edit:'Редактировать дело',upload:'Добавить документ',reviewDoc:'Проверить документ',assess:'Добавить оценку',followup:'Указать следующее действие',deviation:'Проверить расхождение',done:'По выявленным пробелам срочных действий нет.'},
  ar:{handoffTitle:'تسليم مهني',handoffLead:'يجهّز الحالة للمحامي أو شركة التأمين أو المستشار. يتم إنشاء الملف محليًا في المتصفح.',ready:'ملف التسليم جاهز',check:'راجعه قبل المشاركة',missing:'لا يزال ناقصًا',pdf:'ملف PDF',docx:'ملف DOCX',privacy:'لا يرسل التصدير بيانات إضافية. تحقق من الأصول والمواعيد والتقييمات قبل المشاركة.',goal:'الهدف',summary:'ملخص الحالة',deadline:'المهلة التالية',next:'الخطوة التالية',documents:'المستندات',assessments:'التقييمات',timeline:'الخط الزمني',generated:'تم إنشاؤه بواسطة AS Workspace Gold · ملف عمل منظم وليس مراجعة محامٍ',consistencyTitle:'اتساق الحالة والأدلة',score:'الاكتمال',good:'معد جيدًا',review:'يوصى بالمراجعة',attention:'أكمل النواقص',gaps:'نقاط ناقصة أو مفتوحة',deviations:'بيانات مختلفة بين المستندات',deviationNote:'لا تُعد تلقائيًا تناقضًا — تحقق مما إذا كانت تخص فترات أو بنودًا مختلفة.',none:'لم يتم اكتشاف اختلافات ملحوظة.',gapLabels:{goal:'هدف الحالة مفقود',summary:'ملخص الحالة مفقود',deadline:'لا توجد مهلة مسجلة',next_action:'الخطوة التالية مفقودة',documents:'لا توجد مستندات بعد',unread_documents:'مستندات بلا نص مستخرج',assessment:'لا يوجد تقييم موثق',red_without_next:'تقييم أحمر بلا خطوة تالية'},amount:'مبلغ',date:'تاريخ',actionsTitle:'ما يجب فعله الآن',actionsLead:'يحوّل AS Workspace Gold النقاط المفتوحة إلى مهام واضحة.',edit:'تعديل الحالة',upload:'إضافة مستند',reviewDoc:'مراجعة المستند',assess:'إضافة تقييم',followup:'تحديد الإجراء التالي',deviation:'مراجعة الاختلاف',done:'لا يوجد إجراء فوري مطلوب من النواقص المكتشفة.'},
  fa:{handoffTitle:'تحویل حرفه‌ای',handoffLead:'پرونده را برای وکیل، بیمه یا مشاور ساختاربندی می‌کند. فایل به‌صورت محلی در مرورگر ساخته می‌شود.',ready:'پرونده تحویل آماده است',check:'پیش از ارسال بررسی شود',missing:'موارد ناقص',pdf:'پرونده PDF',docx:'پرونده DOCX',privacy:'خروجی باعث ارسال اضافی داده نمی‌شود. اصل مدارک، مهلت‌ها و ارزیابی‌ها را پیش از اشتراک بررسی کنید.',goal:'هدف',summary:'وضعیت پرونده',deadline:'مهلت بعدی',next:'گام بعدی',documents:'اسناد',assessments:'ارزیابی‌ها',timeline:'خط زمانی',generated:'ساخته‌شده با AS Workspace Gold · پرونده کاری ساختاریافته، نه بررسی وکیل',consistencyTitle:'سازگاری پرونده و مدارک',score:'کامل بودن',good:'خوب آماده شده',review:'بررسی توصیه می‌شود',attention:'نواقص را تکمیل کنید',gaps:'موارد ناقص یا باز',deviations:'اطلاعات متفاوت میان اسناد',deviationNote:'به‌طور خودکار تناقض محسوب نمی‌شود — بررسی کنید آیا مربوط به دوره‌ها یا اقلام متفاوت است.',none:'اختلاف قابل توجهی شناسایی نشد.',gapLabels:{goal:'هدف پرونده وارد نشده',summary:'شرح وضعیت پرونده وارد نشده',deadline:'مهلت پرونده ثبت نشده',next_action:'گام بعدی مشخص نشده',documents:'هنوز سندی وجود ندارد',unread_documents:'اسناد بدون متن استخراج‌شده',assessment:'هنوز ارزیابی مستندی وجود ندارد',red_without_next:'ارزیابی قرمز بدون گام بعدی'},amount:'مبلغ',date:'تاریخ',actionsTitle:'اقدام بعدی',actionsLead:'AS Workspace Gold موارد باز را به کارهای مشخص تبدیل می‌کند.',edit:'ویرایش پرونده',upload:'افزودن سند',reviewDoc:'بررسی سند',assess:'افزودن ارزیابی',followup:'تعیین اقدام بعدی',deviation:'بررسی اختلاف',done:'از نواقص شناسایی‌شده اقدام فوری لازم نیست.'},
  ro:{handoffTitle:'Predare profesională',handoffLead:'Pregătește cazul pentru avocat, asigurător sau consultant. Fișierul este creat local în browser.',ready:'Dosar de predare pregătit',check:'Verificați înainte de trimitere',missing:'Încă lipsă',pdf:'Dosar PDF',docx:'Dosar DOCX',privacy:'Exportul nu transmite date suplimentare. Verificați originalele, termenele și evaluările înainte de partajare.',goal:'Obiectiv',summary:'Situația cazului',deadline:'Următorul termen',next:'Pasul următor',documents:'Documente',assessments:'Evaluări',timeline:'Cronologie',generated:'Creat cu AS Workspace Gold · material de lucru structurat, fără verificare juridică',consistencyTitle:'Coerența cazului și dovezi',score:'Completitudine',good:'Bine pregătit',review:'Verificare recomandată',attention:'Completați lipsurile',gaps:'Puncte lipsă sau deschise',deviations:'Date diferite între documente',deviationNote:'Nu sunt tratate automat ca contradicție — verificați dacă privesc perioade sau poziții diferite.',none:'Nu au fost detectate diferențe notabile.',gapLabels:{goal:'Lipsește obiectivul cazului',summary:'Lipsește situația cazului',deadline:'Nu este salvat un termen',next_action:'Lipsește pasul următor',documents:'Nu există documente',unread_documents:'Documente fără text extras',assessment:'Nu există evaluare documentată',red_without_next:'Evaluare roșie fără pas următor'},amount:'Sumă',date:'Dată',actionsTitle:'Ce faceți acum',actionsLead:'AS Workspace Gold transformă punctele deschise în sarcini concrete.',edit:'Editați cazul',upload:'Adăugați document',reviewDoc:'Verificați documentul',assess:'Adăugați evaluare',followup:'Stabiliți următoarea acțiune',deviation:'Verificați diferența',done:'Nu există acțiuni imediate rezultate din lipsurile detectate.'},
  bg:{handoffTitle:'Професионално предаване',handoffLead:'Подготвя случая за адвокат, застраховател или консултант. Файлът се създава локално в браузъра.',ready:'Пакетът е готов',check:'Проверете преди изпращане',missing:'Все още липсва',pdf:'Пакет PDF',docx:'Пакет DOCX',privacy:'Експортът не изпраща допълнителни данни. Проверете оригиналите, сроковете и оценките преди споделяне.',goal:'Цел',summary:'Състояние',deadline:'Следващ срок',next:'Следваща стъпка',documents:'Документи',assessments:'Оценки',timeline:'Хронология',generated:'Създадено с AS Workspace Gold · структуриран работен материал, не адвокатска проверка',consistencyTitle:'Съгласуваност на случая и доказателства',score:'Пълнота',good:'Добре подготвено',review:'Препоръчва се проверка',attention:'Попълнете липсите',gaps:'Липсващи или отворени точки',deviations:'Различни данни между документите',deviationNote:'Не се приемат автоматично за противоречие — проверете дали се отнасят за различни периоди или позиции.',none:'Не са открити съществени разлики.',gapLabels:{goal:'Липсва цел на случая',summary:'Липсва описание на случая',deadline:'Няма записан срок',next_action:'Липсва следваща стъпка',documents:'Все още няма документи',unread_documents:'Документи без извлечен текст',assessment:'Няма документирана оценка',red_without_next:'Червена оценка без следваща стъпка'},amount:'Сума',date:'Дата',actionsTitle:'Какво да направите сега',actionsLead:'AS Workspace Gold превръща отворените точки в конкретни задачи.',edit:'Редактирайте случая',upload:'Добавете документ',reviewDoc:'Проверете документа',assess:'Добавете оценка',followup:'Задайте следващо действие',deviation:'Проверете разликата',done:'Няма непосредствено действие по откритите липси.'}
}

function t(language){return labels[labels[language]?language:'de']}
function displayDate(value){if(!value)return '';try{return new Date(value).toLocaleDateString()}catch{return String(value)}}
function timelineFor(item,documents){
  const events=(documents||[]).map(document=>({date:document.document_date||document.created_at||'',title:document.title||'Dokument',detail:document.document_type||''})).filter(event=>event.date)
  if(item?.deadline_at) events.push({date:item.deadline_at,title:'Frist',detail:item.next_action||''})
  return events
}
function handoffData(item,documents,assessments){
  return buildProfessionalHandoff({
    title:item?.title||'AS Workspace Gold Fallakte',goal:item?.goal||'',summary:item?.summary||'',deadline:item?.deadline_at?displayDate(item.deadline_at):'',nextAction:item?.next_action||'',
    documents:(documents||[]).map(document=>({date:document.document_date||displayDate(document.created_at),title:document.title||'',status:document.extracted_text?'Text vorhanden':''})),
    assessments:(assessments||[]).map(entry=>({trafficLight:entry.traffic_light||'yellow',title:entry.title||'',reasoning:entry.reasoning||'',nextStep:entry.next_step||''})),
    timeline:timelineFor(item,documents)
  })
}
function fileName(ext){return `AS-Gold_Uebergabeakte_${new Date().toISOString().slice(0,10)}.${ext}`}
function saveBlob(blob,name){const url=URL.createObjectURL(blob);const anchor=document.createElement('a');anchor.href=url;anchor.download=name;document.body.appendChild(anchor);anchor.click();anchor.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}
async function exportPdf(data,copy){
  const {jsPDF}=await import('jspdf');const pdf=new jsPDF({unit:'mm',format:'a4'});let y=18
  const add=(text,size=10,bold=false)=>{pdf.setFontSize(size);pdf.setFont('helvetica',bold?'bold':'normal');const lines=pdf.splitTextToSize(String(text||'—'),175);if(y+lines.length*5>282){pdf.addPage();y=18}pdf.text(lines,18,y);y+=lines.length*5+2}
  add(`AS Workspace Gold · ${copy.handoffTitle}`,16,true);add(data.title,13,true);add(`${copy.goal}: ${data.goal||'—'}`);add(`${copy.summary}: ${data.summary||'—'}`);add(`${copy.deadline}: ${data.deadline||'—'}`);add(`${copy.next}: ${data.nextAction||'—'}`);add(copy.documents,12,true);data.documents.forEach((entry,index)=>add(`${index+1}. ${entry.date||'—'} · ${entry.title}${entry.status?' · '+entry.status:''}`));add(copy.assessments,12,true);data.assessments.forEach(entry=>add(`${entry.trafficLight.toUpperCase()} · ${entry.title}\n${entry.reasoning}${entry.nextStep?'\n'+entry.nextStep:''}`));if(data.timeline.length){add(copy.timeline,12,true);data.timeline.forEach(entry=>add(`${entry.date} · ${entry.title}${entry.detail?' · '+entry.detail:''}`))}add(copy.generated,8);pdf.save(fileName('pdf'))
}
async function exportDocx(data,copy){
  const {Document,Packer,Paragraph,TextRun,HeadingLevel}=await import('docx');const row=(label,value)=>new Paragraph({children:[new TextRun({text:label+': ',bold:true}),new TextRun(String(value||'—'))]});const children=[new Paragraph({text:`AS Workspace Gold · ${copy.handoffTitle}`,heading:HeadingLevel.TITLE}),new Paragraph({text:data.title,heading:HeadingLevel.HEADING_1}),row(copy.goal,data.goal),row(copy.summary,data.summary),row(copy.deadline,data.deadline),row(copy.next,data.nextAction),new Paragraph({text:copy.documents,heading:HeadingLevel.HEADING_2}),...data.documents.map((entry,index)=>new Paragraph(`${index+1}. ${entry.date||'—'} · ${entry.title}${entry.status?' · '+entry.status:''}`)),new Paragraph({text:copy.assessments,heading:HeadingLevel.HEADING_2}),...data.assessments.flatMap(entry=>[new Paragraph({children:[new TextRun({text:`${entry.trafficLight.toUpperCase()} · ${entry.title}`,bold:true})]}),new Paragraph(entry.reasoning||'—'),new Paragraph(entry.nextStep||'')])];if(data.timeline.length)children.push(new Paragraph({text:copy.timeline,heading:HeadingLevel.HEADING_2}),...data.timeline.map(entry=>new Paragraph(`${entry.date} · ${entry.title}${entry.detail?' · '+entry.detail:''}`)));children.push(new Paragraph({children:[new TextRun({text:copy.generated,italics:true})]}));saveBlob(await Packer.toBlob(new Document({sections:[{children}]})),fileName('docx'))
}

export function ProfessionalHandoffPanel({language='de',item,documents=[],assessments=[]}){
  const copy=t(language);const data=useMemo(()=>handoffData(item,documents,assessments),[item,documents,assessments]);const [busy,setBusy]=useState(false);const priority=handoffPriority(data.assessments);const icon=priority==='red'?'🔴':priority==='green'?'🟢':'🟡';const fieldNames={goal:copy.goal,summary:copy.summary,documents:copy.documents,assessments:copy.assessments};const missing=data.missing.map(key=>fieldNames[key]||key).join(', ')
  async function run(fn){if(busy)return;setBusy(true);try{await fn(data,copy)}finally{setBusy(false)}}
  return <section className="detailCard v40ProfessionalHandoff" data-v40-handoff="direct"><div className="detailCardHead"><div><h3>{copy.handoffTitle}</h3></div><strong>{icon} {data.ready?copy.ready:copy.check}</strong></div><p>{copy.handoffLead}</p>{missing&&<p><b>{copy.missing}:</b> {missing}</p>}<div className="documentReviewActions"><button type="button" className="secondary" disabled={busy} onClick={()=>run(exportPdf)}>{copy.pdf}</button><button type="button" className="primary" disabled={busy} onClick={()=>run(exportDocx)}>{copy.docx}</button></div><small>{copy.privacy}</small></section>
}

export function CaseConsistencyPanel({language='de',result}){
  const copy=t(language);const state=copy[result.status]||copy.review;const icon=result.status==='good'?'🟢':result.status==='review'?'🟡':'🔴'
  return <section className="detailCard v41CaseConsistency" data-v41-consistency="direct"><div className="detailCardHead"><div><h3>{copy.consistencyTitle}</h3></div><strong>{icon} {result.score}% · {state}</strong></div><div className="v41Metrics" aria-label={copy.consistencyTitle}><span><b>{copy.documents}</b><strong>{result.readableCount}/{result.documentCount}</strong></span><span><b>{copy.assessments}</b><strong>{result.assessmentCount}</strong><small>🔴 {result.redCount} · 🟡 {result.yellowCount} · 🟢 {result.greenCount}</small></span><span><b>{copy.gapLabels.red_without_next}</b><strong>{result.redWithoutNextCount}</strong></span><span><b>{copy.deviations}</b><strong>{result.deviations.length}</strong></span></div><h4>{copy.gaps}</h4>{result.gaps.length?<ul>{result.gaps.map(gap=><li key={gap}>{copy.gapLabels[gap]||gap}{gap==='unread_documents'&&result.unreadCount?` (${result.unreadCount})`:gap==='red_without_next'&&result.redWithoutNextCount?` (${result.redWithoutNextCount})`:''}</li>)}</ul>:<p>✓ {copy.good}</p>}{result.assessmentComplexes.length?<div className="v41Complexes"><h4>{copy.assessments}</h4><ul>{result.assessmentComplexes.map(complex=><li key={complex.title}><b>{complex.title}</b><span>🔴 {complex.red} · 🟡 {complex.yellow} · 🟢 {complex.green}{complex.withoutNext?` · ${copy.gapLabels.red_without_next}: ${complex.withoutNext}`:''}</span></li>)}</ul></div>:null}<div id="case-consistency-deviations"><h4>{copy.deviations}</h4>{result.deviations.length?<><ul>{result.deviations.map((deviation,index)=><li key={`${deviation.type}-${deviation.concept}-${index}`}><b>{copy[deviation.type]||deviation.type} · {deviation.concept}</b>: {deviation.values.map(value=>value.value).join(' ↔ ')}</li>)}</ul><small>{copy.deviationNote}</small></>:<p>{copy.none}</p>}</div></section>
}

function gapAction(gap,copy){
  if(['goal','summary','deadline','next_action'].includes(gap))return {kind:'edit',label:copy.edit}
  if(gap==='documents')return {kind:'upload',label:copy.upload}
  if(gap==='unread_documents')return {kind:'reviewDoc',label:copy.reviewDoc}
  if(gap==='assessment')return {kind:'assess',label:copy.assess}
  if(gap==='red_without_next')return {kind:'assess',label:copy.followup}
  return {kind:'edit',label:copy.edit}
}

export function ActionableGapsPanel({language='de',result,onEdit,onAddDocument,onOpenDocument,onAssess,documents=[]}){
  const copy=t(language);const tasks=result.gaps.map(gap=>({gap,label:copy.gapLabels[gap]||gap,...gapAction(gap,copy)}));if(result.deviations.length)tasks.push({gap:'deviation',label:result.deviations[0].concept||copy.deviations,kind:'deviation',actionLabel:copy.deviation})
  function run(task){if(task.kind==='edit')onEdit?.();else if(task.kind==='upload')onAddDocument?.();else if(task.kind==='reviewDoc'){const target=documents.find(document=>!document.extracted_text)||documents[0];if(target)onOpenDocument?.(target);else onAddDocument?.()}else if(task.kind==='assess')onAssess?.()}
  return <section className="detailCard v42Actions" data-v42-actions="direct"><div className="detailCardHead"><div><h3>{copy.actionsTitle}</h3><p>{copy.actionsLead}</p></div></div>{tasks.length?<div className="v42TaskList">{tasks.map((task,index)=>task.kind==='deviation'?<a className="itemRow buttonRow" data-v42-task={index} href="#case-consistency-deviations" key={`${task.gap}-${index}`}><span>{task.label}</span><b>{task.actionLabel||copy.deviation} ›</b></a>:<button type="button" className="itemRow buttonRow" data-v42-task={index} onClick={()=>run(task)} key={`${task.gap}-${index}`}><span>{task.label}</span><b>{task.label&&gapAction(task.gap,copy).label} ›</b></button>)}</div>:<p>✓ {copy.done}</p>}</section>
}

export function CaseCompletionPanels({language='de',item,documents=[],assessments=[],onEdit,onAddDocument,onOpenDocument,onAssess}){
  const result=useMemo(()=>analyzeCaseConsistency({caseItem:item||{},documents,assessments}),[item,documents,assessments])
  return <><ProfessionalHandoffPanel language={language} item={item} documents={documents} assessments={assessments}/><CaseConsistencyPanel language={language} result={result}/><ActionableGapsPanel language={language} result={result} documents={documents} onEdit={onEdit} onAddDocument={onAddDocument} onOpenDocument={onOpenDocument} onAssess={onAssess}/></>
}

export function V40ProfessionalHandoff(){return null}
export function V41CaseConsistency(){return null}
export function V42ActionableGaps(){return null}
