'use client'

import { useState } from 'react'
import { ControlledDocumentAnalysis } from './V26DocumentAnalysis'
import { DeadlineWarningCard } from './V38DeadlineCardEnhancer'
import { AssessmentExplainability } from './V38AssessmentExplainability'
import { PrimaryNextStepCard } from './V38PrimaryNextStep'
import { CaseTimeline, DocumentAutoAssessment } from './V39CaseTimelineAutoAssessment'
import { componentTranslations } from '../lib/v30ComponentTranslations.mjs'

const copy = {
  de:{quickTitle:'Direkt starten',quickLead:'Die wichtigsten Schritte sind auf dem Smartphone sofort erreichbar.',newCase:'Neuer Fall',scanDocument:'Dokument scannen',uploadFile:'Datei hochladen',clients:'Kunden',deadlines:'Fristen',approvals:'Freigaben',dueSoon:'Nächste Fristen',noDeadline:'Noch keine Fristen eingetragen.',caseSetup:'Fall anlegen',caseSetupHelp:'Erfassen Sie Ziel, Sachstand und nächste Frist. Eine Bewertung entsteht erst aus nachvollziehbaren Grundlagen.',title:'Fallbezeichnung',documentTitle:'Dokumenttitel',client:'Kunde',noClient:'Eigener Vorgang / noch kein Kunde',reference:'Aktenzeichen / Referenz',goal:'Was soll erreicht werden?',summary:'Bisheriger Sachstand',deadline:'Nächste Frist',nextAction:'Nächster geplanter Schritt',createCase:'Fall speichern',saveChanges:'Änderungen speichern',cancel:'Abbrechen',editCase:'Fall bearbeiten',sourceBasis:'Quellenbasis',assessmentState:'Prüfstatus',notAssessable:'Nicht sicher bewertbar – noch keine Dokumente zugeordnet.',reviewRequired:'Unterlagen vorhanden – Bewertung und Quellenprüfung stehen noch aus.',reviewed:'Eine Bewertung ist dokumentiert. Neue Informationen müssen erneut geprüft werden.',noDocuments:'Noch keine Dokumente zugeordnet.',currentAssessments:'Dokumentierte Bewertungen',noAssessment:'Noch keine Bewertung dokumentiert.',addAssessment:'Bewertung hinzufügen',assessmentTitle:'Bewertungspunkt',trafficLight:'Ampel',reasoning:'Begründung und Quelle',assessmentNext:'Nächster Schritt aus dieser Bewertung',saveAssessment:'Bewertung speichern',green:'Grün',yellow:'Gelb',red:'Rot',documentUpload:'Dokument hinzufügen',uploadMode:'Datei',scanMode:'Kamera',scanHelp:'Auf dem Smartphone öffnet sich die Kamera. Das Foto wird erst nach Ihrer Auswahl hochgeladen.',uploadHelp:'Unterstützte Testformate können dem Fall zugeordnet werden. Die 50-MB-Grenze ist vorläufig.',file:'Datei',documentType:'Dokumenttyp',documentDate:'Dokumentdatum',withoutCase:'Ohne Fallzuordnung',upload:'Hochladen',uploading:'Wird hochgeladen …',documentReview:'Dokument prüfen',documentReviewHelp:'Erkannte oder manuell ergänzte Angaben bleiben korrigierbar. Ohne ausgelesenen Inhalt wird keine sichere Analyse behauptet.',originalFile:'Originaldatei öffnen',extractedText:'Ausgelesener Inhalt',noExtraction:'Noch kein Inhalt ausgelesen. Für PDF, Office und Bilder folgt die geschützte Verarbeitungspipeline.',textAvailable:'Inhalt vorhanden – bitte fachlich prüfen.',analysisSummary:'Prüfergebnis / Zusammenfassung',analysisNext:'Nächster Schritt',saveDocument:'Dokumentdaten speichern',back:'← Zurück',created:'Erstellt',clientUnknown:'Kein Kunde zugeordnet',documents:'Dokumente',caseRecord:'Fallakte',selectCase:'Fall auswählen'},
  en:{quickTitle:'Start directly',quickLead:'The most important actions are immediately available on mobile.',newCase:'New case',scanDocument:'Scan document',uploadFile:'Upload file',clients:'Clients',deadlines:'Deadlines',approvals:'Approvals',dueSoon:'Upcoming deadlines',noDeadline:'No deadlines entered yet.',caseSetup:'Create case',caseSetupHelp:'Record the goal, current facts and next deadline. An assessment is only made from traceable sources.',title:'Case title',documentTitle:'Document title',client:'Client',noClient:'Own matter / no client yet',reference:'Reference number',goal:'What should be achieved?',summary:'Current facts',deadline:'Next deadline',nextAction:'Next planned action',createCase:'Save case',saveChanges:'Save changes',cancel:'Cancel',editCase:'Edit case',sourceBasis:'Source basis',assessmentState:'Review status',notAssessable:'Not reliably assessable – no documents assigned yet.',reviewRequired:'Documents available – assessment and source review are still pending.',reviewed:'An assessment is documented. New information must be reviewed again.',noDocuments:'No documents assigned yet.',currentAssessments:'Documented assessments',noAssessment:'No assessment documented yet.',addAssessment:'Add assessment',assessmentTitle:'Assessment point',trafficLight:'Traffic light',reasoning:'Reasoning and source',assessmentNext:'Next step from this assessment',saveAssessment:'Save assessment',green:'Green',yellow:'Yellow',red:'Red',documentUpload:'Add document',uploadMode:'File',scanMode:'Camera',scanHelp:'On mobile, the camera opens. The photo is uploaded only after you select it.',uploadHelp:'Supported test formats can be assigned to a case. The 50 MB limit is temporary.',file:'File',documentType:'Document type',documentDate:'Document date',withoutCase:'Without case assignment',upload:'Upload',uploading:'Uploading …',documentReview:'Review document',documentReviewHelp:'Detected or manually added information remains editable. No reliable analysis is claimed without extracted content.',originalFile:'Open original file',extractedText:'Extracted content',noExtraction:'No content extracted yet. A protected processing pipeline for PDF, Office files and images follows.',textAvailable:'Content available – please review it.',analysisSummary:'Review result / summary',analysisNext:'Next step',saveDocument:'Save document data',back:'← Back',created:'Created',clientUnknown:'No client assigned',documents:'Documents',caseRecord:'Case file',selectCase:'Select case'},
  tr:{quickTitle:'Hemen başlayın',quickLead:'En önemli adımlar telefonda hemen kullanılabilir.',newCase:'Yeni dosya',scanDocument:'Belge tara',uploadFile:'Dosya yükle',clients:'Müşteriler',deadlines:'Süreler',approvals:'Onaylar',dueSoon:'Yaklaşan süreler',noDeadline:'Henüz süre girilmedi.',caseSetup:'Dosya oluştur',caseSetupHelp:'Hedefi, mevcut durumu ve sonraki süreyi kaydedin. Değerlendirme yalnızca izlenebilir kaynaklara dayanır.',title:'Dosya adı',documentTitle:'Belge başlığı',client:'Müşteri',noClient:'Kendi işlemi / henüz müşteri yok',reference:'Referans numarası',goal:'Ne elde edilmek isteniyor?',summary:'Mevcut durum',deadline:'Sonraki süre',nextAction:'Planlanan sonraki adım',createCase:'Dosyayı kaydet',saveChanges:'Değişiklikleri kaydet',cancel:'İptal',editCase:'Dosyayı düzenle',sourceBasis:'Kaynak temeli',assessmentState:'İnceleme durumu',notAssessable:'Güvenilir biçimde değerlendirilemez – belge atanmamış.',reviewRequired:'Belgeler var – değerlendirme ve kaynak kontrolü bekliyor.',reviewed:'Bir değerlendirme kaydedildi. Yeni bilgiler yeniden incelenmelidir.',noDocuments:'Henüz belge atanmadı.',currentAssessments:'Belgelenmiş değerlendirmeler',noAssessment:'Henüz değerlendirme yok.',addAssessment:'Değerlendirme ekle',assessmentTitle:'Değerlendirme konusu',trafficLight:'Trafik ışığı',reasoning:'Gerekçe ve kaynak',assessmentNext:'Sonraki adım',saveAssessment:'Değerlendirmeyi kaydet',green:'Yeşil',yellow:'Sarı',red:'Kırmızı',documentUpload:'Belge ekle',uploadMode:'Dosya',scanMode:'Kamera',scanHelp:'Telefonda kamera açılır. Fotoğraf yalnızca seçiminizden sonra yüklenir.',uploadHelp:'Desteklenen test biçimleri bir dosyaya atanabilir. 50 MB sınırı geçicidir.',file:'Dosya',documentType:'Belge türü',documentDate:'Belge tarihi',withoutCase:'Dosya ataması olmadan',upload:'Yükle',uploading:'Yükleniyor …',documentReview:'Belgeyi kontrol et',documentReviewHelp:'Algılanan veya elle eklenen bilgiler düzeltilebilir. Çıkarılmış içerik olmadan güvenilir analiz iddia edilmez.',originalFile:'Orijinal dosyayı aç',extractedText:'Çıkarılan içerik',noExtraction:'Henüz içerik çıkarılmadı. PDF, Office ve görüntüler için korumalı işleme hattı eklenecek.',textAvailable:'İçerik mevcut – lütfen kontrol edin.',analysisSummary:'İnceleme sonucu / özet',analysisNext:'Sonraki adım',saveDocument:'Belge verilerini kaydet',back:'← Geri',created:'Oluşturuldu',clientUnknown:'Müşteri atanmadı',documents:'Belgeler',caseRecord:'Dosya kaydı',selectCase:'Dosya seç'},
  pl:{quickTitle:'Zacznij od razu',quickLead:'Najważniejsze działania są od razu dostępne na telefonie.',newCase:'Nowa sprawa',scanDocument:'Skanuj dokument',uploadFile:'Prześlij plik',clients:'Klienci',deadlines:'Terminy',approvals:'Zatwierdzenia',dueSoon:'Najbliższe terminy',noDeadline:'Nie wpisano jeszcze terminów.',caseSetup:'Utwórz sprawę',caseSetupHelp:'Zapisz cel, stan sprawy i najbliższy termin. Ocena powstaje wyłącznie na podstawie możliwych do prześledzenia źródeł.',title:'Nazwa sprawy',documentTitle:'Tytuł dokumentu',client:'Klient',noClient:'Własna sprawa / bez klienta',reference:'Numer referencyjny',goal:'Jaki jest cel?',summary:'Aktualny stan sprawy',deadline:'Najbliższy termin',nextAction:'Planowany następny krok',createCase:'Zapisz sprawę',saveChanges:'Zapisz zmiany',cancel:'Anuluj',editCase:'Edytuj sprawę',sourceBasis:'Podstawa źródłowa',assessmentState:'Status weryfikacji',notAssessable:'Brak możliwości rzetelnej oceny – nie przypisano dokumentów.',reviewRequired:'Dokumenty są dostępne – ocena i kontrola źródeł są w toku.',reviewed:'Ocena została udokumentowana. Nowe informacje wymagają ponownej kontroli.',noDocuments:'Nie przypisano dokumentów.',currentAssessments:'Udokumentowane oceny',noAssessment:'Brak udokumentowanej oceny.',addAssessment:'Dodaj ocenę',assessmentTitle:'Punkt oceny',trafficLight:'Sygnalizacja',reasoning:'Uzasadnienie i źródło',assessmentNext:'Następny krok',saveAssessment:'Zapisz ocenę',green:'Zielony',yellow:'Żółty',red:'Czerwony',documentUpload:'Dodaj dokument',uploadMode:'Plik',scanMode:'Kamera',scanHelp:'Na telefonie otworzy się kamera. Zdjęcie zostanie przesłane dopiero po wyborze.',uploadHelp:'Obsługiwane formaty testowe można przypisać do sprawy. Limit 50 MB jest tymczasowy.',file:'Plik',documentType:'Typ dokumentu',documentDate:'Data dokumentu',withoutCase:'Bez przypisania do sprawy',upload:'Prześlij',uploading:'Przesyłanie …',documentReview:'Sprawdź dokument',documentReviewHelp:'Rozpoznane lub ręcznie dodane dane można poprawić. Bez odczytanej treści nie jest deklarowana pewna analiza.',originalFile:'Otwórz oryginał',extractedText:'Odczytana treść',noExtraction:'Treść nie została jeszcze odczytana. Następnym krokiem jest chroniony proces dla PDF, Office i obrazów.',textAvailable:'Treść dostępna – wymaga weryfikacji.',analysisSummary:'Wynik kontroli / podsumowanie',analysisNext:'Następny krok',saveDocument:'Zapisz dane dokumentu',back:'← Wstecz',created:'Utworzono',clientUnknown:'Brak przypisanego klienta',documents:'Dokumenty',caseRecord:'Akta sprawy',selectCase:'Wybierz sprawę'},
  ru:{quickTitle:'Начать сразу',quickLead:'Основные действия сразу доступны на телефоне.',newCase:'Новое дело',scanDocument:'Сканировать документ',uploadFile:'Загрузить файл',clients:'Клиенты',deadlines:'Сроки',approvals:'Согласования',dueSoon:'Ближайшие сроки',noDeadline:'Сроки пока не внесены.',caseSetup:'Создать дело',caseSetupHelp:'Укажите цель, текущее состояние и ближайший срок. Оценка основывается только на проверяемых источниках.',title:'Название дела',documentTitle:'Название документа',client:'Клиент',noClient:'Собственное дело / без клиента',reference:'Номер дела / ссылка',goal:'Какую цель нужно достичь?',summary:'Текущее состояние',deadline:'Ближайший срок',nextAction:'Запланированный следующий шаг',createCase:'Сохранить дело',saveChanges:'Сохранить изменения',cancel:'Отмена',editCase:'Редактировать дело',sourceBasis:'Источники',assessmentState:'Статус проверки',notAssessable:'Нельзя надежно оценить – документы не назначены.',reviewRequired:'Документы есть – оценка и проверка источников еще не завершены.',reviewed:'Оценка задокументирована. Новые сведения требуют повторной проверки.',noDocuments:'Документы еще не назначены.',currentAssessments:'Задокументированные оценки',noAssessment:'Оценок пока нет.',addAssessment:'Добавить оценку',assessmentTitle:'Пункт оценки',trafficLight:'Светофор',reasoning:'Обоснование и источник',assessmentNext:'Следующий шаг',saveAssessment:'Сохранить оценку',green:'Зеленый',yellow:'Желтый',red:'Красный',documentUpload:'Добавить документ',uploadMode:'Файл',scanMode:'Камера',scanHelp:'На телефоне откроется камера. Фото загружается только после вашего выбора.',uploadHelp:'Поддерживаемые тестовые форматы можно связать с делом. Лимит 50 МБ временный.',file:'Файл',documentType:'Тип документа',documentDate:'Дата документа',withoutCase:'Без привязки к делу',upload:'Загрузить',uploading:'Загрузка …',documentReview:'Проверить документ',documentReviewHelp:'Распознанные или добавленные вручную данные можно исправить. Без извлеченного текста надежный анализ не заявляется.',originalFile:'Открыть оригинал',extractedText:'Извлеченный текст',noExtraction:'Текст еще не извлечен. Далее будет защищенная обработка PDF, Office и изображений.',textAvailable:'Текст доступен – проверьте его.',analysisSummary:'Результат проверки / итог',analysisNext:'Следующий шаг',saveDocument:'Сохранить данные документа',back:'← Назад',created:'Создано',clientUnknown:'Клиент не назначен',documents:'Документы',caseRecord:'Материалы дела',selectCase:'Выбрать дело'},
  ar:{quickTitle:'ابدأ مباشرة',quickLead:'أهم الإجراءات متاحة فورًا على الهاتف.',newCase:'حالة جديدة',scanDocument:'مسح مستند',uploadFile:'رفع ملف',clients:'العملاء',deadlines:'المواعيد',approvals:'الموافقات',dueSoon:'المواعيد القادمة',noDeadline:'لم تُسجل مواعيد بعد.',caseSetup:'إنشاء حالة',caseSetupHelp:'سجّل الهدف والوضع الحالي والموعد التالي. لا يتم التقييم إلا استنادًا إلى مصادر قابلة للتتبع.',title:'اسم الحالة',documentTitle:'عنوان المستند',client:'العميل',noClient:'موضوع شخصي / لا يوجد عميل بعد',reference:'رقم المرجع',goal:'ما الهدف المطلوب؟',summary:'الوضع الحالي',deadline:'الموعد التالي',nextAction:'الخطوة التالية المخططة',createCase:'حفظ الحالة',saveChanges:'حفظ التغييرات',cancel:'إلغاء',editCase:'تعديل الحالة',sourceBasis:'أساس المصادر',assessmentState:'حالة المراجعة',notAssessable:'لا يمكن التقييم بشكل موثوق – لا توجد مستندات مرتبطة.',reviewRequired:'المستندات موجودة – التقييم وفحص المصادر ما زالا مطلوبين.',reviewed:'تم توثيق تقييم. يجب مراجعة أي معلومات جديدة.',noDocuments:'لا توجد مستندات مرتبطة بعد.',currentAssessments:'التقييمات الموثقة',noAssessment:'لا يوجد تقييم موثق بعد.',addAssessment:'إضافة تقييم',assessmentTitle:'نقطة التقييم',trafficLight:'إشارة التقييم',reasoning:'التعليل والمصدر',assessmentNext:'الخطوة التالية',saveAssessment:'حفظ التقييم',green:'أخضر',yellow:'أصفر',red:'أحمر',documentUpload:'إضافة مستند',uploadMode:'ملف',scanMode:'الكاميرا',scanHelp:'تفتح الكاميرا على الهاتف. لا تُرفع الصورة إلا بعد اختيارك.',uploadHelp:'يمكن ربط صيغ الاختبار المدعومة بالحالة. حد 50 ميغابايت مؤقت.',file:'الملف',documentType:'نوع المستند',documentDate:'تاريخ المستند',withoutCase:'دون ربط بحالة',upload:'رفع',uploading:'جارٍ الرفع …',documentReview:'مراجعة المستند',documentReviewHelp:'يمكن تصحيح المعلومات المكتشفة أو المضافة يدويًا. لا يُدّعى وجود تحليل موثوق دون محتوى مستخرج.',originalFile:'فتح الملف الأصلي',extractedText:'المحتوى المستخرج',noExtraction:'لم يُستخرج محتوى بعد. ستتبع معالجة محمية لملفات PDF وOffice والصور.',textAvailable:'المحتوى متاح – يرجى مراجعته.',analysisSummary:'نتيجة المراجعة / الملخص',analysisNext:'الخطوة التالية',saveDocument:'حفظ بيانات المستند',back:'← رجوع',created:'تاريخ الإنشاء',clientUnknown:'لا يوجد عميل مرتبط',documents:'المستندات',caseRecord:'ملف الحالة',selectCase:'اختيار الحالة'}
}

Object.assign(copy, componentTranslations.workspaceCopy)

export function getV24Copy(language){ return copy[language] || copy.de }

function fieldId(prefix,name){ return `${prefix}-${name}` }

function localDateTime(value){
  if(!value) return ''
  const date = new Date(value)
  if(Number.isNaN(date.getTime())) return ''
  return new Date(date.getTime()-date.getTimezoneOffset()*60000).toISOString().slice(0,16)
}

export function QuickActions({copy:on, onAction, deadlineCases=[]}){
  const actions=[['case',on.newCase],['scan',on.scanDocument],['upload',on.uploadFile],['clients',on.clients],['deadlines',on.deadlines],['approvals',on.approvals]]
  return <>
    <section className="quickStart"><div><span className="modeBadge">V26</span><h3>{on.quickTitle}</h3><p>{on.quickLead}</p></div><div className="quickActionGrid">{actions.map(([key,label])=><button type="button" className="quickAction" onClick={()=>onAction(key)} key={key}><span aria-hidden="true">{key==='case'?'＋':key==='scan'?'▣':key==='upload'?'↑':key==='clients'?'◎':key==='deadlines'?'◷':'✓'}</span><b>{label}</b></button>)}</div></section>
    <section className="deadlineStrip"><div><b>{on.dueSoon}</b>{deadlineCases.length?<div className="deadlineList">{deadlineCases.slice(0,3).map(item=><button type="button" onClick={()=>onAction('open-case',item)} key={item.id}><span>{new Date(item.deadline_at).toLocaleDateString()}</span><b>{item.title}</b></button>)}</div>:<p>{on.noDeadline}</p>}</div></section>
  </>
}

export function CaseSection({copy:on, clients, cases, newCase, setNewCase, showForm, setShowForm, onSubmit, onSelect}){
  return <>
    <button className="primary actionBtn" type="button" onClick={()=>setShowForm(value=>!value)}>{showForm?on.cancel:`＋ ${on.newCase}`}</button>
    {showForm&&<form className="actionCard coreForm" onSubmit={onSubmit}>
      <div className="formIntro"><h3>{on.caseSetup}</h3><p>{on.caseSetupHelp}</p></div>
      <label htmlFor={fieldId('new-case','title')}>{on.title}<input id={fieldId('new-case','title')} value={newCase.title} onChange={event=>setNewCase({...newCase,title:event.target.value})} required/></label>
      <label htmlFor={fieldId('new-case','client')}>{on.client}<select id={fieldId('new-case','client')} value={newCase.client_id} onChange={event=>setNewCase({...newCase,client_id:event.target.value})}><option value="">{on.noClient}</option>{clients.map(client=><option value={client.id} key={client.id}>{client.name}</option>)}</select></label>
      <label htmlFor={fieldId('new-case','reference')}>{on.reference}<input id={fieldId('new-case','reference')} value={newCase.reference_no} onChange={event=>setNewCase({...newCase,reference_no:event.target.value})}/></label>
      <label htmlFor={fieldId('new-case','goal')}>{on.goal}<textarea id={fieldId('new-case','goal')} value={newCase.goal} onChange={event=>setNewCase({...newCase,goal:event.target.value})} required/></label>
      <label htmlFor={fieldId('new-case','summary')}>{on.summary}<textarea id={fieldId('new-case','summary')} value={newCase.summary} onChange={event=>setNewCase({...newCase,summary:event.target.value})}/></label>
      <label htmlFor={fieldId('new-case','deadline')}>{on.deadline}<input id={fieldId('new-case','deadline')} type="datetime-local" value={newCase.deadline_at} onChange={event=>setNewCase({...newCase,deadline_at:event.target.value})}/></label>
      <label htmlFor={fieldId('new-case','next')}>{on.nextAction}<textarea id={fieldId('new-case','next')} value={newCase.next_action} onChange={event=>setNewCase({...newCase,next_action:event.target.value})}/></label>
      <button className="primary full">{on.createCase}</button>
    </form>}
    {cases.length?<div className="itemList">{cases.map(item=><button className="itemRow buttonRow" type="button" onClick={()=>onSelect(item)} key={item.id}><div><b>{item.title}</b><div className="pills"><span className="pill">{item.status}</span><span className={`pill ${item.traffic_light||'yellow'}`}>{item.traffic_light==='red'?`🔴 ${on.red}`:item.traffic_light==='green'?`🟢 ${on.green}`:`🟡 ${on.yellow}`}</span>{item.deadline_at&&<span className="pill">{new Date(item.deadline_at).toLocaleDateString()}</span>}</div></div><span className="chev">›</span></button>)}</div>:null}
  </>
}

export function CaseDetail({copy:on, analysis, language='de', item, clients, documents, assessments, onBack, onSave, onAddAssessment, onAddDocument, onOpenDocument}){
  const [editing,setEditing]=useState(false)
  const [draft,setDraft]=useState({title:item.title||'',client_id:item.client_id||'',reference_no:item.reference_no||'',goal:item.goal||'',summary:item.summary||'',deadline_at:localDateTime(item.deadline_at),next_action:item.next_action||'',status:item.status||'open'})
  const [assessment,setAssessment]=useState({title:'',traffic_light:'yellow',reasoning:'',next_step:''})
  const client=clients.find(entry=>entry.id===item.client_id)
  const readiness=!documents.length?on.notAssessable:!assessments.length?on.reviewRequired:on.reviewed
  return <>
    <button className="backBtn" type="button" onClick={onBack}>{on.back}</button>
    <div className="caseTitleRow"><div><span className="modeBadge">{on.caseRecord}</span><h2>{item.title}</h2><p>{client?.name||on.clientUnknown}{item.reference_no?` · ${item.reference_no}`:''}</p></div><button className="secondary" type="button" onClick={()=>setEditing(value=>!value)}>{editing?on.cancel:on.editCase}</button></div>
    {editing&&<form className="actionCard coreForm" onSubmit={event=>{event.preventDefault();onSave(item.id,draft).then(saved=>{if(saved)setEditing(false)})}}>
      <label htmlFor={fieldId(item.id,'title')}>{on.title}<input id={fieldId(item.id,'title')} value={draft.title} onChange={event=>setDraft({...draft,title:event.target.value})} required/></label>
      <label htmlFor={fieldId(item.id,'client')}>{on.client}<select id={fieldId(item.id,'client')} value={draft.client_id} onChange={event=>setDraft({...draft,client_id:event.target.value})}><option value="">{on.noClient}</option>{clients.map(entry=><option value={entry.id} key={entry.id}>{entry.name}</option>)}</select></label>
      <label htmlFor={fieldId(item.id,'reference')}>{on.reference}<input id={fieldId(item.id,'reference')} value={draft.reference_no} onChange={event=>setDraft({...draft,reference_no:event.target.value})}/></label>
      <label htmlFor={fieldId(item.id,'goal')}>{on.goal}<textarea id={fieldId(item.id,'goal')} value={draft.goal} onChange={event=>setDraft({...draft,goal:event.target.value})}/></label>
      <label htmlFor={fieldId(item.id,'summary')}>{on.summary}<textarea id={fieldId(item.id,'summary')} value={draft.summary} onChange={event=>setDraft({...draft,summary:event.target.value})}/></label>
      <label htmlFor={fieldId(item.id,'deadline')}>{on.deadline}<input id={fieldId(item.id,'deadline')} type="datetime-local" value={draft.deadline_at} onChange={event=>setDraft({...draft,deadline_at:event.target.value})}/></label>
      <label htmlFor={fieldId(item.id,'next')}>{on.nextAction}<textarea id={fieldId(item.id,'next')} value={draft.next_action} onChange={event=>setDraft({...draft,next_action:event.target.value})}/></label>
      <button className="primary full">{on.saveChanges}</button>
    </form>}
    <section className="caseCoreGrid"><article><b>{on.goal}</b><p>{item.goal||'—'}</p></article><article><b>{on.summary}</b><p>{item.summary||'—'}</p></article><article><b>{on.deadline}</b><p>{item.deadline_at?new Date(item.deadline_at).toLocaleString():'—'}</p></article><article><b>{on.nextAction}</b><p>{item.next_action||'—'}</p></article></section>
    <DeadlineWarningCard language={language} caseDeadline={item.deadline_at||''} mode="case"/>
    <PrimaryNextStepCard language={language} item={item} documents={documents} assessments={assessments}/>
    <CaseTimeline language={language} caseDeadline={item.deadline_at||''} documents={documents}/>
    <section className={`readinessCard ${!documents.length?'attentionBox':''}`}><b>{on.assessmentState}</b><p>{readiness}</p></section>
    <section className="detailCard"><div className="detailCardHead"><h3>{on.sourceBasis}</h3><button className="secondary" type="button" onClick={()=>onAddDocument(item.id)}>＋ {on.documentUpload}</button></div>{documents.length?<div className="sourceList">{documents.map(document=><button type="button" onClick={()=>onOpenDocument(document)} key={document.id}><span>{document.document_date||new Date(document.created_at).toLocaleDateString()}</span><b>{document.title}</b><small>{document.extracted_text?on.textAvailable:(analysis?.notStarted||on.noExtraction)}</small></button>)}</div>:<div className="emptyState">{on.noDocuments}</div>}</section>
    <section className="detailCard"><h3>{on.currentAssessments}</h3>{assessments.length?<div className="assessmentList">{assessments.map(entry=><article className={`assessment ${entry.traffic_light}`} key={entry.id}><div><span>{entry.traffic_light==='red'?`🔴 ${on.red}`:entry.traffic_light==='green'?`🟢 ${on.green}`:`🟡 ${on.yellow}`}</span><b>{entry.title}</b></div><p>{entry.reasoning||'—'}</p><small>{on.nextAction}: {entry.next_step||'—'}</small><AssessmentExplainability language={language} reasoning={entry.reasoning} next={entry.next_step}/></article>)}</div>:<p>{on.noAssessment}</p>}
      <form className="inlineAssessment" onSubmit={event=>{event.preventDefault();onAddAssessment(item.id,assessment).then(saved=>{if(saved)setAssessment({title:'',traffic_light:'yellow',reasoning:'',next_step:''})})}}><h4>{on.addAssessment}</h4><label htmlFor={fieldId(item.id,'assessment-title')}>{on.assessmentTitle}<input id={fieldId(item.id,'assessment-title')} value={assessment.title} onChange={event=>setAssessment({...assessment,title:event.target.value})} required/></label><label htmlFor={fieldId(item.id,'assessment-light')}>{on.trafficLight}<select id={fieldId(item.id,'assessment-light')} value={assessment.traffic_light} onChange={event=>setAssessment({...assessment,traffic_light:event.target.value})}><option value="green">{on.green}</option><option value="yellow">{on.yellow}</option><option value="red">{on.red}</option></select></label><label htmlFor={fieldId(item.id,'assessment-reasoning')}>{on.reasoning}<textarea id={fieldId(item.id,'assessment-reasoning')} value={assessment.reasoning} onChange={event=>setAssessment({...assessment,reasoning:event.target.value})} required/></label><label htmlFor={fieldId(item.id,'assessment-next')}>{on.assessmentNext}<textarea id={fieldId(item.id,'assessment-next')} value={assessment.next_step} onChange={event=>setAssessment({...assessment,next_step:event.target.value})}/></label><button className="secondary full" type="submit">{on.saveAssessment}</button></form>
    </section>
  </>
}

export function DocumentSection({copy:on, privacy, cases, documents, mode, setMode, defaultCaseId, onSubmit, uploading, accept, onSelect}){
  return <>
    <form className="actionCard coreForm" onSubmit={onSubmit}>
      <div className="formIntro"><h3>{on.documentUpload}</h3><div className="modeSwitch"><button type="button" className={mode==='upload'?'active':''} onClick={()=>setMode('upload')}>{on.uploadMode}</button><button type="button" className={mode==='scan'?'active':''} onClick={()=>setMode('scan')}>{on.scanMode}</button></div><p>{mode==='scan'?on.scanHelp:on.uploadHelp}</p></div>
      <label htmlFor="v24-document-file">{on.file}<input key={mode} id="v24-document-file" name="file" type="file" accept={mode==='scan'?'image/*':accept} capture={mode==='scan'?'environment':undefined} required/></label>
      <label htmlFor="v24-document-case">{on.selectCase}<select id="v24-document-case" name="case_id" defaultValue={defaultCaseId||''}><option value="">{on.withoutCase}</option>{cases.map(item=><option value={item.id} key={item.id}>{item.title}</option>)}</select></label>
      <label htmlFor="v24-document-type">{on.documentType}<input id="v24-document-type" name="document_type" placeholder="z. B. Vertrag, Schreiben, Rechnung"/></label>
      <label htmlFor="v24-document-date">{on.documentDate}<input id="v24-document-date" name="document_date" type="date"/></label>
      {privacy&&<><div className="documentPrivacyIntro"><b>{privacy.classification}</b><p>{privacy.uploadHelp}</p><a href="/datenschutz" target="_blank" rel="noreferrer">{privacy.privacy} →</a></div><label htmlFor="v28-document-classification">{privacy.classification}<select id="v28-document-classification" name="data_classification" defaultValue="" required><option value="" disabled>—</option><option value="synthetic">{privacy.synthetic}</option><option value="anonymized">{privacy.anonymized}</option></select></label><label className="documentPrivacyConfirm"><input name="test_data_confirmed" type="checkbox" required/><span>{privacy.uploadConfirm}</span></label></>}
      <input type="hidden" name="source" value={mode}/>
      <button className="primary full" disabled={uploading}>{uploading?on.uploading:on.upload}</button>
    </form>
    {documents.length?<div className="itemList">{documents.map(item=><button className="itemRow buttonRow" type="button" onClick={()=>onSelect(item)} key={item.id}><div><b>{item.title}</b><p>{item.document_type||on.documentType}{item.document_date?` · ${item.document_date}`:''}</p></div><span className="chev">›</span></button>)}</div>:null}
  </>
}

export function DocumentDetail({copy:on, analysis, language='de', item, cases, onBack, onSave, onAnalyze, onOpen, onPrepareApproval, approvalLabel}){
  const [draft,setDraft]=useState({title:item.title||'',case_id:item.case_id||'',document_type:item.document_type||'',document_date:item.document_date||'',extracted_text:item.extracted_text||'',analysis_summary:item.analysis_summary||'',analysis_next_step:item.analysis_next_step||''})
  const [analysisPhase,setAnalysisPhase]=useState(item.extracted_text||item.analysis_summary||item.analysis_next_step?'saved':'uploaded')
  async function save(event){
    event.preventDefault()
    const saved=await onSave(item.id,draft)
    if(saved){
      setAnalysisPhase('saved')
      setDraft(current=>({...current,analysis_generated:false}))
    }
  }
  return <>
    <button className="backBtn" type="button" onClick={onBack}>{on.back}</button>
    <section className="documentReviewHead"><div><span className="modeBadge">V28</span><h2>{on.documentReview}</h2><p>{on.documentReviewHelp}</p></div><div className="documentReviewActions">{item.file_path&&<button className="secondary" type="button" onClick={()=>onOpen(item)}>{on.originalFile}</button>}{item.case_id&&onPrepareApproval&&<button className="primary" type="button" onClick={()=>onPrepareApproval(item)}>{approvalLabel}</button>}</div></section>
    <DeadlineWarningCard language={language} text={draft.extracted_text} mode="document"/>
    <DocumentAutoAssessment language={language} text={draft.extracted_text}/>
    <div className={`readinessCard ${draft.extracted_text?'':'attentionBox'}`}><b>{on.assessmentState}</b><p>{draft.extracted_text?on.textAvailable:(analysis?.notStarted||on.noExtraction)}</p></div>
    {analysis&&onAnalyze&&<ControlledDocumentAnalysis copy={analysis} item={item} draft={draft} onChange={setDraft} onAnalyze={onAnalyze} phase={analysisPhase} onPhase={setAnalysisPhase}/>}
    <form className="actionCard coreForm documentReviewForm" onSubmit={save}>
      <label htmlFor={fieldId(item.id,'document-title')}>{on.documentTitle}<input id={fieldId(item.id,'document-title')} value={draft.title} onChange={event=>setDraft({...draft,title:event.target.value})} required/></label>
      <label htmlFor={fieldId(item.id,'document-case')}>{on.selectCase}<select id={fieldId(item.id,'document-case')} value={draft.case_id} onChange={event=>setDraft({...draft,case_id:event.target.value})}><option value="">{on.withoutCase}</option>{cases.map(entry=><option value={entry.id} key={entry.id}>{entry.title}</option>)}</select></label>
      <label htmlFor={fieldId(item.id,'document-type')}>{on.documentType}<input id={fieldId(item.id,'document-type')} value={draft.document_type} onChange={event=>setDraft({...draft,document_type:event.target.value})}/></label>
      <label htmlFor={fieldId(item.id,'document-date')}>{on.documentDate}<input id={fieldId(item.id,'document-date')} type="date" value={draft.document_date} onChange={event=>setDraft({...draft,document_date:event.target.value})}/></label>
      <label className="wideField" htmlFor={fieldId(item.id,'extracted')}>{on.extractedText}<textarea id={fieldId(item.id,'extracted')} value={draft.extracted_text} onChange={event=>setDraft({...draft,extracted_text:event.target.value})} rows="10"/></label>
      <label className="wideField" htmlFor={fieldId(item.id,'analysis')}>{on.analysisSummary}<textarea id={fieldId(item.id,'analysis')} value={draft.analysis_summary} onChange={event=>setDraft({...draft,analysis_summary:event.target.value})} rows="5"/></label>
      <label className="wideField" htmlFor={fieldId(item.id,'analysis-next')}>{on.analysisNext}<textarea id={fieldId(item.id,'analysis-next')} value={draft.analysis_next_step} onChange={event=>setDraft({...draft,analysis_next_step:event.target.value})}/></label>
      <button className="primary full wideField">{analysis?.save||on.saveDocument}</button>
    </form>
  </>
}
