const keys=['session','access','consent','limit','sources','review','timeout','stale','input']
const messages={
  de:['Bitte erneut anmelden. Die Sitzung oder der Testzugang ist abgelaufen.','Diese Funktion ist für diesen Zugang nicht freigeschaltet. Bitte den Leistungsumfang prüfen.','Bitte die aktuelle Datenschutzbestätigung und die Freigabe zur KI-Verarbeitung prüfen.','Das Tageslimit ist erreicht. Bitte später erneut versuchen.','Keine lesbaren amtlichen Quellen verifiziert. Kein Vergleich gespeichert. Bitte die Rechtsfrage eingrenzen und erneut recherchieren.','Aussagen sind noch nicht vollständig belegt oder widerspruchsfrei. Kein neues Ergebnis gespeichert. Bitte Originale und Zuordnung prüfen und erneut erstellen.','Die Prüfung hat ihr Zeitlimit erreicht. Kein ungeprüftes Ergebnis gespeichert. Bitte erneut versuchen.','Die Grundlage oder der gespeicherte Stand hat sich geändert. Bitte neu laden und bei geänderten Unterlagen einen neuen Fahrplan erstellen.','Bitte die Eingaben, vollständig eingelesenen Unterlagen und erforderlichen vorherigen Schritte prüfen.'],
  en:['Please sign in again. Your session or test access has expired.','This feature is not included in your access. Please check the available features.','Please check the current privacy acknowledgement and permission for AI processing.','The daily limit has been reached. Please try again later.','No readable official sources were verified. No comparison was saved. Please narrow the legal question and search again.','Some statements still lack support or contain contradictions. No new result was saved. Check the originals and their assignment, then generate again.','The review timed out. No unchecked result was saved. Please try again.','The underlying documents or saved progress have changed. Reload and create a new roadmap if the documents changed.','Please check the entries, fully read documents and required preceding steps.'],
  fr:['Reconnectez-vous. La session ou l’accès test a expiré.','Cette fonction n’est pas incluse dans votre accès. Vérifiez les prestations disponibles.','Vérifiez la confirmation de confidentialité actuelle et l’autorisation de traitement par IA.','La limite quotidienne est atteinte. Réessayez plus tard.','Aucune source officielle lisible n’a été vérifiée. Aucune comparaison enregistrée. Précisez la question juridique et relancez la recherche.','Certaines affirmations restent non étayées ou contradictoires. Aucun nouveau résultat enregistré. Vérifiez les originaux et leur affectation, puis relancez.','La vérification a dépassé le délai. Aucun résultat non vérifié enregistré. Réessayez.','Les documents ou l’avancement enregistré ont changé. Rechargez et créez un nouveau plan si les documents ont changé.','Vérifiez les saisies, la lecture complète des documents et les étapes préalables requises.'],
  tr:['Yeniden giriş yapın. Oturumunuz veya test erişiminiz sona erdi.','Bu özellik erişiminize dahil değil. Kullanılabilir hizmetleri kontrol edin.','Güncel gizlilik onayını ve yapay zekâ işleme iznini kontrol edin.','Günlük sınıra ulaşıldı. Daha sonra tekrar deneyin.','Okunabilir resmî kaynak doğrulanamadı. Karşılaştırma kaydedilmedi. Hukuki soruyu daraltıp yeniden araştırın.','Bazı ifadeler hâlâ dayanaksız veya çelişkili. Yeni sonuç kaydedilmedi. Asılları ve eşleştirmeyi kontrol edip yeniden oluşturun.','İnceleme zaman aşımına uğradı. Kontrol edilmemiş sonuç kaydedilmedi. Tekrar deneyin.','Belgeler veya kayıtlı ilerleme değişti. Yenileyin; belgeler değiştiyse yeni bir yol haritası oluşturun.','Girdileri, belgelerin tamamen okunmasını ve gerekli önceki adımları kontrol edin.'],
  pl:['Zaloguj się ponownie. Sesja lub dostęp testowy wygasły.','Ta funkcja nie jest objęta Twoim dostępem. Sprawdź dostępne usługi.','Sprawdź aktualne potwierdzenie prywatności i zgodę na przetwarzanie przez AI.','Osiągnięto dzienny limit. Spróbuj później.','Nie zweryfikowano czytelnych źródeł urzędowych. Nie zapisano porównania. Zawęź pytanie prawne i wyszukaj ponownie.','Niektóre stwierdzenia są nadal nieudokumentowane lub sprzeczne. Nie zapisano nowego wyniku. Sprawdź oryginały i ich przypisanie, a następnie utwórz wynik ponownie.','Przekroczono czas weryfikacji. Nie zapisano niesprawdzonego wyniku. Spróbuj ponownie.','Dokumenty lub zapisany postęp zmieniły się. Odśwież; po zmianie dokumentów utwórz nowy plan.','Sprawdź dane, pełny odczyt dokumentów i wymagane wcześniejsze kroki.'],
  ru:['Войдите снова. Срок сеанса или тестового доступа истёк.','Эта функция не входит в ваш доступ. Проверьте доступные услуги.','Проверьте актуальное подтверждение конфиденциальности и разрешение на обработку ИИ.','Достигнут дневной лимит. Повторите попытку позже.','Читаемые официальные источники не подтверждены. Сравнение не сохранено. Уточните правовой вопрос и повторите поиск.','Некоторые утверждения ещё не подтверждены или противоречивы. Новый результат не сохранён. Проверьте оригиналы и их привязку, затем создайте заново.','Время проверки истекло. Непроверенный результат не сохранён. Повторите попытку.','Документы или сохранённый прогресс изменились. Обновите страницу; при изменении документов создайте новый план.','Проверьте введённые данные, полный текст документов и необходимые предыдущие шаги.'],
  ar:['سجّل الدخول مجدداً. انتهت الجلسة أو صلاحية الوصول التجريبي.','هذه الميزة غير مشمولة في صلاحياتك. راجع الخدمات المتاحة.','راجع تأكيد الخصوصية الحالي والإذن بالمعالجة بالذكاء الاصطناعي.','تم بلوغ الحد اليومي. حاول لاحقاً.','لم يتم التحقق من مصادر رسمية قابلة للقراءة. لم تُحفظ مقارنة. حدّد السؤال القانوني وأعد البحث.','بعض العبارات غير مدعومة أو متناقضة. لم تُحفظ نتيجة جديدة. راجع الأصول وربطها ثم أعد الإنشاء.','انتهت مهلة المراجعة. لم تُحفظ نتيجة غير متحققة. حاول مجدداً.','تغيّرت المستندات أو حالة التقدم المحفوظة. أعد التحميل وأنشئ خطة جديدة إذا تغيّرت المستندات.','راجع المدخلات وقراءة المستندات كاملة والخطوات السابقة المطلوبة.'],
  fa:['دوباره وارد شوید. نشست یا دسترسی آزمایشی منقضی شده است.','این قابلیت در دسترسی شما نیست. خدمات موجود را بررسی کنید.','تأیید فعلی حریم خصوصی و اجازه پردازش با هوش مصنوعی را بررسی کنید.','به محدودیت روزانه رسیده‌اید. بعداً دوباره تلاش کنید.','منبع رسمی خوانایی تأیید نشد. مقایسه‌ای ذخیره نشد. پرسش حقوقی را دقیق‌تر کنید و دوباره جست‌وجو کنید.','بعضی گفته‌ها هنوز بدون پشتوانه یا متناقض‌اند. نتیجه جدیدی ذخیره نشد. اصل اسناد و ارتباطشان را بررسی و دوباره ایجاد کنید.','زمان بررسی تمام شد. نتیجه بررسی‌نشده‌ای ذخیره نشد. دوباره تلاش کنید.','اسناد یا پیشرفت ذخیره‌شده تغییر کرده است. صفحه را تازه کنید و اگر اسناد تغییر کرده‌اند برنامه جدید بسازید.','ورودی‌ها، خواندن کامل اسناد و گام‌های قبلی لازم را بررسی کنید.'],
  ro:['Autentificați-vă din nou. Sesiunea sau accesul de test a expirat.','Această funcție nu este inclusă în accesul dvs. Verificați serviciile disponibile.','Verificați confirmarea actuală de confidențialitate și permisiunea de procesare AI.','Limita zilnică a fost atinsă. Încercați mai târziu.','Nu au fost verificate surse oficiale lizibile. Nu s-a salvat comparația. Restrângeți întrebarea juridică și căutați din nou.','Unele afirmații nu sunt încă susținute sau sunt contradictorii. Nu s-a salvat un rezultat nou. Verificați originalele și asocierea lor, apoi generați din nou.','Verificarea a depășit timpul disponibil. Nu s-a salvat un rezultat neverificat. Încercați din nou.','Documentele sau progresul salvat s-au schimbat. Reîncărcați și creați un plan nou dacă documentele s-au schimbat.','Verificați datele introduse, citirea integrală a documentelor și pașii anteriori necesari.'],
  bg:['Влезте отново. Сесията или тестовият достъп е изтекъл.','Тази функция не е включена във вашия достъп. Проверете наличните услуги.','Проверете актуалното потвърждение за поверителност и разрешението за обработка с ИИ.','Достигнат е дневният лимит. Опитайте по-късно.','Не са потвърдени четими официални източници. Не е записано сравнение. Уточнете правния въпрос и потърсете отново.','Някои твърдения още са неподкрепени или противоречиви. Не е записан нов резултат. Проверете оригиналите и връзките им, след това генерирайте отново.','Времето за проверка изтече. Не е записан непроверен резултат. Опитайте отново.','Документите или записаният напредък са променени. Презаредете и създайте нов план при промяна на документите.','Проверете въведените данни, пълното прочитане на документите и необходимите предходни стъпки.'],
  vi:['Đăng nhập lại. Phiên làm việc hoặc quyền dùng thử đã hết hạn.','Quyền truy cập của bạn không bao gồm tính năng này. Hãy kiểm tra các dịch vụ có sẵn.','Kiểm tra xác nhận quyền riêng tư hiện hành và quyền xử lý bằng AI.','Đã đạt giới hạn hằng ngày. Vui lòng thử lại sau.','Chưa xác minh được nguồn chính thức có thể đọc. Chưa lưu bản so sánh. Hãy thu hẹp câu hỏi pháp lý và tìm lại.','Một số nhận định vẫn thiếu căn cứ hoặc mâu thuẫn. Chưa lưu kết quả mới. Kiểm tra bản gốc và cách liên kết, rồi tạo lại.','Quá thời gian kiểm tra. Chưa lưu kết quả chưa kiểm chứng. Vui lòng thử lại.','Tài liệu hoặc tiến độ đã lưu đã thay đổi. Tải lại và tạo lộ trình mới nếu tài liệu thay đổi.','Kiểm tra dữ liệu nhập, việc đọc đầy đủ tài liệu và các bước trước cần hoàn thành.']
}
const providerMessages={
  de:['Die KI-Verarbeitung ist wegen ausgeschöpften Guthabens beim Anbieter nicht verfügbar. Der ASH-Betreiber muss den KI-Zugang wieder freischalten. Ihre Unterlagen bleiben gespeichert.','Der KI-Dienst ist vorübergehend ausgelastet. Bitte später erneut versuchen. Ihre Unterlagen bleiben gespeichert.'],
  en:['AI processing is unavailable because the provider credits are exhausted. The ASH operator must restore AI access. Your documents remain saved.','The AI service is temporarily busy. Please try again later. Your documents remain saved.'],
  fr:['Le traitement IA est indisponible car les crédits du fournisseur sont épuisés. L’exploitant d’ASH doit rétablir l’accès à l’IA. Vos documents restent enregistrés.','Le service IA est temporairement surchargé. Réessayez plus tard. Vos documents restent enregistrés.'],
  tr:['Sağlayıcı kredileri tükendiği için yapay zekâ işlemesi kullanılamıyor. ASH işletmecisi yapay zekâ erişimini yeniden sağlamalıdır. Belgeleriniz kayıtlı kalır.','Yapay zekâ hizmeti geçici olarak yoğun. Daha sonra tekrar deneyin. Belgeleriniz kayıtlı kalır.'],
  pl:['Przetwarzanie AI jest niedostępne, ponieważ środki u dostawcy zostały wyczerpane. Operator ASH musi przywrócić dostęp do AI. Dokumenty pozostają zapisane.','Usługa AI jest chwilowo przeciążona. Spróbuj później. Dokumenty pozostają zapisane.'],
  ru:['Обработка ИИ недоступна: средства у поставщика исчерпаны. Оператор ASH должен восстановить доступ к ИИ. Ваши документы остаются сохранёнными.','Сервис ИИ временно перегружен. Повторите попытку позже. Ваши документы остаются сохранёнными.'],
  ar:['معالجة الذكاء الاصطناعي غير متاحة لنفاد الرصيد لدى المزوّد. يجب على مشغّل ASH استعادة الوصول إلى الخدمة. تبقى مستنداتك محفوظة.','خدمة الذكاء الاصطناعي مشغولة مؤقتاً. حاول لاحقاً. تبقى مستنداتك محفوظة.'],
  fa:['پردازش هوش مصنوعی به دلیل تمام شدن اعتبار نزد ارائه‌دهنده در دسترس نیست. گرداننده ASH باید دسترسی را دوباره برقرار کند. اسناد شما ذخیره می‌مانند.','سرویس هوش مصنوعی موقتاً شلوغ است. بعداً دوباره تلاش کنید. اسناد شما ذخیره می‌مانند.'],
  ro:['Procesarea AI nu este disponibilă deoarece creditul la furnizor s-a epuizat. Operatorul ASH trebuie să restabilească accesul AI. Documentele rămân salvate.','Serviciul AI este temporar suprasolicitat. Încercați mai târziu. Documentele rămân salvate.'],
  bg:['Обработката с ИИ е недостъпна поради изчерпан кредит при доставчика. Операторът на ASH трябва да възстанови достъпа до ИИ. Документите ви остават запазени.','Услугата с ИИ е временно претоварена. Опитайте по-късно. Документите ви остават запазени.'],
  vi:['Không thể xử lý bằng AI vì tín dụng tại nhà cung cấp đã hết. Đơn vị vận hành ASH cần khôi phục quyền truy cập AI. Tài liệu của bạn vẫn được lưu.','Dịch vụ AI tạm thời quá tải. Vui lòng thử lại sau. Tài liệu của bạn vẫn được lưu.']
}
const groups={no_verified_sources:'sources',source_review_unresolved:'review',review_unresolved:'review',source_unresolved:'review',provider_timeout:'timeout'}
// Older deployed handlers use German messages. Keep their concrete failure
// categories understandable while new handlers return stable machine codes.
const legacy=[
  ['session',/Nicht angemeldet|Sitzung ungültig|Zugriff abgelaufen/u],
  ['access',/Leistungsumfang|nicht freigeschaltet|Zugang mit Fallanalyse/u],
  ['consent',/Datenschutz|KI-Freigabe|Verarbeitung dieses Testfalls bestätigen/u],
  ['limit',/Tageslimit/u],['stale',/geändert|neu laden/u],
  ['review',/Quellen belegen|Gegenprüfung|Belegprüfung|Zuordnung zu den Originalen/u],
  ['timeout',/Zeitlimit|zu lange gedauert/u],
  ['input',/Bitte zuerst|Bitte den Briefkopf|Bitte die Erledigung|Testbetrieb erlaubt|Dieser Fall ist.*groß/u]
]
export function workflowErrorMessage(payload,fallback,language='de') {
  if(['provider_quota','provider_rate_limit'].includes(payload?.code))return (providerMessages[language]||providerMessages.de)[payload.code==='provider_quota'?0:1]
  const detail=payload?.error||payload?.message||payload?.detail||''
  const group=groups[payload?.code]||legacy.find(([,pattern])=>pattern.test(detail))?.[0]
  if(group)return (messages[language]||messages.de)[keys.indexOf(group)]
  // Do not insert untranslated server diagnostics or model review prose into
  // another interface language. The caller supplies its localized fallback.
  return fallback
}

export async function readWorkflowError(error,fallback,language='de') {
  if(!error)return fallback
  try {
    if(typeof error.context?.json==='function')return workflowErrorMessage(await error.context.json(),fallback,language)
  }catch{}
  return workflowErrorMessage(error,fallback,language)
}
