const keys=['title','next','read','review','approval','deadline','case','create','upload','recent','allCases','documents','approvals','deadlines','settings','more','empty','confirmed','unresolved','openDocument','openApproval','openCase','openDeadlines']
const rows={
  de:['Meine Übersicht','Jetzt zu tun','Dokument auslesen und prüfen','Dokumentprüfung abschließen','Schreiben prüfen','Frist prüfen','Am Fall weiterarbeiten','Neuen Fall anlegen','Dokument hochladen','Zuletzt bearbeitete Fälle','Alle Fälle','Dokumente prüfen','Freigaben prüfen','Feste Fristen','Einstellungen','Konto und weitere Bereiche','Beginnen Sie mit Ihrem ersten Fall.','terminiert','ungeklärt','Dokument öffnen','Schreiben öffnen','Fall öffnen','Fristen öffnen'],
  en:['My overview','What to do next','Read and check a document','Complete document review','Review a letter','Check a deadline','Continue a case','Create a case','Upload a document','Recently updated cases','All cases','Documents to review','Approvals to review','Confirmed deadlines','Settings','Account and more','Start with your first case.','dated','unresolved','Open document','Open letter','Open case','Open deadlines'],
  fr:['Mon aperçu','À faire maintenant','Lire et vérifier un document','Terminer la vérification du document','Vérifier un courrier','Vérifier un délai','Poursuivre un dossier','Créer un dossier','Importer un document','Dossiers récemment modifiés','Tous les dossiers','Documents à vérifier','Approbations à vérifier','Délais confirmés','Paramètres','Compte et autres rubriques','Commencez par votre premier dossier.','datés','non clarifiés','Ouvrir le document','Ouvrir le courrier','Ouvrir le dossier','Ouvrir les délais'],
  tr:['Genel görünümüm','Şimdi yapılacak','Belgeyi okuyup kontrol edin','Belge incelemesini tamamlayın','Yazıyı inceleyin','Süreyi kontrol edin','Dosyaya devam edin','Yeni dosya oluştur','Belge yükle','Son güncellenen dosyalar','Tüm dosyalar','İncelenecek belgeler','İncelenecek onaylar','Belirlenmiş süreler','Ayarlar','Hesap ve diğer bölümler','İlk dosyanızla başlayın.','tarihli','belirsiz','Belgeyi aç','Yazıyı aç','Dosyayı aç','Süreleri aç'],
  pl:['Mój przegląd','Co zrobić teraz','Odczytaj i sprawdź dokument','Dokończ weryfikację dokumentu','Sprawdź pismo','Sprawdź termin','Kontynuuj sprawę','Utwórz sprawę','Prześlij dokument','Ostatnio zmienione sprawy','Wszystkie sprawy','Dokumenty do sprawdzenia','Zatwierdzenia do sprawdzenia','Ustalone terminy','Ustawienia','Konto i inne obszary','Zacznij od pierwszej sprawy.','ustalone','niewyjaśnione','Otwórz dokument','Otwórz pismo','Otwórz sprawę','Otwórz terminy'],
  ru:['Мой обзор','Что сделать сейчас','Прочитать и проверить документ','Завершить проверку документа','Проверить письмо','Проверить срок','Продолжить дело','Создать дело','Загрузить документ','Недавно изменённые дела','Все дела','Документы для проверки','Согласования для проверки','Установленные сроки','Настройки','Аккаунт и другие разделы','Начните с первого дела.','установлено','не уточнено','Открыть документ','Открыть письмо','Открыть дело','Открыть сроки'],
  ar:['نظرتي العامة','ما يجب فعله الآن','قراءة مستند والتحقق منه','إكمال مراجعة المستند','مراجعة خطاب','التحقق من موعد','متابعة الملف','إنشاء ملف','تحميل مستند','الملفات المعدلة مؤخراً','جميع الملفات','مستندات للمراجعة','موافقات للمراجعة','مواعيد محددة','الإعدادات','الحساب وأقسام أخرى','ابدأ بملفك الأول.','محدد','غير محسوم','فتح المستند','فتح الخطاب','فتح الملف','فتح المواعيد'],
  fa:['نمای کلی من','اقدام بعدی','خواندن و بررسی سند','تکمیل بررسی سند','بررسی نامه','بررسی مهلت','ادامه پرونده','ایجاد پرونده','بارگذاری سند','پرونده‌های اخیراً ویرایش‌شده','همه پرونده‌ها','اسناد نیازمند بررسی','تأییدهای نیازمند بررسی','مهلت‌های مشخص','تنظیمات','حساب و بخش‌های دیگر','با اولین پرونده خود شروع کنید.','مشخص','نامشخص','باز کردن سند','باز کردن نامه','باز کردن پرونده','باز کردن مهلت‌ها'],
  ro:['Privirea mea de ansamblu','Ce urmează','Citiți și verificați documentul','Finalizați verificarea documentului','Verificați scrisoarea','Verificați termenul','Continuați dosarul','Creați un dosar','Încărcați un document','Dosare modificate recent','Toate dosarele','Documente de verificat','Aprobări de verificat','Termene stabilite','Setări','Cont și alte secțiuni','Începeți cu primul dosar.','stabilite','neclarificate','Deschide documentul','Deschide scrisoarea','Deschide dosarul','Deschide termenele'],
  bg:['Моят преглед','Какво следва','Прочетете и проверете документ','Завършете проверката на документа','Проверете писмото','Проверете срока','Продължете случая','Създайте случай','Качете документ','Наскоро променени случаи','Всички случаи','Документи за проверка','Одобрения за проверка','Определени срокове','Настройки','Профил и други раздели','Започнете с първия случай.','определени','неизяснени','Отвори документа','Отвори писмото','Отвори случая','Отвори сроковете'],
  vi:['Tổng quan của tôi','Việc cần làm tiếp','Đọc và kiểm tra tài liệu','Hoàn tất kiểm tra tài liệu','Kiểm tra thư','Kiểm tra thời hạn','Tiếp tục hồ sơ','Tạo hồ sơ','Tải tài liệu lên','Hồ sơ cập nhật gần đây','Tất cả hồ sơ','Tài liệu cần kiểm tra','Phê duyệt cần kiểm tra','Thời hạn đã xác định','Cài đặt','Tài khoản và các mục khác','Bắt đầu với hồ sơ đầu tiên.','đã định','chưa rõ','Mở tài liệu','Mở thư','Mở hồ sơ','Mở thời hạn']
}
export function workspaceOverviewCopy(language='de'){
  return Object.fromEntries(keys.map((key,index)=>[key,(rows[language]||rows.de)[index]]))
}
